{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBannerViewDelegate","text":"POBBannerViewDelegate"},{"text":")?","kind":"text"}],"externalID":"c:objc(cs)POBBannerView(py)delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"symbolKind":"property","roleHeading":"Instance Property","title":"delegate","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"text":"POBBannerViewDelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBannerViewDelegate"},{"text":")? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbannerview\/delegate"]},{"paths":["\/documentation\/openwrapsdk\/pobbannerview\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/delegate"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView":{"navigatorTitle":[{"kind":"identifier","text":"POBBannerView"}],"url":"\/documentation\/openwrapsdk\/pobbannerview","abstract":[{"text":"The view class that displays the banner ad.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerView"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","type":"topic","title":"POBBannerView","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate":{"navigatorTitle":[{"text":"POBBannerViewDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate","abstract":[{"text":"Protocol for interaction with the POBBannerView instance.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBBannerViewDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate","type":"topic","title":"POBBannerViewDelegate","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/delegate":{"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerview\/delegate","abstract":[],"kind":"symbol","title":"delegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)POBBannerViewDelegate","text":"POBBannerViewDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/delegate","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"delegate","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"text":"id<POBBannerViewDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)POBBannerViewDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/title","value":"POBBannerView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/fragments","value":[{"text":"POBBannerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate\/title","value":"POBBannerViewDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate\/fragments","op":"replace","value":[{"text":"POBBannerViewDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1delegate\/title","value":"delegate"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1delegate\/fragments"}]}]}