{"abstract":[{"type":"text","text":"Pauses the auto refresh, By default, banner refreshes automatically as per"},{"type":"text","text":" "},{"type":"text","text":"configured refresh interval on openwrap portal. Calling this method"},{"text":" ","type":"text"},{"text":"prevents the refresh cycle to happen even if a refresh interval has been specified.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/pauseAutoRefresh()"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbannerview\/pauseautorefresh()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobbannerview\/pauseautorefresh()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseAutoRefresh"},{"kind":"text","text":"()"}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"It is recommended to use this method whenever the ad view is about to be hidden"},{"text":" ","type":"text"},{"type":"text","text":"from the user for any period of time, to avoid unnecessary ad requests. You can"},{"type":"text","text":" "},{"text":"then call ","type":"text"},{"type":"codeVoice","code":"resumeAutoRefresh"},{"text":" to resume the refresh when banner becomes","type":"text"},{"type":"text","text":" "},{"text":"visible.","type":"text"}]}]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"pauseAutoRefresh"}],"role":"symbol","title":"pauseAutoRefresh()","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pauseAutoRefresh","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:objc(cs)POBBannerView(im)pauseAutoRefresh","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/pauseAutoRefresh()":{"abstract":[{"type":"text","text":"Pauses the auto refresh, By default, banner refreshes automatically as per"},{"text":" ","type":"text"},{"type":"text","text":"configured refresh interval on openwrap portal. Calling this method"},{"type":"text","text":" "},{"text":"prevents the refresh cycle to happen even if a refresh interval has been specified.","type":"text"}],"navigatorTitle":[{"text":"pauseAutoRefresh","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerview\/pauseautorefresh()","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/pauseAutoRefresh()","type":"topic","title":"pauseAutoRefresh()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseAutoRefresh"},{"kind":"text","text":"()"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView":{"navigatorTitle":[{"kind":"identifier","text":"POBBannerView"}],"url":"\/documentation\/openwrapsdk\/pobbannerview","abstract":[{"text":"The view class that displays the banner ad.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerView"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","type":"topic","title":"POBBannerView","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"pauseAutoRefresh","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pauseAutoRefresh"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"pauseAutoRefresh","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1pauseAutoRefresh()\/title","value":"pauseAutoRefresh","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pauseAutoRefresh","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1pauseAutoRefresh()\/fragments"},{"value":"POBBannerView","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/fragments","value":[{"text":"POBBannerView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}