{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView"]]},"abstract":[{"text":"Resumes the autorefresh as per configured refresh interval on openwrap portal, call this method only if you have previously paused autorefresh using ","type":"text"},{"type":"codeVoice","code":"pauseAutoRefresh"},{"type":"text","text":". This method has no effect if a refresh interval has not been set."}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/resumeAutoRefresh()","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"method","title":"resumeAutoRefresh()","role":"symbol","navigatorTitle":[{"text":"resumeAutoRefresh","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resumeAutoRefresh","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:objc(cs)POBBannerView(im)resumeAutoRefresh"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resumeAutoRefresh"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbannerview\/resumeautorefresh()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobbannerview\/resumeautorefresh()"]}],"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView":{"navigatorTitle":[{"kind":"identifier","text":"POBBannerView"}],"url":"\/documentation\/openwrapsdk\/pobbannerview","abstract":[{"text":"The view class that displays the banner ad.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerView"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","type":"topic","title":"POBBannerView","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/resumeAutoRefresh()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resumeAutoRefresh","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Resumes the autorefresh as per configured refresh interval on openwrap portal, call this method only if you have previously paused autorefresh using "},{"code":"pauseAutoRefresh","type":"codeVoice"},{"type":"text","text":". This method has no effect if a refresh interval has not been set."}],"navigatorTitle":[{"kind":"identifier","text":"resumeAutoRefresh"}],"url":"\/documentation\/openwrapsdk\/pobbannerview\/resumeautorefresh()","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/resumeAutoRefresh()","title":"resumeAutoRefresh()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"resumeAutoRefresh"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"resumeAutoRefresh","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"resumeAutoRefresh"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/title","value":"POBBannerView"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/fragments","value":[{"text":"POBBannerView","kind":"identifier"}],"op":"replace"},{"value":"resumeAutoRefresh","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1resumeAutoRefresh()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"resumeAutoRefresh","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1resumeAutoRefresh()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}