{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adFormat"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@POBAdFormat","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat","text":"POBAdFormat"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"adFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"POBAdFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBAdFormat"}],"externalID":"c:objc(cs)POBSignalConfig(py)adFormat","navigatorTitle":[{"kind":"identifier","text":"adFormat"}],"symbolKind":"property","roleHeading":"Instance Property","title":"adFormat","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobsignalconfig\/adformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobsignalconfig\/adformat"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig\/adFormat","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSignalConfig/adFormat":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig\/adFormat","abstract":[],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobsignalconfig\/adformat","navigatorTitle":[{"text":"adFormat","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"adFormat","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"POBAdFormat","preciseIdentifier":"c:@E@POBAdFormat"}],"role":"symbol","title":"adFormat","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdFormat":{"abstract":[{"text":"Indicates the ad format to request\/render","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadformat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBAdFormat","kind":"identifier"}],"title":"POBAdFormat","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat","navigatorTitle":[{"text":"POBAdFormat","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSignalConfig":{"navigatorTitle":[{"kind":"identifier","text":"POBSignalConfig"}],"url":"\/documentation\/openwrapsdk\/pobsignalconfig","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBSignalConfig","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig","type":"topic","title":"POBSignalConfig","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"adFormat","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"adFormat","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"POBAdFormat","preciseIdentifier":"c:@E@POBAdFormat","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"adFormat","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"adFormat","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig~1adFormat\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig~1adFormat\/fragments","value":[{"kind":"identifier","text":"adFormat"}],"op":"replace"},{"value":"POBAdFormat","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat\/fragments","value":[{"text":"POBAdFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig\/title","value":"POBSignalConfig","op":"replace"},{"value":[{"text":"POBSignalConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig\/fragments"}]}]}