{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","title":"init(adFormat:)","roleHeading":"Initializer","externalID":"c:objc(cs)POBSignalConfig(im)initWithAdFormat:","navigatorTitle":[{"text":"initWithAdFormat:","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"adFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"POBAdFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBAdFormat"},{"kind":"text","text":")"}],"symbolKind":"init"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig\/init(adFormat:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobsignalconfig\/init(adformat:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobsignalconfig\/init(adformat:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"adFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@POBAdFormat","text":"POBAdFormat","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSignalConfig":{"navigatorTitle":[{"kind":"identifier","text":"POBSignalConfig"}],"url":"\/documentation\/openwrapsdk\/pobsignalconfig","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBSignalConfig","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig","type":"topic","title":"POBSignalConfig","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSignalConfig/init(adFormat:)":{"title":"init(adFormat:)","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig\/init(adFormat:)","navigatorTitle":[{"text":"initWithAdFormat:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"adFormat","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@POBAdFormat","kind":"typeIdentifier","text":"POBAdFormat"},{"text":")","kind":"text"}],"url":"\/documentation\/openwrapsdk\/pobsignalconfig\/init(adformat:)","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdFormat":{"abstract":[{"text":"Indicates the ad format to request\/render","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadformat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBAdFormat","kind":"identifier"}],"title":"POBAdFormat","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat","navigatorTitle":[{"text":"POBAdFormat","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithAdFormat:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithAdFormat:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithAdFormat:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@POBAdFormat","text":"POBAdFormat","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat"},{"text":") ","kind":"text"},{"text":"adFormat","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig\/title","value":"POBSignalConfig","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig\/fragments","value":[{"kind":"identifier","text":"POBSignalConfig"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig~1init(adFormat:)\/title","op":"replace","value":"initWithAdFormat:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig~1init(adFormat:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAdFormat:","kind":"identifier"}]},{"value":"POBAdFormat","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat\/title","op":"replace"},{"value":[{"text":"POBAdFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}