{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"paid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:POBDataTypes.h@T@POBBOOL","text":"POBBOOL","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBOOL","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Possible values are:"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"POBBOOLNo - Free version"}]},{"type":"paragraph","inlineContent":[{"text":"POBBOOLYes - Paid version","type":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/paid"},"metadata":{"title":"paid","externalID":"c:objc(cs)POBApplicationInfo(py)paid","modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"paid","kind":"identifier"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paid","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:POBDataTypes.h@T@POBBOOL","text":"POBBOOL"}]},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobapplicationinfo\/paid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobapplicationinfo\/paid"]}],"sections":[],"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBApplicationInfo":{"abstract":[{"type":"text","text":"Provides setters to pass application information, Like store URL, application domain, categories, …etc. It is very important to provide transparency for buyers of your app inventory."}],"navigatorTitle":[{"text":"POBApplicationInfo","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBApplicationInfo","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobapplicationinfo","role":"symbol","title":"POBApplicationInfo","kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBApplicationInfo/paid":{"url":"\/documentation\/openwrapsdk\/pobapplicationinfo\/paid","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paid"},{"text":": ","kind":"text"},{"text":"POBBOOL","kind":"typeIdentifier","preciseIdentifier":"c:POBDataTypes.h@T@POBBOOL"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/paid","navigatorTitle":[{"kind":"identifier","text":"paid"}],"abstract":[],"title":"paid"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBOOL":{"kind":"symbol","type":"topic","title":"POBBOOL","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBOOL","url":"\/documentation\/openwrapsdk\/pobbool","role":"symbol","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBOOL","kind":"identifier"}],"navigatorTitle":[{"text":"POBBOOL","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"paid","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"paid","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":") ","kind":"text"},{"text":"POBBOOL","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBOOL","preciseIdentifier":"c:POBDataTypes.h@T@POBBOOL"},{"kind":"text","text":" "},{"text":"paid","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo\/title","value":"POBApplicationInfo"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo\/fragments","op":"replace","value":[{"text":"POBApplicationInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo~1paid\/title","value":"paid"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo~1paid\/fragments","op":"replace","value":[{"kind":"identifier","text":"paid"}]},{"value":"POBBOOL","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBOOL\/title"},{"value":[{"text":"POBBOOL","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBOOL\/fragments"}]}]}