{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adServerAdView"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"OpenWrapSDK"}],"platforms":[{"unavailable":false,"introducedAt":"2.0","beta":false,"deprecated":false,"name":"iOS"}],"roleHeading":"Instance Method","title":"adServerAdView()","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adServerAdView"},{"text":"() -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"externalID":"c:objc(pl)POBNativeAdEventBridge(im)adServerAdView","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"adServerAdView"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge"]]},"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadeventbridge\/adserveradview()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativeadeventbridge\/adserveradview()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/adServerAdView()","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventBridge":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Bridge for the native custom event protocol that manages communication with an ad server SDK."}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeAdEventBridge"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadeventbridge","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdEventBridge"}],"title":"POBNativeAdEventBridge"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventBridge/adServerAdView()":{"type":"topic","required":true,"abstract":[],"role":"symbol","navigatorTitle":[{"text":"adServerAdView","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/adServerAdView()","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadeventbridge\/adserveradview()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adServerAdView","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"title":"adServerAdView()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"adServerAdView","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"adServerAdView","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"adServerAdView","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"POBNativeAdEventBridge","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge\/fragments","value":[{"text":"POBNativeAdEventBridge","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1adServerAdView()\/title","op":"replace","value":"adServerAdView"},{"value":[{"kind":"text","text":"- "},{"text":"adServerAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1adServerAdView()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}