{"metadata":{"title":"setDelegate(_:)","role":"symbol","required":true,"symbolKind":"method","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(pl)POBNativeAdEventBridge(im)setDelegate:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setDelegate","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"POBNativeAdEventDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAdEventDelegate"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setDelegate:","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/setDelegate(_:)"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDelegate"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAdEventDelegate","text":"POBNativeAdEventDelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadeventbridge\/setdelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativeadeventbridge\/setdelegate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventBridge/setDelegate(_:)":{"title":"setDelegate(_:)","required":true,"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/setDelegate(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDelegate","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"POBNativeAdEventDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAdEventDelegate"},{"kind":"text","text":")"}],"url":"\/documentation\/openwrapsdk\/pobnativeadeventbridge\/setdelegate(_:)","navigatorTitle":[{"kind":"identifier","text":"setDelegate:"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventBridge":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Bridge for the native custom event protocol that manages communication with an ad server SDK."}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeAdEventBridge"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadeventbridge","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdEventBridge"}],"title":"POBNativeAdEventBridge"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventDelegate":{"title":"POBNativeAdEventDelegate","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBNativeAdEventDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativeadeventdelegate","navigatorTitle":[{"text":"POBNativeAdEventDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The native custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"setDelegate:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"setDelegate:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setDelegate:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<POBNativeAdEventDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)POBNativeAdEventDelegate"},{"kind":"text","text":") "},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1setDelegate(_:)\/title","value":"setDelegate:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDelegate:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1setDelegate(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge\/title","value":"POBNativeAdEventBridge","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBNativeAdEventBridge"}]},{"op":"replace","value":"POBNativeAdEventDelegate","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate\/title"},{"op":"replace","value":[{"text":"POBNativeAdEventDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate\/fragments"}]}]}