{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerRendering"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerRendering\/renderAdDescriptor(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobbannerrendering\/renderaddescriptor(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobbannerrendering\/renderaddescriptor(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderAdDescriptor"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"descriptor","kind":"internalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)POBAdDescriptor","kind":"typeIdentifier","text":"POBAdDescriptor","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor"},{"kind":"text","text":")!)"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"required":true,"navigatorTitle":[{"text":"renderAdDescriptor:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(pl)POBBannerRendering(im)renderAdDescriptor:","roleHeading":"Instance Method","title":"renderAdDescriptor(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"renderAdDescriptor","kind":"identifier"},{"kind":"text","text":"((any "},{"text":"POBAdDescriptor","preciseIdentifier":"c:objc(pl)POBAdDescriptor","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"role":"symbol"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerRendering/renderAdDescriptor(_:)":{"abstract":[],"required":true,"navigatorTitle":[{"text":"renderAdDescriptor:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbannerrendering\/renderaddescriptor(_:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerRendering\/renderAdDescriptor(_:)","title":"renderAdDescriptor(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderAdDescriptor"},{"kind":"text","text":"((any "},{"text":"POBAdDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBAdDescriptor"},{"kind":"text","text":")!)"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerRendering":{"abstract":[{"text":"Ad banner rendering protocol, implement these methods to write custom ad renderer","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBBannerRendering"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbannerrendering","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerRendering","type":"topic","title":"POBBannerRendering","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBBannerRendering"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdDescriptor":{"url":"\/documentation\/openwrapsdk\/pobaddescriptor","type":"topic","title":"POBAdDescriptor","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBAdDescriptor"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor","role":"symbol","abstract":[{"type":"text","text":"Ad descriptor protocol, provided creative string through "},{"type":"codeVoice","code":"renderableContent"},{"text":". POBAdRendering protocol renders object which conforms to POBAdDescriptor protocol","type":"text"}],"navigatorTitle":[{"text":"POBAdDescriptor","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"renderAdDescriptor:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"renderAdDescriptor:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"renderAdDescriptor:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)POBAdDescriptor","text":"id<POBAdDescriptor>"},{"text":") ","kind":"text"},{"text":"descriptor","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerRendering~1renderAdDescriptor(_:)\/title","value":"renderAdDescriptor:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerRendering~1renderAdDescriptor(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"renderAdDescriptor:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerRendering\/title","value":"POBBannerRendering"},{"value":[{"text":"POBBannerRendering","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerRendering\/fragments"},{"value":"POBAdDescriptor","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"POBAdDescriptor"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor\/fragments"}]}]}