{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidClickAd(_:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerViewDidClickAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBBannerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBannerView"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)POBBannerViewDelegate(im)bannerViewDidClickAd:","navigatorTitle":[{"kind":"identifier","text":"bannerViewDidClickAd:"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"OpenWrapSDK"}],"title":"bannerViewDidClickAd(_:)","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"bannerViewDidClickAd","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"bannerView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBBannerView","text":"POBBannerView","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewdidclickad(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewdidclickad(_:)"]}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate":{"navigatorTitle":[{"text":"POBBannerViewDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate","abstract":[{"text":"Protocol for interaction with the POBBannerView instance.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBBannerViewDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate","type":"topic","title":"POBBannerViewDelegate","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView":{"navigatorTitle":[{"kind":"identifier","text":"POBBannerView"}],"url":"\/documentation\/openwrapsdk\/pobbannerview","abstract":[{"text":"The view class that displays the banner ad.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerView"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","type":"topic","title":"POBBannerView","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate/bannerViewDidClickAd(_:)":{"abstract":[],"navigatorTitle":[{"text":"bannerViewDidClickAd:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewdidclickad(_:)","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidClickAd(_:)","type":"topic","title":"bannerViewDidClickAd(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bannerViewDidClickAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBBannerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBannerView"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"bannerViewDidClickAd:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bannerViewDidClickAd:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"bannerViewDidClickAd:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","kind":"typeIdentifier","text":"POBBannerView","preciseIdentifier":"c:objc(cs)POBBannerView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bannerView"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate\/title","value":"POBBannerViewDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate\/fragments","value":[{"text":"POBBannerViewDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/title","value":"POBBannerView","op":"replace"},{"op":"replace","value":[{"text":"POBBannerView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidClickAd(_:)\/title","value":"bannerViewDidClickAd:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bannerViewDidClickAd:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidClickAd(_:)\/fragments","op":"replace"}]}]}