{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(pl)POBBannerViewDelegate(im)bannerViewDidReceiveAd:","modules":[{"name":"OpenWrapSDK"}],"title":"bannerViewDidReceiveAd(_:)","navigatorTitle":[{"text":"bannerViewDidReceiveAd:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerViewDidReceiveAd","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBBannerView","kind":"typeIdentifier","text":"POBBannerView"},{"kind":"text","text":")"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerViewDidReceiveAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"bannerView","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBannerView","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","text":"POBBannerView"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewdidreceivead(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewdidreceivead(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidReceiveAd(_:)"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate":{"navigatorTitle":[{"text":"POBBannerViewDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate","abstract":[{"text":"Protocol for interaction with the POBBannerView instance.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBBannerViewDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate","type":"topic","title":"POBBannerViewDelegate","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate/bannerViewDidReceiveAd(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bannerViewDidReceiveAd","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)POBBannerView","text":"POBBannerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"bannerViewDidReceiveAd:","kind":"identifier"}],"title":"bannerViewDidReceiveAd(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidReceiveAd(_:)","abstract":[],"url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewdidreceivead(_:)","type":"topic","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView":{"navigatorTitle":[{"kind":"identifier","text":"POBBannerView"}],"url":"\/documentation\/openwrapsdk\/pobbannerview","abstract":[{"text":"The view class that displays the banner ad.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerView"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","type":"topic","title":"POBBannerView","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"bannerViewDidReceiveAd:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bannerViewDidReceiveAd:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"bannerViewDidReceiveAd:","kind":"identifier"},{"kind":"text","text":"("},{"text":"POBBannerView","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBannerView"},{"kind":"text","text":" *) "},{"text":"bannerView","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"POBBannerViewDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate\/title"},{"value":[{"kind":"identifier","text":"POBBannerViewDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidReceiveAd(_:)\/title","value":"bannerViewDidReceiveAd:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidReceiveAd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bannerViewDidReceiveAd:"}],"op":"replace"},{"value":"POBBannerView","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/title"},{"value":[{"text":"POBBannerView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}