{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerViewWillPresentModal","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"bannerView","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"POBBannerView","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","preciseIdentifier":"c:objc(cs)POBBannerView"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"bannerViewWillPresentModal(_:)","modules":[{"name":"OpenWrapSDK"}],"navigatorTitle":[{"kind":"identifier","text":"bannerViewWillPresentModal:"}],"symbolKind":"method","role":"symbol","externalID":"c:objc(pl)POBBannerViewDelegate(im)bannerViewWillPresentModal:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerViewWillPresentModal","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)POBBannerView","kind":"typeIdentifier","text":"POBBannerView"},{"text":")","kind":"text"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewWillPresentModal(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewwillpresentmodal(_:)"]},{"paths":["\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewwillpresentmodal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate":{"navigatorTitle":[{"text":"POBBannerViewDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate","abstract":[{"text":"Protocol for interaction with the POBBannerView instance.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBBannerViewDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate","type":"topic","title":"POBBannerViewDelegate","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate/bannerViewWillPresentModal(_:)":{"title":"bannerViewWillPresentModal(_:)","abstract":[],"navigatorTitle":[{"text":"bannerViewWillPresentModal:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewwillpresentmodal(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerViewWillPresentModal","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBBannerView","text":"POBBannerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewWillPresentModal(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView":{"navigatorTitle":[{"kind":"identifier","text":"POBBannerView"}],"url":"\/documentation\/openwrapsdk\/pobbannerview","abstract":[{"text":"The view class that displays the banner ad.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerView"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","type":"topic","title":"POBBannerView","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"bannerViewWillPresentModal:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bannerViewWillPresentModal:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"bannerViewWillPresentModal:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBannerView","text":"POBBannerView"},{"kind":"text","text":" *) "},{"text":"bannerView","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate\/title","value":"POBBannerViewDelegate","op":"replace"},{"value":[{"text":"POBBannerViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewWillPresentModal(_:)\/title","value":"bannerViewWillPresentModal:","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewWillPresentModal(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"bannerViewWillPresentModal:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/title","op":"replace","value":"POBBannerView"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/fragments","value":[{"text":"POBBannerView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}