{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewdidrecordimpression(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewdidrecordimpression(_:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate"]]},"metadata":{"externalID":"c:objc(pl)POBBannerViewDelegate(im)bannerViewDidRecordImpression:","modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bannerViewDidRecordImpression:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerViewDidRecordImpression"},{"kind":"text","text":"("},{"text":"POBBannerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBannerView"},{"text":")","kind":"text"}],"title":"bannerViewDidRecordImpression(_:)","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidRecordImpression(_:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerViewDidRecordImpression","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"bannerView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"POBBannerView","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","preciseIdentifier":"c:objc(cs)POBBannerView"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"bannerView","content":[{"inlineContent":[{"type":"text","text":"The POBBannerView instance sending the message."}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView":{"navigatorTitle":[{"kind":"identifier","text":"POBBannerView"}],"url":"\/documentation\/openwrapsdk\/pobbannerview","abstract":[{"text":"The view class that displays the banner ad.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerView"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","type":"topic","title":"POBBannerView","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate/bannerViewDidRecordImpression(_:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bannerViewDidRecordImpression:"}],"url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewdidrecordimpression(_:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidRecordImpression(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bannerViewDidRecordImpression","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBannerView","text":"POBBannerView"},{"kind":"text","text":")"}],"title":"bannerViewDidRecordImpression(_:)","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate":{"navigatorTitle":[{"text":"POBBannerViewDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate","abstract":[{"text":"Protocol for interaction with the POBBannerView instance.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBBannerViewDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate","type":"topic","title":"POBBannerViewDelegate","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"bannerViewDidRecordImpression:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bannerViewDidRecordImpression:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"bannerViewDidRecordImpression:","kind":"identifier"},{"kind":"text","text":"("},{"text":"POBBannerView","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBannerView"},{"text":" *) ","kind":"text"},{"text":"bannerView","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/title","op":"replace","value":"POBBannerView"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/fragments","value":[{"text":"POBBannerView","kind":"identifier"}],"op":"replace"},{"value":"bannerViewDidRecordImpression:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidRecordImpression(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidRecordImpression(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bannerViewDidRecordImpression:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate\/title","value":"POBBannerViewDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBBannerViewDelegate"}]}]}]}