{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorNetworkError"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/poberrorcode\/errornetworkerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/poberrorcode\/errornetworkerror"]}],"abstract":[{"type":"text","text":"There was an error while retrieving the data from the network."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNetworkError","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"case","roleHeading":"Case","title":"POBErrorCode.errorNetworkError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"errorNetworkError","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"POBErrorNetworkError","kind":"identifier"}],"externalID":"c:@E@POBErrorCode@POBErrorNetworkError"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode":{"url":"\/documentation\/openwrapsdk\/poberrorcode","type":"topic","abstract":[{"text":"Error codes PubMatic SDK gives in error callback.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBErrorCode","kind":"identifier"}],"title":"POBErrorCode","navigatorTitle":[{"kind":"identifier","text":"POBErrorCode"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorNetworkError":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorNetworkError","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/poberrorcode\/errornetworkerror","title":"POBErrorCode.errorNetworkError","abstract":[{"type":"text","text":"There was an error while retrieving the data from the network."}],"navigatorTitle":[{"kind":"identifier","text":"POBErrorNetworkError"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorNetworkError"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"POBErrorNetworkError"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"POBErrorNetworkError","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"POBErrorNetworkError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode\/title","op":"replace","value":"POBErrorCode"},{"value":[{"text":"POBErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorNetworkError\/title","value":"POBErrorNetworkError"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorNetworkError\/fragments","value":[{"text":"POBErrorNetworkError","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}