{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode"]]},"abstract":[{"text":"Bid lost the client auction between OpenWrap  server side partners and client side partners-","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorClientSideAuctionLost","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorClientSideAuctionLost"},"metadata":{"externalID":"c:@E@POBErrorCode@POBErrorClientSideAuctionLost","modules":[{"name":"OpenWrapSDK"}],"title":"POBErrorCode.errorClientSideAuctionLost","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"errorClientSideAuctionLost","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBErrorClientSideAuctionLost"}],"roleHeading":"Case","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/poberrorcode\/errorclientsideauctionlost"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/poberrorcode\/errorclientsideauctionlost"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode":{"url":"\/documentation\/openwrapsdk\/poberrorcode","type":"topic","abstract":[{"text":"Error codes PubMatic SDK gives in error callback.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBErrorCode","kind":"identifier"}],"title":"POBErrorCode","navigatorTitle":[{"kind":"identifier","text":"POBErrorCode"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorClientSideAuctionLost":{"url":"\/documentation\/openwrapsdk\/poberrorcode\/errorclientsideauctionlost","type":"topic","abstract":[{"type":"text","text":"Bid lost the client auction between OpenWrap  server side partners and client side partners-"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorClientSideAuctionLost"}],"title":"POBErrorCode.errorClientSideAuctionLost","navigatorTitle":[{"text":"POBErrorClientSideAuctionLost","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorClientSideAuctionLost"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"POBErrorClientSideAuctionLost","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBErrorClientSideAuctionLost"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"POBErrorClientSideAuctionLost","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode\/title","value":"POBErrorCode"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode\/fragments","value":[{"text":"POBErrorCode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorClientSideAuctionLost\/title","value":"POBErrorClientSideAuctionLost"},{"value":[{"kind":"identifier","text":"POBErrorClientSideAuctionLost"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorClientSideAuctionLost\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}