{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorNoAds","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode"]]},"abstract":[{"type":"text","text":"There was no ads available to deliver for ad request."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"errorNoAds","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/poberrorcode\/errornoads"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/poberrorcode\/errornoads"]}],"metadata":{"modules":[{"name":"OpenWrapSDK"}],"title":"POBErrorCode.errorNoAds","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNoAds"}],"role":"symbol","roleHeading":"Case","externalID":"c:@E@POBErrorCode@POBErrorNoAds","navigatorTitle":[{"kind":"identifier","text":"POBErrorNoAds"}]},"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode":{"url":"\/documentation\/openwrapsdk\/poberrorcode","type":"topic","abstract":[{"text":"Error codes PubMatic SDK gives in error callback.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBErrorCode","kind":"identifier"}],"title":"POBErrorCode","navigatorTitle":[{"kind":"identifier","text":"POBErrorCode"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorNoAds":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorNoAds","url":"\/documentation\/openwrapsdk\/poberrorcode\/errornoads","abstract":[{"text":"There was no ads available to deliver for ad request.","type":"text"}],"title":"POBErrorCode.errorNoAds","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"errorNoAds","kind":"identifier"}],"navigatorTitle":[{"text":"POBErrorNoAds","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"POBErrorNoAds"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBErrorNoAds","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"POBErrorNoAds","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode\/title","value":"POBErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode\/fragments","value":[{"text":"POBErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorNoAds\/title","value":"POBErrorNoAds","op":"replace"},{"value":[{"text":"POBErrorNoAds","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorNoAds\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}