{"abstract":[{"text":"Internal error","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"POBErrorInternalError"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:@E@POBErrorCode@POBErrorInternalError","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"errorInternalError","kind":"identifier"}],"title":"POBErrorCode.errorInternalError"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInternalError","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/poberrorcode\/errorinternalerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/poberrorcode\/errorinternalerror"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorInternalError","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorInternalError":{"url":"\/documentation\/openwrapsdk\/poberrorcode\/errorinternalerror","abstract":[{"type":"text","text":"Internal error"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInternalError","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBErrorInternalError"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorInternalError"}],"title":"POBErrorCode.errorInternalError"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode":{"url":"\/documentation\/openwrapsdk\/poberrorcode","type":"topic","abstract":[{"text":"Error codes PubMatic SDK gives in error callback.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBErrorCode","kind":"identifier"}],"title":"POBErrorCode","navigatorTitle":[{"kind":"identifier","text":"POBErrorCode"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"POBErrorInternalError","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBErrorInternalError"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"POBErrorInternalError","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorInternalError\/title","value":"POBErrorInternalError"},{"value":[{"text":"POBErrorInternalError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorInternalError\/fragments"},{"value":"POBErrorCode","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode\/title"},{"value":[{"text":"POBErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode\/fragments","op":"replace"}]}]}