{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorServerError","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorServerError"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@E@POBErrorCode@POBErrorServerError","symbolKind":"case","title":"POBErrorCode.errorServerError","navigatorTitle":[{"text":"POBErrorServerError","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorServerError"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/openwrapsdk\/poberrorcode\/errorservererror"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/poberrorcode\/errorservererror"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode"]]},"abstract":[{"text":"Failed to process ad request by Ad Server.","type":"text"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode":{"url":"\/documentation\/openwrapsdk\/poberrorcode","type":"topic","abstract":[{"text":"Error codes PubMatic SDK gives in error callback.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBErrorCode","kind":"identifier"}],"title":"POBErrorCode","navigatorTitle":[{"kind":"identifier","text":"POBErrorCode"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorServerError":{"abstract":[{"text":"Failed to process ad request by Ad Server.","type":"text"}],"url":"\/documentation\/openwrapsdk\/poberrorcode\/errorservererror","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorServerError","title":"POBErrorCode.errorServerError","type":"topic","navigatorTitle":[{"text":"POBErrorServerError","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorServerError"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"POBErrorServerError","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"POBErrorServerError","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"POBErrorServerError"}]}],"kind":"declarations"},"op":"replace"},{"value":"POBErrorCode","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode\/fragments","value":[{"text":"POBErrorCode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorServerError\/title","value":"POBErrorServerError"},{"value":[{"kind":"identifier","text":"POBErrorServerError"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorServerError\/fragments","op":"replace"}]}]}