{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDataResponseAsset"]]},"metadata":{"externalID":"c:objc(cs)POBNativeAdDataResponseAsset(im)initWithType:value:length:builder:","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithType:value:length:builder:","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithType:value:length:builder:","kind":"identifier"}],"title":"initWithType:value:length:builder:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeaddataresponseasset\/initwithtype:value:length:builder:"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithType:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@POBNativeDataAssetType","text":"POBNativeDataAssetType","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"length:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"length","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"builder:"},{"kind":"text","text":"("},{"text":"POBNativeAdResponseAssetBuilder","preciseIdentifier":"c:objc(cs)POBNativeAdResponseAssetBuilder","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"builder","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDataResponseAsset\/initWithType:value:length:builder:","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDataResponseAsset":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDataResponseAsset","role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeaddataresponseasset","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdDataResponseAsset"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdDataResponseAsset"}],"type":"topic","abstract":[],"title":"POBNativeAdDataResponseAsset"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeDataAssetType","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Native Data asset types"}],"navigatorTitle":[{"text":"POBNativeDataAssetType","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativedataassettype","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType","title":"POBNativeDataAssetType"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDataResponseAsset/initWithType:value:length:builder:":{"abstract":[],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeaddataresponseasset\/initwithtype:value:length:builder:","fragments":[{"kind":"text","text":"- "},{"text":"initWithType:value:length:builder:","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithType:value:length:builder:"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDataResponseAsset\/initWithType:value:length:builder:","title":"initWithType:value:length:builder:"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDataResponseAsset\/title","value":"POBNativeAdDataResponseAsset"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDataResponseAsset\/fragments","value":[{"text":"POBNativeAdDataResponseAsset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/title","value":"POBNativeDataAssetType","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/fragments","op":"replace","value":[{"text":"POBNativeDataAssetType","kind":"identifier"}]}]}]}