{"kind":"symbol","metadata":{"symbolKind":"init","title":"init(publisherId:andProfileIds:)","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"publisherId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"andProfileIds","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPublisherId:andProfileIds:"}],"externalID":"c:objc(cs)OpenWrapSDKConfig(im)initWithPublisherId:andProfileIds:"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"publisherId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"andProfileIds","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"profileIds","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"])","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/openwrapsdk\/openwrapsdkconfig\/init(publisherid:andprofileids:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/openwrapsdkconfig\/init(publisherid:andprofileids:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig\/init(publisherId:andProfileIds:)"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDKConfig":{"navigatorTitle":[{"kind":"identifier","text":"OpenWrapSDKConfig"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OpenWrapSDKConfig","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/openwrapsdkconfig","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig","title":"OpenWrapSDKConfig","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDKConfig/init(publisherId:andProfileIds:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"publisherId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"andProfileIds","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"])","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithPublisherId:andProfileIds:","kind":"identifier"}],"title":"init(publisherId:andProfileIds:)","abstract":[],"url":"\/documentation\/openwrapsdk\/openwrapsdkconfig\/init(publisherid:andprofileids:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig\/init(publisherId:andProfileIds:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithPublisherId:andProfileIds:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPublisherId:andProfileIds:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithPublisherId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"publisherId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"andProfileIds:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"profileIds"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig\/title","op":"replace","value":"OpenWrapSDKConfig"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"OpenWrapSDKConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig~1init(publisherId:andProfileIds:)\/title","value":"initWithPublisherId:andProfileIds:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithPublisherId:andProfileIds:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig~1init(publisherId:andProfileIds:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}