{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"productSpcific","kind":"identifier"}]}]}],"sections":[],"abstract":[{"text":"Product context such as product listings, details, recommendations, reviews, or similar.","type":"text"}],"metadata":{"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"productSpcific","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"POBNativeContextTypeProductSpcific"}],"roleHeading":"Case","title":"POBNativeContextType.productSpcific","role":"symbol","externalID":"c:@E@POBNativeContextType@POBNativeContextTypeProductSpcific"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/productSpcific"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativecontexttype\/productspcific"]},{"paths":["\/documentation\/openwrapsdk\/pobnativecontexttype\/productspcific"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextType/productSpcific":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/productSpcific","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"productSpcific"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontexttype\/productspcific","abstract":[{"type":"text","text":"Product context such as product listings, details, recommendations, reviews, or similar."}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeContextTypeProductSpcific"}],"title":"POBNativeContextType.productSpcific","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextType":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBNativeContextType"}],"url":"\/documentation\/openwrapsdk\/pobnativecontexttype","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeContextType","kind":"identifier"}],"title":"POBNativeContextType","abstract":[{"type":"text","text":"The context in which the ad appears - what type of content is surrounding the ad on the  page at a high level."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeContextTypeProductSpcific"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"POBNativeContextTypeProductSpcific","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"POBNativeContextTypeProductSpcific","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType~1productSpcific\/title","op":"replace","value":"POBNativeContextTypeProductSpcific"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType~1productSpcific\/fragments","value":[{"text":"POBNativeContextTypeProductSpcific","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType\/title","value":"POBNativeContextType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType\/fragments","value":[{"text":"POBNativeContextType","kind":"identifier"}]}]}]}