{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/socialCentric","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"socialCentric","kind":"identifier"}],"externalID":"c:@E@POBNativeContextType@POBNativeContextTypeSocialCentric","navigatorTitle":[{"kind":"identifier","text":"POBNativeContextTypeSocialCentric"}],"symbolKind":"case","roleHeading":"Case","title":"POBNativeContextType.socialCentric","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"socialCentric","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Social-centric context such as social network feed, email, chat, or similar."}],"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativecontexttype\/socialcentric"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativecontexttype\/socialcentric"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextType":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBNativeContextType"}],"url":"\/documentation\/openwrapsdk\/pobnativecontexttype","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeContextType","kind":"identifier"}],"title":"POBNativeContextType","abstract":[{"type":"text","text":"The context in which the ad appears - what type of content is surrounding the ad on the  page at a high level."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextType/socialCentric":{"url":"\/documentation\/openwrapsdk\/pobnativecontexttype\/socialcentric","title":"POBNativeContextType.socialCentric","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/socialCentric","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"socialCentric"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBNativeContextTypeSocialCentric"}],"abstract":[{"type":"text","text":"Social-centric context such as social network feed, email, chat, or similar."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeContextTypeSocialCentric"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBNativeContextTypeSocialCentric"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"POBNativeContextTypeSocialCentric","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"POBNativeContextType","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType\/fragments","op":"replace","value":[{"text":"POBNativeContextType","kind":"identifier"}]},{"value":"POBNativeContextTypeSocialCentric","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType~1socialCentric\/title","op":"replace"},{"value":[{"kind":"identifier","text":"POBNativeContextTypeSocialCentric"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType~1socialCentric\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}