{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd"]]},"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerView"},{"kind":"text","text":"("},{"text":"forInteractions","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clickableViews"},{"kind":"text","text":": ["},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"])"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"2.0","deprecated":false}],"title":"registerView(forInteractions:clickableViews:)","modules":[{"name":"OpenWrapSDK"}],"required":true,"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"registerViewForInteractions:clickableViews:"}],"externalID":"c:objc(pl)POBNativeAd(im)registerViewForInteractions:clickableViews:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forInteractions"},{"text":" ","kind":"text"},{"text":"adView","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"text":"clickableViews","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":"])","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/registerView(forInteractions:clickableViews:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativead\/registerview(forinteractions:clickableviews:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativead\/registerview(forinteractions:clickableviews:)"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd/registerView(forInteractions:clickableViews:)":{"navigatorTitle":[{"kind":"identifier","text":"registerViewForInteractions:clickableViews:"}],"title":"registerView(forInteractions:clickableViews:)","type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativead\/registerview(forinteractions:clickableviews:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/registerView(forInteractions:clickableViews:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerView"},{"text":"(","kind":"text"},{"text":"forInteractions","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"clickableViews"},{"kind":"text","text":": ["},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd":{"navigatorTitle":[{"text":"POBNativeAd","kind":"identifier"}],"title":"POBNativeAd","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","url":"\/documentation\/openwrapsdk\/pobnativead","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAd"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"registerViewForInteractions:clickableViews:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerViewForInteractions:clickableViews:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"registerViewForInteractions:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"adView"},{"text":" ","kind":"text"},{"text":"clickableViews:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<UIView *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"clickableViews","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1registerView(forInteractions:clickableViews:)\/title","value":"registerViewForInteractions:clickableViews:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1registerView(forInteractions:clickableViews:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"registerViewForInteractions:clickableViews:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"POBNativeAd","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/fragments","op":"replace","value":[{"text":"POBNativeAd","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}