{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/renderAd(completion:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderAd"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:POBNativeAd.h@T@POBNativeAdRenderingCompletionBlock","kind":"typeIdentifier","text":"POBNativeAdRenderingCompletionBlock"},{"text":")","kind":"text"}],"required":true,"externalID":"c:objc(pl)POBNativeAd(im)renderAdWithCompletion:","navigatorTitle":[{"kind":"identifier","text":"renderAdWithCompletion:"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"renderAd(completion:)","modules":[{"name":"OpenWrapSDK"}]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativead\/renderad(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativead\/renderad(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"text":"POBNativeAdRenderingCompletionBlock","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdRenderingCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:POBNativeAd.h@T@POBNativeAdRenderingCompletionBlock"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdRenderingCompletionBlock":{"navigatorTitle":[{"text":"POBNativeAdRenderingCompletionBlock","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdRenderingCompletionBlock"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativeadrenderingcompletionblock","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdRenderingCompletionBlock","title":"POBNativeAdRenderingCompletionBlock","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd":{"navigatorTitle":[{"text":"POBNativeAd","kind":"identifier"}],"title":"POBNativeAd","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","url":"\/documentation\/openwrapsdk\/pobnativead","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAd"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd/renderAd(completion:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"POBNativeAdRenderingCompletionBlock","preciseIdentifier":"c:POBNativeAd.h@T@POBNativeAdRenderingCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"renderAdWithCompletion:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativead\/renderad(completion:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/renderAd(completion:)","title":"renderAd(completion:)","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"renderAdWithCompletion:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"renderAdWithCompletion:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"renderAdWithCompletion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*Qoobjc(pl)POBNativeAd#*$objc(cs)NSError)","kind":"typeIdentifier","text":"void (^)(id<POBNativeAd>, NSError *)"},{"kind":"text","text":") "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdRenderingCompletionBlock\/title","value":"POBNativeAdRenderingCompletionBlock","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdRenderingCompletionBlock\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBNativeAdRenderingCompletionBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/title","value":"POBNativeAd"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/fragments","value":[{"text":"POBNativeAd","kind":"identifier"}]},{"value":"renderAdWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1renderAd(completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"renderAdWithCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1renderAd(completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}