{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/renderAd(with:andCompletion:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderAd"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBNativeTemplateView","text":"POBNativeTemplateView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"andCompletion"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:POBNativeAd.h@T@POBNativeAdRenderingCompletionBlock","kind":"typeIdentifier","text":"POBNativeAdRenderingCompletionBlock"},{"text":")","kind":"text"}],"modules":[{"name":"OpenWrapSDK"}],"title":"renderAd(with:andCompletion:)","externalID":"c:objc(pl)POBNativeAd(im)renderAdWithTemplateView:andCompletion:","required":true,"navigatorTitle":[{"text":"renderAdWithTemplateView:andCompletion:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativead\/renderad(with:andcompletion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativead\/renderad(with:andcompletion:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"templateview","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)POBNativeTemplateView","text":"POBNativeTemplateView","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView"},{"text":", ","kind":"text"},{"text":"andCompletion","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:POBNativeAd.h@T@POBNativeAdRenderingCompletionBlock","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdRenderingCompletionBlock","text":"POBNativeAdRenderingCompletionBlock"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateView":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"POBNativeTemplateView","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativetemplateview","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeTemplateView","kind":"identifier"}],"title":"POBNativeTemplateView","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd":{"navigatorTitle":[{"text":"POBNativeAd","kind":"identifier"}],"title":"POBNativeAd","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","url":"\/documentation\/openwrapsdk\/pobnativead","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAd"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd/renderAd(with:andCompletion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBNativeTemplateView","text":"POBNativeTemplateView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"andCompletion"},{"text":": ","kind":"text"},{"text":"POBNativeAdRenderingCompletionBlock","preciseIdentifier":"c:POBNativeAd.h@T@POBNativeAdRenderingCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"renderAd(with:andCompletion:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/renderAd(with:andCompletion:)","required":true,"kind":"symbol","navigatorTitle":[{"text":"renderAdWithTemplateView:andCompletion:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativead\/renderad(with:andcompletion:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdRenderingCompletionBlock":{"navigatorTitle":[{"text":"POBNativeAdRenderingCompletionBlock","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdRenderingCompletionBlock"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativeadrenderingcompletionblock","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdRenderingCompletionBlock","title":"POBNativeAdRenderingCompletionBlock","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"renderAdWithTemplateView:andCompletion:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"renderAdWithTemplateView:andCompletion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"renderAdWithTemplateView:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView","kind":"typeIdentifier","text":"POBNativeTemplateView","preciseIdentifier":"c:objc(cs)POBNativeTemplateView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"templateview"},{"text":" ","kind":"text"},{"text":"andCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(id<POBNativeAd>, NSError *)","preciseIdentifier":"c:BFv(#*Qoobjc(pl)POBNativeAd#*$objc(cs)NSError)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView\/title","value":"POBNativeTemplateView","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"POBNativeTemplateView"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/title","op":"replace","value":"POBNativeAd"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBNativeAd"}]},{"op":"replace","value":"renderAdWithTemplateView:andCompletion:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1renderAd(with:andCompletion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"renderAdWithTemplateView:andCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1renderAd(with:andCompletion:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdRenderingCompletionBlock\/title","op":"replace","value":"POBNativeAdRenderingCompletionBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdRenderingCompletionBlock\/fragments","value":[{"text":"POBNativeAdRenderingCompletionBlock","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}