{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/impression"},"abstract":[{"type":"text","text":"impression"}],"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeeventtype\/impression"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeeventtype\/impression"]}],"metadata":{"roleHeading":"Case","externalID":"c:@E@POBNativeEventType@POBNativeEventTypeImpression","role":"symbol","symbolKind":"case","modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"impression","kind":"identifier"}],"navigatorTitle":[{"text":"POBNativeEventTypeImpression","kind":"identifier"}],"title":"POBNativeEventType.impression"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"impression"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType/impression":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"impression"}],"title":"POBNativeEventType.impression","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/impression","url":"\/documentation\/openwrapsdk\/pobnativeeventtype\/impression","abstract":[{"type":"text","text":"impression"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"POBNativeEventTypeImpression","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventType"}],"abstract":[{"type":"text","text":"Native Event Type for Event Tracking"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeEventType","kind":"identifier"}],"title":"POBNativeEventType","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType","url":"\/documentation\/openwrapsdk\/pobnativeeventtype"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"POBNativeEventTypeImpression"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBNativeEventTypeImpression","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"POBNativeEventTypeImpression"}]}]}},{"op":"replace","value":"POBNativeEventTypeImpression","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1impression\/title"},{"value":[{"text":"POBNativeEventTypeImpression","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1impression\/fragments","op":"replace"},{"value":"POBNativeEventType","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType\/title","op":"replace"},{"value":[{"text":"POBNativeEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType\/fragments"}]}]}