{"abstract":[{"text":"Signifies the event as OMID event.","type":"text"}],"kind":"symbol","metadata":{"externalID":"c:@E@POBNativeEventType@POBNativeEventTypeOMID","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"POBNativeEventTypeOMID","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OMID"}],"title":"POBNativeEventType.OMID"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeeventtype\/omid"]},{"paths":["\/documentation\/openwrapsdk\/pobnativeeventtype\/omid"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/OMID"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OMID"}],"languages":["swift"]}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventType"}],"abstract":[{"type":"text","text":"Native Event Type for Event Tracking"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeEventType","kind":"identifier"}],"title":"POBNativeEventType","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType","url":"\/documentation\/openwrapsdk\/pobnativeeventtype"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType/OMID":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTypeOMID"}],"abstract":[{"text":"Signifies the event as OMID event.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMID"}],"title":"POBNativeEventType.OMID","type":"topic","url":"\/documentation\/openwrapsdk\/pobnativeeventtype\/omid","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/OMID"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeEventTypeOMID"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"POBNativeEventTypeOMID","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"POBNativeEventTypeOMID","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType\/title","value":"POBNativeEventType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType\/fragments","value":[{"kind":"identifier","text":"POBNativeEventType"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1OMID\/title","value":"POBNativeEventTypeOMID","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1OMID\/fragments","value":[{"kind":"identifier","text":"POBNativeEventTypeOMID"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}