{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewMRC50"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/viewMRC50"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType"]]},"abstract":[{"type":"text","text":"Visible impression using MRC definition at 50% in view for 1 second"}],"metadata":{"title":"POBNativeEventType.viewMRC50","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTypeViewMRC50"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"viewMRC50","kind":"identifier"}],"externalID":"c:@E@POBNativeEventType@POBNativeEventTypeViewMRC50","modules":[{"name":"OpenWrapSDK"}],"symbolKind":"case"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeeventtype\/viewmrc50"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeeventtype\/viewmrc50"]}],"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType/viewMRC50":{"title":"POBNativeEventType.viewMRC50","url":"\/documentation\/openwrapsdk\/pobnativeeventtype\/viewmrc50","navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTypeViewMRC50"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewMRC50"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/viewMRC50","abstract":[{"type":"text","text":"Visible impression using MRC definition at 50% in view for 1 second"}],"kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventType"}],"abstract":[{"type":"text","text":"Native Event Type for Event Tracking"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeEventType","kind":"identifier"}],"title":"POBNativeEventType","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType","url":"\/documentation\/openwrapsdk\/pobnativeeventtype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"POBNativeEventTypeViewMRC50"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBNativeEventTypeViewMRC50"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"POBNativeEventTypeViewMRC50"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1viewMRC50\/title","value":"POBNativeEventTypeViewMRC50","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1viewMRC50\/fragments","value":[{"text":"POBNativeEventTypeViewMRC50","kind":"identifier"}]},{"op":"replace","value":"POBNativeEventType","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType\/title"},{"value":[{"text":"POBNativeEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType\/fragments"}]}]}