{"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeeventtype\/viewmrc100"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeeventtype\/viewmrc100"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/viewMRC100"},"kind":"symbol","metadata":{"modules":[{"name":"OpenWrapSDK"}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTypeViewMRC100"}],"externalID":"c:@E@POBNativeEventType@POBNativeEventTypeViewMRC100","title":"POBNativeEventType.viewMRC100","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"viewMRC100","kind":"identifier"}],"role":"symbol","symbolKind":"case"},"abstract":[{"type":"text","text":"100% in view for 1 second (ie GroupM standard)"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewMRC100"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventType"}],"abstract":[{"type":"text","text":"Native Event Type for Event Tracking"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeEventType","kind":"identifier"}],"title":"POBNativeEventType","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType","url":"\/documentation\/openwrapsdk\/pobnativeeventtype"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType/viewMRC100":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewMRC100","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/viewMRC100","navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTypeViewMRC100"}],"title":"POBNativeEventType.viewMRC100","url":"\/documentation\/openwrapsdk\/pobnativeeventtype\/viewmrc100","abstract":[{"type":"text","text":"100% in view for 1 second (ie GroupM standard)"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"POBNativeEventTypeViewMRC100","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBNativeEventTypeViewMRC100","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"POBNativeEventTypeViewMRC100","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"POBNativeEventType","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"POBNativeEventType"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1viewMRC100\/title","op":"replace","value":"POBNativeEventTypeViewMRC100"},{"value":[{"text":"POBNativeEventTypeViewMRC100","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1viewMRC100\/fragments"}]}]}