{"sections":[],"abstract":[{"type":"text","text":"The object that acts as the bidder delegate of the bidder & interested in getting notificaiton from bidder about bit success\/failure response."}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/bidderDelegate","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bidderDelegate"},{"text":": (any ","kind":"text"},{"text":"POBBidderDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBidderDelegate"},{"kind":"text","text":")?"}],"required":true,"externalID":"c:objc(pl)POBBidding(py)bidderDelegate","navigatorTitle":[{"kind":"identifier","text":"bidderDelegate"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"OpenWrapSDK"}],"title":"bidderDelegate","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bidderDelegate"},{"kind":"text","text":": (any "},{"text":"POBBidderDelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidderDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBidderDelegate"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobbidding\/bidderdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobbidding\/bidderdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidding":{"url":"\/documentation\/openwrapsdk\/pobbidding","role":"symbol","kind":"symbol","title":"POBBidding","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding","navigatorTitle":[{"text":"POBBidding","kind":"identifier"}],"type":"topic","abstract":[{"text":"Ad bidding protocol, which lists methods to be implmented to add new bidder. which is responsible for getting bids from various bidders.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidding"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidderDelegate":{"navigatorTitle":[{"kind":"identifier","text":"POBBidderDelegate"}],"url":"\/documentation\/openwrapsdk\/pobbidderdelegate","abstract":[{"text":"Ad bidder delegate protocol, which lists methods to be implmented by bidder delegate receiver.","type":"text"}],"kind":"symbol","title":"POBBidderDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBBidderDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidderDelegate","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidding/bidderDelegate":{"type":"topic","abstract":[{"type":"text","text":"The object that acts as the bidder delegate of the bidder & interested in getting notificaiton from bidder about bit success\/failure response."}],"navigatorTitle":[{"kind":"identifier","text":"bidderDelegate"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/bidderDelegate","title":"bidderDelegate","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bidderDelegate"},{"kind":"text","text":": (any "},{"text":"POBBidderDelegate","preciseIdentifier":"c:objc(pl)POBBidderDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbidding\/bidderdelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"bidderDelegate","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"bidderDelegate","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<POBBidderDelegate>","preciseIdentifier":"c:Qoobjc(pl)POBBidderDelegate"},{"text":" ","kind":"text"},{"text":"bidderDelegate","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding\/title","value":"POBBidding"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding\/fragments","op":"replace","value":[{"text":"POBBidding","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidderDelegate\/title","value":"POBBidderDelegate"},{"value":[{"text":"POBBidderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidderDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding~1bidderDelegate\/title","value":"bidderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding~1bidderDelegate\/fragments","value":[{"text":"bidderDelegate","kind":"identifier"}]}]}]}