{"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadimageresponseasset\/initwithtype:width:height:url:builder:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"initWithType:width:height:url:builder:","navigatorTitle":[{"text":"initWithType:width:height:url:builder:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:width:height:url:builder:"}],"roleHeading":"Instance Method","modules":[{"name":"OpenWrapSDK"}],"role":"symbol","symbolKind":"method","externalID":"c:objc(cs)POBNativeAdImageResponseAsset(im)initWithType:width:height:url:builder:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/initWithType:width:height:url:builder:","interfaceLanguage":"occ"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeImageAssetType","preciseIdentifier":"c:@E@POBNativeImageAssetType","text":"POBNativeImageAssetType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"width:"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"width","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"height:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"height","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"url:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"imageURL","kind":"internalParam"},{"kind":"text","text":" "},{"text":"builder:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"POBNativeAdResponseAssetBuilder","preciseIdentifier":"c:objc(cs)POBNativeAdResponseAssetBuilder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"builder"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeImageAssetType":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeImageAssetType","kind":"symbol","type":"topic","title":"POBNativeImageAssetType","navigatorTitle":[{"text":"POBNativeImageAssetType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeImageAssetType"}],"abstract":[{"type":"text","text":"Native Image Asset Type"}],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeimageassettype"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdImageResponseAsset":{"url":"\/documentation\/openwrapsdk\/pobnativeadimageresponseasset","title":"POBNativeAdImageResponseAsset","navigatorTitle":[{"text":"POBNativeAdImageResponseAsset","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAdImageResponseAsset","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset","kind":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdImageResponseAsset/initWithType:width:height:url:builder:":{"url":"\/documentation\/openwrapsdk\/pobnativeadimageresponseasset\/initwithtype:width:height:url:builder:","title":"initWithType:width:height:url:builder:","navigatorTitle":[{"text":"initWithType:width:height:url:builder:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithType:width:height:url:builder:","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/initWithType:width:height:url:builder:","kind":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"POBNativeImageAssetType","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeImageAssetType\/title","op":"replace"},{"value":[{"text":"POBNativeImageAssetType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeImageAssetType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdImageResponseAsset\/title","value":"POBNativeAdImageResponseAsset"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdImageResponseAsset\/fragments","value":[{"text":"POBNativeAdImageResponseAsset","kind":"identifier"}]}]}]}