{"abstract":[{"text":"Descriptive text associated with the product or text service being advertised. Value is of type Text","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativedataassettype\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativedataassettype\/description"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/description"},"metadata":{"role":"symbol","title":"POBNativeDataAssetType.description","roleHeading":"Case","externalID":"c:@E@POBNativeDataAssetType@POBNativeDataAssetTypeDescription","navigatorTitle":[{"text":"POBNativeDataAssetTypeDescription","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"}],"symbolKind":"case"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/description":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/description","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/description","title":"POBNativeDataAssetType.description","abstract":[{"text":"Descriptive text associated with the product or text service being advertised. Value is of type Text","type":"text"}],"navigatorTitle":[{"text":"POBNativeDataAssetTypeDescription","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeDataAssetType","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Native Data asset types"}],"navigatorTitle":[{"text":"POBNativeDataAssetType","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativedataassettype","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType","title":"POBNativeDataAssetType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"POBNativeDataAssetTypeDescription","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"POBNativeDataAssetTypeDescription"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"POBNativeDataAssetTypeDescription","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1description\/title","value":"POBNativeDataAssetTypeDescription","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1description\/fragments","value":[{"kind":"identifier","text":"POBNativeDataAssetTypeDescription"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/title","value":"POBNativeDataAssetType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/fragments","value":[{"text":"POBNativeDataAssetType","kind":"identifier"}]}]}]}