{"abstract":[{"type":"text","text":"Additional descriptive text associated with the product or service being advertised. Value will be Text"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/description2"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativedataassettype\/description2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativedataassettype\/description2"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description2"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"POBNativeDataAssetTypeDescription2"}],"role":"symbol","title":"POBNativeDataAssetType.description2","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description2","kind":"identifier"}],"externalID":"c:@E@POBNativeDataAssetType@POBNativeDataAssetTypeDescription2","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/description2":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/description2","kind":"symbol","role":"symbol","title":"POBNativeDataAssetType.description2","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/description2","abstract":[{"text":"Additional descriptive text associated with the product or service being advertised. Value will be Text","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeDataAssetTypeDescription2"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"description2","kind":"identifier"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeDataAssetType","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Native Data asset types"}],"navigatorTitle":[{"text":"POBNativeDataAssetType","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativedataassettype","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType","title":"POBNativeDataAssetType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeDataAssetTypeDescription2"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"POBNativeDataAssetTypeDescription2","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"POBNativeDataAssetTypeDescription2","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1description2\/title","value":"POBNativeDataAssetTypeDescription2"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1description2\/fragments","value":[{"text":"POBNativeDataAssetTypeDescription2","kind":"identifier"}],"op":"replace"},{"value":"POBNativeDataAssetType","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/fragments","op":"replace","value":[{"text":"POBNativeDataAssetType","kind":"identifier"}]}]}]}