{"kind":"symbol","identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/phone","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativedataassettype\/phone"]},{"paths":["\/documentation\/openwrapsdk\/pobnativedataassettype\/phone"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Represents Phone number of user. Value will be string","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"phone"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","externalID":"c:@E@POBNativeDataAssetType@POBNativeDataAssetTypePhone","navigatorTitle":[{"text":"POBNativeDataAssetTypePhone","kind":"identifier"}],"title":"POBNativeDataAssetType.phone","roleHeading":"Case","symbolKind":"case"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/phone":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/phone","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/phone","title":"POBNativeDataAssetType.phone","abstract":[{"type":"text","text":"Represents Phone number of user. Value will be string"}],"navigatorTitle":[{"text":"POBNativeDataAssetTypePhone","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeDataAssetType","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Native Data asset types"}],"navigatorTitle":[{"text":"POBNativeDataAssetType","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativedataassettype","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType","title":"POBNativeDataAssetType"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"POBNativeDataAssetTypePhone","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"POBNativeDataAssetTypePhone"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"POBNativeDataAssetTypePhone","kind":"identifier"}]}]}},{"value":"POBNativeDataAssetTypePhone","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1phone\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1phone\/fragments","value":[{"kind":"identifier","text":"POBNativeDataAssetTypePhone"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/title","value":"POBNativeDataAssetType"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/fragments","value":[{"kind":"identifier","text":"POBNativeDataAssetType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}