{"abstract":[{"text":"\/ Rating of the product being offered to the user. For example an app’s rating in an app store from 0-5.Value will be    number formatted as string","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativedataassettype\/rating"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativedataassettype\/rating"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rating"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rating"}],"externalID":"c:@E@POBNativeDataAssetType@POBNativeDataAssetTypeRating","modules":[{"name":"OpenWrapSDK"}],"symbolKind":"case","title":"POBNativeDataAssetType.rating","roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"POBNativeDataAssetTypeRating","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/rating","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/rating":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/rating","kind":"symbol","role":"symbol","title":"POBNativeDataAssetType.rating","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/rating","abstract":[{"type":"text","text":"\/ Rating of the product being offered to the user. For example an app’s rating in an app store from 0-5.Value will be    number formatted as string"}],"navigatorTitle":[{"text":"POBNativeDataAssetTypeRating","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"rating","kind":"identifier"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeDataAssetType","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Native Data asset types"}],"navigatorTitle":[{"text":"POBNativeDataAssetType","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativedataassettype","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType","title":"POBNativeDataAssetType"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"POBNativeDataAssetTypeRating","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"POBNativeDataAssetTypeRating","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"POBNativeDataAssetTypeRating"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"POBNativeDataAssetTypeRating","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1rating\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1rating\/fragments","value":[{"text":"POBNativeDataAssetTypeRating","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/title","op":"replace","value":"POBNativeDataAssetType"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/fragments","value":[{"kind":"identifier","text":"POBNativeDataAssetType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}