{"metadata":{"modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Instance Method","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adServerDidWin"},{"kind":"text","text":"()"}],"symbolKind":"method","navigatorTitle":[{"text":"adServerDidWin","kind":"identifier"}],"externalID":"c:objc(pl)POBAdServerSignalingEventDelegate(im)adServerDidWin","title":"adServerDidWin()"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/adServerDidWin()"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adServerDidWin"},{"kind":"text","text":"()"}]}]}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/adserverdidwin()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/adserverdidwin()"]}],"sections":[],"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdServerSignalingEventDelegate":{"type":"topic","title":"POBAdServerSignalingEventDelegate","url":"\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBAdServerSignalingEventDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"POBAdServerSignalingEventDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdServerSignalingEventDelegate/adServerDidWin()":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/adServerDidWin()","url":"\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/adserverdidwin()","kind":"symbol","required":true,"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adServerDidWin"},{"kind":"text","text":"()"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"adServerDidWin"}],"title":"adServerDidWin()"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"adServerDidWin","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"adServerDidWin","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"adServerDidWin"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate\/title","value":"POBAdServerSignalingEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate\/fragments","value":[{"text":"POBAdServerSignalingEventDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1adServerDidWin()\/title","value":"adServerDidWin","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1adServerDidWin()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adServerDidWin","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}