{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bidsProvider","kind":"identifier"},{"kind":"text","text":"() -> (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBidsProvider","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidsProvider","text":"POBBidsProvider"},{"text":")?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/bidsProvider()"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/bidsprovider()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/bidsprovider()"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bidsProvider","kind":"identifier"},{"text":"() -> (any ","kind":"text"},{"kind":"typeIdentifier","text":"POBBidsProvider","preciseIdentifier":"c:objc(pl)POBBidsProvider"},{"kind":"text","text":")?"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","externalID":"c:objc(pl)POBAdServerSignalingEventDelegate(im)bidsProvider","navigatorTitle":[{"kind":"identifier","text":"bidsProvider"}],"title":"bidsProvider()","roleHeading":"Instance Method","symbolKind":"method","required":true},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdServerSignalingEventDelegate":{"type":"topic","title":"POBAdServerSignalingEventDelegate","url":"\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBAdServerSignalingEventDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"POBAdServerSignalingEventDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdServerSignalingEventDelegate/bidsProvider()":{"required":true,"title":"bidsProvider()","url":"\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/bidsprovider()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/bidsProvider()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bidsProvider"},{"text":"() -> (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBidsProvider","text":"POBBidsProvider"},{"kind":"text","text":")?"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bidsProvider"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidsProvider":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidsProvider"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"POBBidsProvider","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbidsprovider","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidsProvider","title":"POBBidsProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"bidsProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"bidsProvider","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id<POBBidsProvider>","preciseIdentifier":"c:Qoobjc(pl)POBBidsProvider","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"bidsProvider"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate\/title","value":"POBAdServerSignalingEventDelegate"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate\/fragments","op":"replace","value":[{"text":"POBAdServerSignalingEventDelegate","kind":"identifier"}]},{"op":"replace","value":"bidsProvider","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1bidsProvider()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bidsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1bidsProvider()\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidsProvider\/title","value":"POBBidsProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidsProvider\/fragments","value":[{"kind":"identifier","text":"POBBidsProvider"}]}]}]}