{"sections":[],"metadata":{"modules":[{"name":"OpenWrapSDK"}],"platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"2.0"}],"symbolKind":"method","title":"viewControllerForPresentingModal()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewControllerForPresentingModal"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewControllerForPresentingModal","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"required":true,"externalID":"c:objc(pl)POBAdServerSignalingEventDelegate(im)viewControllerForPresentingModal"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/viewcontrollerforpresentingmodal()"]},{"paths":["\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/viewcontrollerforpresentingmodal()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewControllerForPresentingModal"},{"text":"() -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/viewControllerForPresentingModal()"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdServerSignalingEventDelegate":{"type":"topic","title":"POBAdServerSignalingEventDelegate","url":"\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBAdServerSignalingEventDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"POBAdServerSignalingEventDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdServerSignalingEventDelegate/viewControllerForPresentingModal()":{"type":"topic","title":"viewControllerForPresentingModal()","url":"\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/viewcontrollerforpresentingmodal()","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewControllerForPresentingModal","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"viewControllerForPresentingModal"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/viewControllerForPresentingModal()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"viewControllerForPresentingModal","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewControllerForPresentingModal","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"viewControllerForPresentingModal"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate\/title","op":"replace","value":"POBAdServerSignalingEventDelegate"},{"value":[{"text":"POBAdServerSignalingEventDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate\/fragments","op":"replace"},{"op":"replace","value":"viewControllerForPresentingModal","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1viewControllerForPresentingModal()\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1viewControllerForPresentingModal()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewControllerForPresentingModal"}]}]}]}