{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interactionDelegate"},{"text":"() -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)POBFullscreenAdInteractionDelegate","text":"POBFullscreenAdInteractionDelegate","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(pl)POBInterstitialEvent(im)interactionDelegate","title":"interactionDelegate()","modules":[{"name":"OpenWrapSDK"}],"navigatorTitle":[{"text":"interactionDelegate","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interactionDelegate","kind":"identifier"},{"kind":"text","text":"() -> any "},{"kind":"typeIdentifier","text":"POBFullscreenAdInteractionDelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate","preciseIdentifier":"c:objc(pl)POBFullscreenAdInteractionDelegate"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEvent\/interactionDelegate()"},"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobinterstitialevent\/interactiondelegate()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialevent\/interactiondelegate()"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEvent"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEvent":{"type":"topic","title":"POBInterstitialEvent","abstract":[{"type":"text","text":"The interstitial custom event protocol. Your interstitial custom event handler must implement this protocol to communicate with ad server SDK."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBInterstitialEvent"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialEvent","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialevent","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEvent/interactionDelegate()":{"abstract":[],"title":"interactionDelegate()","type":"topic","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEvent\/interactionDelegate()","navigatorTitle":[{"text":"interactionDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interactionDelegate","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"kind":"typeIdentifier","text":"POBFullscreenAdInteractionDelegate","preciseIdentifier":"c:objc(pl)POBFullscreenAdInteractionDelegate"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialevent\/interactiondelegate()","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate":{"role":"symbol","title":"POBFullscreenAdInteractionDelegate","navigatorTitle":[{"kind":"identifier","text":"POBFullscreenAdInteractionDelegate"}],"abstract":[{"type":"text","text":"This delegate is used to inform the fullscreen ad events from OpenWrap SDK ads. Implement this if your ad server implementation requires to be informed about these events."}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBFullscreenAdInteractionDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"interactionDelegate","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"interactionDelegate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id<POBFullscreenAdInteractionDelegate>","preciseIdentifier":"c:Qoobjc(pl)POBFullscreenAdInteractionDelegate","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"interactionDelegate","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEvent\/title","value":"POBInterstitialEvent"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEvent\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBInterstitialEvent"}]},{"value":"interactionDelegate","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEvent~1interactionDelegate()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interactionDelegate"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEvent~1interactionDelegate()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate\/title","op":"replace","value":"POBFullscreenAdInteractionDelegate"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate\/fragments","value":[{"text":"POBFullscreenAdInteractionDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}