{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderer"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPartner"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"partner"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> (any ","kind":"text"},{"text":"POBInterstitialRendering","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBInterstitialRendering"},{"text":")?","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"name of the partner associated with the winning bid","type":"text"}]}],"name":"partner"}]}],"abstract":[{"text":"Optional delegate to provide implementation of POBInterstitialRendering protocol to render ad in custom rendering component. If not implemented, the OpenWrap SDK internally creates its own renderer capable of handling simple HTML and MRAID creatives","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEvent"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEvent\/renderer(forPartner:)"},"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"rendererForPartner:","kind":"identifier"}],"role":"symbol","title":"renderer(forPartner:)","roleHeading":"Instance Method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderer","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPartner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> (any "},{"text":"POBInterstitialRendering","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBInterstitialRendering"},{"text":")?","kind":"text"}],"externalID":"c:objc(pl)POBInterstitialEvent(im)rendererForPartner:","modules":[{"name":"OpenWrapSDK"}]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobinterstitialevent\/renderer(forpartner:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialevent\/renderer(forpartner:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEvent/renderer(forPartner:)":{"abstract":[{"text":"Optional delegate to provide implementation of POBInterstitialRendering protocol to render ad in custom rendering component. If not implemented, the OpenWrap SDK internally creates its own renderer capable of handling simple HTML and MRAID creatives","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderer"},{"text":"(","kind":"text"},{"text":"forPartner","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> (any ","kind":"text"},{"text":"POBInterstitialRendering","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBInterstitialRendering"},{"text":")?","kind":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"rendererForPartner:"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEvent\/renderer(forPartner:)","url":"\/documentation\/openwrapsdk\/pobinterstitialevent\/renderer(forpartner:)","title":"renderer(forPartner:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEvent":{"type":"topic","title":"POBInterstitialEvent","abstract":[{"type":"text","text":"The interstitial custom event protocol. Your interstitial custom event handler must implement this protocol to communicate with ad server SDK."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBInterstitialEvent"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialEvent","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialevent","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendering":{"navigatorTitle":[{"text":"POBInterstitialRendering","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialRendering","kind":"identifier"}],"abstract":[{"type":"text","text":"Ad interstitial rendering protocol, implement these methods to write custom ad renderer"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendering","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering","title":"POBInterstitialRendering","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rendererForPartner:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"rendererForPartner:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id<POBInterstitialRendering>","preciseIdentifier":"c:Qoobjc(pl)POBInterstitialRendering"},{"kind":"text","text":") "},{"kind":"identifier","text":"rendererForPartner:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"partner"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"rendererForPartner:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEvent~1renderer(forPartner:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rendererForPartner:"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEvent~1renderer(forPartner:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEvent\/title","value":"POBInterstitialEvent"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEvent\/fragments","op":"replace","value":[{"text":"POBInterstitialEvent","kind":"identifier"}]},{"value":"POBInterstitialRendering","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering\/fragments","op":"replace","value":[{"text":"POBInterstitialRendering","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}