{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"createBridge","kind":"identifier"}],"role":"symbol","title":"createBridge()","roleHeading":"Instance Method","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createBridge","kind":"identifier"},{"kind":"text","text":"() -> any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAdEventBridge","text":"POBNativeAdEventBridge"}],"externalID":"c:objc(pl)POBNativeAdEvent(im)createBridge","modules":[{"name":"OpenWrapSDK"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createBridge"},{"kind":"text","text":"() -> any "},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge","kind":"typeIdentifier","text":"POBNativeAdEventBridge","preciseIdentifier":"c:objc(pl)POBNativeAdEventBridge"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadevent\/createbridge()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadevent\/createbridge()"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEvent"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEvent\/createBridge()"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEvent/createBridge()":{"required":true,"url":"\/documentation\/openwrapsdk\/pobnativeadevent\/createbridge()","abstract":[],"navigatorTitle":[{"text":"createBridge","kind":"identifier"}],"kind":"symbol","title":"createBridge()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createBridge","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"text":"POBNativeAdEventBridge","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAdEventBridge"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEvent\/createBridge()","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventBridge":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Bridge for the native custom event protocol that manages communication with an ad server SDK."}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeAdEventBridge"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadeventbridge","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdEventBridge"}],"title":"POBNativeAdEventBridge"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEvent":{"role":"symbol","navigatorTitle":[{"text":"POBNativeAdEvent","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAdEvent","kind":"identifier"}],"title":"POBNativeAdEvent","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadevent","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEvent","type":"topic","abstract":[{"text":"The native custom event protocol. Your native custom event handler must implement this protocol to communicate with the ad server SDK.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"createBridge"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createBridge"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id<POBNativeAdEventBridge>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)POBNativeAdEventBridge"},{"kind":"text","text":") "},{"kind":"identifier","text":"createBridge"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEvent~1createBridge()\/title","op":"replace","value":"createBridge"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEvent~1createBridge()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createBridge"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge\/title","value":"POBNativeAdEventBridge","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge\/fragments","value":[{"text":"POBNativeAdEventBridge","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEvent\/title","value":"POBNativeAdEvent"},{"value":[{"text":"POBNativeAdEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEvent\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}