{"kind":"symbol","metadata":{"role":"symbol","title":"clickTrackers","roleHeading":"Instance Property","externalID":"c:objc(pl)POBAdDescriptor(py)clickTrackers","navigatorTitle":[{"text":"clickTrackers","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clickTrackers","kind":"identifier"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"clickTrackers","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobaddescriptor\/clicktrackers"]},{"paths":["\/documentation\/openwrapsdk\/pobaddescriptor\/clicktrackers"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor\/clickTrackers"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdDescriptor":{"url":"\/documentation\/openwrapsdk\/pobaddescriptor","type":"topic","title":"POBAdDescriptor","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBAdDescriptor"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor","role":"symbol","abstract":[{"type":"text","text":"Ad descriptor protocol, provided creative string through "},{"type":"codeVoice","code":"renderableContent"},{"text":". POBAdRendering protocol renders object which conforms to POBAdDescriptor protocol","type":"text"}],"navigatorTitle":[{"text":"POBAdDescriptor","kind":"identifier"}],"kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdDescriptor/clickTrackers":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"clickTrackers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"clickTrackers","kind":"identifier"}],"title":"clickTrackers","abstract":[],"url":"\/documentation\/openwrapsdk\/pobaddescriptor\/clicktrackers","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor\/clickTrackers"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"clickTrackers","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"clickTrackers","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"clickTrackers","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor\/title","value":"POBAdDescriptor"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBAdDescriptor"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor~1clickTrackers\/title","value":"clickTrackers","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor~1clickTrackers\/fragments","op":"replace","value":[{"text":"clickTrackers","kind":"identifier"}]}]}]}