{"abstract":[{"type":"text","text":"Returns whether SDK should render the DSA data."}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor\/shouldRenderDSAData","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobaddescriptor\/shouldrenderdsadata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobaddescriptor\/shouldrenderdsadata"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldRenderDSAData","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"shouldRenderDSAData","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","title":"shouldRenderDSAData","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldRenderDSAData","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:objc(pl)POBAdDescriptor(py)shouldRenderDSAData","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdDescriptor/shouldRenderDSAData":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor\/shouldRenderDSAData","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobaddescriptor\/shouldrenderdsadata","title":"shouldRenderDSAData","abstract":[{"type":"text","text":"Returns whether SDK should render the DSA data."}],"navigatorTitle":[{"kind":"identifier","text":"shouldRenderDSAData"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shouldRenderDSAData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdDescriptor":{"url":"\/documentation\/openwrapsdk\/pobaddescriptor","type":"topic","title":"POBAdDescriptor","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBAdDescriptor"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor","role":"symbol","abstract":[{"type":"text","text":"Ad descriptor protocol, provided creative string through "},{"type":"codeVoice","code":"renderableContent"},{"text":". POBAdRendering protocol renders object which conforms to POBAdDescriptor protocol","type":"text"}],"navigatorTitle":[{"text":"POBAdDescriptor","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"shouldRenderDSAData","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"shouldRenderDSAData"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"shouldRenderDSAData","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor~1shouldRenderDSAData\/title","value":"shouldRenderDSAData"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor~1shouldRenderDSAData\/fragments","op":"replace","value":[{"text":"shouldRenderDSAData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor\/title","value":"POBAdDescriptor"},{"value":[{"kind":"identifier","text":"POBAdDescriptor"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}