{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKLogLevel\/all","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"All logs","type":"text"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"POBSDKLogLevelAll","kind":"identifier"}],"externalID":"c:@E@POBSDKLogLevel@POBSDKLogLevelAll","roleHeading":"Case","symbolKind":"case","title":"POBSDKLogLevel.all","modules":[{"name":"OpenWrapSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"all"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobsdkloglevel\/all"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobsdkloglevel\/all"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKLogLevel"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKLogLevel":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBSDKLogLevel","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobsdkloglevel","abstract":[{"type":"text","text":"Log levels to filter logs."}],"title":"POBSDKLogLevel","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKLogLevel","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBSDKLogLevel"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKLogLevel/all":{"abstract":[{"type":"text","text":"All logs"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBSDKLogLevelAll"}],"url":"\/documentation\/openwrapsdk\/pobsdkloglevel\/all","type":"topic","title":"POBSDKLogLevel.all","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"all","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKLogLevel\/all","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"POBSDKLogLevelAll","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"POBSDKLogLevelAll","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"POBSDKLogLevelAll","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKLogLevel\/title","value":"POBSDKLogLevel","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKLogLevel\/fragments","value":[{"text":"POBSDKLogLevel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKLogLevel~1all\/title","value":"POBSDKLogLevelAll"},{"op":"replace","value":[{"text":"POBSDKLogLevelAll","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKLogLevel~1all\/fragments"}]}]}