{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKLogLevel"]]},"abstract":[{"type":"text","text":"Error, warning, info, debug and verbose logs"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKLogLevel\/verbose"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"POBSDKLogLevel.verbose","navigatorTitle":[{"text":"POBSDKLogLevelVerbose","kind":"identifier"}],"externalID":"c:@E@POBSDKLogLevel@POBSDKLogLevelVerbose","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verbose","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobsdkloglevel\/verbose"]},{"paths":["\/documentation\/openwrapsdk\/pobsdkloglevel\/verbose"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"verbose","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKLogLevel/verbose":{"navigatorTitle":[{"text":"POBSDKLogLevelVerbose","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKLogLevel\/verbose","role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobsdkloglevel\/verbose","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verbose","kind":"identifier"}],"abstract":[{"text":"Error, warning, info, debug and verbose logs","type":"text"}],"title":"POBSDKLogLevel.verbose","kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKLogLevel":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBSDKLogLevel","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobsdkloglevel","abstract":[{"type":"text","text":"Log levels to filter logs."}],"title":"POBSDKLogLevel","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKLogLevel","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBSDKLogLevel"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"POBSDKLogLevelVerbose","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"POBSDKLogLevelVerbose","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"POBSDKLogLevelVerbose","kind":"identifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKLogLevel~1verbose\/title","op":"replace","value":"POBSDKLogLevelVerbose"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKLogLevel~1verbose\/fragments","op":"replace","value":[{"text":"POBSDKLogLevelVerbose","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKLogLevel\/title","op":"replace","value":"POBSDKLogLevel"},{"op":"replace","value":[{"text":"POBSDKLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKLogLevel\/fragments"}]}]}