{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig\/contextSubType","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(cs)POBNativeAdLoaderConfig(py)contextSubType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contextSubType"},{"text":": ","kind":"text"},{"text":"POBNativeContextSubType","preciseIdentifier":"c:@E@POBNativeContextSubType","kind":"typeIdentifier"}],"title":"contextSubType","role":"symbol","navigatorTitle":[{"text":"contextSubType","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contextSubType"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType","kind":"typeIdentifier","text":"POBNativeContextSubType","preciseIdentifier":"c:@E@POBNativeContextSubType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadloaderconfig\/contextsubtype"]},{"paths":["\/documentation\/openwrapsdk\/pobnativeadloaderconfig\/contextsubtype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoaderConfig":{"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadloaderconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdLoaderConfig"}],"title":"POBNativeAdLoaderConfig","role":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"POBNativeAdLoaderConfig"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType":{"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeContextSubType"}],"title":"POBNativeContextSubType","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType","type":"topic","abstract":[{"type":"text","text":"Next-level context in which the ad appears. Again this reflects the primary context, and does not imply no presence of other elements."}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeContextSubType"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoaderConfig/contextSubType":{"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadloaderconfig\/contextsubtype","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contextSubType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"POBNativeContextSubType","preciseIdentifier":"c:@E@POBNativeContextSubType"}],"title":"contextSubType","role":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig\/contextSubType","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"contextSubType"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"contextSubType","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"contextSubType"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@POBNativeContextSubType","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType","text":"POBNativeContextSubType"},{"kind":"text","text":" "},{"text":"contextSubType","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"POBNativeAdLoaderConfig","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderConfig\/title"},{"value":[{"text":"POBNativeAdLoaderConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderConfig\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType\/title","value":"POBNativeContextSubType"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType\/fragments","value":[{"text":"POBNativeContextSubType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderConfig~1contextSubType\/title","value":"contextSubType","op":"replace"},{"value":[{"text":"contextSubType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderConfig~1contextSubType\/fragments"}]}]}