{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeAllSegments","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"method","title":"removeAllSegments()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"removeAllSegments"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeAllSegments","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:objc(cs)POBDataProvider(im)removeAllSegments"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobdataprovider\/removeallsegments()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobdataprovider\/removeallsegments()"]}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider\/removeAllSegments()","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDataProvider/removeAllSegments()":{"type":"topic","title":"removeAllSegments()","url":"\/documentation\/openwrapsdk\/pobdataprovider\/removeallsegments()","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAllSegments","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"removeAllSegments","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider\/removeAllSegments()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDataProvider":{"role":"symbol","title":"POBDataProvider","url":"\/documentation\/openwrapsdk\/pobdataprovider","navigatorTitle":[{"text":"POBDataProvider","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBDataProvider","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"removeAllSegments","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"removeAllSegments","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"removeAllSegments"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"removeAllSegments","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDataProvider~1removeAllSegments()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDataProvider~1removeAllSegments()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"removeAllSegments","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDataProvider\/title","value":"POBDataProvider"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDataProvider\/fragments","op":"replace","value":[{"text":"POBDataProvider","kind":"identifier"}]}]}]}