{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider\/segment(forId:)"},"sections":[],"metadata":{"navigatorTitle":[{"text":"segmentForId:","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(cs)POBDataProvider(im)segmentForId:","title":"segment(forId:)","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"segment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBSegment","text":"POBSegment"},{"kind":"text","text":"?"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"segment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"POBSegment","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSegment","preciseIdentifier":"c:objc(cs)POBSegment"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobdataprovider\/segment(forid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobdataprovider\/segment(forid:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDataProvider/segment(forId:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"segment","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"text":"POBSegment","preciseIdentifier":"c:objc(cs)POBSegment","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"segmentForId:","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider\/segment(forId:)","title":"segment(forId:)","kind":"symbol","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobdataprovider\/segment(forid:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSegment":{"title":"POBSegment","url":"\/documentation\/openwrapsdk\/pobsegment","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSegment","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBSegment","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBSegment"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDataProvider":{"role":"symbol","title":"POBDataProvider","url":"\/documentation\/openwrapsdk\/pobdataprovider","navigatorTitle":[{"text":"POBDataProvider","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBDataProvider","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"segmentForId:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"segmentForId:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"POBSegment","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSegment","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBSegment"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"segmentForId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDataProvider~1segment(forId:)\/title","op":"replace","value":"segmentForId:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDataProvider~1segment(forId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"segmentForId:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSegment\/title","value":"POBSegment"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSegment\/fragments","value":[{"kind":"identifier","text":"POBSegment"}]},{"value":"POBDataProvider","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDataProvider\/title"},{"value":[{"kind":"identifier","text":"POBDataProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDataProvider\/fragments"}]}]}