{"metadata":{"navigatorTitle":[{"text":"POBLinearityAny","kind":"identifier"}],"title":"POBLinearity.any","symbolKind":"case","externalID":"c:@E@POBLinearity@POBLinearityAny","modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"any","kind":"identifier"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"any","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/poblinearity\/any"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/poblinearity\/any"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Video Linearity type Any"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/any"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLinearity/any":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/any","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"any"}],"role":"symbol","title":"POBLinearity.any","navigatorTitle":[{"text":"POBLinearityAny","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/poblinearity\/any","abstract":[{"type":"text","text":"Video Linearity type Any"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLinearity":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBLinearity"}],"role":"symbol","title":"POBLinearity","navigatorTitle":[{"text":"POBLinearity","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/poblinearity","abstract":[{"type":"text","text":"Expected video linearity type by Vast Player"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"POBLinearityAny"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"POBLinearityAny","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"POBLinearityAny","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"POBLinearityAny","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity~1any\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity~1any\/fragments","value":[{"text":"POBLinearityAny","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity\/title","value":"POBLinearity"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity\/fragments","value":[{"kind":"identifier","text":"POBLinearity"}],"op":"replace"}]}]}