{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"linearInStream","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"case","title":"POBLinearity.linearInStream","role":"symbol","navigatorTitle":[{"text":"POBLinearityLinearInStream","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"linearInStream","kind":"identifier"}],"externalID":"c:@E@POBLinearity@POBLinearityLinearInStream"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/poblinearity\/linearinstream"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/poblinearity\/linearinstream"]}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/linearInStream","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Video Linearity type In stream"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLinearity/linearInStream":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/linearInStream","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"linearInStream","kind":"identifier"}],"role":"symbol","title":"POBLinearity.linearInStream","navigatorTitle":[{"kind":"identifier","text":"POBLinearityLinearInStream"}],"url":"\/documentation\/openwrapsdk\/poblinearity\/linearinstream","abstract":[{"type":"text","text":"Video Linearity type In stream"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLinearity":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBLinearity"}],"role":"symbol","title":"POBLinearity","navigatorTitle":[{"text":"POBLinearity","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/poblinearity","abstract":[{"type":"text","text":"Expected video linearity type by Vast Player"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"POBLinearityLinearInStream"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"POBLinearityLinearInStream","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"POBLinearityLinearInStream"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity~1linearInStream\/title","value":"POBLinearityLinearInStream","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity~1linearInStream\/fragments","value":[{"kind":"identifier","text":"POBLinearityLinearInStream"}]},{"op":"replace","value":"POBLinearity","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity\/title"},{"value":[{"text":"POBLinearity","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity\/fragments","op":"replace"}]}]}