{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity"]]},"abstract":[{"text":"Video Linearity type Overlay","type":"text"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/nonLinearOverlay","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openwrapsdk\/poblinearity\/nonlinearoverlay"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/poblinearity\/nonlinearoverlay"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonLinearOverlay"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Case","title":"POBLinearity.nonLinearOverlay","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonLinearOverlay","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"navigatorTitle":[{"text":"POBLinearityNonLinearOverlay","kind":"identifier"}],"externalID":"c:@E@POBLinearity@POBLinearityNonLinearOverlay","symbolKind":"case","role":"symbol"},"kind":"symbol","sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLinearity/nonLinearOverlay":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/nonLinearOverlay","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonLinearOverlay"}],"role":"symbol","title":"POBLinearity.nonLinearOverlay","navigatorTitle":[{"text":"POBLinearityNonLinearOverlay","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/poblinearity\/nonlinearoverlay","abstract":[{"type":"text","text":"Video Linearity type Overlay"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLinearity":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBLinearity"}],"role":"symbol","title":"POBLinearity","navigatorTitle":[{"text":"POBLinearity","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/poblinearity","abstract":[{"type":"text","text":"Expected video linearity type by Vast Player"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"POBLinearityNonLinearOverlay"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"text":"POBLinearityNonLinearOverlay","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"POBLinearityNonLinearOverlay"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity~1nonLinearOverlay\/title","op":"replace","value":"POBLinearityNonLinearOverlay"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity~1nonLinearOverlay\/fragments","op":"replace","value":[{"text":"POBLinearityNonLinearOverlay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity\/title","value":"POBLinearity"},{"value":[{"kind":"identifier","text":"POBLinearity"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}