{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inArticle","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@E@POBPlacement@POBPlacementInArticle","modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"POBPlacementInArticle","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inArticle"}],"title":"POBPlacement.inArticle","symbolKind":"case"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Video ad in Article"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"inArticle","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobplacement\/inarticle"]},{"paths":["\/documentation\/openwrapsdk\/pobplacement\/inarticle"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement":{"role":"symbol","title":"POBPlacement","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBPlacement"}],"abstract":[{"type":"text","text":"Video ad placement type with respect to main content"}],"url":"\/documentation\/openwrapsdk\/pobplacement","navigatorTitle":[{"text":"POBPlacement","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement/inArticle":{"title":"POBPlacement.inArticle","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inArticle","url":"\/documentation\/openwrapsdk\/pobplacement\/inarticle","navigatorTitle":[{"kind":"identifier","text":"POBPlacementInArticle"}],"kind":"symbol","abstract":[{"text":"Video ad in Article","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inArticle"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"POBPlacementInArticle","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"POBPlacementInArticle","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"POBPlacementInArticle","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement\/title","value":"POBPlacement"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement\/fragments","value":[{"text":"POBPlacement","kind":"identifier"}]},{"value":"POBPlacementInArticle","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inArticle\/title","op":"replace"},{"value":[{"kind":"identifier","text":"POBPlacementInArticle"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inArticle\/fragments","op":"replace"}]}]}