{"abstract":[{"text":"Video ad in App feeds","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inFeed","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobplacement\/infeed"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobplacement\/infeed"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inFeed"},"metadata":{"externalID":"c:@E@POBPlacement@POBPlacementInFeed","modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBPlacementInFeed"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inFeed"}],"title":"POBPlacement.inFeed","symbolKind":"case"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement/inFeed":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"inFeed","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Video ad in App feeds","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBPlacementInFeed"}],"url":"\/documentation\/openwrapsdk\/pobplacement\/infeed","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inFeed","title":"POBPlacement.inFeed"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement":{"role":"symbol","title":"POBPlacement","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBPlacement"}],"abstract":[{"type":"text","text":"Video ad placement type with respect to main content"}],"url":"\/documentation\/openwrapsdk\/pobplacement","navigatorTitle":[{"text":"POBPlacement","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"POBPlacementInFeed"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"POBPlacementInFeed"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"POBPlacementInFeed","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inFeed\/title","value":"POBPlacementInFeed","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inFeed\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBPlacementInFeed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement\/title","value":"POBPlacement"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement\/fragments","value":[{"text":"POBPlacement","kind":"identifier"}]}]}]}