{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inStream"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inStream","interfaceLanguage":"swift"},"abstract":[{"text":"In-stream video ad","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"POBPlacementInStream","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"POBPlacement.inStream","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inStream","kind":"identifier"}],"externalID":"c:@E@POBPlacement@POBPlacementInStream","modules":[{"name":"OpenWrapSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobplacement\/instream"]},{"paths":["\/documentation\/openwrapsdk\/pobplacement\/instream"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement/inStream":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inStream"}],"url":"\/documentation\/openwrapsdk\/pobplacement\/instream","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inStream","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBPlacementInStream"}],"abstract":[{"type":"text","text":"In-stream video ad"}],"type":"topic","kind":"symbol","title":"POBPlacement.inStream"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement":{"role":"symbol","title":"POBPlacement","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBPlacement"}],"abstract":[{"type":"text","text":"Video ad placement type with respect to main content"}],"url":"\/documentation\/openwrapsdk\/pobplacement","navigatorTitle":[{"text":"POBPlacement","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"POBPlacementInStream"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBPlacementInStream","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"POBPlacementInStream","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inStream\/title","op":"replace","value":"POBPlacementInStream"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inStream\/fragments","op":"replace","value":[{"text":"POBPlacementInStream","kind":"identifier"}]},{"value":"POBPlacement","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement\/fragments","value":[{"kind":"identifier","text":"POBPlacement"}],"op":"replace"}]}]}