{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBRTBSkadnVersionsParam"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/kpobrtbskadnversionsparam"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/kpobrtbskadnversionsparam"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kPOBRTBSkadnVersionsParam"}],"externalID":"c:@kPOBRTBSkadnVersionsParam","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"kPOBRTBSkadnVersionsParam","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"kPOBRTBSkadnVersionsParam","modules":[{"name":"OpenWrapSDK"}],"symbolKind":"var","roleHeading":"Global Variable"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kPOBRTBSkadnVersionsParam","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/kPOBRTBSkadnVersionsParam":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBRTBSkadnVersionsParam","kind":"symbol","title":"kPOBRTBSkadnVersionsParam","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"kPOBRTBSkadnVersionsParam","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"kPOBRTBSkadnVersionsParam","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/kpobrtbskadnversionsparam"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"kPOBRTBSkadnVersionsParam"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"kPOBRTBSkadnVersionsParam","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"text":"kPOBRTBSkadnVersionsParam","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"kPOBRTBSkadnVersionsParam","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBRTBSkadnVersionsParam\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBRTBSkadnVersionsParam\/fragments","value":[{"text":"kPOBRTBSkadnVersionsParam","kind":"identifier"}],"op":"replace"}]}]}