{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kPOBRTBBoxingAllowedParam","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/kpobrtbboxingallowedparam"]},{"paths":["\/documentation\/openwrapsdk\/kpobrtbboxingallowedparam"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBRTBBoxingAllowedParam"},"metadata":{"role":"symbol","title":"kPOBRTBBoxingAllowedParam","roleHeading":"Global Variable","externalID":"c:@kPOBRTBBoxingAllowedParam","navigatorTitle":[{"text":"kPOBRTBBoxingAllowedParam","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"kPOBRTBBoxingAllowedParam","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"symbolKind":"var"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/kPOBRTBBoxingAllowedParam":{"navigatorTitle":[{"text":"kPOBRTBBoxingAllowedParam","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kPOBRTBBoxingAllowedParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/kpobrtbboxingallowedparam","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBRTBBoxingAllowedParam","title":"kPOBRTBBoxingAllowedParam","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"op":"replace","value":"kPOBRTBBoxingAllowedParam","path":"\/metadata\/title"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"kPOBRTBBoxingAllowedParam","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"text":"kPOBRTBBoxingAllowedParam","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"kPOBRTBBoxingAllowedParam","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBRTBBoxingAllowedParam\/title"},{"op":"replace","value":[{"text":"kPOBRTBBoxingAllowedParam","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBRTBBoxingAllowedParam\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}