{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBBidCrTypeExtPath","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kPOBBidCrTypeExtPath"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/kpobbidcrtypeextpath"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/kpobbidcrtypeextpath"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"kPOBBidCrTypeExtPath"}],"symbolKind":"var","roleHeading":"Global Variable","modules":[{"name":"OpenWrapSDK"}],"role":"symbol","externalID":"c:@kPOBBidCrTypeExtPath","title":"kPOBBidCrTypeExtPath","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kPOBBidCrTypeExtPath"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/kPOBBidCrTypeExtPath":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"kPOBBidCrTypeExtPath","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"text":"kPOBBidCrTypeExtPath","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBBidCrTypeExtPath","abstract":[],"kind":"symbol","role":"symbol","title":"kPOBBidCrTypeExtPath","url":"\/documentation\/openwrapsdk\/kpobbidcrtypeextpath"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"kPOBBidCrTypeExtPath"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kPOBBidCrTypeExtPath"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kPOBBidCrTypeExtPath"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBBidCrTypeExtPath\/title","value":"kPOBBidCrTypeExtPath","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBBidCrTypeExtPath\/fragments","value":[{"text":"kPOBBidCrTypeExtPath","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}