{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBAdServerCustomDataKey","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Global Variable","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"kPOBAdServerCustomDataKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"externalID":"c:@kPOBAdServerCustomDataKey","navigatorTitle":[{"text":"kPOBAdServerCustomDataKey","kind":"identifier"}],"symbolKind":"var","modules":[{"name":"OpenWrapSDK"}],"title":"kPOBAdServerCustomDataKey"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kPOBAdServerCustomDataKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/kpobadservercustomdatakey"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/kpobadservercustomdatakey"]}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/kPOBAdServerCustomDataKey":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBAdServerCustomDataKey","kind":"symbol","title":"kPOBAdServerCustomDataKey","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kPOBAdServerCustomDataKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kPOBAdServerCustomDataKey","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/kpobadservercustomdatakey"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"kPOBAdServerCustomDataKey","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kPOBAdServerCustomDataKey"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"kPOBAdServerCustomDataKey","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"kPOBAdServerCustomDataKey","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBAdServerCustomDataKey\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBAdServerCustomDataKey\/fragments","value":[{"kind":"identifier","text":"kPOBAdServerCustomDataKey"}],"op":"replace"}]}]}