{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/kpobrtbdeliveryparam"]},{"paths":["\/documentation\/openwrapsdk\/kpobrtbdeliveryparam"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBRTBDeliveryParam"},"metadata":{"externalID":"c:@kPOBRTBDeliveryParam","roleHeading":"Global Variable","role":"symbol","modules":[{"name":"OpenWrapSDK"}],"symbolKind":"var","title":"kPOBRTBDeliveryParam","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kPOBRTBDeliveryParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"kPOBRTBDeliveryParam","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"kPOBRTBDeliveryParam","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/kPOBRTBDeliveryParam":{"navigatorTitle":[{"kind":"identifier","text":"kPOBRTBDeliveryParam"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kPOBRTBDeliveryParam","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/kpobrtbdeliveryparam","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBRTBDeliveryParam","title":"kPOBRTBDeliveryParam","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"kPOBRTBDeliveryParam","op":"replace"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"kPOBRTBDeliveryParam"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kPOBRTBDeliveryParam","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBRTBDeliveryParam\/title","op":"replace","value":"kPOBRTBDeliveryParam"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBRTBDeliveryParam\/fragments","value":[{"kind":"identifier","text":"kPOBRTBDeliveryParam"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}