{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kPOBHandlerConfigAllowMultipleInstancesForAdUnit"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"metadata":{"title":"kPOBHandlerConfigAllowMultipleInstancesForAdUnit","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:@kPOBHandlerConfigAllowMultipleInstancesForAdUnit","navigatorTitle":[{"text":"kPOBHandlerConfigAllowMultipleInstancesForAdUnit","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kPOBHandlerConfigAllowMultipleInstancesForAdUnit"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"symbolKind":"var","roleHeading":"Global Variable","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBHandlerConfigAllowMultipleInstancesForAdUnit"},"variants":[{"paths":["\/documentation\/openwrapsdk\/kpobhandlerconfigallowmultipleinstancesforadunit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/kpobhandlerconfigallowmultipleinstancesforadunit"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/kPOBHandlerConfigAllowMultipleInstancesForAdUnit":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBHandlerConfigAllowMultipleInstancesForAdUnit","kind":"symbol","title":"kPOBHandlerConfigAllowMultipleInstancesForAdUnit","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kPOBHandlerConfigAllowMultipleInstancesForAdUnit"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kPOBHandlerConfigAllowMultipleInstancesForAdUnit","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/kpobhandlerconfigallowmultipleinstancesforadunit"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"kPOBHandlerConfigAllowMultipleInstancesForAdUnit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"value":[{"text":"kPOBHandlerConfigAllowMultipleInstancesForAdUnit","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"kPOBHandlerConfigAllowMultipleInstancesForAdUnit"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBHandlerConfigAllowMultipleInstancesForAdUnit\/title","value":"kPOBHandlerConfigAllowMultipleInstancesForAdUnit"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBHandlerConfigAllowMultipleInstancesForAdUnit\/fragments","op":"replace","value":[{"kind":"identifier","text":"kPOBHandlerConfigAllowMultipleInstancesForAdUnit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}