{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBRTBDisplayManagerParam"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/kpobrtbdisplaymanagerparam"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/kpobrtbdisplaymanagerparam"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"kPOBRTBDisplayManagerParam","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"var","navigatorTitle":[{"text":"kPOBRTBDisplayManagerParam","kind":"identifier"}],"role":"symbol","roleHeading":"Global Variable","title":"kPOBRTBDisplayManagerParam","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"kPOBRTBDisplayManagerParam","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"c:@kPOBRTBDisplayManagerParam","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/kPOBRTBDisplayManagerParam":{"navigatorTitle":[{"kind":"identifier","text":"kPOBRTBDisplayManagerParam"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kPOBRTBDisplayManagerParam","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/kpobrtbdisplaymanagerparam","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/kPOBRTBDisplayManagerParam","title":"kPOBRTBDisplayManagerParam","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"kPOBRTBDisplayManagerParam"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"op":"replace","value":[{"text":"kPOBRTBDisplayManagerParam","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kPOBRTBDisplayManagerParam","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"kPOBRTBDisplayManagerParam","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBRTBDisplayManagerParam\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1kPOBRTBDisplayManagerParam\/fragments","value":[{"kind":"identifier","text":"kPOBRTBDisplayManagerParam"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}