{"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"],"kind":"relationships"}],"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig\/init(publisherId:andProfileIds:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig\/profileIds","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig\/publisherId"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/openwrapsdkconfig"]},{"paths":["\/documentation\/openwrapsdk\/openwrapsdkconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OpenWrapSDKConfig","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"inlineContent":[{"type":"text","text":"Use it with OpenWrapSDK’s initialize API."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"OpenWrapSDKConfig","kind":"identifier"}],"role":"symbol","roleHeading":"Class","title":"OpenWrapSDKConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenWrapSDKConfig"}],"externalID":"c:objc(cs)OpenWrapSDKConfig","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDKConfig":{"navigatorTitle":[{"kind":"identifier","text":"OpenWrapSDKConfig"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OpenWrapSDKConfig","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/openwrapsdkconfig","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig","title":"OpenWrapSDKConfig","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDKConfig/publisherId":{"abstract":[],"navigatorTitle":[{"text":"publisherId","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/openwrapsdkconfig\/publisherid","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig\/publisherId","type":"topic","title":"publisherId","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"publisherId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDKConfig/profileIds":{"url":"\/documentation\/openwrapsdk\/openwrapsdkconfig\/profileids","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig\/profileIds","title":"profileIds","type":"topic","role":"symbol","navigatorTitle":[{"text":"profileIds","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"profileIds"},{"kind":"text","text":": ["},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDKConfig/init(publisherId:andProfileIds:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"publisherId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"andProfileIds","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"])","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithPublisherId:andProfileIds:","kind":"identifier"}],"title":"init(publisherId:andProfileIds:)","abstract":[],"url":"\/documentation\/openwrapsdk\/openwrapsdkconfig\/init(publisherid:andprofileids:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig\/init(publisherId:andProfileIds:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP"},"doc://com.pubmatic.openwrapsdk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP"},"doc://com.pubmatic.openwrapsdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"OpenWrapSDKConfig","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"OpenWrapSDKConfig","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"OpenWrapSDKConfig","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig\/profileIds","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig\/publisherId"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig\/init(publisherId:andProfileIds:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OpenWrapSDKConfig"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig\/title","op":"replace","value":"OpenWrapSDKConfig"},{"value":[{"kind":"identifier","text":"OpenWrapSDKConfig"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig\/fragments","op":"replace"},{"op":"replace","value":"publisherId","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig~1publisherId\/title"},{"value":[{"kind":"identifier","text":"publisherId"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig~1publisherId\/fragments"},{"op":"replace","value":"profileIds","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig~1profileIds\/title"},{"value":[{"text":"profileIds","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig~1profileIds\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig~1init(publisherId:andProfileIds:)\/title","op":"replace","value":"initWithPublisherId:andProfileIds:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig~1init(publisherId:andProfileIds:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithPublisherId:andProfileIds:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}