{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/applicationInfo","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/dsaComplianceStatus","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/userInfo"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/addExternalUserId(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/allowAVAudioSessionAccess(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/allowAdvertisingId(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/allowLocationAccess(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/externalUserIds()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/initialize(with:andCompletionHandler:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/removeAllExternalUserIds()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/removeExternalUserIds(withSource:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setApplicationInfo(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setCoppaEnabled(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setDSAComplianceStatus(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setLocation(_:source:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setLogLevel(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setSSLEnabled(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setUserInfo(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/useInternalBrowser(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/version()"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/openwrapsdk"]},{"paths":["\/documentation\/openwrapsdk\/openwrapsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Provides global configurations for the OpenWrap SDK, e.g. enabling logging, location access, etc. These configurations are globally applicable for OpenWrap SDK; you don’t have to set these for every ad request."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OpenWrapSDK","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"class","title":"OpenWrapSDK","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OpenWrapSDK"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"OpenWrapSDK","kind":"identifier"}],"externalID":"c:objc(cs)OpenWrapSDK"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"],"kind":"relationships"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/userInfo":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/userInfo","kind":"symbol","role":"symbol","title":"userInfo","url":"\/documentation\/openwrapsdk\/openwrapsdk\/userinfo","abstract":[],"navigatorTitle":[{"text":"userInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userInfo"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBUserInfo","text":"POBUserInfo","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject","title":"NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/setDSAComplianceStatus(_:)":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setDSAComplianceStatus(_:)","url":"\/documentation\/openwrapsdk\/openwrapsdk\/setdsacompliancestatus(_:)","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setDSAComplianceStatus","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@POBDSAComplianceStatus","text":"POBDSAComplianceStatus"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setDSAComplianceStatus:","kind":"identifier"}],"role":"symbol","title":"setDSAComplianceStatus(_:)","abstract":[{"type":"text","text":"Sets the DSA (Digital Services Act) compliance status."}]},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/removeExternalUserIds(withSource:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/removeExternalUserIds(withSource:)","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/openwrapsdk\/removeexternaluserids(withsource:)","title":"removeExternalUserIds(withSource:)","abstract":[],"navigatorTitle":[{"text":"removeExternalUserIdsWithSource:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeExternalUserIds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withSource","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/removeAllExternalUserIds()":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/removeAllExternalUserIds()","kind":"symbol","role":"symbol","title":"removeAllExternalUserIds()","url":"\/documentation\/openwrapsdk\/openwrapsdk\/removeallexternaluserids()","abstract":[],"navigatorTitle":[{"text":"removeAllExternalUserIds","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeAllExternalUserIds","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/dsaComplianceStatus":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"dsaComplianceStatus"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/dsaComplianceStatus","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dsaComplianceStatus"},{"kind":"text","text":": "},{"text":"POBDSAComplianceStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBDSAComplianceStatus"}],"url":"\/documentation\/openwrapsdk\/openwrapsdk\/dsacompliancestatus","abstract":[{"type":"text","text":"A property to get the current DSA (Digital Services Act) compliance status."},{"type":"text","text":" "},{"type":"text","text":"Default value is @c POBDSAComplianceStatusNotRequired."}],"title":"dsaComplianceStatus"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/setLocation(_:source:)":{"kind":"symbol","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setLocation(_:source:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setLocation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@POBLocSource","text":"POBLocSource"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setLocation:source:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/openwrapsdk\/setlocation(_:source:)","title":"setLocation(_:source:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/setUserInfo(_:)":{"kind":"symbol","type":"topic","title":"setUserInfo(_:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setUserInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"POBUserInfo","preciseIdentifier":"c:objc(cs)POBUserInfo"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"text":"setUserInfo:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/openwrapsdk\/setuserinfo(_:)","role":"symbol","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setUserInfo(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK":{"abstract":[{"type":"text","text":"Provides global configurations for the OpenWrap SDK, e.g. enabling logging, location access, etc. These configurations are globally applicable for OpenWrap SDK; you don’t have to set these for every ad request."}],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK","kind":"symbol","title":"OpenWrapSDK","navigatorTitle":[{"text":"OpenWrapSDK","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/openwrapsdk","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenWrapSDK","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/SH":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/setSSLEnabled(_:)":{"title":"setSSLEnabled(_:)","url":"\/documentation\/openwrapsdk\/openwrapsdk\/setsslenabled(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setSSLEnabled(_:)","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setSSLEnabled","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setSSLEnabled:","kind":"identifier"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/useInternalBrowser(_:)":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/useInternalBrowser(_:)","kind":"symbol","title":"useInternalBrowser(_:)","navigatorTitle":[{"kind":"identifier","text":"useInternalBrowser:"}],"type":"topic","url":"\/documentation\/openwrapsdk\/openwrapsdk\/useinternalbrowser(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useInternalBrowser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/addExternalUserId(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/addExternalUserId(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/openwrapsdk\/addexternaluserid(_:)","title":"addExternalUserId(_:)","abstract":[],"navigatorTitle":[{"text":"addExternalUserId:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addExternalUserId"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBExternalUserId","text":"POBExternalUserId","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/setLogLevel(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setLogLevel(_:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLogLevel"},{"text":"(","kind":"text"},{"text":"POBSDKLogLevel","preciseIdentifier":"c:@E@POBSDKLogLevel","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setLogLevel:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/openwrapsdk\/setloglevel(_:)","title":"setLogLevel(_:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/initialize(with:andCompletionHandler:)":{"title":"initialize(with:andCompletionHandler:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/initialize(with:andCompletionHandler:)","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/openwrapsdk\/initialize(with:andcompletionhandler:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)OpenWrapSDKConfig","kind":"typeIdentifier","text":"OpenWrapSDKConfig"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"andCompletionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenWrapSDKInitCompletionBlock","preciseIdentifier":"c:OpenWrapSDK.h@T@OpenWrapSDKInitCompletionBlock"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initializeWithConfig:andCompletionHandler:"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/allowAdvertisingId(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/allowAdvertisingId(_:)","kind":"symbol","role":"symbol","title":"allowAdvertisingId(_:)","url":"\/documentation\/openwrapsdk\/openwrapsdk\/allowadvertisingid(_:)","abstract":[],"navigatorTitle":[{"text":"allowAdvertisingId:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAdvertisingId"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/externalUserIds()":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/externalUserIds()","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/openwrapsdk\/externaluserids()","title":"externalUserIds()","abstract":[],"navigatorTitle":[{"text":"externalUserIds","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"externalUserIds"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBExternalUserId","text":"POBExternalUserId","kind":"typeIdentifier"},{"kind":"text","text":"]!"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/allowLocationAccess(_:)":{"navigatorTitle":[{"kind":"identifier","text":"allowLocationAccess:"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"allowLocationAccess","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"role":"symbol","title":"allowLocationAccess(_:)","url":"\/documentation\/openwrapsdk\/openwrapsdk\/allowlocationaccess(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/allowLocationAccess(_:)","abstract":[],"kind":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/version()":{"abstract":[],"navigatorTitle":[{"text":"version","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/openwrapsdk\/version()","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/version()","type":"topic","title":"version()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"version","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/setApplicationInfo(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setApplicationInfo(_:)","kind":"symbol","role":"symbol","title":"setApplicationInfo(_:)","url":"\/documentation\/openwrapsdk\/openwrapsdk\/setapplicationinfo(_:)","abstract":[],"navigatorTitle":[{"text":"setApplicationInfo:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setApplicationInfo"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBApplicationInfo","text":"POBApplicationInfo"},{"text":"!)","kind":"text"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/setCoppaEnabled(_:)":{"abstract":[],"title":"setCoppaEnabled(_:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCoppaEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/openwrapsdk\/setcoppaenabled(_:)","navigatorTitle":[{"text":"setCoppaEnabled:","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setCoppaEnabled(_:)"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/allowAVAudioSessionAccess(_:)":{"url":"\/documentation\/openwrapsdk\/openwrapsdk\/allowavaudiosessionaccess(_:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAVAudioSessionAccess"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/allowAVAudioSessionAccess(_:)","navigatorTitle":[{"text":"allowAVAudioSessionAccess:","kind":"identifier"}],"abstract":[],"title":"allowAVAudioSessionAccess(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/applicationInfo":{"url":"\/documentation\/openwrapsdk\/openwrapsdk\/applicationinfo","title":"applicationInfo","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/applicationInfo","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationInfo"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"applicationInfo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"POBApplicationInfo","preciseIdentifier":"c:objc(cs)POBApplicationInfo"},{"kind":"text","text":"!"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"OpenWrapSDK","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"OpenWrapSDK","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OpenWrapSDK"}]},{"op":"replace","value":[{"title":"Type Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/applicationInfo","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/dsaComplianceStatus","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/userInfo"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/addExternalUserId(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/allowAVAudioSessionAccess(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/allowAdvertisingId(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/allowLocationAccess(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/externalUserIds()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/initialize(with:andCompletionHandler:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/removeAllExternalUserIds()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/removeExternalUserIds(withSource:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setApplicationInfo(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setCoppaEnabled(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setDSAComplianceStatus(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setLocation(_:source:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setLogLevel(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setSSLEnabled(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setUserInfo(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/useInternalBrowser(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/version()"],"title":"Type Methods"}],"path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"OpenWrapSDK","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"userInfo","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1userInfo\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1userInfo\/fragments","value":[{"kind":"identifier","text":"userInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setDSAComplianceStatus(_:)\/title","value":"setDSAComplianceStatus:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"setDSAComplianceStatus:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setDSAComplianceStatus(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1removeExternalUserIds(withSource:)\/title","value":"removeExternalUserIdsWithSource:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"removeExternalUserIdsWithSource:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1removeExternalUserIds(withSource:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1removeAllExternalUserIds()\/title","op":"replace","value":"removeAllExternalUserIds"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"removeAllExternalUserIds"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1removeAllExternalUserIds()\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1dsaComplianceStatus\/title","value":"dsaComplianceStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1dsaComplianceStatus\/fragments","value":[{"kind":"identifier","text":"dsaComplianceStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setLocation(_:source:)\/title","value":"setLocation:source:","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setLocation(_:source:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setLocation:source:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setUserInfo(_:)\/title","op":"replace","value":"setUserInfo:"},{"value":[{"text":"+ ","kind":"text"},{"text":"setUserInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setUserInfo(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK\/title","value":"OpenWrapSDK"},{"value":[{"text":"OpenWrapSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK\/fragments"},{"value":"setSSLEnabled:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setSSLEnabled(_:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"setSSLEnabled:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setSSLEnabled(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1useInternalBrowser(_:)\/title","op":"replace","value":"useInternalBrowser:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1useInternalBrowser(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"useInternalBrowser:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1addExternalUserId(_:)\/title","op":"replace","value":"addExternalUserId:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1addExternalUserId(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addExternalUserId:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setLogLevel(_:)\/title","value":"setLogLevel:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setLogLevel(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setLogLevel:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1initialize(with:andCompletionHandler:)\/title","op":"replace","value":"initializeWithConfig:andCompletionHandler:"},{"value":[{"kind":"text","text":"+ "},{"text":"initializeWithConfig:andCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1initialize(with:andCompletionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1allowAdvertisingId(_:)\/title","value":"allowAdvertisingId:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"allowAdvertisingId:"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1allowAdvertisingId(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1externalUserIds()\/title","op":"replace","value":"externalUserIds"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1externalUserIds()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"externalUserIds"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1allowLocationAccess(_:)\/title","value":"allowLocationAccess:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"allowLocationAccess:"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1allowLocationAccess(_:)\/fragments"},{"value":"version","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1version()\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"version"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1version()\/fragments"},{"op":"replace","value":"setApplicationInfo:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setApplicationInfo(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setApplicationInfo(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setApplicationInfo:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setCoppaEnabled(_:)\/title","value":"setCoppaEnabled:","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setCoppaEnabled(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setCoppaEnabled:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1allowAVAudioSessionAccess(_:)\/title","value":"allowAVAudioSessionAccess:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1allowAVAudioSessionAccess(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"allowAVAudioSessionAccess:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1applicationInfo\/title","value":"applicationInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1applicationInfo\/fragments","value":[{"kind":"identifier","text":"applicationInfo"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}