{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_ID_TITLE","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pob_native_id_title"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pob_native_id_title"]}],"metadata":{"modules":[{"name":"OpenWrapSDK"}],"externalID":"c:POBNativeUXSpecs.h@1809@macro@POB_NATIVE_ID_TITLE","roleHeading":"Global Variable","navigatorTitle":[{"text":"POB_NATIVE_ID_TITLE","kind":"identifier"}],"title":"POB_NATIVE_ID_TITLE","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"POB_NATIVE_ID_TITLE","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"role":"symbol","symbolKind":"var"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"POB_NATIVE_ID_TITLE"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POB_NATIVE_ID_TITLE":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_ID_TITLE","type":"topic","kind":"symbol","title":"POB_NATIVE_ID_TITLE","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_ID_TITLE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"text":"POB_NATIVE_ID_TITLE","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pob_native_id_title"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Macro","path":"\/metadata\/roleHeading"},{"value":"POB_NATIVE_ID_TITLE","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POB_NATIVE_ID_TITLE"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"#define"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_ID_TITLE","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","value":"POB_NATIVE_ID_TITLE","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_ID_TITLE\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_ID_TITLE\/fragments","op":"replace","value":[{"text":"POB_NATIVE_ID_TITLE","kind":"identifier"}]}]}]}