{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_ID_MAIN_IMG","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pob_native_id_main_img"]},{"paths":["\/documentation\/openwrapsdk\/pob_native_id_main_img"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_ID_MAIN_IMG","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"POB_NATIVE_ID_MAIN_IMG"}],"role":"symbol","title":"POB_NATIVE_ID_MAIN_IMG","roleHeading":"Global Variable","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_ID_MAIN_IMG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"externalID":"c:POBNativeUXSpecs.h@1961@macro@POB_NATIVE_ID_MAIN_IMG","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POB_NATIVE_ID_MAIN_IMG":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_ID_MAIN_IMG","kind":"symbol","title":"POB_NATIVE_ID_MAIN_IMG","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"POB_NATIVE_ID_MAIN_IMG","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"POB_NATIVE_ID_MAIN_IMG","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pob_native_id_main_img"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Macro"},{"value":"POB_NATIVE_ID_MAIN_IMG","op":"replace","path":"\/metadata\/title"},{"value":"macro","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"POB_NATIVE_ID_MAIN_IMG"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POB_NATIVE_ID_MAIN_IMG"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"POB_NATIVE_ID_MAIN_IMG","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_ID_MAIN_IMG\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_ID_MAIN_IMG\/fragments","value":[{"kind":"identifier","text":"POB_NATIVE_ID_MAIN_IMG"}]}]}]}