{"variants":[{"paths":["\/documentation\/openwrapsdk\/pob_native_id_icon"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pob_native_id_icon"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_ID_ICON","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","externalID":"c:POBNativeUXSpecs.h@1847@macro@POB_NATIVE_ID_ICON","navigatorTitle":[{"kind":"identifier","text":"POB_NATIVE_ID_ICON"}],"title":"POB_NATIVE_ID_ICON","roleHeading":"Global Variable","symbolKind":"var"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_ID_ICON","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_ID_ICON","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POB_NATIVE_ID_ICON":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_ID_ICON","kind":"symbol","title":"POB_NATIVE_ID_ICON","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POB_NATIVE_ID_ICON"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"POB_NATIVE_ID_ICON","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pob_native_id_icon"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Macro","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"POB_NATIVE_ID_ICON"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"path":"\/metadata\/fragments","value":[{"text":"POB_NATIVE_ID_ICON","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_ID_ICON","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"POB_NATIVE_ID_ICON","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_ID_ICON\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_ID_ICON\/fragments","op":"replace","value":[{"text":"POB_NATIVE_ID_ICON","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}