{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_ID_RATING"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POB_NATIVE_ID_RATING"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"externalID":"c:POBNativeUXSpecs.h@1999@macro@POB_NATIVE_ID_RATING","navigatorTitle":[{"text":"POB_NATIVE_ID_RATING","kind":"identifier"}],"symbolKind":"var","roleHeading":"Global Variable","title":"POB_NATIVE_ID_RATING","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_ID_RATING","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pob_native_id_rating"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pob_native_id_rating"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POB_NATIVE_ID_RATING":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_ID_RATING","type":"topic","kind":"symbol","title":"POB_NATIVE_ID_RATING","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_ID_RATING","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"navigatorTitle":[{"text":"POB_NATIVE_ID_RATING","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pob_native_id_rating"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Macro"},{"op":"replace","path":"\/metadata\/title","value":"POB_NATIVE_ID_RATING"},{"path":"\/metadata\/symbolKind","op":"replace","value":"macro"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"POB_NATIVE_ID_RATING","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"#define","kind":"keyword"},{"kind":"text","text":" "},{"text":"POB_NATIVE_ID_RATING","kind":"identifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_ID_RATING\/title","op":"replace","value":"POB_NATIVE_ID_RATING"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_ID_RATING\/fragments","op":"replace","value":[{"text":"POB_NATIVE_ID_RATING","kind":"identifier"}]}]}]}