{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pob_native_id_desc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pob_native_id_desc"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"POB_NATIVE_ID_DESC","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"text":"POB_NATIVE_ID_DESC","kind":"identifier"}],"symbolKind":"var","role":"symbol","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:POBNativeUXSpecs.h@1885@macro@POB_NATIVE_ID_DESC","roleHeading":"Global Variable","title":"POB_NATIVE_ID_DESC"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POB_NATIVE_ID_DESC"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_ID_DESC"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POB_NATIVE_ID_DESC":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_ID_DESC","kind":"symbol","title":"POB_NATIVE_ID_DESC","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POB_NATIVE_ID_DESC"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"POB_NATIVE_ID_DESC","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pob_native_id_desc"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Macro","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"POB_NATIVE_ID_DESC","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POB_NATIVE_ID_DESC","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_ID_DESC","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_ID_DESC\/title","value":"POB_NATIVE_ID_DESC"},{"op":"replace","value":[{"text":"POB_NATIVE_ID_DESC","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_ID_DESC\/fragments"}]}]}