{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pob_native_main_img_w"]},{"paths":["\/documentation\/openwrapsdk\/pob_native_main_img_w"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POB_NATIVE_MAIN_IMG_W"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","symbolKind":"var","title":"POB_NATIVE_MAIN_IMG_W","roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_MAIN_IMG_W","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"modules":[{"name":"OpenWrapSDK"}],"navigatorTitle":[{"text":"POB_NATIVE_MAIN_IMG_W","kind":"identifier"}],"externalID":"c:POBNativeUXSpecs.h@2599@macro@POB_NATIVE_MAIN_IMG_W"},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_MAIN_IMG_W","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POB_NATIVE_MAIN_IMG_W":{"role":"symbol","title":"POB_NATIVE_MAIN_IMG_W","url":"\/documentation\/openwrapsdk\/pob_native_main_img_w","kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_MAIN_IMG_W","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_MAIN_IMG_W","navigatorTitle":[{"kind":"identifier","text":"POB_NATIVE_MAIN_IMG_W"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Macro"},{"op":"replace","path":"\/metadata\/title","value":"POB_NATIVE_MAIN_IMG_W"},{"value":"macro","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"POB_NATIVE_MAIN_IMG_W","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POB_NATIVE_MAIN_IMG_W"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"POB_NATIVE_MAIN_IMG_W","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_MAIN_IMG_W\/title"},{"value":[{"kind":"identifier","text":"POB_NATIVE_MAIN_IMG_W"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_MAIN_IMG_W\/fragments"}]}]}