{"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Global Variable","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_AD_ICON_H","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"var","title":"POB_NATIVE_AD_ICON_H","externalID":"c:POBNativeUXSpecs.h@2528@macro@POB_NATIVE_AD_ICON_H","navigatorTitle":[{"kind":"identifier","text":"POB_NATIVE_AD_ICON_H"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_AD_ICON_H"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pob_native_ad_icon_h"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pob_native_ad_icon_h"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_AD_ICON_H","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POB_NATIVE_AD_ICON_H":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_AD_ICON_H","type":"topic","kind":"symbol","title":"POB_NATIVE_AD_ICON_H","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_AD_ICON_H","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"navigatorTitle":[{"kind":"identifier","text":"POB_NATIVE_AD_ICON_H"}],"url":"\/documentation\/openwrapsdk\/pob_native_ad_icon_h"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Macro","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"POB_NATIVE_AD_ICON_H"},{"op":"replace","value":"macro","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POB_NATIVE_AD_ICON_H"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"#define","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POB_NATIVE_AD_ICON_H"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_AD_ICON_H\/title","value":"POB_NATIVE_AD_ICON_H"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_AD_ICON_H\/fragments","value":[{"text":"POB_NATIVE_AD_ICON_H","kind":"identifier"}]}]}]}