{"metadata":{"symbolKind":"var","roleHeading":"Global Variable","title":"POB_NATIVE_MAIN_IMG_H","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POB_NATIVE_MAIN_IMG_H","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"POB_NATIVE_MAIN_IMG_H","kind":"identifier"}],"externalID":"c:POBNativeUXSpecs.h@2650@macro@POB_NATIVE_MAIN_IMG_H"},"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_MAIN_IMG_H","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POB_NATIVE_MAIN_IMG_H"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pob_native_main_img_h"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pob_native_main_img_h"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POB_NATIVE_MAIN_IMG_H":{"title":"POB_NATIVE_MAIN_IMG_H","url":"\/documentation\/openwrapsdk\/pob_native_main_img_h","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POB_NATIVE_MAIN_IMG_H","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"POB_NATIVE_MAIN_IMG_H","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POB_NATIVE_MAIN_IMG_H"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Macro","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"POB_NATIVE_MAIN_IMG_H"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POB_NATIVE_MAIN_IMG_H","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"#define"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POB_NATIVE_MAIN_IMG_H"}]}],"kind":"declarations"}},{"value":"POB_NATIVE_MAIN_IMG_H","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_MAIN_IMG_H\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POB_NATIVE_MAIN_IMG_H\/fragments","value":[{"kind":"identifier","text":"POB_NATIVE_MAIN_IMG_H"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}