{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobapplicationinfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobapplicationinfo"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBApplicationInfo","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Class","externalID":"c:objc(cs)POBApplicationInfo","role":"symbol","symbolKind":"class","modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBApplicationInfo"}],"navigatorTitle":[{"kind":"identifier","text":"POBApplicationInfo"}],"title":"POBApplicationInfo"},"abstract":[{"text":"Provides setters to pass application information, Like store URL, application domain, categories, …etc. It is very important to provide transparency for buyers of your app inventory.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/categories","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/domain","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/keywords","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/paid","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/storeURL"],"title":"Instance Properties"}],"references":{"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBApplicationInfo/domain":{"url":"\/documentation\/openwrapsdk\/pobapplicationinfo\/domain","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"domain"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/domain","navigatorTitle":[{"kind":"identifier","text":"domain"}],"abstract":[],"title":"domain"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBApplicationInfo/storeURL":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"storeURL"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/storeURL","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"storeURL","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"}],"url":"\/documentation\/openwrapsdk\/pobapplicationinfo\/storeurl","role":"symbol","kind":"symbol","title":"storeURL"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBApplicationInfo/categories":{"url":"\/documentation\/openwrapsdk\/pobapplicationinfo\/categories","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"categories","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/categories","navigatorTitle":[{"kind":"identifier","text":"categories"}],"abstract":[],"title":"categories"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBApplicationInfo":{"abstract":[{"type":"text","text":"Provides setters to pass application information, Like store URL, application domain, categories, …etc. It is very important to provide transparency for buyers of your app inventory."}],"navigatorTitle":[{"text":"POBApplicationInfo","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBApplicationInfo","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobapplicationinfo","role":"symbol","title":"POBApplicationInfo","kind":"symbol"},"doc://com.pubmatic.openwrapsdk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject","title":"NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBApplicationInfo/paid":{"url":"\/documentation\/openwrapsdk\/pobapplicationinfo\/paid","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paid"},{"text":": ","kind":"text"},{"text":"POBBOOL","kind":"typeIdentifier","preciseIdentifier":"c:POBDataTypes.h@T@POBBOOL"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/paid","navigatorTitle":[{"kind":"identifier","text":"paid"}],"abstract":[],"title":"paid"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBApplicationInfo/keywords":{"url":"\/documentation\/openwrapsdk\/pobapplicationinfo\/keywords","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"keywords","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/keywords","navigatorTitle":[{"kind":"identifier","text":"keywords"}],"abstract":[],"title":"keywords"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"POBApplicationInfo","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBApplicationInfo"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"POBApplicationInfo"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/categories","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/domain","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/keywords","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/paid","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBApplicationInfo\/storeURL"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBApplicationInfo"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"domain","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo~1domain\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo~1domain\/fragments","op":"replace","value":[{"text":"domain","kind":"identifier"}]},{"op":"replace","value":"storeURL","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo~1storeURL\/title"},{"value":[{"text":"storeURL","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo~1storeURL\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo~1categories\/title","value":"categories","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo~1categories\/fragments","value":[{"kind":"identifier","text":"categories"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo\/title","value":"POBApplicationInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo\/fragments","value":[{"text":"POBApplicationInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo~1paid\/title","op":"replace","value":"paid"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo~1paid\/fragments","op":"replace","value":[{"kind":"identifier","text":"paid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo~1keywords\/title","value":"keywords"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBApplicationInfo~1keywords\/fragments","value":[{"text":"keywords","kind":"identifier"}]}]}]}