{"sections":[],"abstract":[{"text":"List of supported API frameworks for this impression. If an API is not","type":"text"},{"text":" ","type":"text"},{"text":"explicitly listed, it is assumed not to be supported.","type":"text"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/MRAID_1","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/MRAID_2","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/MRAID_3","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/OMSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/ORMMA","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/VPAID_1_0","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/VPAID_2_0"]},{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/RawRepresentable-Implementations"],"generated":true}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBAPI","kind":"identifier"}],"externalID":"c:@E@POBAPI","navigatorTitle":[{"kind":"identifier","text":"POBAPI"}],"symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"OpenWrapSDK"}],"title":"POBAPI","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBAPI","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobapi"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobapi"]}],"references":{"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAPI/MRAID_2":{"type":"topic","abstract":[{"type":"text","text":"API MRAID-2"}],"navigatorTitle":[{"text":"POBAPI_MRAID_2","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/MRAID_2","title":"POBAPI.MRAID_2","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MRAID_2"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobapi\/mraid_2"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAPI":{"type":"topic","url":"\/documentation\/openwrapsdk\/pobapi","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBAPI"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBAPI"}],"title":"POBAPI","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI","abstract":[{"type":"text","text":"List of supported API frameworks for this impression. If an API is not"},{"text":" ","type":"text"},{"type":"text","text":"explicitly listed, it is assumed not to be supported."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAPI/MRAID_3":{"title":"POBAPI.MRAID_3","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MRAID_3"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/MRAID_3","abstract":[{"type":"text","text":"API MRAID-3"}],"url":"\/documentation\/openwrapsdk\/pobapi\/mraid_3","navigatorTitle":[{"text":"POBAPI_MRAID_3","kind":"identifier"}],"role":"symbol"},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAPI/ORMMA":{"type":"topic","abstract":[{"text":"API ORMMA","type":"text"}],"navigatorTitle":[{"text":"POBAPI_ORMMA","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/ORMMA","title":"POBAPI.ORMMA","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ORMMA","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobapi\/ormma"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAPI/init(rawValue:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobapi\/init(rawvalue:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAPI/VPAID_1_0":{"navigatorTitle":[{"text":"POBAPI_VPAID_1_0","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobapi\/vpaid_1_0","abstract":[{"type":"text","text":"API VPAID 1.0"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VPAID_1_0"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/VPAID_1_0","type":"topic","title":"POBAPI.VPAID_1_0","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAPI/OMSDK":{"navigatorTitle":[{"text":"POBAPI_OMSDK","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobapi\/omsdk","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/OMSDK","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OMSDK","kind":"identifier"}],"title":"POBAPI.OMSDK","abstract":[{"type":"text","text":"API OMSDK"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAPI/MRAID_1":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MRAID_1"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBAPI_MRAID_1"}],"title":"POBAPI.MRAID_1","abstract":[{"text":"API MRAID-1","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobapi\/mraid_1","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/MRAID_1"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAPI/Equatable-Implementations":{"kind":"article","role":"collectionGroup","abstract":[],"title":"Equatable Implementations","url":"\/documentation\/openwrapsdk\/pobapi\/equatable-implementations","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/Equatable-Implementations"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAPI/RawRepresentable-Implementations":{"type":"topic","url":"\/documentation\/openwrapsdk\/pobapi\/rawrepresentable-implementations","role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/RawRepresentable-Implementations"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAPI/VPAID_2_0":{"navigatorTitle":[{"kind":"identifier","text":"POBAPI_VPAID_2_0"}],"url":"\/documentation\/openwrapsdk\/pobapi\/vpaid_2_0","abstract":[{"type":"text","text":"API VPAID 2.0"}],"kind":"symbol","title":"POBAPI.VPAID_2_0","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VPAID_2_0"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/VPAID_2_0","role":"symbol"},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"POBAPI"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"POBAPI","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"POBAPI"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/MRAID_1","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/MRAID_2","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/MRAID_3","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/OMSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/ORMMA","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/VPAID_1_0","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/VPAID_2_0"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBAPI","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1MRAID_2\/title","op":"replace","value":"POBAPI_MRAID_2"},{"op":"replace","value":[{"text":"POBAPI_MRAID_2","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1MRAID_2\/fragments"},{"value":"POBAPI","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI\/title"},{"op":"replace","value":[{"kind":"identifier","text":"POBAPI"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1MRAID_3\/title","op":"replace","value":"POBAPI_MRAID_3"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1MRAID_3\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBAPI_MRAID_3"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1ORMMA\/title","op":"replace","value":"POBAPI_ORMMA"},{"op":"replace","value":[{"kind":"identifier","text":"POBAPI_ORMMA"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1ORMMA\/fragments"},{"op":"replace","value":"POBAPI_VPAID_1_0","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1VPAID_1_0\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1VPAID_1_0\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBAPI_VPAID_1_0"}]},{"value":"POBAPI_OMSDK","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1OMSDK\/title"},{"value":[{"text":"POBAPI_OMSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1OMSDK\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1MRAID_1\/title","value":"POBAPI_MRAID_1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1MRAID_1\/fragments","value":[{"text":"POBAPI_MRAID_1","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1VPAID_2_0\/title","value":"POBAPI_VPAID_2_0","op":"replace"},{"value":[{"text":"POBAPI_VPAID_2_0","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1VPAID_2_0\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}