{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBAdServerSignalingEventDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/adServerDidWin()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/bidsProvider()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/failedWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/openWrapPartnerDidWin(forBid:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/viewControllerForPresentingModal()"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"metadata":{"symbolKind":"protocol","title":"POBAdServerSignalingEventDelegate","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBAdServerSignalingEventDelegate"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"POBAdServerSignalingEventDelegate","kind":"identifier"}],"externalID":"c:objc(pl)POBAdServerSignalingEventDelegate"},"kind":"symbol","sections":[],"references":{"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdServerSignalingEventDelegate":{"type":"topic","title":"POBAdServerSignalingEventDelegate","url":"\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBAdServerSignalingEventDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"POBAdServerSignalingEventDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdServerSignalingEventDelegate/bidsProvider()":{"required":true,"title":"bidsProvider()","url":"\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/bidsprovider()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/bidsProvider()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bidsProvider"},{"text":"() -> (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBidsProvider","text":"POBBidsProvider"},{"kind":"text","text":")?"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bidsProvider"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdServerSignalingEventDelegate/failedWithError(_:)":{"required":true,"title":"failedWithError(_:)","url":"\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/failedwitherror(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/failedWithError(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedWithError"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?)","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"failedWithError:"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdServerSignalingEventDelegate/viewControllerForPresentingModal()":{"type":"topic","title":"viewControllerForPresentingModal()","url":"\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/viewcontrollerforpresentingmodal()","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewControllerForPresentingModal","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"viewControllerForPresentingModal"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/viewControllerForPresentingModal()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdServerSignalingEventDelegate/adServerDidWin()":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/adServerDidWin()","url":"\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/adserverdidwin()","kind":"symbol","required":true,"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adServerDidWin"},{"kind":"text","text":"()"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"adServerDidWin"}],"title":"adServerDidWin()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdServerSignalingEventDelegate/openWrapPartnerDidWin(forBid:)":{"abstract":[],"required":true,"role":"symbol","url":"\/documentation\/openwrapsdk\/pobadserversignalingeventdelegate\/openwrappartnerdidwin(forbid:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openWrapPartnerDidWinForBid:"}],"title":"openWrapPartnerDidWin(forBid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openWrapPartnerDidWin","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forBid"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/openWrapPartnerDidWin(forBid:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"POBAdServerSignalingEventDelegate"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBAdServerSignalingEventDelegate"}],"op":"replace"},{"value":[{"kind":"identifier","text":"POBAdServerSignalingEventDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/adServerDidWin()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/bidsProvider()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/failedWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/openWrapPartnerDidWin(forBid:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdServerSignalingEventDelegate\/viewControllerForPresentingModal()"],"title":"Instance Methods"}],"path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBAdServerSignalingEventDelegate"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate\/title","value":"POBAdServerSignalingEventDelegate"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBAdServerSignalingEventDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1bidsProvider()\/title","value":"bidsProvider"},{"value":[{"kind":"text","text":"- "},{"text":"bidsProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1bidsProvider()\/fragments"},{"value":"failedWithError:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1failedWithError(_:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1failedWithError(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"failedWithError:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1viewControllerForPresentingModal()\/title","value":"viewControllerForPresentingModal"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1viewControllerForPresentingModal()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewControllerForPresentingModal"}]},{"value":"adServerDidWin","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1adServerDidWin()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1adServerDidWin()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adServerDidWin","kind":"identifier"}]},{"value":"openWrapPartnerDidWinForBid:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1openWrapPartnerDidWin(forBid:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdServerSignalingEventDelegate~1openWrapPartnerDidWin(forBid:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"openWrapPartnerDidWinForBid:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}