{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBAdRendererDelegate","kind":"identifier"}],"externalID":"c:objc(pl)POBAdRendererDelegate","navigatorTitle":[{"text":"POBAdRendererDelegate","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","modules":[{"name":"OpenWrapSDK"}],"title":"POBAdRendererDelegate","role":"symbol"},"abstract":[{"text":"Ad banner rendering delegate, It is used to provide feedback events from custom renderer","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobadrendererdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobadrendererdelegate"]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererAboutToSkip(completion:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidClickAd(for:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidDismissModal()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidExpireAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidFailToRenderAdWithError(_:for:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidPresentModal()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidRecordImpression()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidRenderAd(_:for:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidUnloadMRAIDAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererRequestedAdRefresh(afterInterval:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererWillLeaveApp()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererWillPresentModal()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/viewControllerForPresentingModal()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBAdRendererDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererDidRecordImpression()":{"abstract":[],"required":true,"navigatorTitle":[{"text":"rendererDidRecordImpression","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdidrecordimpression()","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidRecordImpression()","title":"rendererDidRecordImpression()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rendererDidRecordImpression"},{"kind":"text","text":"()"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererDidExpireAd()":{"type":"topic","title":"rendererDidExpireAd()","url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdidexpiread()","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rendererDidExpireAd"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rendererDidExpireAd"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidExpireAd()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererDidDismissModal()":{"abstract":[],"required":true,"navigatorTitle":[{"text":"rendererDidDismissModal","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdiddismissmodal()","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidDismissModal()","type":"topic","title":"rendererDidDismissModal()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rendererDidDismissModal","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate":{"url":"\/documentation\/openwrapsdk\/pobadrendererdelegate","type":"topic","abstract":[{"text":"Ad banner rendering delegate, It is used to provide feedback events from custom renderer","type":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBAdRendererDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"POBAdRendererDelegate","kind":"identifier"}],"title":"POBAdRendererDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererDidFailToRenderAdWithError(_:for:)":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"rendererDidFailToRenderAdWithError:forDescriptor:","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidFailToRenderAdWithError(_:for:)","title":"rendererDidFailToRenderAdWithError(_:for:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rendererDidFailToRenderAdWithError","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")!, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)POBAdDescriptor","text":"POBAdDescriptor","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdidfailtorenderadwitherror(_:for:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/viewControllerForPresentingModal()":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/viewControllerForPresentingModal()","abstract":[],"role":"symbol","navigatorTitle":[{"text":"viewControllerForPresentingModal","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/viewcontrollerforpresentingmodal()","title":"viewControllerForPresentingModal()","required":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewControllerForPresentingModal"},{"text":"() -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererRequestedAdRefresh(afterInterval:)":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"rendererRequestedAdRefreshAfterInterval:","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rendererRequestedAdRefresh","kind":"identifier"},{"kind":"text","text":"("},{"text":"afterInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererRequestedAdRefresh(afterInterval:)","kind":"symbol","title":"rendererRequestedAdRefresh(afterInterval:)","url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererrequestedadrefresh(afterinterval:)","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererWillPresentModal()":{"abstract":[],"required":true,"navigatorTitle":[{"text":"rendererWillPresentModal","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererwillpresentmodal()","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererWillPresentModal()","title":"rendererWillPresentModal()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rendererWillPresentModal","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererWillLeaveApp()":{"url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererwillleaveapp()","type":"topic","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererWillLeaveApp()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rendererWillLeaveApp","kind":"identifier"},{"kind":"text","text":"()"}],"required":true,"navigatorTitle":[{"text":"rendererWillLeaveApp","kind":"identifier"}],"title":"rendererWillLeaveApp()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererDidClickAd(for:)":{"abstract":[],"navigatorTitle":[{"text":"rendererDidClickAdForDescriptor:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdidclickad(for:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidClickAd(for:)","title":"rendererDidClickAd(for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rendererDidClickAd"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"POBAdDescriptor","preciseIdentifier":"c:objc(pl)POBAdDescriptor"},{"text":")!)","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererDidUnloadMRAIDAd()":{"required":true,"title":"rendererDidUnloadMRAIDAd()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidUnloadMRAIDAd()","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rendererDidUnloadMRAIDAd","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdidunloadmraidad()","navigatorTitle":[{"text":"rendererDidUnloadMRAIDAd","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererDidPresentModal()":{"navigatorTitle":[{"text":"rendererDidPresentModal","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidPresentModal()","kind":"symbol","type":"topic","abstract":[],"title":"rendererDidPresentModal()","url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdidpresentmodal()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rendererDidPresentModal"},{"text":"()","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererDidRenderAd(_:for:)":{"navigatorTitle":[{"text":"rendererDidRenderAd:forDescriptor:","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdidrenderad(_:for:)","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidRenderAd(_:for:)","type":"topic","title":"rendererDidRenderAd(_:for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rendererDidRenderAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"!, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"POBAdDescriptor","preciseIdentifier":"c:objc(pl)POBAdDescriptor","kind":"typeIdentifier"},{"kind":"text","text":")!)"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererAboutToSkip(completion:)":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"rendererAboutToSkipWithCompletion:"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererabouttoskip(completion:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererAboutToSkip(completion:)","title":"rendererAboutToSkip(completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rendererAboutToSkip"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")!)","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","value":"POBAdRendererDelegate","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBAdRendererDelegate"}]},{"value":[{"kind":"identifier","text":"POBAdRendererDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererAboutToSkip(completion:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidClickAd(for:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidDismissModal()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidExpireAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidFailToRenderAdWithError(_:for:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidPresentModal()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidRecordImpression()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidRenderAd(_:for:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidUnloadMRAIDAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererRequestedAdRefresh(afterInterval:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererWillLeaveApp()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererWillPresentModal()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/viewControllerForPresentingModal()"],"title":"Instance Methods"}]},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBAdRendererDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["occ"]}]}},{"value":"rendererDidRecordImpression","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidRecordImpression()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rendererDidRecordImpression"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidRecordImpression()\/fragments"},{"value":"rendererDidExpireAd","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidExpireAd()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidExpireAd()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rendererDidExpireAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidDismissModal()\/title","value":"rendererDidDismissModal"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"rendererDidDismissModal","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidDismissModal()\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate\/title","value":"POBAdRendererDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"POBAdRendererDelegate"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate\/fragments","op":"replace"},{"value":"rendererDidFailToRenderAdWithError:forDescriptor:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidFailToRenderAdWithError(_:for:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidFailToRenderAdWithError(_:for:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rendererDidFailToRenderAdWithError:forDescriptor:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1viewControllerForPresentingModal()\/title","value":"viewControllerForPresentingModal"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1viewControllerForPresentingModal()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewControllerForPresentingModal","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererRequestedAdRefresh(afterInterval:)\/title","value":"rendererRequestedAdRefreshAfterInterval:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererRequestedAdRefresh(afterInterval:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"rendererRequestedAdRefreshAfterInterval:","kind":"identifier"}],"op":"replace"},{"value":"rendererWillPresentModal","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererWillPresentModal()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"rendererWillPresentModal","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererWillPresentModal()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererWillLeaveApp()\/title","value":"rendererWillLeaveApp","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"rendererWillLeaveApp","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererWillLeaveApp()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidClickAd(for:)\/title","value":"rendererDidClickAdForDescriptor:"},{"value":[{"text":"- ","kind":"text"},{"text":"rendererDidClickAdForDescriptor:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidClickAd(for:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidUnloadMRAIDAd()\/title","op":"replace","value":"rendererDidUnloadMRAIDAd"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidUnloadMRAIDAd()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rendererDidUnloadMRAIDAd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidPresentModal()\/title","op":"replace","value":"rendererDidPresentModal"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidPresentModal()\/fragments","value":[{"kind":"text","text":"- "},{"text":"rendererDidPresentModal","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidRenderAd(_:for:)\/title","op":"replace","value":"rendererDidRenderAd:forDescriptor:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidRenderAd(_:for:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rendererDidRenderAd:forDescriptor:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererAboutToSkip(completion:)\/title","op":"replace","value":"rendererAboutToSkipWithCompletion:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rendererAboutToSkipWithCompletion:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererAboutToSkip(completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}