{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBAdSizeMakeFromCGSize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"POBAdSize","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdSize","preciseIdentifier":"c:objc(cs)POBAdSize"},{"text":"!","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobadsizemakefromcgsize(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobadsizemakefromcgsize(_:)"]}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdSizeMakeFromCGSize(_:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"POBAdSizeMakeFromCGSize(_:)","roleHeading":"Function","externalID":"c:@F@POBAdSizeMakeFromCGSize","navigatorTitle":[{"kind":"identifier","text":"POBAdSizeMakeFromCGSize"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBAdSizeMakeFromCGSize"},{"text":"(","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"POBAdSize","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBAdSize"},{"text":"!","kind":"text"}],"symbolKind":"func"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdSize":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBAdSize","kind":"identifier"}],"navigatorTitle":[{"text":"POBAdSize","kind":"identifier"}],"title":"POBAdSize","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdSize","abstract":[{"type":"text","text":"Defines the size of a banner ad."}],"url":"\/documentation\/openwrapsdk\/pobadsize","kind":"symbol","type":"topic","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdSizeMakeFromCGSize(_:)":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdSizeMakeFromCGSize(_:)","kind":"symbol","title":"POBAdSizeMakeFromCGSize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"POBAdSizeMakeFromCGSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBAdSize","text":"POBAdSize","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"POBAdSizeMakeFromCGSize","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobadsizemakefromcgsize(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Function","path":"\/metadata\/roleHeading","op":"replace"},{"value":"POBAdSizeMakeFromCGSize","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBAdSizeMakeFromCGSize"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"POBAdSize","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdSize","preciseIdentifier":"c:objc(cs)POBAdSize"},{"kind":"text","text":" * "},{"text":"POBAdSizeMakeFromCGSize","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" "},{"text":"size","kind":"internalParam"},{"text":");","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdSize\/title","op":"replace","value":"POBAdSize"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdSize\/fragments","value":[{"kind":"identifier","text":"POBAdSize"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdSizeMakeFromCGSize(_:)\/title","value":"POBAdSizeMakeFromCGSize","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdSizeMakeFromCGSize(_:)\/fragments","value":[{"kind":"identifier","text":"POBAdSizeMakeFromCGSize"}]}]}]}