{"sections":[],"abstract":[{"type":"text","text":"Specify the bid event error"}],"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/adExpiry","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/clientSideAuctionLoss","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/other"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidEventErrorCode"}],"externalID":"c:@E@POBBidEventErrorCode","navigatorTitle":[{"kind":"identifier","text":"POBBidEventErrorCode"}],"symbolKind":"enum","roleHeading":"Enumeration","title":"POBBidEventErrorCode","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBBidEventErrorCode","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbideventerrorcode"]},{"paths":["\/documentation\/openwrapsdk\/pobbideventerrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/s8SendableP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.pubmatic.openwrapsdk/SY":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventErrorCode/clientSideAuctionLoss":{"navigatorTitle":[{"text":"POBBidEventErrorClientSideAuctionLoss","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbideventerrorcode\/clientsideauctionloss","abstract":[{"text":"Indicates client-side auction loss","type":"text"}],"kind":"symbol","title":"POBBidEventErrorCode.clientSideAuctionLoss","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientSideAuctionLoss"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/clientSideAuctionLoss","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventErrorCode/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbideventerrorcode\/rawrepresentable-implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://com.pubmatic.openwrapsdk/SQ":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/SH":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventErrorCode/init(rawValue:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/init(rawValue:)","role":"symbol","title":"init(rawValue:)","url":"\/documentation\/openwrapsdk\/pobbideventerrorcode\/init(rawvalue:)","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventErrorCode/other":{"type":"topic","abstract":[{"type":"text","text":"Other error, for custom use cases"}],"navigatorTitle":[{"text":"POBBidEventErrorOther","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/other","title":"POBBidEventErrorCode.other","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbideventerrorcode\/other"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventErrorCode/adExpiry":{"url":"\/documentation\/openwrapsdk\/pobbideventerrorcode\/adexpiry","title":"POBBidEventErrorCode.adExpiry","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/adExpiry","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adExpiry"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"POBBidEventErrorAdExpiry","kind":"identifier"}],"abstract":[{"text":"Indicates bid expiry","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventErrorCode":{"navigatorTitle":[{"text":"POBBidEventErrorCode","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbideventerrorcode","abstract":[{"type":"text","text":"Specify the bid event error"}],"kind":"symbol","title":"POBBidEventErrorCode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidEventErrorCode"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventErrorCode/Equatable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/openwrapsdk\/pobbideventerrorcode\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"POBBidEventErrorCode","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"POBBidEventErrorCode"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"POBBidEventErrorCode"}]},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/adExpiry","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/clientSideAuctionLoss","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/other"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBidEventErrorCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode~1clientSideAuctionLoss\/title","value":"POBBidEventErrorClientSideAuctionLoss","op":"replace"},{"value":[{"kind":"identifier","text":"POBBidEventErrorClientSideAuctionLoss"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode~1clientSideAuctionLoss\/fragments","op":"replace"},{"value":"POBBidEventErrorOther","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode~1other\/title"},{"value":[{"text":"POBBidEventErrorOther","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode~1other\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode~1adExpiry\/title","value":"POBBidEventErrorAdExpiry"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode~1adExpiry\/fragments","value":[{"kind":"identifier","text":"POBBidEventErrorAdExpiry"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode\/title","op":"replace","value":"POBBidEventErrorCode"},{"value":[{"text":"POBBidEventErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}