{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBOOLNo","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobboolno"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobboolno"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"var","roleHeading":"Global Variable","title":"POBBOOLNo","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBBOOLNo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:POBDataTypes.h@T@POBBOOL","text":"POBBOOL","kind":"typeIdentifier"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"POBBOOLNo","kind":"identifier"}],"externalID":"c:@POBBOOLNo"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBBOOLNo"},{"text":": ","kind":"text"},{"text":"POBBOOL","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBOOL","preciseIdentifier":"c:POBDataTypes.h@T@POBBOOL"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBOOLNo":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBOOLNo","kind":"symbol","title":"POBBOOLNo","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBOOLNo","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:POBDataTypes.h@T@POBBOOL","text":"POBBOOL"}],"navigatorTitle":[{"text":"POBBOOLNo","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobboolno"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBOOL":{"kind":"symbol","type":"topic","title":"POBBOOL","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBOOL","url":"\/documentation\/openwrapsdk\/pobbool","role":"symbol","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBOOL","kind":"identifier"}],"navigatorTitle":[{"text":"POBBOOL","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"POBBOOLNo","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBBOOLNo","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBBOOL","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBOOL","kind":"typeIdentifier","preciseIdentifier":"c:POBDataTypes.h@T@POBBOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBOOLNo"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBOOLNo\/title","value":"POBBOOLNo"},{"value":[{"text":"POBBOOLNo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBOOLNo\/fragments"},{"op":"replace","value":"POBBOOL","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBOOL\/title"},{"value":[{"text":"POBBOOL","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBOOL\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}