{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidderDelegate"},"abstract":[{"type":"text","text":"Ad bidder delegate protocol, which lists methods to be implmented by bidder delegate receiver."}],"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidderDelegate\/bidder(_:didFailToReceiveBidsWithError:)"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbidderdelegate"]},{"paths":["\/documentation\/openwrapsdk\/pobbidderdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBBidderDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBidderDelegate","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(pl)POBBidderDelegate","navigatorTitle":[{"kind":"identifier","text":"POBBidderDelegate"}],"roleHeading":"Protocol","symbolKind":"protocol","title":"POBBidderDelegate"},"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidderDelegate/bidder:didReceiveAdResponse:":{"role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"bidder:didReceiveAdResponse:","kind":"identifier"}],"type":"topic","url":"\/documentation\/openwrapsdk\/pobbidderdelegate\/bidder:didreceiveadresponse:","navigatorTitle":[{"text":"bidder:didReceiveAdResponse:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidderDelegate\/bidder:didReceiveAdResponse:","title":"bidder:didReceiveAdResponse:"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidderDelegate/bidder(_:didFailToReceiveBidsWithError:)":{"required":true,"url":"\/documentation\/openwrapsdk\/pobbidderdelegate\/bidder(_:didfailtoreceivebidswitherror:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"bidder:didFailToReceiveBidsWithError:"}],"kind":"symbol","title":"bidder(_:didFailToReceiveBidsWithError:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bidder"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"POBBidding","preciseIdentifier":"c:objc(pl)POBBidding"},{"kind":"text","text":", "},{"text":"didFailToReceiveBidsWithError","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidderDelegate\/bidder(_:didFailToReceiveBidsWithError:)","role":"symbol"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidderDelegate":{"navigatorTitle":[{"kind":"identifier","text":"POBBidderDelegate"}],"url":"\/documentation\/openwrapsdk\/pobbidderdelegate","abstract":[{"text":"Ad bidder delegate protocol, which lists methods to be implmented by bidder delegate receiver.","type":"text"}],"kind":"symbol","title":"POBBidderDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBBidderDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidderDelegate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"POBBidderDelegate","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBBidderDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"POBBidderDelegate"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidderDelegate\/bidder(_:didFailToReceiveBidsWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidderDelegate\/bidder:didReceiveAdResponse:"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBBidderDelegate"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidderDelegate~1bidder(_:didFailToReceiveBidsWithError:)\/title","value":"bidder:didFailToReceiveBidsWithError:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bidder:didFailToReceiveBidsWithError:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidderDelegate~1bidder(_:didFailToReceiveBidsWithError:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidderDelegate\/title","value":"POBBidderDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidderDelegate\/fragments","value":[{"kind":"identifier","text":"POBBidderDelegate"}]}]}]}