{"sections":[],"abstract":[{"text":"Ad bidding protocol, which lists methods to be implmented to add new bidder. which is responsible for getting bids from various bidders.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/bidderDelegate","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/identifier"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/requestBids()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding"},"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBBidding","kind":"identifier"}],"externalID":"c:objc(pl)POBBidding","navigatorTitle":[{"kind":"identifier","text":"POBBidding"}],"symbolKind":"protocol","roleHeading":"Protocol","title":"POBBidding","role":"symbol","modules":[{"name":"OpenWrapSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBBidding"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbidding"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobbidding"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidding/identifier":{"type":"topic","abstract":[{"type":"text","text":"Set\/Gets the id\/name of bidder."}],"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/identifier","title":"identifier","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbidding\/identifier"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidding":{"url":"\/documentation\/openwrapsdk\/pobbidding","role":"symbol","kind":"symbol","title":"POBBidding","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding","navigatorTitle":[{"text":"POBBidding","kind":"identifier"}],"type":"topic","abstract":[{"text":"Ad bidding protocol, which lists methods to be implmented to add new bidder. which is responsible for getting bids from various bidders.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidding"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidding/requestBids()":{"url":"\/documentation\/openwrapsdk\/pobbidding\/requestbids()","required":true,"kind":"symbol","title":"requestBids()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/requestBids()","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Sends RTB request to fetch the available bids."}],"navigatorTitle":[{"kind":"identifier","text":"requestBids"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestBids"},{"text":"()","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidding/bidderResultMappings":{"url":"\/documentation\/openwrapsdk\/pobbidding\/bidderresultmappings","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bidderResultMappings"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/bidderResultMappings","navigatorTitle":[{"text":"bidderResultMappings","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns bidder response dictionary, It contains the metadata about the response e.g. network response time, error reasons, bids…etc"}],"title":"bidderResultMappings"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidding/response":{"url":"\/documentation\/openwrapsdk\/pobbidding\/response","title":"response","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/response","type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"response","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"response"}],"abstract":[{"text":"Returns config updated by bidder response.","type":"text"}]},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidding/bidderDelegate":{"type":"topic","abstract":[{"type":"text","text":"The object that acts as the bidder delegate of the bidder & interested in getting notificaiton from bidder about bit success\/failure response."}],"navigatorTitle":[{"kind":"identifier","text":"bidderDelegate"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/bidderDelegate","title":"bidderDelegate","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bidderDelegate"},{"kind":"text","text":": (any "},{"text":"POBBidderDelegate","preciseIdentifier":"c:objc(pl)POBBidderDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbidding\/bidderdelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"value":"POBBidding","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBBidding"}]},{"value":[{"kind":"identifier","text":"POBBidding"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/bidderDelegate","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/identifier"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/bidderResultMappings","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/requestBids()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding\/response"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"POBBidding","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding~1identifier\/title","value":"identifier"},{"value":[{"text":"identifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding~1identifier\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding\/title","op":"replace","value":"POBBidding"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding\/fragments","value":[{"text":"POBBidding","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding~1requestBids()\/title","value":"requestBids","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"requestBids","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding~1requestBids()\/fragments"},{"value":"bidderDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding~1bidderDelegate\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding~1bidderDelegate\/fragments","value":[{"kind":"identifier","text":"bidderDelegate"}],"op":"replace"}]}]}