{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent","interfaceLanguage":"swift"},"metadata":{"symbolKind":"protocol","navigatorTitle":[{"text":"POBBannerEvent","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol","title":"POBBannerEvent","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBBannerEvent"}],"externalID":"c:objc(pl)POBBannerEvent","modules":[{"name":"OpenWrapSDK"}]},"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/adContentSize()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/adServerAdView()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/renderer(forPartner:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/requestAd(with:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/requestedAdSizes()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/setDelegate(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/trackClick()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/trackImpression()"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobbannerevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobbannerevent"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBBannerEvent","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEvent/renderer(forPartner:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderer","kind":"identifier"},{"kind":"text","text":"("},{"text":"forPartner","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBannerRendering","text":"POBBannerRendering"},{"text":")?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rendererForPartner:"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbannerevent\/renderer(forpartner:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/renderer(forPartner:)","title":"renderer(forPartner:)","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEvent/trackImpression()":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackImpression"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"trackImpression"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbannerevent\/trackimpression()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/trackImpression()","title":"trackImpression()","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEvent/adContentSize()":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adContentSize"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"navigatorTitle":[{"text":"adContentSize","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbannerevent\/adcontentsize()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/adContentSize()","title":"adContentSize()","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEvent/adServerAdView()":{"navigatorTitle":[{"kind":"identifier","text":"adServerAdView"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adServerAdView","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbannerevent\/adserveradview()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/adServerAdView()","title":"adServerAdView()","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEvent/requestedAdSizes()":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestedAdSizes","kind":"identifier"},{"kind":"text","text":"() -> ["},{"text":"POBAdSize","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBAdSize"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"requestedAdSizes"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbannerevent\/requestedadsizes()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/requestedAdSizes()","title":"requestedAdSizes()","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEvent":{"navigatorTitle":[{"text":"POBBannerEvent","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerevent","abstract":[],"kind":"symbol","title":"POBBannerEvent","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBBannerEvent"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEvent/requestAd(with:)":{"required":true,"url":"\/documentation\/openwrapsdk\/pobbannerevent\/requestad(with:)","abstract":[],"navigatorTitle":[{"text":"requestAdWithBid:","kind":"identifier"}],"kind":"symbol","title":"requestAd(with:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"requestAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)POBBid","kind":"typeIdentifier","text":"POBBid"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/requestAd(with:)","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEvent/trackClick()":{"navigatorTitle":[{"text":"trackClick","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"trackClick","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbannerevent\/trackclick()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/trackClick()","title":"trackClick()","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEvent/setDelegate(_:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"(any "},{"text":"POBBannerEventDelegate","preciseIdentifier":"c:objc(pl)POBBannerEventDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setDelegate:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbannerevent\/setdelegate(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/setDelegate(_:)","title":"setDelegate(_:)","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","value":"POBBannerEvent","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"text":"POBBannerEvent","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"POBBannerEvent"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/adContentSize()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/adServerAdView()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/renderer(forPartner:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/requestAd(with:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/requestedAdSizes()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/setDelegate(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/trackClick()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/trackImpression()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBannerEvent","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"rendererForPartner:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1renderer(forPartner:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1renderer(forPartner:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"rendererForPartner:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1trackImpression()\/title","value":"trackImpression"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackImpression"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1trackImpression()\/fragments"},{"value":"adContentSize","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1adContentSize()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adContentSize"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1adContentSize()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1adServerAdView()\/title","value":"adServerAdView"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1adServerAdView()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adServerAdView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1requestedAdSizes()\/title","value":"requestedAdSizes"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1requestedAdSizes()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"requestedAdSizes","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent\/title","value":"POBBannerEvent"},{"op":"replace","value":[{"kind":"identifier","text":"POBBannerEvent"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1requestAd(with:)\/title","value":"requestAdWithBid:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"requestAdWithBid:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1requestAd(with:)\/fragments"},{"value":"trackClick","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1trackClick()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1trackClick()\/fragments","value":[{"kind":"text","text":"- "},{"text":"trackClick","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1setDelegate(_:)\/title","op":"replace","value":"setDelegate:"},{"value":[{"text":"- ","kind":"text"},{"text":"setDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1setDelegate(_:)\/fragments","op":"replace"}]}]}