{"metadata":{"externalID":"c:objc(cs)POBBannerView","role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"POBBannerView","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerView"}],"title":"POBBannerView"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/init(publisherId:profileId:adUnitId:adSizes:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/init(publisherId:profileId:adUnitId:eventHandler:)"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/delegate","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/impression","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/request"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/bid()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/creativeSize()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/forceRefresh()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/loadAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/loadAd(withResponse:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/pauseAutoRefresh()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/resumeAutoRefresh()"],"title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBannerView","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It renders a banner ad from either the ad server SDK or openwrap partner whichever gets a chance in the auction."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To request banner ad, your delegate must conform to POBBannerViewDelegate, to pass mandatory UIViewController using"}]},{"items":[{"content":[{"inlineContent":[{"text":"(UIViewController * _Nonnull)bannerViewPresentationController;","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","interfaceLanguage":"swift"},"abstract":[{"text":"The view class that displays the banner ad.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbannerview"]},{"paths":["\/documentation\/openwrapsdk\/pobbannerview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)UIView"],"kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSCoding","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)CALayerDelegate","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearance","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearanceContainer","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UICoordinateSpace","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIDynamicItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusEnvironment","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItemContainer","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UILargeContentViewerItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pubmatic.openwrapsdk\/5UIKit23UITraitChangeObservableP","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UITraitEnvironment","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView":{"navigatorTitle":[{"kind":"identifier","text":"POBBannerView"}],"url":"\/documentation\/openwrapsdk\/pobbannerview","abstract":[{"text":"The view class that displays the banner ad.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerView"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","type":"topic","title":"POBBannerView","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/loadAd(withResponse:)":{"title":"loadAd(withResponse:)","url":"\/documentation\/openwrapsdk\/pobbannerview\/loadad(withresponse:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/loadAd(withResponse:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withResponse","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadAdWithResponse:"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/pauseAutoRefresh()":{"abstract":[{"type":"text","text":"Pauses the auto refresh, By default, banner refreshes automatically as per"},{"text":" ","type":"text"},{"type":"text","text":"configured refresh interval on openwrap portal. Calling this method"},{"type":"text","text":" "},{"text":"prevents the refresh cycle to happen even if a refresh interval has been specified.","type":"text"}],"navigatorTitle":[{"text":"pauseAutoRefresh","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerview\/pauseautorefresh()","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/pauseAutoRefresh()","type":"topic","title":"pauseAutoRefresh()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseAutoRefresh"},{"kind":"text","text":"()"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/resumeAutoRefresh()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resumeAutoRefresh","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Resumes the autorefresh as per configured refresh interval on openwrap portal, call this method only if you have previously paused autorefresh using "},{"code":"pauseAutoRefresh","type":"codeVoice"},{"type":"text","text":". This method has no effect if a refresh interval has not been set."}],"navigatorTitle":[{"kind":"identifier","text":"resumeAutoRefresh"}],"url":"\/documentation\/openwrapsdk\/pobbannerview\/resumeautorefresh()","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/resumeAutoRefresh()","title":"resumeAutoRefresh()"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/creativeSize()":{"type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"creativeSize","kind":"identifier"}],"title":"creativeSize()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"creativeSize"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBAdSize","kind":"typeIdentifier","text":"POBAdSize"}],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/creativeSize()","url":"\/documentation\/openwrapsdk\/pobbannerview\/creativesize()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/init(publisherId:profileId:adUnitId:adSizes:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"publisherId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"profileId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adUnitId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adSizes"},{"text":": [","kind":"text"},{"text":"POBAdSize","preciseIdentifier":"c:objc(cs)POBAdSize","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithPublisherId:profileId:adUnitId:adSizes:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerview\/init(publisherid:profileid:adunitid:adsizes:)","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/init(publisherId:profileId:adUnitId:adSizes:)","title":"init(publisherId:profileId:adUnitId:adSizes:)"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(cs)UIView":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)UIView","title":"UIView","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/loadAd()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAd","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"loadAd","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerview\/loadad()","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/loadAd()","title":"loadAd()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/impression":{"abstract":[],"navigatorTitle":[{"text":"impression","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbannerview\/impression","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/impression","title":"impression","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"impression","kind":"identifier"},{"text":": ","kind":"text"},{"text":"POBImpression","preciseIdentifier":"c:objc(cs)POBImpression","kind":"typeIdentifier"}]},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItemContainer"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSCoding"},"doc://com.pubmatic.openwrapsdk/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)CALayerDelegate"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearanceContainer"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearance"},"doc://com.pubmatic.openwrapsdk/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UILargeContentViewerItem"},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/delegate":{"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerview\/delegate","abstract":[],"kind":"symbol","title":"delegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)POBBannerViewDelegate","text":"POBBannerViewDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/delegate","role":"symbol"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItem"},"doc://com.pubmatic.openwrapsdk/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UICoordinateSpace"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/request":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"request","kind":"identifier"},{"text":": ","kind":"text"},{"text":"POBRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBRequest"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"request","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerview\/request","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/request","title":"request"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEvent":{"navigatorTitle":[{"text":"POBBidEvent","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidEvent"}],"abstract":[{"type":"text","text":"This prototol is responsinble for interacting with SDK’s banner & interstitial objects to get bid details, continue the bid execution flow."},{"type":"text","text":" "},{"text":"All methods of this protocol are expected to be called from Main thread.","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobbidevent","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent","title":"POBBidEvent","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UITraitEnvironment"},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAccessibilityIdentification"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/forceRefresh()":{"title":"forceRefresh()","abstract":[],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/forceRefresh()","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobbannerview\/forcerefresh()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"forceRefresh","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"forceRefresh"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/init(publisherId:profileId:adUnitId:eventHandler:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"publisherId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"profileId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adUnitId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"eventHandler","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"POBBannerEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBannerEvent"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithPublisherId:profileId:adUnitId:eventHandler:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerview\/init(publisherid:profileid:adunitid:eventhandler:)","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/init(publisherId:profileId:adUnitId:eventHandler:)","title":"init(publisherId:profileId:adUnitId:eventHandler:)"},"doc://com.pubmatic.openwrapsdk/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView/bid()":{"url":"\/documentation\/openwrapsdk\/pobbannerview\/bid()","title":"bid()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/bid()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bid","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"POBBid","preciseIdentifier":"c:objc(cs)POBBid","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"bid","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"POBBannerView","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBBannerView"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"POBBannerView"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/delegate","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/impression","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/request"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/bid()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/creativeSize()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/forceRefresh()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/init(publisherId:profileId:adUnitId:adSizes:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/init(publisherId:profileId:adUnitId:eventHandler:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/loadAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/loadAd(withResponse:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/pauseAutoRefresh()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView\/resumeAutoRefresh()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerView"},{"kind":"text","text":" : "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/title","op":"replace","value":"POBBannerView"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/fragments","value":[{"kind":"identifier","text":"POBBannerView"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1loadAd(withResponse:)\/title","op":"replace","value":"loadAdWithResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1loadAd(withResponse:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadAdWithResponse:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1pauseAutoRefresh()\/title","value":"pauseAutoRefresh","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1pauseAutoRefresh()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pauseAutoRefresh"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1resumeAutoRefresh()\/title","op":"replace","value":"resumeAutoRefresh"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1resumeAutoRefresh()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"resumeAutoRefresh"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1creativeSize()\/title","value":"creativeSize","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"creativeSize"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1creativeSize()\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1init(publisherId:profileId:adUnitId:adSizes:)\/title","value":"initWithPublisherId:profileId:adUnitId:adSizes:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithPublisherId:profileId:adUnitId:adSizes:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1init(publisherId:profileId:adUnitId:adSizes:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1loadAd()\/title","op":"replace","value":"loadAd"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1loadAd()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loadAd","kind":"identifier"}]},{"value":"impression","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1impression\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1impression\/fragments","value":[{"kind":"identifier","text":"impression"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1delegate\/title","op":"replace","value":"delegate"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1request\/title","value":"request"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1request\/fragments","value":[{"text":"request","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent\/title","op":"replace","value":"POBBidEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent\/fragments","value":[{"text":"POBBidEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1forceRefresh()\/title","value":"forceRefresh"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1forceRefresh()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"forceRefresh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1init(publisherId:profileId:adUnitId:eventHandler:)\/title","value":"initWithPublisherId:profileId:adUnitId:eventHandler:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1init(publisherId:profileId:adUnitId:eventHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPublisherId:profileId:adUnitId:eventHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1bid()\/title","op":"replace","value":"bid"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView~1bid()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bid","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}