{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd"],"title":"Conforming Types","type":"conformingTypes"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbidevent"]},{"paths":["\/documentation\/openwrapsdk\/pobbidevent"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"This prototol is responsinble for interacting with SDK’s banner & interstitial objects to get bid details, continue the bid execution flow."},{"type":"text","text":" "},{"type":"text","text":"All methods of this protocol are expected to be called from Main thread."}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBBidEvent","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"POBBidEvent","kind":"identifier"}],"externalID":"c:objc(pl)POBBidEvent","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBBidEvent","kind":"identifier"}],"title":"POBBidEvent","modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Protocol","role":"symbol"},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent\/bidEventDelegate"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent\/proceed(onError:andDescription:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent\/proceedToLoadAd()"]}],"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBInterstitial","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"POBInterstitial","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial","title":"POBInterstitial","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial","abstract":[{"text":"Displays Interstitial Ads.","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEvent/proceedToLoadAd()":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent\/proceedToLoadAd()","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"proceedToLoadAd"}],"url":"\/documentation\/openwrapsdk\/pobbidevent\/proceedtoloadad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"proceedToLoadAd"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"proceedToLoadAd()","kind":"symbol","role":"symbol","required":true},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEvent/proceed(onError:andDescription:)":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent\/proceed(onError:andDescription:)","abstract":[],"navigatorTitle":[{"text":"proceedOnError:andDescription:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbidevent\/proceed(onerror:anddescription:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"proceed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onError"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@POBBidEventErrorCode","text":"POBBidEventErrorCode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!)"}],"title":"proceed(onError:andDescription:)","kind":"symbol","role":"symbol","required":true},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAd":{"title":"POBRewardedAd","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","abstract":[{"type":"text","text":"Displays Rewarded Ads."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBRewardedAd"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedad","navigatorTitle":[{"text":"POBRewardedAd","kind":"identifier"}],"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEvent":{"navigatorTitle":[{"text":"POBBidEvent","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidEvent"}],"abstract":[{"type":"text","text":"This prototol is responsinble for interacting with SDK’s banner & interstitial objects to get bid details, continue the bid execution flow."},{"type":"text","text":" "},{"text":"All methods of this protocol are expected to be called from Main thread.","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobbidevent","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent","title":"POBBidEvent","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEvent/bidEventDelegate":{"title":"bidEventDelegate","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bidEventDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"POBBidEventDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBidEventDelegate"},{"text":")!","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent\/bidEventDelegate","abstract":[],"url":"\/documentation\/openwrapsdk\/pobbidevent\/bideventdelegate","navigatorTitle":[{"kind":"identifier","text":"bidEventDelegate"}],"required":true,"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerView":{"navigatorTitle":[{"kind":"identifier","text":"POBBannerView"}],"url":"\/documentation\/openwrapsdk\/pobbannerview","abstract":[{"text":"The view class that displays the banner ad.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerView"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","type":"topic","title":"POBBannerView","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","value":"POBBidEvent","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"POBBidEvent"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"POBBidEvent","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent\/bidEventDelegate"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent\/proceed(onError:andDescription:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent\/proceedToLoadAd()"]}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforming Types","type":"conformingTypes","kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerView","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBBidEvent","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"]}]}},{"value":"POBInterstitial","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/fragments","value":[{"text":"POBInterstitial","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent~1proceedToLoadAd()\/title","value":"proceedToLoadAd"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent~1proceedToLoadAd()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"proceedToLoadAd","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent~1proceed(onError:andDescription:)\/title","value":"proceedOnError:andDescription:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"proceedOnError:andDescription:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent~1proceed(onError:andDescription:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd\/title","value":"POBRewardedAd","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"POBRewardedAd"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd\/fragments"},{"value":"POBBidEvent","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent\/fragments","op":"replace","value":[{"text":"POBBidEvent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent~1bidEventDelegate\/title","op":"replace","value":"bidEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent~1bidEventDelegate\/fragments","value":[{"kind":"identifier","text":"bidEventDelegate"}]},{"value":"POBBannerView","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/title"},{"value":[{"text":"POBBannerView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerView\/fragments","op":"replace"}]}]}