{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBOOLYes","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobboolyes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobboolyes"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"POBBOOLYes","externalID":"c:@POBBOOLYes","roleHeading":"Global Variable","navigatorTitle":[{"kind":"identifier","text":"POBBOOLYes"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBOOLYes"},{"kind":"text","text":": "},{"text":"POBBOOL","preciseIdentifier":"c:POBDataTypes.h@T@POBBOOL","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"var"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBOOLYes","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBOOL","text":"POBBOOL","kind":"typeIdentifier","preciseIdentifier":"c:POBDataTypes.h@T@POBBOOL"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBOOLYes":{"kind":"symbol","type":"topic","title":"POBBOOLYes","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBOOLYes","url":"\/documentation\/openwrapsdk\/pobboolyes","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"POBBOOLYes","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:POBDataTypes.h@T@POBBOOL","text":"POBBOOL","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"POBBOOLYes","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBOOL":{"kind":"symbol","type":"topic","title":"POBBOOL","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBOOL","url":"\/documentation\/openwrapsdk\/pobbool","role":"symbol","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBOOL","kind":"identifier"}],"navigatorTitle":[{"text":"POBBOOL","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"POBBOOLYes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBBOOLYes"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:POBDataTypes.h@T@POBBOOL","kind":"typeIdentifier","text":"POBBOOL","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBBOOLYes"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBOOLYes\/title","value":"POBBOOLYes"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBOOLYes\/fragments","value":[{"text":"POBBOOLYes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBOOL\/title","value":"POBBOOL"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBOOL\/fragments","value":[{"text":"POBBOOL","kind":"identifier"}],"op":"replace"}]}]}