{"abstract":[{"text":"Protocol for interaction with the POBBannerView instance.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerView(_:didFailToReceiveAdWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidClickAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidDismissModal(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidReceiveAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidRecordImpression(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewPresentationController()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewWillLeaveApplication(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewWillPresentModal(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbannerviewdelegate"]},{"paths":["\/documentation\/openwrapsdk\/pobbannerviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBBannerViewDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"inlineContent":[{"text":"All messages are guaranteed to occur on the main thread.","type":"text"}],"type":"paragraph"}]}],"metadata":{"symbolKind":"protocol","navigatorTitle":[{"text":"POBBannerViewDelegate","kind":"identifier"}],"role":"symbol","title":"POBBannerViewDelegate","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBBannerViewDelegate","kind":"identifier"}],"externalID":"c:objc(pl)POBBannerViewDelegate","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate/bannerViewWillPresentModal(_:)":{"title":"bannerViewWillPresentModal(_:)","abstract":[],"navigatorTitle":[{"text":"bannerViewWillPresentModal:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewwillpresentmodal(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerViewWillPresentModal","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBBannerView","text":"POBBannerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewWillPresentModal(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate":{"navigatorTitle":[{"text":"POBBannerViewDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate","abstract":[{"text":"Protocol for interaction with the POBBannerView instance.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBBannerViewDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate","type":"topic","title":"POBBannerViewDelegate","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate/bannerViewPresentationController()":{"navigatorTitle":[{"text":"bannerViewPresentationController","kind":"identifier"}],"required":true,"title":"bannerViewPresentationController()","url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewpresentationcontroller()","abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewPresentationController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerViewPresentationController"},{"kind":"text","text":"() -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate/bannerView(_:didFailToReceiveAdWithError:)":{"navigatorTitle":[{"text":"bannerView:didFailToReceiveAdWithError:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerview(_:didfailtoreceiveadwitherror:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBBannerView","preciseIdentifier":"c:objc(cs)POBBannerView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToReceiveAdWithError"},{"text":": any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerView(_:didFailToReceiveAdWithError:)","type":"topic","title":"bannerView(_:didFailToReceiveAdWithError:)","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate/bannerViewDidReceiveAd(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bannerViewDidReceiveAd","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)POBBannerView","text":"POBBannerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"bannerViewDidReceiveAd:","kind":"identifier"}],"title":"bannerViewDidReceiveAd(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidReceiveAd(_:)","abstract":[],"url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewdidreceivead(_:)","type":"topic","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate/bannerViewDidRecordImpression(_:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bannerViewDidRecordImpression:"}],"url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewdidrecordimpression(_:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidRecordImpression(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bannerViewDidRecordImpression","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBannerView","text":"POBBannerView"},{"kind":"text","text":")"}],"title":"bannerViewDidRecordImpression(_:)","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate/bannerViewDidClickAd(_:)":{"abstract":[],"navigatorTitle":[{"text":"bannerViewDidClickAd:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewdidclickad(_:)","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidClickAd(_:)","type":"topic","title":"bannerViewDidClickAd(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bannerViewDidClickAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBBannerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBannerView"},{"kind":"text","text":")"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate/bannerViewDidDismissModal(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidDismissModal(_:)","navigatorTitle":[{"text":"bannerViewDidDismissModal:","kind":"identifier"}],"required":true,"abstract":[],"role":"symbol","type":"topic","title":"bannerViewDidDismissModal(_:)","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewdiddismissmodal(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerViewDidDismissModal"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"POBBannerView","preciseIdentifier":"c:objc(cs)POBBannerView"},{"kind":"text","text":")"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerViewDelegate/bannerViewWillLeaveApplication(_:)":{"abstract":[],"navigatorTitle":[{"text":"bannerViewWillLeaveApplication:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbannerviewdelegate\/bannerviewwillleaveapplication(_:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewWillLeaveApplication(_:)","title":"bannerViewWillLeaveApplication(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerViewWillLeaveApplication"},{"text":"(","kind":"text"},{"text":"POBBannerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBannerView"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"POBBannerViewDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBBannerViewDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"POBBannerViewDelegate","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerView(_:didFailToReceiveAdWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidClickAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidDismissModal(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidReceiveAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewDidRecordImpression(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewPresentationController()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewWillLeaveApplication(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerViewDelegate\/bannerViewWillPresentModal(_:)"]}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBBannerViewDelegate"},{"kind":"text","text":" <"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewWillPresentModal(_:)\/title","value":"bannerViewWillPresentModal:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewWillPresentModal(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bannerViewWillPresentModal:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate\/title","value":"POBBannerViewDelegate"},{"op":"replace","value":[{"text":"POBBannerViewDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewPresentationController()\/title","op":"replace","value":"bannerViewPresentationController"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewPresentationController()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bannerViewPresentationController"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerView(_:didFailToReceiveAdWithError:)\/title","op":"replace","value":"bannerView:didFailToReceiveAdWithError:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerView(_:didFailToReceiveAdWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"bannerView:didFailToReceiveAdWithError:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"bannerViewDidReceiveAd:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidReceiveAd(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidReceiveAd(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bannerViewDidReceiveAd:"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidRecordImpression(_:)\/title","op":"replace","value":"bannerViewDidRecordImpression:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidRecordImpression(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bannerViewDidRecordImpression:"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidClickAd(_:)\/title","op":"replace","value":"bannerViewDidClickAd:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidClickAd(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bannerViewDidClickAd:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidDismissModal(_:)\/title","value":"bannerViewDidDismissModal:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewDidDismissModal(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bannerViewDidDismissModal:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewWillLeaveApplication(_:)\/title","value":"bannerViewWillLeaveApplication:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerViewDelegate~1bannerViewWillLeaveApplication(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bannerViewWillLeaveApplication:","kind":"identifier"}]}]}]}