{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"abstract":[{"type":"text","text":"Protocol for bid event notifications"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBBidEventDelegate","kind":"identifier"}],"externalID":"c:objc(pl)POBBidEventDelegate","navigatorTitle":[{"kind":"identifier","text":"POBBidEventDelegate"}],"symbolKind":"protocol","roleHeading":"Protocol","modules":[{"name":"OpenWrapSDK"}],"title":"POBBidEventDelegate","role":"symbol"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate\/bidEvent(_:didFailToReceiveBidWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate\/bidEvent(_:didReceive:)"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbideventdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobbideventdelegate"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBidEventDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"inlineContent":[{"text":"All messages are guaranteed to occur on the main thread.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventDelegate/bidEvent(_:didFailToReceiveBidWithError:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bidEvent"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBidEvent","text":"POBBidEvent"},{"kind":"text","text":")!, "},{"kind":"externalParam","text":"didFailToReceiveBidWithError"},{"text":": (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")!)","kind":"text"}],"navigatorTitle":[{"text":"bidEvent:didFailToReceiveBidWithError:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbideventdelegate\/bidevent(_:didfailtoreceivebidwitherror:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate\/bidEvent(_:didFailToReceiveBidWithError:)","title":"bidEvent(_:didFailToReceiveBidWithError:)","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventDelegate/bidEvent(_:didReceive:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bidEvent","kind":"identifier"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)POBBidEvent","text":"POBBidEvent","kind":"typeIdentifier"},{"text":")!, ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBBid","kind":"typeIdentifier","text":"POBBid"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"bidEvent:didReceiveBid:"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbideventdelegate\/bidevent(_:didreceive:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate\/bidEvent(_:didReceive:)","title":"bidEvent(_:didReceive:)","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventDelegate":{"navigatorTitle":[{"kind":"identifier","text":"POBBidEventDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBidEventDelegate","kind":"identifier"}],"abstract":[{"text":"Protocol for bid event notifications","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobbideventdelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate","title":"POBBidEventDelegate","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"POBBidEventDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"POBBidEventDelegate","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"POBBidEventDelegate"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate\/bidEvent(_:didFailToReceiveBidWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate\/bidEvent(_:didReceive:)"]}],"op":"replace"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBBidEventDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate~1bidEvent(_:didFailToReceiveBidWithError:)\/title","op":"replace","value":"bidEvent:didFailToReceiveBidWithError:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate~1bidEvent(_:didFailToReceiveBidWithError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bidEvent:didFailToReceiveBidWithError:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate~1bidEvent(_:didReceive:)\/title","value":"bidEvent:didReceiveBid:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"bidEvent:didReceiveBid:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate~1bidEvent(_:didReceive:)\/fragments","op":"replace"},{"value":"POBBidEventDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate\/fragments","op":"replace","value":[{"text":"POBBidEventDelegate","kind":"identifier"}]}]}]}