{"abstract":[{"text":"DSA (Digital Services Act) compliance requirement status.","type":"text"}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"kind":"relationships"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/notRequired","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/optional","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/required","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/requiredPubOnlinePlatform"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobdsacompliancestatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobdsacompliancestatus"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBDSAComplianceStatus","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"enum","navigatorTitle":[{"text":"POBDSAComplianceStatus","kind":"identifier"}],"role":"symbol","title":"POBDSAComplianceStatus","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBDSAComplianceStatus"}],"externalID":"c:@E@POBDSAComplianceStatus","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus/notRequired":{"navigatorTitle":[{"kind":"identifier","text":"POBDSAComplianceStatusNotRequired"}],"url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus\/notrequired","abstract":[{"type":"text","text":"Not required"}],"kind":"symbol","title":"POBDSAComplianceStatus.notRequired","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notRequired","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/notRequired","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus/init(rawValue:)":{"url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus\/init(rawvalue:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(rawValue:)","abstract":[]},"doc://com.pubmatic.openwrapsdk/SQ":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus/requiredPubOnlinePlatform":{"type":"topic","title":"POBDSAComplianceStatus.requiredPubOnlinePlatform","url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus\/requiredpubonlineplatform","role":"symbol","abstract":[{"text":"Required, bid responses without DSA object will not be accepted, Publisher is an Online Platform","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Only bid response with DSA info will be rendered."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"requiredPubOnlinePlatform","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBDSAComplianceStatusRequiredPubOnlinePlatform"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/requiredPubOnlinePlatform"},"doc://com.pubmatic.openwrapsdk/SY":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.pubmatic.openwrapsdk/SH":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus/required":{"url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus\/required","title":"POBDSAComplianceStatus.required","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/required","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"required","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"POBDSAComplianceStatusRequired","kind":"identifier"}],"abstract":[{"type":"text","text":"Required, bid responses without a DSA object will not be accepted, only bid response"},{"text":" ","type":"text"},{"type":"text","text":"with DSA info will be rendered."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus\/equatable-implementations","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/Equatable-Implementations","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus\/rawrepresentable-implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus","url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBDSAComplianceStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBDSAComplianceStatus"}],"role":"symbol","title":"POBDSAComplianceStatus","abstract":[{"type":"text","text":"DSA (Digital Services Act) compliance requirement status."}]},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus/optional":{"type":"topic","abstract":[{"text":"Optional, bid responses with or without the DSA object will be accepted and","type":"text"},{"type":"text","text":" "},{"type":"text","text":"DSA info will be rendered if available in bid response."}],"navigatorTitle":[{"text":"POBDSAComplianceStatusOptional","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/optional","title":"POBDSAComplianceStatus.optional","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"optional","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus\/optional"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"POBDSAComplianceStatus","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"POBDSAComplianceStatus","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"POBDSAComplianceStatus"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/notRequired","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/optional","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/required","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/requiredPubOnlinePlatform"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBDSAComplianceStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus~1notRequired\/title","op":"replace","value":"POBDSAComplianceStatusNotRequired"},{"value":[{"text":"POBDSAComplianceStatusNotRequired","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus~1notRequired\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus~1requiredPubOnlinePlatform\/title","value":"POBDSAComplianceStatusRequiredPubOnlinePlatform"},{"op":"replace","value":[{"text":"POBDSAComplianceStatusRequiredPubOnlinePlatform","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus~1requiredPubOnlinePlatform\/fragments"},{"value":"POBDSAComplianceStatusRequired","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus~1required\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus~1required\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBDSAComplianceStatusRequired"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus\/title","op":"replace","value":"POBDSAComplianceStatus"},{"op":"replace","value":[{"text":"POBDSAComplianceStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus\/fragments"},{"op":"replace","value":"POBDSAComplianceStatusOptional","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus~1optional\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus~1optional\/fragments","value":[{"kind":"identifier","text":"POBDSAComplianceStatusOptional"}],"op":"replace"}]}]}