{"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"],"kind":"relationships"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The POBDSATransparencyInfo class represents the transparency information for DSA (Digital Services Act) compliance."},{"type":"text","text":" "},{"text":"It provides the domain name and user parameters for platform or sell-side use.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBDSATransparencyInfo"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobdsatransparencyinfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobdsatransparencyinfo"]}],"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/domainName","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/userParams"],"title":"Instance Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/build(with:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/uniqueUserParamsString(from:)"]}],"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBDSATransparencyInfo","kind":"identifier"}],"title":"POBDSATransparencyInfo","navigatorTitle":[{"text":"POBDSATransparencyInfo","kind":"identifier"}],"externalID":"c:objc(cs)POBDSATransparencyInfo","symbolKind":"class","role":"symbol","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.pubmatic.openwrapsdk/SH":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSATransparencyInfo/domainName":{"title":"domainName","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"domainName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/domainname","navigatorTitle":[{"kind":"identifier","text":"domainName"}],"abstract":[{"type":"text","text":"Domain of the entity that applied user parameters for DSA."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/domainName"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSATransparencyInfo/uniqueUserParamsString(from:)":{"title":"uniqueUserParamsString(from:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uniqueUserParamsString"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"POBDSATransparencyInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBDSATransparencyInfo"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/uniqueuserparamsstring(from:)","navigatorTitle":[{"text":"uniqueUserParamsStringFromArray:","kind":"identifier"}],"abstract":[{"text":"Creates a unique, comma-separated string of user parameters from an array of transparency info objects.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/uniqueUserParamsString(from:)"},"doc://com.pubmatic.openwrapsdk/objc(cs)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSATransparencyInfo":{"url":"\/documentation\/openwrapsdk\/pobdsatransparencyinfo","type":"topic","title":"POBDSATransparencyInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBDSATransparencyInfo","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo","role":"symbol","abstract":[{"type":"text","text":"The POBDSATransparencyInfo class represents the transparency information for DSA (Digital Services Act) compliance."},{"text":" ","type":"text"},{"type":"text","text":"It provides the domain name and user parameters for platform or sell-side use."}],"navigatorTitle":[{"kind":"identifier","text":"POBDSATransparencyInfo"}],"kind":"symbol"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/SQ":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSATransparencyInfo/build(with:)":{"title":"build(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]) -> ","kind":"text"},{"text":"POBDSATransparencyInfo","preciseIdentifier":"c:objc(cs)POBDSATransparencyInfo","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/build(with:)","navigatorTitle":[{"text":"buildWithDictionary:","kind":"identifier"}],"abstract":[{"text":"Creates and returns a POBDSATransparencyInfo instance based on the provided dictionary.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/build(with:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSATransparencyInfo/userParams":{"title":"userParams","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"userParams","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"]","kind":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/userparams","navigatorTitle":[{"text":"userParams","kind":"identifier"}],"abstract":[{"text":"An array of NSNumber objects representing user parameters for platform or sell-side use.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This property stores an array of integers, encapsulated as NSNumber objects,"},{"type":"text","text":" "},{"type":"text","text":"that can be used by the platform or sell-side for DSA compliance."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/userParams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"POBDSATransparencyInfo","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"POBDSATransparencyInfo","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"POBDSATransparencyInfo"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/domainName","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/userParams"]},{"title":"Type Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/build(with:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/uniqueUserParamsString(from:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBDSATransparencyInfo","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"domainName","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1domainName\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1domainName\/fragments","op":"replace","value":[{"text":"domainName","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1uniqueUserParamsString(from:)\/title","value":"uniqueUserParamsStringFromArray:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"uniqueUserParamsStringFromArray:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1uniqueUserParamsString(from:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo\/title","op":"replace","value":"POBDSATransparencyInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo\/fragments","value":[{"text":"POBDSATransparencyInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1build(with:)\/title","value":"buildWithDictionary:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1build(with:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"buildWithDictionary:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"userParams","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1userParams\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1userParams\/fragments","value":[{"kind":"identifier","text":"userParams"}]}]}]}