{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBExternalUserId"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobexternaluserid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobexternaluserid"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/init(source:andId:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/atype","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/extension","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/externalUserId","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/source"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBExternalUserId"}],"roleHeading":"Class","title":"POBExternalUserId","modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"POBExternalUserId","kind":"identifier"}],"externalID":"c:objc(cs)POBExternalUserId"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"]}],"abstract":[{"text":"Class to hold the user’s identity data.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This data will be fetched by the application from identity vendors which is required by different identity partners."},{"text":" ","type":"text"},{"text":"Application should pass this data to OpenWrap SDK which will be sent in each ad request.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBExternalUserId/externalUserId":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"externalUserId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"externalUserId","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobexternaluserid\/externaluserid","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/externalUserId","role":"symbol","navigatorTitle":[{"text":"externalUserId","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP"},"doc://com.pubmatic.openwrapsdk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBExternalUserId/atype":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"atype","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"title":"atype","kind":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobexternaluserid\/atype","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/atype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"atype"}]},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBExternalUserId":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBExternalUserId","kind":"identifier"}],"title":"POBExternalUserId","kind":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobexternaluserid","abstract":[{"text":"Class to hold the user’s identity data.","type":"text"},{"text":" ","type":"text"},{"text":"This data will be fetched by the application from identity vendors which is required by different identity partners.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Application should pass this data to OpenWrap SDK which will be sent in each ad request."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId","role":"symbol","navigatorTitle":[{"text":"POBExternalUserId","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBExternalUserId/init(source:andId:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"source","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"andId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(source:andId:)","kind":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobexternaluserid\/init(source:andid:)","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/init(source:andId:)","role":"symbol","navigatorTitle":[{"text":"initWithSource:andId:","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/SQ":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBExternalUserId/source":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"source","kind":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobexternaluserid\/source","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/source","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"source"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBExternalUserId/extension":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"`extension`","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":"]"}],"title":"extension","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobexternaluserid\/extension","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/extension","role":"symbol","navigatorTitle":[{"text":"extension","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"POBExternalUserId","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"POBExternalUserId","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"POBExternalUserId","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/atype","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/extension","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/externalUserId","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/source"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId\/init(source:andId:)"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBExternalUserId"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0"},{"value":"externalUserId","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId~1externalUserId\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId~1externalUserId\/fragments","value":[{"text":"externalUserId","kind":"identifier"}],"op":"replace"},{"value":"atype","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId~1atype\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId~1atype\/fragments","value":[{"kind":"identifier","text":"atype"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId\/title","op":"replace","value":"POBExternalUserId"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId\/fragments","op":"replace","value":[{"text":"POBExternalUserId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId~1init(source:andId:)\/title","op":"replace","value":"initWithSource:andId:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId~1init(source:andId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSource:andId:","kind":"identifier"}],"op":"replace"},{"value":"source","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId~1source\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId~1source\/fragments","value":[{"kind":"identifier","text":"source"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId~1extension\/title","value":"extension"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId~1extension\/fragments","op":"replace","value":[{"kind":"identifier","text":"extension"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}