{"sections":[],"abstract":[{"type":"text","text":"Error codes PubMatic SDK gives in error callback."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdAlreadyShown","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdExpired","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdNotReady","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdNotUsed","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdRequestNotAllowed","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdServerAuctionLost","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorClientSideAuctionLost","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInitFailed","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInternalError","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInvalidRequest","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInvalidResponse","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInvalidRewardSelected","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorNetworkError","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorNoAds","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorNoPartnerDetails","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorRenderError","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorRequestCancelled","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorServerError","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorTimeout","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/signalingError"]},{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/RawRepresentable-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode"},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBErrorCode","kind":"identifier"}],"externalID":"c:@E@POBErrorCode","navigatorTitle":[{"text":"POBErrorCode","kind":"identifier"}],"symbolKind":"enum","roleHeading":"Enumeration","title":"POBErrorCode","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBErrorCode","kind":"identifier"}]}]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/poberrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/poberrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/Equatable-Implementations":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/Equatable-Implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/openwrapsdk\/poberrorcode\/equatable-implementations","abstract":[],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorAdNotReady":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"POBErrorAdNotReady","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/poberrorcode\/erroradnotready","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdNotReady","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorAdNotReady","kind":"identifier"}],"title":"POBErrorCode.errorAdNotReady","abstract":[{"type":"text","text":"Indicated ad is not ready to show yet"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/init(rawValue:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/openwrapsdk\/poberrorcode\/init(rawvalue:)","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorAdAlreadyShown":{"type":"topic","abstract":[{"type":"text","text":"Indicates ad is already shown"}],"navigatorTitle":[{"text":"POBErrorAdAlreadyShown","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdAlreadyShown","title":"POBErrorCode.errorAdAlreadyShown","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorAdAlreadyShown"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/poberrorcode\/erroradalreadyshown"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorNoPartnerDetails":{"type":"topic","abstract":[{"text":"Indicates that partner details are not found","type":"text"}],"navigatorTitle":[{"text":"POBErrorNoPartnerDetails","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorNoPartnerDetails","title":"POBErrorCode.errorNoPartnerDetails","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"errorNoPartnerDetails","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/poberrorcode\/errornopartnerdetails"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/signalingError":{"type":"topic","abstract":[{"text":"Ad server SDK sent unexpectd\/delayed partner bid win response","type":"text"}],"navigatorTitle":[{"text":"POBSignalingError","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/signalingError","title":"POBErrorCode.signalingError","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"signalingError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/poberrorcode\/signalingerror"},"doc://com.pubmatic.openwrapsdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","title":"Swift.RawRepresentable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorRenderError":{"navigatorTitle":[{"text":"POBErrorRenderError","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/poberrorcode\/errorrendererror","abstract":[{"type":"text","text":"There was some issue while rendering the creative."}],"kind":"symbol","title":"POBErrorCode.errorRenderError","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorRenderError","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorRenderError","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorServerError":{"abstract":[{"text":"Failed to process ad request by Ad Server.","type":"text"}],"url":"\/documentation\/openwrapsdk\/poberrorcode\/errorservererror","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorServerError","title":"POBErrorCode.errorServerError","type":"topic","navigatorTitle":[{"text":"POBErrorServerError","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorServerError"}]},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","title":"Swift.Sendable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode":{"url":"\/documentation\/openwrapsdk\/poberrorcode","type":"topic","abstract":[{"text":"Error codes PubMatic SDK gives in error callback.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBErrorCode","kind":"identifier"}],"title":"POBErrorCode","navigatorTitle":[{"kind":"identifier","text":"POBErrorCode"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorNetworkError":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorNetworkError","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/poberrorcode\/errornetworkerror","title":"POBErrorCode.errorNetworkError","abstract":[{"type":"text","text":"There was an error while retrieving the data from the network."}],"navigatorTitle":[{"kind":"identifier","text":"POBErrorNetworkError"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorNetworkError"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorInvalidRequest":{"title":"POBErrorCode.errorInvalidRequest","abstract":[{"text":"Invalid ad request. e.g, missing or invalid parameters","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"errorInvalidRequest","kind":"identifier"}],"navigatorTitle":[{"text":"POBErrorInvalidRequest","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/poberrorcode\/errorinvalidrequest","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInvalidRequest"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorAdExpired":{"type":"topic","abstract":[{"text":"Indicates ad is expired","type":"text"}],"navigatorTitle":[{"text":"POBErrorAdExpired","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdExpired","title":"POBErrorCode.errorAdExpired","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorAdExpired"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/poberrorcode\/erroradexpired"},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorTimeout":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorTimeout","type":"topic","kind":"symbol","url":"\/documentation\/openwrapsdk\/poberrorcode\/errortimeout","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"errorTimeout","kind":"identifier"}],"title":"POBErrorCode.errorTimeout","abstract":[{"type":"text","text":"Ad request was timed out"}],"navigatorTitle":[{"kind":"identifier","text":"POBErrorTimeout"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/RawRepresentable-Implementations":{"url":"\/documentation\/openwrapsdk\/poberrorcode\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","abstract":[],"kind":"article","role":"collectionGroup"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorInvalidResponse":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInvalidResponse","kind":"symbol","role":"symbol","title":"POBErrorCode.errorInvalidResponse","url":"\/documentation\/openwrapsdk\/poberrorcode\/errorinvalidresponse","abstract":[{"text":"Invalid ad response. SDK does not able to parse the response received from Server.","type":"text"}],"navigatorTitle":[{"text":"POBErrorInvalidResponse","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"errorInvalidResponse","kind":"identifier"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorInternalError":{"url":"\/documentation\/openwrapsdk\/poberrorcode\/errorinternalerror","abstract":[{"type":"text","text":"Internal error"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInternalError","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBErrorInternalError"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorInternalError"}],"title":"POBErrorCode.errorInternalError"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorRequestCancelled":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorRequestCancelled","role":"symbol","abstract":[{"type":"text","text":"Ad request gets cancelled."}],"url":"\/documentation\/openwrapsdk\/poberrorcode\/errorrequestcancelled","title":"POBErrorCode.errorRequestCancelled","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"errorRequestCancelled","kind":"identifier"}],"navigatorTitle":[{"text":"POBErrorRequestCancelled","kind":"identifier"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorAdNotUsed":{"type":"topic","abstract":[{"type":"text","text":"Bid won the auction but never used."}],"navigatorTitle":[{"kind":"identifier","text":"POBErrorAdNotUsed"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdNotUsed","title":"POBErrorCode.errorAdNotUsed","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"errorAdNotUsed","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/poberrorcode\/erroradnotused"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorAdRequestNotAllowed":{"title":"POBErrorCode.errorAdRequestNotAllowed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorAdRequestNotAllowed"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/poberrorcode\/erroradrequestnotallowed","navigatorTitle":[{"kind":"identifier","text":"POBErrorAdRequestNotAllowed"}],"abstract":[{"text":"Indicates  ad request not allowed for device’s current country","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdRequestNotAllowed"},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorClientSideAuctionLost":{"url":"\/documentation\/openwrapsdk\/poberrorcode\/errorclientsideauctionlost","type":"topic","abstract":[{"type":"text","text":"Bid lost the client auction between OpenWrap  server side partners and client side partners-"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorClientSideAuctionLost"}],"title":"POBErrorCode.errorClientSideAuctionLost","navigatorTitle":[{"text":"POBErrorClientSideAuctionLost","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorClientSideAuctionLost"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorNoAds":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorNoAds","url":"\/documentation\/openwrapsdk\/poberrorcode\/errornoads","abstract":[{"text":"There was no ads available to deliver for ad request.","type":"text"}],"title":"POBErrorCode.errorNoAds","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"errorNoAds","kind":"identifier"}],"navigatorTitle":[{"text":"POBErrorNoAds","kind":"identifier"}],"kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorAdServerAuctionLost":{"type":"topic","abstract":[{"type":"text","text":"Bid won the auction between OpenWrap partners but lost the primary ad server’s auction"}],"navigatorTitle":[{"text":"POBErrorAdServerAuctionLost","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdServerAuctionLost","title":"POBErrorCode.errorAdServerAuctionLost","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorAdServerAuctionLost"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/poberrorcode\/erroradserverauctionlost"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorInvalidRewardSelected":{"type":"topic","abstract":[{"text":"Indicates invalid reward selection","type":"text"}],"navigatorTitle":[{"text":"POBErrorInvalidRewardSelected","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInvalidRewardSelected","title":"POBErrorCode.errorInvalidRewardSelected","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"errorInvalidRewardSelected","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/poberrorcode\/errorinvalidrewardselected"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBErrorCode/errorInitFailed":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInitFailed","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/poberrorcode\/errorinitfailed","title":"POBErrorCode.errorInitFailed","abstract":[{"type":"text","text":"Indicates the "},{"type":"codeVoice","code":"OpenWrapSDKInit"},{"type":"text","text":" failed"}],"navigatorTitle":[{"text":"POBErrorInitFailed","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorInitFailed","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"POBErrorCode","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBErrorCode","kind":"identifier"}]},{"op":"replace","value":[{"text":"POBErrorCode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdAlreadyShown","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdExpired","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdNotReady","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdNotUsed","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdRequestNotAllowed","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorAdServerAuctionLost","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorClientSideAuctionLost","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInitFailed","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInternalError","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInvalidRequest","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInvalidResponse","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorInvalidRewardSelected","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorNetworkError","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorNoAds","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorNoPartnerDetails","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorRenderError","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorRequestCancelled","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorServerError","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/errorTimeout","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBErrorCode\/signalingError"],"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBErrorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"POBErrorAdNotReady","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorAdNotReady\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorAdNotReady\/fragments","value":[{"text":"POBErrorAdNotReady","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorAdAlreadyShown\/title","value":"POBErrorAdAlreadyShown","op":"replace"},{"op":"replace","value":[{"text":"POBErrorAdAlreadyShown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorAdAlreadyShown\/fragments"},{"value":"POBErrorNoPartnerDetails","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorNoPartnerDetails\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorNoPartnerDetails\/fragments","value":[{"kind":"identifier","text":"POBErrorNoPartnerDetails"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1signalingError\/title","op":"replace","value":"POBSignalingError"},{"op":"replace","value":[{"text":"POBSignalingError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1signalingError\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorRenderError\/title","op":"replace","value":"POBErrorRenderError"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorRenderError\/fragments","value":[{"kind":"identifier","text":"POBErrorRenderError"}]},{"value":"POBErrorServerError","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorServerError\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorServerError\/fragments","op":"replace","value":[{"text":"POBErrorServerError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode\/title","value":"POBErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode\/fragments","value":[{"text":"POBErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorNetworkError\/title","value":"POBErrorNetworkError"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorNetworkError\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBErrorNetworkError"}]},{"value":"POBErrorInvalidRequest","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorInvalidRequest\/title"},{"value":[{"kind":"identifier","text":"POBErrorInvalidRequest"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorInvalidRequest\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorAdExpired\/title","value":"POBErrorAdExpired"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorAdExpired\/fragments","value":[{"text":"POBErrorAdExpired","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorTimeout\/title","value":"POBErrorTimeout","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorTimeout\/fragments","value":[{"kind":"identifier","text":"POBErrorTimeout"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorInvalidResponse\/title","op":"replace","value":"POBErrorInvalidResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorInvalidResponse\/fragments","value":[{"kind":"identifier","text":"POBErrorInvalidResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorInternalError\/title","value":"POBErrorInternalError"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorInternalError\/fragments","value":[{"text":"POBErrorInternalError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorRequestCancelled\/title","op":"replace","value":"POBErrorRequestCancelled"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorRequestCancelled\/fragments","value":[{"kind":"identifier","text":"POBErrorRequestCancelled"}],"op":"replace"},{"op":"replace","value":"POBErrorAdNotUsed","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorAdNotUsed\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorAdNotUsed\/fragments","op":"replace","value":[{"text":"POBErrorAdNotUsed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorAdRequestNotAllowed\/title","op":"replace","value":"POBErrorAdRequestNotAllowed"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorAdRequestNotAllowed\/fragments","value":[{"text":"POBErrorAdRequestNotAllowed","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorClientSideAuctionLost\/title","value":"POBErrorClientSideAuctionLost"},{"op":"replace","value":[{"kind":"identifier","text":"POBErrorClientSideAuctionLost"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorClientSideAuctionLost\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorNoAds\/title","value":"POBErrorNoAds"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorNoAds\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBErrorNoAds"}]},{"value":"POBErrorAdServerAuctionLost","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorAdServerAuctionLost\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorAdServerAuctionLost\/fragments","value":[{"kind":"identifier","text":"POBErrorAdServerAuctionLost"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorInvalidRewardSelected\/title","value":"POBErrorInvalidRewardSelected"},{"value":[{"text":"POBErrorInvalidRewardSelected","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorInvalidRewardSelected\/fragments"},{"op":"replace","value":"POBErrorInitFailed","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorInitFailed\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBErrorCode~1errorInitFailed\/fragments","op":"replace","value":[{"text":"POBErrorInitFailed","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}