{"sections":[],"abstract":[{"text":"This delegate is used to inform the fullscreen ad events from OpenWrap SDK ads. Implement this if your ad server implementation requires to be informed about these events.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventClick()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidAppear()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidDisappear()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidExpire()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidLoad()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventFailedToLoadWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventFailedToShowWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventImpression()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillAppear()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillDisappear()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillLeaveApplication()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillRewardUser(_:)"],"title":"Instance Methods"}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBFullscreenAdInteractionDelegate","kind":"identifier"}],"externalID":"c:objc(pl)POBFullscreenAdInteractionDelegate","navigatorTitle":[{"kind":"identifier","text":"POBFullscreenAdInteractionDelegate"}],"symbolKind":"protocol","roleHeading":"Protocol","modules":[{"name":"OpenWrapSDK"}],"title":"POBFullscreenAdInteractionDelegate","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBFullscreenAdInteractionDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate":{"role":"symbol","title":"POBFullscreenAdInteractionDelegate","navigatorTitle":[{"kind":"identifier","text":"POBFullscreenAdInteractionDelegate"}],"abstract":[{"type":"text","text":"This delegate is used to inform the fullscreen ad events from OpenWrap SDK ads. Implement this if your ad server implementation requires to be informed about these events."}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBFullscreenAdInteractionDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventClick()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullscreenAdEventClick","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventclick()","type":"topic","title":"fullscreenAdEventClick()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventClick()","navigatorTitle":[{"text":"fullscreenAdEventClick","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventWillLeaveApplication()":{"title":"fullscreenAdEventWillLeaveApplication()","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreenAdEventWillLeaveApplication","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillLeaveApplication()","abstract":[],"url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventwillleaveapplication()","navigatorTitle":[{"kind":"identifier","text":"fullscreenAdEventWillLeaveApplication"}],"required":true,"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventWillAppear()":{"title":"fullscreenAdEventWillAppear()","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullscreenAdEventWillAppear"},{"kind":"text","text":"()"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"fullscreenAdEventWillAppear"}],"url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventwillappear()","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillAppear()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventDidDisappear()":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidDisappear()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fullscreenAdEventDidDisappear","kind":"identifier"},{"kind":"text","text":"()"}],"title":"fullscreenAdEventDidDisappear()","url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventdiddisappear()","abstract":[],"navigatorTitle":[{"text":"fullscreenAdEventDidDisappear","kind":"identifier"}],"required":true,"type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventWillDisappear()":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"fullscreenAdEventWillDisappear","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillDisappear()","title":"fullscreenAdEventWillDisappear()","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreenAdEventWillDisappear","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventwilldisappear()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventImpression()":{"title":"fullscreenAdEventImpression()","url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventimpression()","navigatorTitle":[{"kind":"identifier","text":"fullscreenAdEventImpression"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullscreenAdEventImpression"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventImpression()","abstract":[],"required":true},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventDidExpire()":{"kind":"symbol","type":"topic","title":"fullscreenAdEventDidExpire()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreenAdEventDidExpire"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"fullscreenAdEventDidExpire","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventdidexpire()","role":"symbol","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidExpire()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventDidLoad()":{"abstract":[],"required":true,"navigatorTitle":[{"kind":"identifier","text":"fullscreenAdEventDidLoad"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventdidload()","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidLoad()","title":"fullscreenAdEventDidLoad()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullscreenAdEventDidLoad","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventFailedToShowWithError(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"fullscreenAdEventFailedToShowWithError:","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventFailedToShowWithError(_:)","title":"fullscreenAdEventFailedToShowWithError(_:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreenAdEventFailedToShowWithError","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventfailedtoshowwitherror(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventWillRewardUser(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"fullscreenAdEventWillRewardUser:","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillRewardUser(_:)","title":"fullscreenAdEventWillRewardUser(_:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fullscreenAdEventWillRewardUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBReward","preciseIdentifier":"c:objc(cs)POBReward","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventwillrewarduser(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventDidAppear()":{"role":"symbol","title":"fullscreenAdEventDidAppear()","required":true,"navigatorTitle":[{"kind":"identifier","text":"fullscreenAdEventDidAppear"}],"abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreenAdEventDidAppear","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventdidappear()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidAppear()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventFailedToLoadWithError(_:)":{"title":"fullscreenAdEventFailedToLoadWithError(_:)","url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventfailedtoloadwitherror(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventFailedToLoadWithError(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullscreenAdEventFailedToLoadWithError","kind":"identifier"},{"kind":"text","text":"((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?)","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fullscreenAdEventFailedToLoadWithError:"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","value":"POBFullscreenAdInteractionDelegate","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"POBFullscreenAdInteractionDelegate"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"POBFullscreenAdInteractionDelegate"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventClick()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidAppear()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidDisappear()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidExpire()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidLoad()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventFailedToLoadWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventFailedToShowWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventImpression()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillAppear()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillDisappear()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillLeaveApplication()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillRewardUser(_:)"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBFullscreenAdInteractionDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate\/title","op":"replace","value":"POBFullscreenAdInteractionDelegate"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBFullscreenAdInteractionDelegate"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventClick()\/title","value":"fullscreenAdEventClick","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventClick()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fullscreenAdEventClick"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventWillLeaveApplication()\/title","value":"fullscreenAdEventWillLeaveApplication"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"fullscreenAdEventWillLeaveApplication","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventWillLeaveApplication()\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventWillAppear()\/title","op":"replace","value":"fullscreenAdEventWillAppear"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventWillAppear()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fullscreenAdEventWillAppear","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventDidDisappear()\/title","op":"replace","value":"fullscreenAdEventDidDisappear"},{"value":[{"text":"- ","kind":"text"},{"text":"fullscreenAdEventDidDisappear","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventDidDisappear()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventWillDisappear()\/title","op":"replace","value":"fullscreenAdEventWillDisappear"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventWillDisappear()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fullscreenAdEventWillDisappear","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventImpression()\/title","value":"fullscreenAdEventImpression","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fullscreenAdEventImpression"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventImpression()\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventDidExpire()\/title","op":"replace","value":"fullscreenAdEventDidExpire"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventDidExpire()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fullscreenAdEventDidExpire","kind":"identifier"}]},{"op":"replace","value":"fullscreenAdEventDidLoad","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventDidLoad()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fullscreenAdEventDidLoad"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventDidLoad()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventFailedToShowWithError(_:)\/title","value":"fullscreenAdEventFailedToShowWithError:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventFailedToShowWithError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fullscreenAdEventFailedToShowWithError:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventWillRewardUser(_:)\/title","value":"fullscreenAdEventWillRewardUser:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fullscreenAdEventWillRewardUser:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventWillRewardUser(_:)\/fragments","op":"replace"},{"value":"fullscreenAdEventDidAppear","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventDidAppear()\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventDidAppear()\/fragments","value":[{"kind":"text","text":"- "},{"text":"fullscreenAdEventDidAppear","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventFailedToLoadWithError(_:)\/title","op":"replace","value":"fullscreenAdEventFailedToLoadWithError:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fullscreenAdEventFailedToLoadWithError:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventFailedToLoadWithError(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}