{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"POBGender","modules":[{"name":"OpenWrapSDK"}],"navigatorTitle":[{"kind":"identifier","text":"POBGender"}],"symbolKind":"enum","role":"symbol","externalID":"c:@E@POBGender","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBGender","kind":"identifier"}]},"kind":"symbol","abstract":[{"type":"text","text":"Gender to help deliver more relevant ads."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/female","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/male","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/other"]},{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBGender","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobgender"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobgender"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBGender/female":{"type":"topic","navigatorTitle":[{"text":"POBGenderFemale","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/female","url":"\/documentation\/openwrapsdk\/pobgender\/female","kind":"symbol","abstract":[{"type":"text","text":"Gender female"}],"role":"symbol","title":"POBGender.female","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"female","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBGender":{"url":"\/documentation\/openwrapsdk\/pobgender","role":"symbol","title":"POBGender","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBGender","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"POBGender","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Gender to help deliver more relevant ads."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBGender/male":{"navigatorTitle":[{"text":"POBGenderMale","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobgender\/male","abstract":[{"text":"Gender male","type":"text"}],"kind":"symbol","title":"POBGender.male","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"male","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/male","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBGender/other":{"navigatorTitle":[{"kind":"identifier","text":"POBGenderOther"}],"url":"\/documentation\/openwrapsdk\/pobgender\/other","abstract":[{"text":"Other gender","type":"text"}],"kind":"symbol","title":"POBGender.other","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/other","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBGender/Equatable-Implementations":{"url":"\/documentation\/openwrapsdk\/pobgender\/equatable-implementations","abstract":[],"kind":"article","title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/Equatable-Implementations","role":"collectionGroup"},"doc://com.pubmatic.openwrapsdk/SQ":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBGender/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/openwrapsdk\/pobgender\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBGender/init(rawValue:)":{"url":"\/documentation\/openwrapsdk\/pobgender\/init(rawvalue:)","abstract":[],"kind":"symbol","title":"init(rawValue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/init(rawValue:)","role":"symbol"},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","title":"Swift.Sendable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","title":"Swift.RawRepresentable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"POBGender"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBGender","kind":"identifier"}]},{"value":[{"text":"POBGender","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/female","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/male","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/other"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBGender","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender~1female\/title","value":"POBGenderFemale","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"POBGenderFemale"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender~1female\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender\/title","value":"POBGender"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender\/fragments","value":[{"text":"POBGender","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender~1male\/title","op":"replace","value":"POBGenderMale"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender~1male\/fragments","value":[{"text":"POBGenderMale","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender~1other\/title","op":"replace","value":"POBGenderOther"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender~1other\/fragments","op":"replace","value":[{"text":"POBGenderOther","kind":"identifier"}]}]}]}