{"sections":[],"abstract":[{"type":"text","text":"Enum represents different criteria of ad impression record."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/method1pxViewable","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/methodOnLoad"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBImpressionCountingMethod","kind":"identifier"}],"externalID":"c:@E@POBImpressionCountingMethod","navigatorTitle":[{"text":"POBImpressionCountingMethod","kind":"identifier"}],"symbolKind":"enum","roleHeading":"Enumeration","title":"POBImpressionCountingMethod","role":"symbol","modules":[{"name":"OpenWrapSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBImpressionCountingMethod"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobimpressioncountingmethod"]},{"paths":["\/documentation\/openwrapsdk\/pobimpressioncountingmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBImpressionCountingMethod/method1pxViewable":{"url":"\/documentation\/openwrapsdk\/pobimpressioncountingmethod\/method1pxviewable","title":"POBImpressionCountingMethod.method1pxViewable","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBImpressionCountingMethod1pxViewable"}],"type":"topic","abstract":[{"text":"Record impression when at least 1 pixel of the ad is visible.","type":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/method1pxViewable","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"method1pxViewable"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBImpressionCountingMethod/init(rawValue:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobimpressioncountingmethod\/init(rawvalue:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"title":"init(rawValue:)","abstract":[]},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","title":"Swift.Sendable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBImpressionCountingMethod":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBImpressionCountingMethod"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBImpressionCountingMethod","kind":"identifier"}],"kind":"symbol","title":"POBImpressionCountingMethod","url":"\/documentation\/openwrapsdk\/pobimpressioncountingmethod","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod","type":"topic","abstract":[{"type":"text","text":"Enum represents different criteria of ad impression record."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBImpressionCountingMethod/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","url":"\/documentation\/openwrapsdk\/pobimpressioncountingmethod\/rawrepresentable-implementations","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/RawRepresentable-Implementations","type":"topic","abstract":[],"title":"RawRepresentable Implementations"},"doc://com.pubmatic.openwrapsdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","title":"Swift.RawRepresentable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBImpressionCountingMethod/Equatable-Implementations":{"url":"\/documentation\/openwrapsdk\/pobimpressioncountingmethod\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/Equatable-Implementations","kind":"article","type":"topic","role":"collectionGroup","title":"Equatable Implementations"},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH"},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBImpressionCountingMethod/methodOnLoad":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBImpressionCountingMethodOnLoad"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"methodOnLoad","kind":"identifier"}],"title":"POBImpressionCountingMethod.methodOnLoad","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobimpressioncountingmethod\/methodonload","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/methodOnLoad","type":"topic","abstract":[{"type":"text","text":"Record impression when ad is loaded in the web view."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"POBImpressionCountingMethod","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBImpressionCountingMethod","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"POBImpressionCountingMethod","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/method1pxViewable","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/methodOnLoad"]}],"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBImpressionCountingMethod","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"POBImpressionCountingMethod1pxViewable","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod~1method1pxViewable\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod~1method1pxViewable\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBImpressionCountingMethod1pxViewable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod\/title","value":"POBImpressionCountingMethod"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod\/fragments","op":"replace","value":[{"text":"POBImpressionCountingMethod","kind":"identifier"}]},{"value":"POBImpressionCountingMethodOnLoad","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod~1methodOnLoad\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod~1methodOnLoad\/fragments","value":[{"text":"POBImpressionCountingMethodOnLoad","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}