{"abstract":[{"text":"Displays Interstitial Ads.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"],"kind":"relationships","type":"conformsTo"}],"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/init(publisherId:profileId:adUnitId:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/init(publisherId:profileId:adUnitId:eventHandler:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/delegate","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/impression","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/isReady","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/request","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/videoDelegate"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/bid()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/loadAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/loadAd(withResponse:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/show(from:)"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobinterstitial"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitial"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBInterstitial","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"POBInterstitial","kind":"identifier"}],"role":"symbol","roleHeading":"Class","title":"POBInterstitial","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBInterstitial"}],"externalID":"c:objc(cs)POBInterstitial","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial/loadAd(withResponse:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"withResponse","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"loadAdWithResponse:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial\/loadad(withresponse:)","title":"loadAd(withResponse:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/loadAd(withResponse:)","abstract":[]},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial/delegate":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"POBInterstitialDelegate","preciseIdentifier":"c:objc(pl)POBInterstitialDelegate"},{"kind":"text","text":")?"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial\/delegate","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/delegate","title":"delegate"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial/bid()":{"url":"\/documentation\/openwrapsdk\/pobinterstitial\/bid()","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/bid()","abstract":[],"title":"bid()","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"bid","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)POBBid","kind":"typeIdentifier","text":"POBBid"}],"navigatorTitle":[{"kind":"identifier","text":"bid"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial/loadAd()":{"abstract":[],"navigatorTitle":[{"text":"loadAd","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial\/loadad()","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/loadAd()","title":"loadAd()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadAd"},{"text":"()","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial/request":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"request","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBRequest","kind":"typeIdentifier","text":"POBRequest"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"request"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial\/request","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/request","title":"request"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial/show(from:)":{"abstract":[],"navigatorTitle":[{"text":"showFromViewController:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial\/show(from:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/show(from:)","title":"show(from:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":")","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/SQ":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial/videoDelegate":{"title":"videoDelegate","navigatorTitle":[{"text":"videoDelegate","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/videoDelegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"videoDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"POBInterstitialVideoDelegate","preciseIdentifier":"c:objc(pl)POBInterstitialVideoDelegate"},{"text":")?","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobinterstitial\/videodelegate","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(cs)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEvent":{"navigatorTitle":[{"text":"POBBidEvent","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidEvent"}],"abstract":[{"type":"text","text":"This prototol is responsinble for interacting with SDK’s banner & interstitial objects to get bid details, continue the bid execution flow."},{"type":"text","text":" "},{"text":"All methods of this protocol are expected to be called from Main thread.","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobbidevent","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent","title":"POBBidEvent","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/SH":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial/init(publisherId:profileId:adUnitId:eventHandler:)":{"url":"\/documentation\/openwrapsdk\/pobinterstitial\/init(publisherid:profileid:adunitid:eventhandler:)","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/init(publisherId:profileId:adUnitId:eventHandler:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithPublisherId:profileId:adUnitId:eventHandler:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"publisherId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"profileId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":", "},{"text":"adUnitId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"eventHandler","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)POBInterstitialEvent","text":"POBInterstitialEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(publisherId:profileId:adUnitId:eventHandler:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial/init(publisherId:profileId:adUnitId:)":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"initWithPublisherId:profileId:adUnitId:","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/init(publisherId:profileId:adUnitId:)","title":"init(publisherId:profileId:adUnitId:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"publisherId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"profileId"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adUnitId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobinterstitial\/init(publisherid:profileid:adunitid:)"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial/isReady":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/isReady","kind":"symbol","role":"symbol","title":"isReady","url":"\/documentation\/openwrapsdk\/pobinterstitial\/isready","abstract":[],"navigatorTitle":[{"text":"isReady","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isReady","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBInterstitial","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"POBInterstitial","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial","title":"POBInterstitial","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial","abstract":[{"text":"Displays Interstitial Ads.","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial/impression":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"impression"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial\/impression","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/impression","title":"impression","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"impression"},{"text":": ","kind":"text"},{"text":"POBImpression","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBImpression"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"POBInterstitial","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"POBInterstitial","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"POBInterstitial","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/delegate","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/impression","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/isReady","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/request","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/videoDelegate"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/bid()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/init(publisherId:profileId:adUnitId:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/init(publisherId:profileId:adUnitId:eventHandler:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/loadAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/loadAd(withResponse:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/show(from:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent"],"title":"Conforms To","type":"conformsTo"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBInterstitial","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"loadAdWithResponse:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1loadAd(withResponse:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1loadAd(withResponse:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"loadAdWithResponse:","kind":"identifier"}],"op":"replace"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1delegate\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1bid()\/title","op":"replace","value":"bid"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1bid()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bid"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1loadAd()\/title","value":"loadAd","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1loadAd()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadAd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1request\/title","value":"request","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1request\/fragments","value":[{"text":"request","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1show(from:)\/title","op":"replace","value":"showFromViewController:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1show(from:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"showFromViewController:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1videoDelegate\/title","value":"videoDelegate"},{"value":[{"text":"videoDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1videoDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent\/title","value":"POBBidEvent"},{"value":[{"kind":"identifier","text":"POBBidEvent"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1init(publisherId:profileId:adUnitId:eventHandler:)\/title","value":"initWithPublisherId:profileId:adUnitId:eventHandler:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1init(publisherId:profileId:adUnitId:eventHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPublisherId:profileId:adUnitId:eventHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1init(publisherId:profileId:adUnitId:)\/title","op":"replace","value":"initWithPublisherId:profileId:adUnitId:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPublisherId:profileId:adUnitId:"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1init(publisherId:profileId:adUnitId:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1isReady\/title","value":"isReady","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1isReady\/fragments","value":[{"kind":"identifier","text":"isReady"}],"op":"replace"},{"value":"POBInterstitial","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/fragments","value":[{"text":"POBInterstitial","kind":"identifier"}]},{"value":"impression","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1impression\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1impression\/fragments","value":[{"text":"impression","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}