{"abstract":[{"type":"text","text":"Protocol for VAST based video ad events"},{"text":" ","type":"text"},{"type":"text","text":"All messages are guaranteed to occur on the main thread."}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialVideoDelegate","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBInterstitialVideoDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobinterstitialvideodelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialvideodelegate"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialVideoDelegate\/interstitialDidFinishVideoPlayback(_:)"]}],"metadata":{"navigatorTitle":[{"text":"POBInterstitialVideoDelegate","kind":"identifier"}],"title":"POBInterstitialVideoDelegate","roleHeading":"Protocol","symbolKind":"protocol","modules":[{"name":"OpenWrapSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBInterstitialVideoDelegate"}],"externalID":"c:objc(pl)POBInterstitialVideoDelegate"},"references":{"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialVideoDelegate":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialVideoDelegate","navigatorTitle":[{"kind":"identifier","text":"POBInterstitialVideoDelegate"}],"title":"POBInterstitialVideoDelegate","abstract":[{"type":"text","text":"Protocol for VAST based video ad events"},{"text":" ","type":"text"},{"text":"All messages are guaranteed to occur on the main thread.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobinterstitialvideodelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBInterstitialVideoDelegate","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialVideoDelegate/interstitialDidFinishVideoPlayback(_:)":{"type":"topic","title":"interstitialDidFinishVideoPlayback(_:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interstitialDidFinishVideoPlayback","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"interstitialDidFinishVideoPlayback:"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialVideoDelegate\/interstitialDidFinishVideoPlayback(_:)","url":"\/documentation\/openwrapsdk\/pobinterstitialvideodelegate\/interstitialdidfinishvideoplayback(_:)","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"POBInterstitialVideoDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"text":"POBInterstitialVideoDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"POBInterstitialVideoDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialVideoDelegate\/interstitialDidFinishVideoPlayback(_:)"],"title":"Instance Methods"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBInterstitialVideoDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialVideoDelegate\/title","value":"POBInterstitialVideoDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialVideoDelegate\/fragments","value":[{"text":"POBInterstitialVideoDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"interstitialDidFinishVideoPlayback:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialVideoDelegate~1interstitialDidFinishVideoPlayback(_:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialVideoDelegate~1interstitialDidFinishVideoPlayback(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interstitialDidFinishVideoPlayback:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}