{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendering"]},{"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendering"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBInterstitialRendering","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"protocol","title":"POBInterstitialRendering","externalID":"c:objc(pl)POBInterstitialRendering","navigatorTitle":[{"text":"POBInterstitialRendering","kind":"identifier"}]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialRendering","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/renderAdDescriptor(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/setDelegate(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/setVideoDelegate(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/show(from:in:)"]}],"abstract":[{"type":"text","text":"Ad interstitial rendering protocol, implement these methods to write custom ad renderer"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendering/setDelegate(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/setDelegate(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"text":"((any ","kind":"text"},{"kind":"typeIdentifier","text":"POBInterstitialRendererDelegate","preciseIdentifier":"c:objc(pl)POBInterstitialRendererDelegate"},{"text":")!)","kind":"text"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendering\/setdelegate(_:)","navigatorTitle":[{"kind":"identifier","text":"setDelegate:"}],"type":"topic","kind":"symbol","required":true,"role":"symbol","title":"setDelegate(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendering/show(from:in:)":{"title":"show(from:in:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"!, ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIInterfaceOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientation"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"showFromViewController:inOrientation:"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/show(from:in:)","type":"topic","url":"\/documentation\/openwrapsdk\/pobinterstitialrendering\/show(from:in:)","kind":"symbol","abstract":[],"required":true},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendering/renderAdDescriptor(_:)":{"type":"topic","title":"renderAdDescriptor(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/renderAdDescriptor(_:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"renderAdDescriptor","kind":"identifier"},{"text":"((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBAdDescriptor","text":"POBAdDescriptor"},{"kind":"text","text":")!)"}],"navigatorTitle":[{"kind":"identifier","text":"renderAdDescriptor:"}],"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobinterstitialrendering\/renderaddescriptor(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendering/setVideoDelegate(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/setVideoDelegate(_:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setVideoDelegate","kind":"identifier"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)POBVideoRenderingDelegate","kind":"typeIdentifier","text":"POBVideoRenderingDelegate"},{"text":")!)","kind":"text"}],"abstract":[],"title":"setVideoDelegate(_:)","url":"\/documentation\/openwrapsdk\/pobinterstitialrendering\/setvideodelegate(_:)","navigatorTitle":[{"kind":"identifier","text":"setVideoDelegate:"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendering":{"navigatorTitle":[{"text":"POBInterstitialRendering","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialRendering","kind":"identifier"}],"abstract":[{"type":"text","text":"Ad interstitial rendering protocol, implement these methods to write custom ad renderer"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendering","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering","title":"POBInterstitialRendering","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"POBInterstitialRendering"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"POBInterstitialRendering","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"POBInterstitialRendering"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/renderAdDescriptor(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/setDelegate(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/setVideoDelegate(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/show(from:in:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"POBInterstitialRendering","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1setDelegate(_:)\/title","op":"replace","value":"setDelegate:"},{"value":[{"text":"- ","kind":"text"},{"text":"setDelegate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1setDelegate(_:)\/fragments"},{"value":"showFromViewController:inOrientation:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1show(from:in:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"showFromViewController:inOrientation:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1show(from:in:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1renderAdDescriptor(_:)\/title","value":"renderAdDescriptor:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1renderAdDescriptor(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"renderAdDescriptor:"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1setVideoDelegate(_:)\/title","value":"setVideoDelegate:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setVideoDelegate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1setVideoDelegate(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering\/title","op":"replace","value":"POBInterstitialRendering"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering\/fragments","value":[{"kind":"identifier","text":"POBInterstitialRendering"}]}]}]}