{"sections":[],"abstract":[{"type":"text","text":"Ad interstitial rendering delegate, It is used to provide feedback events from custom renderer"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidClick()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidDismissModal()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidExpireAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidFailToRenderAdWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidPresentModal()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidRecordImpression()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidRenderAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidUnloadMRAIDAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererWillLeaveApp()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererWillPresentModal()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/viewControllerForPresentingModal()"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBInterstitialRendererDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"metadata":{"symbolKind":"protocol","modules":[{"name":"OpenWrapSDK"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBInterstitialRendererDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"POBInterstitialRendererDelegate"}],"roleHeading":"Protocol","externalID":"c:objc(pl)POBInterstitialRendererDelegate","title":"POBInterstitialRendererDelegate","role":"symbol"},"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/interstitialRendererWillLeaveApp()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialRendererWillLeaveApp"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialRendererWillLeaveApp"}],"type":"topic","url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererwillleaveapp()","abstract":[],"required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererWillLeaveApp()","title":"interstitialRendererWillLeaveApp()"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/interstitialRendererDidExpireAd()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"interstitialRendererDidExpireAd","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"interstitialRendererDidExpireAd","kind":"identifier"}],"type":"topic","url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidexpiread()","abstract":[{"type":"text","text":"This method is called to notify ad expiration"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidExpireAd()","title":"interstitialRendererDidExpireAd()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/interstitialRendererDidFailToRenderAdWithError(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialRendererDidFailToRenderAdWithError"},{"text":"((any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")!)"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialRendererDidFailToRenderAdWithError:"}],"type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidfailtorenderadwitherror(_:)","required":true,"kind":"symbol","role":"symbol","title":"interstitialRendererDidFailToRenderAdWithError(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidFailToRenderAdWithError(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/interstitialRendererDidClick()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialRendererDidClick"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialRendererDidClick"}],"type":"topic","url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidclick()","abstract":[],"required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidClick()","title":"interstitialRendererDidClick()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/viewControllerForPresentingModal()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewControllerForPresentingModal"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"viewControllerForPresentingModal"}],"type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/viewcontrollerforpresentingmodal()","required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/viewControllerForPresentingModal()","title":"viewControllerForPresentingModal()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/interstitialRendererDidPresentModal()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialRendererDidPresentModal"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialRendererDidPresentModal"}],"type":"topic","url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidpresentmodal()","abstract":[],"required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidPresentModal()","title":"interstitialRendererDidPresentModal()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/interstitialRendererDidRecordImpression()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialRendererDidRecordImpression"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialRendererDidRecordImpression"}],"type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidrecordimpression()","required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidRecordImpression()","title":"interstitialRendererDidRecordImpression()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/interstitialRendererDidUnloadMRAIDAd()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialRendererDidUnloadMRAIDAd"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialRendererDidUnloadMRAIDAd"}],"type":"topic","url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidunloadmraidad()","abstract":[],"required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidUnloadMRAIDAd()","title":"interstitialRendererDidUnloadMRAIDAd()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/interstitialRendererDidDismissModal()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialRendererDidDismissModal"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialRendererDidDismissModal"}],"type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdiddismissmodal()","required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidDismissModal()","title":"interstitialRendererDidDismissModal()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/interstitialRendererDidRenderAd()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialRendererDidRenderAd"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialRendererDidRenderAd"}],"type":"topic","url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidrenderad()","abstract":[],"required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidRenderAd()","title":"interstitialRendererDidRenderAd()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBInterstitialRendererDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBInterstitialRendererDelegate"}],"type":"topic","abstract":[{"type":"text","text":"Ad interstitial rendering delegate, It is used to provide feedback events from custom renderer"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate","title":"POBInterstitialRendererDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/interstitialRendererWillPresentModal()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"interstitialRendererWillPresentModal","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialRendererWillPresentModal"}],"type":"topic","url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererwillpresentmodal()","abstract":[],"required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererWillPresentModal()","title":"interstitialRendererWillPresentModal()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"POBInterstitialRendererDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"text":"POBInterstitialRendererDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"POBInterstitialRendererDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidClick()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidDismissModal()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidExpireAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidFailToRenderAdWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidPresentModal()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidRecordImpression()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidRenderAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidUnloadMRAIDAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererWillLeaveApp()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererWillPresentModal()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/viewControllerForPresentingModal()"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBInterstitialRendererDelegate"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererWillLeaveApp()\/title","value":"interstitialRendererWillLeaveApp","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererWillLeaveApp()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"interstitialRendererWillLeaveApp","kind":"identifier"}]},{"value":"interstitialRendererDidExpireAd","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidExpireAd()\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidExpireAd()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialRendererDidExpireAd"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidFailToRenderAdWithError(_:)\/title","op":"replace","value":"interstitialRendererDidFailToRenderAdWithError:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidFailToRenderAdWithError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"interstitialRendererDidFailToRenderAdWithError:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidClick()\/title","value":"interstitialRendererDidClick","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidClick()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interstitialRendererDidClick"}],"op":"replace"},{"value":"viewControllerForPresentingModal","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1viewControllerForPresentingModal()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewControllerForPresentingModal","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1viewControllerForPresentingModal()\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidPresentModal()\/title","value":"interstitialRendererDidPresentModal","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"interstitialRendererDidPresentModal","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidPresentModal()\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidRecordImpression()\/title","value":"interstitialRendererDidRecordImpression","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidRecordImpression()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"interstitialRendererDidRecordImpression","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidUnloadMRAIDAd()\/title","value":"interstitialRendererDidUnloadMRAIDAd","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"interstitialRendererDidUnloadMRAIDAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidUnloadMRAIDAd()\/fragments","op":"replace"},{"value":"interstitialRendererDidDismissModal","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidDismissModal()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"interstitialRendererDidDismissModal","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidDismissModal()\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidRenderAd()\/title","value":"interstitialRendererDidRenderAd","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidRenderAd()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"interstitialRendererDidRenderAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate\/title","value":"POBInterstitialRendererDelegate"},{"value":[{"text":"POBInterstitialRendererDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate\/fragments","op":"replace"},{"value":"interstitialRendererWillPresentModal","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererWillPresentModal()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"interstitialRendererWillPresentModal","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererWillPresentModal()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}