{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitial(_:didFailToReceiveAdWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitial(_:didFailToShowAdWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidClickAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidDismissAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidExpireAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidPresentAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidReceiveAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidRecordImpression(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialWillLeaveApplication(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialWillPresentAd(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBInterstitialDelegate"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate"},"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBInterstitialDelegate","kind":"identifier"}],"title":"POBInterstitialDelegate","roleHeading":"Protocol","symbolKind":"protocol","navigatorTitle":[{"text":"POBInterstitialDelegate","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(pl)POBInterstitialDelegate"},"abstract":[{"text":"Protocol for interaction with the POBInterstitial instance.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All messages are guaranteed to occur on the main thread."}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobinterstitialdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobinterstitialdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitial(_:didFailToReceiveAdWithError:)":{"role":"symbol","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitial"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBInterstitial","kind":"typeIdentifier","text":"POBInterstitial"},{"text":", ","kind":"text"},{"text":"didFailToReceiveAdWithError","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"title":"interstitial(_:didFailToReceiveAdWithError:)","navigatorTitle":[{"kind":"identifier","text":"interstitial:didFailToReceiveAdWithError:"}],"abstract":[],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitial(_:didfailtoreceiveadwitherror:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitial(_:didFailToReceiveAdWithError:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitialDidExpireAd(_:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialDidExpireAd","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"interstitialDidExpireAd(_:)","navigatorTitle":[{"kind":"identifier","text":"interstitialDidExpireAd:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidExpireAd(_:)","url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialdidexpiread(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitialDidDismissAd(_:)":{"role":"symbol","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialDidDismissAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBInterstitial","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBInterstitial"},{"text":")","kind":"text"}],"title":"interstitialDidDismissAd(_:)","navigatorTitle":[{"kind":"identifier","text":"interstitialDidDismissAd:"}],"abstract":[],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialdiddismissad(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidDismissAd(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitialDidRecordImpression(_:)":{"role":"symbol","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialDidRecordImpression","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"interstitialDidRecordImpression(_:)","navigatorTitle":[{"kind":"identifier","text":"interstitialDidRecordImpression:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidRecordImpression(_:)","url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialdidrecordimpression(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitialDidPresentAd(_:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialDidPresentAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBInterstitial","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBInterstitial"},{"text":")","kind":"text"}],"title":"interstitialDidPresentAd(_:)","navigatorTitle":[{"kind":"identifier","text":"interstitialDidPresentAd:"}],"abstract":[],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialdidpresentad(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidPresentAd(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate":{"kind":"symbol","title":"POBInterstitialDelegate","role":"symbol","abstract":[{"type":"text","text":"Protocol for interaction with the POBInterstitial instance."},{"text":" ","type":"text"},{"type":"text","text":"All messages are guaranteed to occur on the main thread."}],"url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBInterstitialDelegate"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitialWillLeaveApplication(_:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialWillLeaveApplication","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"interstitialWillLeaveApplication(_:)","navigatorTitle":[{"kind":"identifier","text":"interstitialWillLeaveApplication:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialWillLeaveApplication(_:)","url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialwillleaveapplication(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitialDidReceiveAd(_:)":{"kind":"symbol","title":"interstitialDidReceiveAd(_:)","role":"symbol","abstract":[],"url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialdidreceivead(_:)","required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialDidReceiveAd","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)POBInterstitial","kind":"typeIdentifier","text":"POBInterstitial"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialDidReceiveAd:"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidReceiveAd(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitialWillPresentAd(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialWillPresentAd","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"POBInterstitial","preciseIdentifier":"c:objc(cs)POBInterstitial"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialWillPresentAd:"}],"title":"interstitialWillPresentAd(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialWillPresentAd(_:)","url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialwillpresentad(_:)","type":"topic","abstract":[],"role":"symbol","required":true,"kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitialDidClickAd(_:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialDidClickAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBInterstitial","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBInterstitial"},{"text":")","kind":"text"}],"title":"interstitialDidClickAd(_:)","navigatorTitle":[{"kind":"identifier","text":"interstitialDidClickAd:"}],"abstract":[],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialdidclickad(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidClickAd(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitial(_:didFailToShowAdWithError:)":{"role":"symbol","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitial","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailToShowAdWithError"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"interstitial(_:didFailToShowAdWithError:)","navigatorTitle":[{"kind":"identifier","text":"interstitial:didFailToShowAdWithError:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitial(_:didFailToShowAdWithError:)","url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitial(_:didfailtoshowadwitherror:)"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"POBInterstitialDelegate","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"POBInterstitialDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"POBInterstitialDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitial(_:didFailToReceiveAdWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitial(_:didFailToShowAdWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidClickAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidDismissAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidExpireAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidPresentAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidReceiveAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidRecordImpression(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialWillLeaveApplication(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialWillPresentAd(_:)"]}]},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBInterstitialDelegate"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitial(_:didFailToReceiveAdWithError:)\/title","op":"replace","value":"interstitial:didFailToReceiveAdWithError:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitial(_:didFailToReceiveAdWithError:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interstitial:didFailToReceiveAdWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidExpireAd(_:)\/title","value":"interstitialDidExpireAd:"},{"value":[{"text":"- ","kind":"text"},{"text":"interstitialDidExpireAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidExpireAd(_:)\/fragments"},{"value":"interstitialDidDismissAd:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidDismissAd(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidDismissAd(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"interstitialDidDismissAd:","kind":"identifier"}]},{"value":"interstitialDidRecordImpression:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidRecordImpression(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidRecordImpression(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"interstitialDidRecordImpression:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidPresentAd(_:)\/title","value":"interstitialDidPresentAd:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interstitialDidPresentAd:"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidPresentAd(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate\/title","value":"POBInterstitialDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate\/fragments","op":"replace","value":[{"text":"POBInterstitialDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialWillLeaveApplication(_:)\/title","value":"interstitialWillLeaveApplication:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialWillLeaveApplication(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"interstitialWillLeaveApplication:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidReceiveAd(_:)\/title","value":"interstitialDidReceiveAd:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidReceiveAd(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"interstitialDidReceiveAd:","kind":"identifier"}]},{"op":"replace","value":"interstitialWillPresentAd:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialWillPresentAd(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialWillPresentAd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"interstitialWillPresentAd:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidClickAd(_:)\/title","value":"interstitialDidClickAd:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidClickAd(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"interstitialDidClickAd:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitial(_:didFailToShowAdWithError:)\/title","op":"replace","value":"interstitial:didFailToShowAdWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitial(_:didFailToShowAdWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"interstitial:didFailToShowAdWithError:","kind":"identifier"}]}]}]}