{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBInterstitialEventDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate","interfaceLanguage":"swift"},"abstract":[{"text":"The interstitial custom event delegate. It is used to inform ad server events back to the OpenWrap SDK","type":"text"}],"metadata":{"symbolKind":"protocol","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(pl)POBInterstitialEventDelegate","role":"symbol","title":"POBInterstitialEventDelegate","navigatorTitle":[{"text":"POBInterstitialEventDelegate","kind":"identifier"}],"roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBInterstitialEventDelegate"}]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobinterstitialeventdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobinterstitialeventdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/adDidExpireAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/adServerAdDidRecordImpression()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/adServerDidWin()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/bidsProvider()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/didClickAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/didDismissAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/didPresentAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/failedToLoadWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/failedToShowWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/openWrapPartnerDidWin(forBid:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/willLeaveApp()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/willPresentAd()"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/didPresentAd()":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/didpresentad()","required":true,"kind":"symbol","title":"didPresentAd()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/didPresentAd()","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"didPresentAd"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didPresentAd"},{"kind":"text","text":"()"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/failedToShowWithError(_:)":{"required":true,"type":"topic","title":"failedToShowWithError(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"failedToShowWithError","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/failedToShowWithError(_:)","role":"symbol","url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/failedtoshowwitherror(_:)","navigatorTitle":[{"text":"failedToShowWithError:","kind":"identifier"}],"kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/didDismissAd()":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/diddismissad()","required":true,"kind":"symbol","title":"didDismissAd()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/didDismissAd()","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"didDismissAd"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didDismissAd","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/didClickAd()":{"required":true,"title":"didClickAd()","url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/didclickad()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/didClickAd()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didClickAd"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"didClickAd","kind":"identifier"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/willLeaveApp()":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/willleaveapp()","title":"willLeaveApp()","navigatorTitle":[{"kind":"identifier","text":"willLeaveApp"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willLeaveApp"},{"text":"()","kind":"text"}],"required":true,"role":"symbol","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/willLeaveApp()","type":"topic","kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/adServerAdDidRecordImpression()":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/adserveraddidrecordimpression()","required":true,"kind":"symbol","title":"adServerAdDidRecordImpression()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/adServerAdDidRecordImpression()","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"adServerAdDidRecordImpression"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adServerAdDidRecordImpression"},{"kind":"text","text":"()"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/failedToLoadWithError(_:)":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/failedtoloadwitherror(_:)","required":true,"kind":"symbol","title":"failedToLoadWithError(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/failedToLoadWithError(_:)","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"failedToLoadWithError:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"failedToLoadWithError","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/bidsProvider()":{"abstract":[],"title":"bidsProvider()","type":"topic","role":"symbol","navigatorTitle":[{"text":"bidsProvider","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/bidsprovider()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bidsProvider","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)POBBidsProvider","text":"POBBidsProvider","kind":"typeIdentifier"}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/bidsProvider()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate","title":"POBInterstitialEventDelegate","navigatorTitle":[{"kind":"identifier","text":"POBInterstitialEventDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBInterstitialEventDelegate"}],"role":"symbol","abstract":[{"type":"text","text":"The interstitial custom event delegate. It is used to inform ad server events back to the OpenWrap SDK"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate","kind":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/openWrapPartnerDidWin(forBid:)":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/openwrappartnerdidwin(forbid:)","required":true,"kind":"symbol","title":"openWrapPartnerDidWin(forBid:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/openWrapPartnerDidWin(forBid:)","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"openWrapPartnerDidWinForBid:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"openWrapPartnerDidWin","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forBid"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/adDidExpireAd()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adDidExpireAd","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"adDidExpireAd","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/addidexpiread()","kind":"symbol","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/adDidExpireAd()","title":"adDidExpireAd()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/willPresentAd()":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/willpresentad()","required":true,"kind":"symbol","title":"willPresentAd()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/willPresentAd()","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"willPresentAd","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willPresentAd"},{"kind":"text","text":"()"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/adServerDidWin()":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"adServerDidWin"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/adserverdidwin()","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/adServerDidWin()","required":true,"title":"adServerDidWin()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adServerDidWin","kind":"identifier"},{"text":"()","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"POBInterstitialEventDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"POBInterstitialEventDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"POBInterstitialEventDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/adDidExpireAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/adServerAdDidRecordImpression()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/adServerDidWin()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/bidsProvider()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/didClickAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/didDismissAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/didPresentAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/failedToLoadWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/failedToShowWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/openWrapPartnerDidWin(forBid:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/willLeaveApp()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/willPresentAd()"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBInterstitialEventDelegate"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1didPresentAd()\/title","value":"didPresentAd","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1didPresentAd()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didPresentAd"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1failedToShowWithError(_:)\/title","op":"replace","value":"failedToShowWithError:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1failedToShowWithError(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"failedToShowWithError:","kind":"identifier"}]},{"value":"didDismissAd","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1didDismissAd()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1didDismissAd()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didDismissAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1didClickAd()\/title","value":"didClickAd","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didClickAd"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1didClickAd()\/fragments"},{"value":"willLeaveApp","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1willLeaveApp()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1willLeaveApp()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willLeaveApp"}]},{"value":"adServerAdDidRecordImpression","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1adServerAdDidRecordImpression()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1adServerAdDidRecordImpression()\/fragments","value":[{"kind":"text","text":"- "},{"text":"adServerAdDidRecordImpression","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1failedToLoadWithError(_:)\/title","value":"failedToLoadWithError:"},{"value":[{"text":"- ","kind":"text"},{"text":"failedToLoadWithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1failedToLoadWithError(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1bidsProvider()\/title","value":"bidsProvider","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"bidsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1bidsProvider()\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate\/title","value":"POBInterstitialEventDelegate","op":"replace"},{"value":[{"text":"POBInterstitialEventDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate\/fragments"},{"value":"openWrapPartnerDidWinForBid:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1openWrapPartnerDidWin(forBid:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1openWrapPartnerDidWin(forBid:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"openWrapPartnerDidWinForBid:","kind":"identifier"}],"op":"replace"},{"value":"adDidExpireAd","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1adDidExpireAd()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1adDidExpireAd()\/fragments","value":[{"kind":"text","text":"- "},{"text":"adDidExpireAd","kind":"identifier"}]},{"value":"willPresentAd","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1willPresentAd()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1willPresentAd()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willPresentAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1adServerDidWin()\/title","value":"adServerDidWin"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adServerDidWin"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1adServerDidWin()\/fragments"}]}]}