{"sections":[],"abstract":[{"type":"text","text":"Location source"}],"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/GPS","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/ipAddress","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/userProvided"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/RawRepresentable-Implementations"]}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBLocSource","kind":"identifier"}],"externalID":"c:@E@POBLocSource","navigatorTitle":[{"kind":"identifier","text":"POBLocSource"}],"symbolKind":"enum","roleHeading":"Enumeration","title":"POBLocSource","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBLocSource","kind":"identifier"}]}]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/poblocsource"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/poblocsource"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLocSource/ipAddress":{"title":"POBLocSource.ipAddress","abstract":[{"text":"Location is determined from IP address","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ipAddress"}],"navigatorTitle":[{"text":"POBLocSourceIPAddress","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/poblocsource\/ipaddress","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/ipAddress"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLocSource/Equatable-Implementations":{"kind":"article","type":"topic","title":"Equatable Implementations","url":"\/documentation\/openwrapsdk\/poblocsource\/equatable-implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/Equatable-Implementations"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLocSource/init(rawValue:)":{"url":"\/documentation\/openwrapsdk\/poblocsource\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/init(rawValue:)","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLocSource":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBLocSource"}],"abstract":[{"type":"text","text":"Location source"}],"title":"POBLocSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBLocSource","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource","url":"\/documentation\/openwrapsdk\/poblocsource"},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ"},"doc://com.pubmatic.openwrapsdk/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY"},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH"},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLocSource/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/openwrapsdk\/poblocsource\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLocSource/userProvided":{"type":"topic","abstract":[{"type":"text","text":"Location is provided by user"}],"navigatorTitle":[{"text":"POBLocSourceUserProvided","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/userProvided","title":"POBLocSource.userProvided","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userProvided","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/poblocsource\/userprovided"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLocSource/GPS":{"type":"topic","abstract":[{"type":"text","text":"Location is determined from GPS"}],"navigatorTitle":[{"text":"POBLocSourceGPS","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/GPS","title":"POBLocSource.GPS","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GPS","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/poblocsource\/gps"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"POBLocSource","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBLocSource"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"POBLocSource"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/GPS","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/ipAddress","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/userProvided"],"title":"Enumeration Cases"}]},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBLocSource"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource~1ipAddress\/title","value":"POBLocSourceIPAddress","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource~1ipAddress\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBLocSourceIPAddress"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource\/title","op":"replace","value":"POBLocSource"},{"value":[{"text":"POBLocSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource~1userProvided\/title","op":"replace","value":"POBLocSourceUserProvided"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource~1userProvided\/fragments","value":[{"text":"POBLocSourceUserProvided","kind":"identifier"}],"op":"replace"},{"value":"POBLocSourceGPS","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource~1GPS\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource~1GPS\/fragments","value":[{"text":"POBLocSourceGPS","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}