{"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"kind":"relationships"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBLinearity"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/poblinearity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/poblinearity"]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/any","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/linearInStream","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/nonLinearOverlay"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"metadata":{"symbolKind":"enum","externalID":"c:@E@POBLinearity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBLinearity","kind":"identifier"}],"role":"symbol","roleHeading":"Enumeration","title":"POBLinearity","modules":[{"name":"OpenWrapSDK"}],"navigatorTitle":[{"kind":"identifier","text":"POBLinearity"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Expected video linearity type by Vast Player"}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLinearity/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/Equatable-Implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/openwrapsdk\/poblinearity\/equatable-implementations","abstract":[]},"doc://com.pubmatic.openwrapsdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLinearity/any":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/any","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"any"}],"role":"symbol","title":"POBLinearity.any","navigatorTitle":[{"text":"POBLinearityAny","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/poblinearity\/any","abstract":[{"type":"text","text":"Video Linearity type Any"}]},"doc://com.pubmatic.openwrapsdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLinearity/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","title":"init(rawValue:)","url":"\/documentation\/openwrapsdk\/poblinearity\/init(rawvalue:)","abstract":[]},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLinearity/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/openwrapsdk\/poblinearity\/rawrepresentable-implementations","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLinearity":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBLinearity"}],"role":"symbol","title":"POBLinearity","navigatorTitle":[{"text":"POBLinearity","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/poblinearity","abstract":[{"type":"text","text":"Expected video linearity type by Vast Player"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLinearity/linearInStream":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/linearInStream","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"linearInStream","kind":"identifier"}],"role":"symbol","title":"POBLinearity.linearInStream","navigatorTitle":[{"kind":"identifier","text":"POBLinearityLinearInStream"}],"url":"\/documentation\/openwrapsdk\/poblinearity\/linearinstream","abstract":[{"type":"text","text":"Video Linearity type In stream"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLinearity/nonLinearOverlay":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/nonLinearOverlay","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonLinearOverlay"}],"role":"symbol","title":"POBLinearity.nonLinearOverlay","navigatorTitle":[{"text":"POBLinearityNonLinearOverlay","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/poblinearity\/nonlinearoverlay","abstract":[{"type":"text","text":"Video Linearity type Overlay"}]},"doc://com.pubmatic.openwrapsdk/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","value":"POBLinearity","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"kind":"identifier","text":"POBLinearity"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"POBLinearity","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/any","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/linearInStream","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLinearity\/nonLinearOverlay"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBLinearity"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity~1any\/title","value":"POBLinearityAny","op":"replace"},{"value":[{"text":"POBLinearityAny","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity~1any\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity\/title","value":"POBLinearity"},{"value":[{"text":"POBLinearity","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity~1linearInStream\/title","value":"POBLinearityLinearInStream"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity~1linearInStream\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBLinearityLinearInStream"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity~1nonLinearOverlay\/title","op":"replace","value":"POBLinearityNonLinearOverlay"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLinearity~1nonLinearOverlay\/fragments","op":"replace","value":[{"text":"POBLinearityNonLinearOverlay","kind":"identifier"}]}]}]}