{"abstract":[{"type":"text","text":"The FORMAT of the ad you are purchasing, separate from the surrounding context"}],"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBNativePlacementType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/atomic","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/belowArticle","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/feed","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/outsideCoreContent"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/RawRepresentable-Implementations"],"generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","metadata":{"externalID":"c:@E@POBNativePlacementType","roleHeading":"Enumeration","navigatorTitle":[{"text":"POBNativePlacementType","kind":"identifier"}],"symbolKind":"enum","role":"symbol","modules":[{"name":"OpenWrapSDK"}],"title":"POBNativePlacementType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativePlacementType"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeplacementtype"]},{"paths":["\/documentation\/openwrapsdk\/pobnativeplacementtype"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType/belowArticle":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/belowArticle","title":"POBNativePlacementType.belowArticle","url":"\/documentation\/openwrapsdk\/pobnativeplacementtype\/belowarticle","type":"topic","abstract":[{"text":"Recommendation widget, most commonly presented below the article content.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"belowArticle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBNativePlacementTypeBelowArticle"}]},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/init(rawValue:)","title":"init(rawValue:)","url":"\/documentation\/openwrapsdk\/pobnativeplacementtype\/init(rawvalue:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType/Equatable-Implementations":{"url":"\/documentation\/openwrapsdk\/pobnativeplacementtype\/equatable-implementations","type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/Equatable-Implementations","title":"Equatable Implementations","abstract":[]},"doc://com.pubmatic.openwrapsdk/SH":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType/outsideCoreContent":{"url":"\/documentation\/openwrapsdk\/pobnativeplacementtype\/outsidecorecontent","type":"topic","kind":"symbol","navigatorTitle":[{"text":"POBNativePlacementTypeOutsideCoreContent","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/outsideCoreContent","title":"POBNativePlacementType.outsideCoreContent","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"outsideCoreContent","kind":"identifier"}],"abstract":[{"type":"text","text":"Outside the core content - for example in the ads section on the right rail, as a banner-style placement near the content, etc."}]},"doc://com.pubmatic.openwrapsdk/SQ":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType","title":"POBNativePlacementType","url":"\/documentation\/openwrapsdk\/pobnativeplacementtype","type":"topic","abstract":[{"text":"The FORMAT of the ad you are purchasing, separate from the surrounding context","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativePlacementType","kind":"identifier"}],"navigatorTitle":[{"text":"POBNativePlacementType","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType/RawRepresentable-Implementations":{"url":"\/documentation\/openwrapsdk\/pobnativeplacementtype\/rawrepresentable-implementations","type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","abstract":[]},"doc://com.pubmatic.openwrapsdk/SY":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType/feed":{"abstract":[{"type":"text","text":"In the feed of content - for example as an item inside the organic feed\/grid\/listing\/carousel."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeplacementtype\/feed","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"feed","kind":"identifier"}],"title":"POBNativePlacementType.feed","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/feed","navigatorTitle":[{"kind":"identifier","text":"POBNativePlacementTypeFeed"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType/atomic":{"url":"\/documentation\/openwrapsdk\/pobnativeplacementtype\/atomic","type":"topic","kind":"symbol","navigatorTitle":[{"text":"POBNativePlacementTypeAtomic","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/atomic","title":"POBNativePlacementType.atomic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"atomic"}],"abstract":[{"type":"text","text":"In the atomic unit of the content - IE in the article page or single image page"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"POBNativePlacementType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"POBNativePlacementType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"POBNativePlacementType","kind":"identifier"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/atomic","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/belowArticle","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/feed","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/outsideCoreContent"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativePlacementType"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1belowArticle\/title","value":"POBNativePlacementTypeBelowArticle"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1belowArticle\/fragments","value":[{"kind":"identifier","text":"POBNativePlacementTypeBelowArticle"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1outsideCoreContent\/title","op":"replace","value":"POBNativePlacementTypeOutsideCoreContent"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1outsideCoreContent\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBNativePlacementTypeOutsideCoreContent"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType\/title","value":"POBNativePlacementType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"POBNativePlacementType"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType\/fragments"},{"op":"replace","value":"POBNativePlacementTypeFeed","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1feed\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1feed\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBNativePlacementTypeFeed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1atomic\/title","value":"POBNativePlacementTypeAtomic"},{"value":[{"kind":"identifier","text":"POBNativePlacementTypeAtomic"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1atomic\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}