{"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAd(_:didRecordClickForAsset:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidDismissModal(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidPresentModal(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidRecordClick(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidRecordImpression(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdWillLeaveApplication(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdWillPresentModal(_:)"],"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeaddelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeaddelegate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAdDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"POBNativeAdDelegate Protocol","anchor":"POBNativeAdDelegate-Protocol"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"metadata":{"modules":[{"name":"OpenWrapSDK"}],"title":"POBNativeAdDelegate","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdDelegate"}],"role":"symbol","roleHeading":"Protocol","externalID":"c:objc(pl)POBNativeAdDelegate","navigatorTitle":[{"text":"POBNativeAdDelegate","kind":"identifier"}]},"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate/nativeAdWillPresentModal(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeAdWillPresentModal","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"POBNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAd"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeAdWillPresentModal:","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdWillPresentModal(_:)","title":"nativeAdWillPresentModal(_:)","type":"topic","url":"\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeadwillpresentmodal(_:)","role":"symbol","kind":"symbol","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate/nativeAd(_:didRecordClickForAsset:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAd"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","text":"POBNativeAd","preciseIdentifier":"c:objc(pl)POBNativeAd"},{"text":", ","kind":"text"},{"text":"didRecordClickForAsset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"nativeAd:didRecordClickForAsset:"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAd(_:didRecordClickForAsset:)","title":"nativeAd(_:didRecordClickForAsset:)","required":true,"type":"topic","url":"\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativead(_:didrecordclickforasset:)","role":"symbol","kind":"symbol","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate/nativeAdDidRecordImpression(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeAdDidRecordImpression","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"POBNativeAd","preciseIdentifier":"c:objc(pl)POBNativeAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"nativeAdDidRecordImpression:","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidRecordImpression(_:)","title":"nativeAdDidRecordImpression(_:)","type":"topic","url":"\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeaddidrecordimpression(_:)","role":"symbol","kind":"symbol","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate/nativeAdWillLeaveApplication(_:)":{"navigatorTitle":[{"kind":"identifier","text":"nativeAdWillLeaveApplication:"}],"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nativeAdWillLeaveApplication","kind":"identifier"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","text":"POBNativeAd","preciseIdentifier":"c:objc(pl)POBNativeAd"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdWillLeaveApplication(_:)","role":"symbol","title":"nativeAdWillLeaveApplication(_:)","type":"topic","url":"\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeadwillleaveapplication(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate":{"title":"POBNativeAdDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdDelegate"}],"type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativeaddelegate","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdDelegate"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate/nativeAdDidRecordClick(_:)":{"role":"symbol","kind":"symbol","title":"nativeAdDidRecordClick(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeAdDidRecordClick","kind":"identifier"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)POBNativeAd","kind":"typeIdentifier","text":"POBNativeAd"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeAdDidRecordClick:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeaddidrecordclick(_:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidRecordClick(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate/nativeAdDidPresentModal(_:)":{"required":true,"url":"\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeaddidpresentmodal(_:)","title":"nativeAdDidPresentModal(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeAdDidPresentModal","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"POBNativeAd","preciseIdentifier":"c:objc(pl)POBNativeAd"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidPresentModal(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nativeAdDidPresentModal:"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate/nativeAdDidDismissModal(_:)":{"required":true,"url":"\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeaddiddismissmodal(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"nativeAdDidDismissModal:"}],"kind":"symbol","title":"nativeAdDidDismissModal(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdDidDismissModal"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)POBNativeAd","kind":"typeIdentifier","text":"POBNativeAd"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidDismissModal(_:)","role":"symbol"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeAdDelegate"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBNativeAdDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"POBNativeAdDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAd(_:didRecordClickForAsset:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidDismissModal(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidPresentModal(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidRecordClick(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidRecordImpression(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdWillLeaveApplication(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdWillPresentModal(_:)"],"title":"Instance Methods"}]},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdDelegate"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdWillPresentModal(_:)\/title","op":"replace","value":"nativeAdWillPresentModal:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeAdWillPresentModal:"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdWillPresentModal(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAd(_:didRecordClickForAsset:)\/title","value":"nativeAd:didRecordClickForAsset:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeAd:didRecordClickForAsset:"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAd(_:didRecordClickForAsset:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdDidRecordImpression(_:)\/title","op":"replace","value":"nativeAdDidRecordImpression:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdDidRecordImpression(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"nativeAdDidRecordImpression:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdWillLeaveApplication(_:)\/title","value":"nativeAdWillLeaveApplication:","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdWillLeaveApplication(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeAdWillLeaveApplication:","kind":"identifier"}],"op":"replace"},{"value":"POBNativeAdDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate\/title"},{"value":[{"text":"POBNativeAdDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdDidRecordClick(_:)\/title","value":"nativeAdDidRecordClick:","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdDidRecordClick(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeAdDidRecordClick:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"nativeAdDidPresentModal:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdDidPresentModal(_:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdDidPresentModal(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nativeAdDidPresentModal:","kind":"identifier"}]},{"op":"replace","value":"nativeAdDidDismissModal:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdDidDismissModal(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"nativeAdDidDismissModal:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdDidDismissModal(_:)\/fragments","op":"replace"}]}]}