{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"class","title":"POBNativeRequestDataAsset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBNativeRequestDataAsset"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"POBNativeRequestDataAsset","kind":"identifier"}],"externalID":"c:objc(cs)POBNativeRequestDataAsset"},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset\/init(id:required:type:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset\/length","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset\/type"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeRequestDataAsset"}]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"text":"Ratings, Review Count, Stars, Download count, descriptions etc.","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativerequestdataasset"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativerequestdataasset"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestDataAsset/type":{"type":"topic","title":"type","url":"\/documentation\/openwrapsdk\/pobnativerequestdataasset\/type","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"text":"POBNativeDataAssetType","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBNativeDataAssetType"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset\/type"},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestDataAsset/length":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset\/length","kind":"symbol","title":"length","type":"topic","navigatorTitle":[{"kind":"identifier","text":"length"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"length","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"abstract":[],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativerequestdataasset\/length"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject","title":"NSObject"},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestDataAsset/init(id:required:type:)":{"type":"topic","title":"init(id:required:type:)","url":"\/documentation\/openwrapsdk\/pobnativerequestdataasset\/init(id:required:type:)","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"required","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"POBNativeDataAssetType","preciseIdentifier":"c:@E@POBNativeDataAssetType"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithId:required:type:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset\/init(id:required:type:)"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestAsset":{"abstract":[],"title":"POBNativeRequestAsset","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBNativeRequestAsset","kind":"identifier"}],"navigatorTitle":[{"text":"POBNativeRequestAsset","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativerequestasset","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset","kind":"symbol"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestDataAsset":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset","kind":"symbol","type":"topic","title":"POBNativeRequestDataAsset","navigatorTitle":[{"text":"POBNativeRequestDataAsset","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBNativeRequestDataAsset","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativerequestdataasset"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"POBNativeRequestDataAsset","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"POBNativeRequestDataAsset","kind":"identifier"}]},{"op":"replace","value":[{"text":"POBNativeRequestDataAsset","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset\/length","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset\/type"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset\/init(id:required:type:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset"],"title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeRequestDataAsset"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset~1type\/title","value":"type"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset~1type\/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset~1length\/title","op":"replace","value":"length"},{"value":[{"kind":"identifier","text":"length"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset~1length\/fragments"},{"value":"initWithId:required:type:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset~1init(id:required:type:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithId:required:type:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset~1init(id:required:type:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestAsset\/title","value":"POBNativeRequestAsset"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestAsset\/fragments","value":[{"kind":"identifier","text":"POBNativeRequestAsset"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset\/title","op":"replace","value":"POBNativeRequestDataAsset"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset\/fragments","value":[{"text":"POBNativeRequestDataAsset","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}