{"sections":[],"abstract":[{"text":"Bridge for the native custom event protocol that manages communication with an ad server SDK.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdEventBridge"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAdEventBridge","kind":"identifier"}],"externalID":"c:objc(pl)POBNativeAdEventBridge","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdEventBridge"}],"symbolKind":"protocol","roleHeading":"Protocol","title":"POBNativeAdEventBridge","role":"symbol","modules":[{"name":"OpenWrapSDK"}]},"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/adServerAdView()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/requestAd(with:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/setDelegate(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/setSignaling(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/trackClick()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/trackImpression()"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadeventbridge"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadeventbridge"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventBridge/setSignaling(_:)":{"role":"symbol","navigatorTitle":[{"text":"setSignalingDelegate:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativeadeventbridge\/setsignaling(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSignaling","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"POBAdServerSignalingEventDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBAdServerSignalingEventDelegate"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/setSignaling(_:)","kind":"symbol","title":"setSignaling(_:)","required":true},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventBridge/adServerAdView()":{"type":"topic","required":true,"abstract":[],"role":"symbol","navigatorTitle":[{"text":"adServerAdView","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/adServerAdView()","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadeventbridge\/adserveradview()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adServerAdView","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"title":"adServerAdView()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventBridge/requestAd(with:)":{"role":"symbol","navigatorTitle":[{"text":"requestAdWithBid:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativeadeventbridge\/requestad(with:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"POBBid","preciseIdentifier":"c:objc(cs)POBBid","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/requestAd(with:)","type":"topic","title":"requestAd(with:)","kind":"symbol","required":true},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventBridge":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Bridge for the native custom event protocol that manages communication with an ad server SDK."}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeAdEventBridge"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadeventbridge","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdEventBridge"}],"title":"POBNativeAdEventBridge"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventBridge/trackClick()":{"navigatorTitle":[{"text":"trackClick","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativeadeventbridge\/trackclick()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackClick"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/trackClick()","kind":"symbol","title":"trackClick()","role":"symbol"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventBridge/trackImpression()":{"role":"symbol","navigatorTitle":[{"text":"trackImpression","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativeadeventbridge\/trackimpression()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"trackImpression","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/trackImpression()","kind":"symbol","title":"trackImpression()","required":true},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventBridge/setDelegate(_:)":{"title":"setDelegate(_:)","required":true,"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/setDelegate(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDelegate","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"POBNativeAdEventDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAdEventDelegate"},{"kind":"text","text":")"}],"url":"\/documentation\/openwrapsdk\/pobnativeadeventbridge\/setdelegate(_:)","navigatorTitle":[{"kind":"identifier","text":"setDelegate:"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeAdEventBridge"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"text":"POBNativeAdEventBridge","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"POBNativeAdEventBridge","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/adServerAdView()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/requestAd(with:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/setDelegate(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/setSignaling(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/trackClick()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventBridge\/trackImpression()"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdEventBridge"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"setSignalingDelegate:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1setSignaling(_:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1setSignaling(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setSignalingDelegate:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1adServerAdView()\/title","value":"adServerAdView","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1adServerAdView()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adServerAdView"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1requestAd(with:)\/title","value":"requestAdWithBid:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"requestAdWithBid:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1requestAd(with:)\/fragments"},{"value":"POBNativeAdEventBridge","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge\/title"},{"value":[{"text":"POBNativeAdEventBridge","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1trackClick()\/title","value":"trackClick","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1trackClick()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"trackClick","kind":"identifier"}]},{"op":"replace","value":"trackImpression","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1trackImpression()\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1trackImpression()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"trackImpression","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1setDelegate(_:)\/title","op":"replace","value":"setDelegate:"},{"value":[{"text":"- ","kind":"text"},{"text":"setDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventBridge~1setDelegate(_:)\/fragments","op":"replace"}]}]}