{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","metadata":{"roleHeading":"Protocol","role":"symbol","externalID":"c:objc(pl)POBNativeRequestAsset","symbolKind":"protocol","modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeRequestAsset"}],"navigatorTitle":[{"text":"POBNativeRequestAsset","kind":"identifier"}],"title":"POBNativeRequestAsset"},"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestTitleAsset"],"title":"Conforming Types","type":"conformingTypes"}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativerequestasset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativerequestasset"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeRequestAsset"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}]}]}],"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset\/assetId","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset\/required"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset\/buildJSON()"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestTitleAsset":{"url":"\/documentation\/openwrapsdk\/pobnativerequesttitleasset","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeRequestTitleAsset"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestTitleAsset","navigatorTitle":[{"text":"POBNativeRequestTitleAsset","kind":"identifier"}],"abstract":[],"title":"POBNativeRequestTitleAsset"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestDataAsset":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset","kind":"symbol","type":"topic","title":"POBNativeRequestDataAsset","navigatorTitle":[{"text":"POBNativeRequestDataAsset","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBNativeRequestDataAsset","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativerequestdataasset"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestAsset":{"abstract":[],"title":"POBNativeRequestAsset","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBNativeRequestAsset","kind":"identifier"}],"navigatorTitle":[{"text":"POBNativeRequestAsset","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativerequestasset","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset","kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestAsset/required":{"url":"\/documentation\/openwrapsdk\/pobnativerequestasset\/required","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset\/required","navigatorTitle":[{"text":"required","kind":"identifier"}],"required":true,"abstract":[],"title":"required"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestAsset/assetId":{"url":"\/documentation\/openwrapsdk\/pobnativerequestasset\/assetid","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"assetId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset\/assetId","navigatorTitle":[{"text":"assetId","kind":"identifier"}],"required":true,"abstract":[],"title":"assetId"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestImageAsset":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset","kind":"symbol","title":"POBNativeRequestImageAsset","type":"topic","navigatorTitle":[{"text":"POBNativeRequestImageAsset","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"POBNativeRequestImageAsset","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativerequestimageasset"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestAsset/buildJSON()":{"url":"\/documentation\/openwrapsdk\/pobnativerequestasset\/buildjson()","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildJSON"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset\/buildJSON()","navigatorTitle":[{"kind":"identifier","text":"buildJSON"}],"required":true,"abstract":[],"title":"buildJSON()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeRequestAsset"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"POBNativeRequestAsset","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"POBNativeRequestAsset"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset\/assetId","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset\/required"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset\/buildJSON()"]}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestTitleAsset"],"title":"Conforming Types","type":"conformingTypes"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"POBNativeRequestAsset","kind":"identifier"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestTitleAsset\/title","value":"POBNativeRequestTitleAsset"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestTitleAsset\/fragments","value":[{"text":"POBNativeRequestTitleAsset","kind":"identifier"}],"op":"replace"},{"value":"POBNativeRequestDataAsset","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset\/fragments","op":"replace","value":[{"text":"POBNativeRequestDataAsset","kind":"identifier"}]},{"op":"replace","value":"POBNativeRequestAsset","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestAsset\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestAsset\/fragments","value":[{"text":"POBNativeRequestAsset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestAsset~1required\/title","value":"required","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestAsset~1required\/fragments","op":"replace","value":[{"text":"required","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestAsset~1assetId\/title","op":"replace","value":"assetId"},{"op":"replace","value":[{"kind":"identifier","text":"assetId"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestAsset~1assetId\/fragments"},{"value":"POBNativeRequestImageAsset","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset\/fragments","op":"replace","value":[{"text":"POBNativeRequestImageAsset","kind":"identifier"}]},{"op":"replace","value":"buildJSON","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestAsset~1buildJSON()\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestAsset~1buildJSON()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"buildJSON"}],"op":"replace"}]}]}