{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeeventtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeeventtype"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativeEventType","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"kind":"relationships"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/OMID","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/impression","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/viewMRC100","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/viewMRC50"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/RawRepresentable-Implementations"]}],"metadata":{"role":"symbol","title":"POBNativeEventType","roleHeading":"Enumeration","externalID":"c:@E@POBNativeEventType","navigatorTitle":[{"kind":"identifier","text":"POBNativeEventType"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeEventType","kind":"identifier"}],"symbolKind":"enum"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Native Event Type for Event Tracking"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType/impression":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"impression"}],"title":"POBNativeEventType.impression","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/impression","url":"\/documentation\/openwrapsdk\/pobnativeeventtype\/impression","abstract":[{"type":"text","text":"impression"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"POBNativeEventTypeImpression","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType/viewMRC100":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewMRC100","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/viewMRC100","navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTypeViewMRC100"}],"title":"POBNativeEventType.viewMRC100","url":"\/documentation\/openwrapsdk\/pobnativeeventtype\/viewmrc100","abstract":[{"type":"text","text":"100% in view for 1 second (ie GroupM standard)"}],"type":"topic","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType/viewMRC50":{"title":"POBNativeEventType.viewMRC50","url":"\/documentation\/openwrapsdk\/pobnativeeventtype\/viewmrc50","navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTypeViewMRC50"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewMRC50"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/viewMRC50","abstract":[{"type":"text","text":"Visible impression using MRC definition at 50% in view for 1 second"}],"kind":"symbol"},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativeeventtype\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","title":"Swift.Sendable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventType"}],"abstract":[{"type":"text","text":"Native Event Type for Event Tracking"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeEventType","kind":"identifier"}],"title":"POBNativeEventType","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType","url":"\/documentation\/openwrapsdk\/pobnativeeventtype"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/openwrapsdk\/pobnativeeventtype\/init(rawvalue:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/init(rawValue:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType/OMID":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTypeOMID"}],"abstract":[{"text":"Signifies the event as OMID event.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMID"}],"title":"POBNativeEventType.OMID","type":"topic","url":"\/documentation\/openwrapsdk\/pobnativeeventtype\/omid","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/OMID"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventType/Equatable-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/openwrapsdk\/pobnativeeventtype\/equatable-implementations","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/Equatable-Implementations","role":"collectionGroup"},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","title":"Swift.RawRepresentable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeEventType"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"POBNativeEventType"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"POBNativeEventType","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/OMID","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/impression","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/viewMRC100","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventType\/viewMRC50"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativeEventType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"POBNativeEventTypeImpression","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1impression\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1impression\/fragments","value":[{"text":"POBNativeEventTypeImpression","kind":"identifier"}],"op":"replace"},{"value":"POBNativeEventTypeViewMRC100","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1viewMRC100\/title"},{"op":"replace","value":[{"kind":"identifier","text":"POBNativeEventTypeViewMRC100"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1viewMRC100\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1viewMRC50\/title","value":"POBNativeEventTypeViewMRC50"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1viewMRC50\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBNativeEventTypeViewMRC50"}]},{"op":"replace","value":"POBNativeEventType","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType\/fragments","op":"replace","value":[{"text":"POBNativeEventType","kind":"identifier"}]},{"value":"POBNativeEventTypeOMID","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1OMID\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventType~1OMID\/fragments","value":[{"kind":"identifier","text":"POBNativeEventTypeOMID"}],"op":"replace"}]}]}