{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"metadata":{"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdLoaderConfig"}],"roleHeading":"Class","title":"POBNativeAdLoaderConfig","modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"POBNativeAdLoaderConfig","kind":"identifier"}],"externalID":"c:objc(cs)POBNativeAdLoaderConfig"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBNativeAdLoaderConfig","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig\/contextSubType","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig\/contextType","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig\/placementType"],"title":"Instance Properties"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadloaderconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadloaderconfig"]}],"references":{"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoaderConfig/contextType":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"contextType","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig\/contextType","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"contextType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"POBNativeContextType","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBNativeContextType"}],"url":"\/documentation\/openwrapsdk\/pobnativeadloaderconfig\/contexttype","kind":"symbol","title":"contextType"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoaderConfig":{"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadloaderconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdLoaderConfig"}],"title":"POBNativeAdLoaderConfig","role":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"POBNativeAdLoaderConfig"}]},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.pubmatic.openwrapsdk/SQ":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoaderConfig/contextSubType":{"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadloaderconfig\/contextsubtype","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contextSubType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"POBNativeContextSubType","preciseIdentifier":"c:@E@POBNativeContextSubType"}],"title":"contextSubType","role":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig\/contextSubType","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"contextSubType"}]},"doc://com.pubmatic.openwrapsdk/SH":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoaderConfig/placementType":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"placementType","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig\/placementType","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placementType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@POBNativePlacementType","text":"POBNativePlacementType"}],"url":"\/documentation\/openwrapsdk\/pobnativeadloaderconfig\/placementtype","kind":"symbol","title":"placementType"},"doc://com.pubmatic.openwrapsdk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeAdLoaderConfig"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"text":"POBNativeAdLoaderConfig","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"POBNativeAdLoaderConfig","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig\/contextSubType","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig\/contextType","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderConfig\/placementType"]}]},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdLoaderConfig"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"contextType","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderConfig~1contextType\/title","op":"replace"},{"value":[{"text":"contextType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderConfig~1contextType\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderConfig\/title","op":"replace","value":"POBNativeAdLoaderConfig"},{"value":[{"text":"POBNativeAdLoaderConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderConfig\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderConfig~1contextSubType\/title","op":"replace","value":"contextSubType"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderConfig~1contextSubType\/fragments","value":[{"kind":"identifier","text":"contextSubType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderConfig~1placementType\/title","value":"placementType"},{"value":[{"text":"placementType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderConfig~1placementType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}