{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdSmallTemplateView"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadsmalltemplateview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadsmalltemplateview"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativeAdSmallTemplateView","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"inlineContent":[{"type":"text","text":"All these assets are required, and will be rendered by OpenWrap SDK."}],"type":"paragraph"}]}],"metadata":{"symbolKind":"class","roleHeading":"Class","title":"POBNativeAdSmallTemplateView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAdSmallTemplateView","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"POBNativeAdSmallTemplateView","kind":"identifier"}],"externalID":"c:objc(cs)POBNativeAdSmallTemplateView"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView"]},{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSCoding","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)CALayerDelegate","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearance","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearanceContainer","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UICoordinateSpace","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIDynamicItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusEnvironment","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItemContainer","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UILargeContentViewerItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pubmatic.openwrapsdk\/5UIKit23UITraitChangeObservableP","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UITraitEnvironment","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo"}],"references":{"doc://com.pubmatic.openwrapsdk/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSCoding","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateView":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"POBNativeTemplateView","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativetemplateview","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeTemplateView","kind":"identifier"}],"title":"POBNativeTemplateView","abstract":[]},"doc://com.pubmatic.openwrapsdk/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)CALayerDelegate","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdSmallTemplateView":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdSmallTemplateView","type":"topic","kind":"symbol","title":"POBNativeAdSmallTemplateView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdSmallTemplateView"}],"navigatorTitle":[{"text":"POBNativeAdSmallTemplateView","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativeadsmalltemplateview"},"doc://com.pubmatic.openwrapsdk/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearance","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"POBNativeAdSmallTemplateView","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBNativeAdSmallTemplateView","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"POBNativeAdSmallTemplateView"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdSmallTemplateView"},{"text":" : ","kind":"text"},{"text":"POBNativeTemplateView","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBNativeTemplateView"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView\/title","op":"replace","value":"POBNativeTemplateView"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBNativeTemplateView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdSmallTemplateView\/title","value":"POBNativeAdSmallTemplateView"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdSmallTemplateView\/fragments","op":"replace","value":[{"text":"POBNativeAdSmallTemplateView","kind":"identifier"}]}]}]}