{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/adIconImgView","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/ctaButton","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/descriptionLabel","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/dsaIconImgView","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/iconImgView","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/privacyIconImgView","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/titleLabel"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)UIView"],"kind":"relationships"},{"type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdMediumTemplateView","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdSmallTemplateView"],"kind":"relationships"},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSCoding","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)CALayerDelegate","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearance","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearanceContainer","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UICoordinateSpace","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIDynamicItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusEnvironment","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItemContainer","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UILargeContentViewerItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pubmatic.openwrapsdk\/5UIKit23UITraitChangeObservableP","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UITraitEnvironment","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView"},"metadata":{"externalID":"c:objc(cs)POBNativeTemplateView","navigatorTitle":[{"kind":"identifier","text":"POBNativeTemplateView"}],"role":"symbol","title":"POBNativeTemplateView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBNativeTemplateView","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Class"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeTemplateView"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"All these assets are required, and will be rendered by OpenWrap SDK."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativetemplateview"]},{"paths":["\/documentation\/openwrapsdk\/pobnativetemplateview"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdMediumTemplateView":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdMediumTemplateView","type":"topic","kind":"symbol","title":"POBNativeAdMediumTemplateView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdMediumTemplateView"}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeAdMediumTemplateView"}],"url":"\/documentation\/openwrapsdk\/pobnativeadmediumtemplateview"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateView/dsaIconImgView":{"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/dsaIconImgView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dsaIconImgView","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIImageView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"!"}],"kind":"symbol","title":"dsaIconImgView","navigatorTitle":[{"text":"dsaIconImgView","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativetemplateview\/dsaiconimgview"},"doc://com.pubmatic.openwrapsdk/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateView/iconImgView":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"iconImgView","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/iconImgView","title":"iconImgView","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"iconImgView","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativetemplateview\/iconimgview"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateView/privacyIconImgView":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/privacyIconImgView","kind":"symbol","role":"symbol","title":"privacyIconImgView","url":"\/documentation\/openwrapsdk\/pobnativetemplateview\/privacyiconimgview","abstract":[],"navigatorTitle":[{"text":"privacyIconImgView","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"privacyIconImgView"},{"kind":"text","text":": "},{"text":"UIImageView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"!"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateView/adIconImgView":{"url":"\/documentation\/openwrapsdk\/pobnativetemplateview\/adiconimgview","navigatorTitle":[{"text":"adIconImgView","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"adIconImgView","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adIconImgView","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/adIconImgView"},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)CALayerDelegate"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearanceContainer"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateView/descriptionLabel":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"descriptionLabel"}],"url":"\/documentation\/openwrapsdk\/pobnativetemplateview\/descriptionlabel","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/descriptionLabel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"descriptionLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"!","kind":"text"}],"title":"descriptionLabel","abstract":[]},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAccessibilityIdentification"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItemContainer"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateView":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"POBNativeTemplateView","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativetemplateview","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeTemplateView","kind":"identifier"}],"title":"POBNativeTemplateView","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdSmallTemplateView":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdSmallTemplateView","type":"topic","kind":"symbol","title":"POBNativeAdSmallTemplateView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdSmallTemplateView"}],"navigatorTitle":[{"text":"POBNativeAdSmallTemplateView","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativeadsmalltemplateview"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateView/ctaButton":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ctaButton","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ctaButton"}],"url":"\/documentation\/openwrapsdk\/pobnativetemplateview\/ctabutton","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/ctaButton","title":"ctaButton"},"doc://com.pubmatic.openwrapsdk/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/5UIKit23UITraitChangeObservableP"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearance"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIDynamicItem"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIResponderStandardEditActions"},"doc://com.pubmatic.openwrapsdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP"},"doc://com.pubmatic.openwrapsdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ"},"doc://com.pubmatic.openwrapsdk/objc(cs)UIView":{"title":"UIView","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)UIView"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItem"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSCoding"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateView/titleLabel":{"kind":"symbol","type":"topic","title":"titleLabel","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"url":"\/documentation\/openwrapsdk\/pobnativetemplateview\/titlelabel","role":"symbol","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/titleLabel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"POBNativeTemplateView","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"POBNativeTemplateView","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"POBNativeTemplateView"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/adIconImgView","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/ctaButton","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/descriptionLabel","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/dsaIconImgView","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/iconImgView","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/privacyIconImgView","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/titleLabel"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)UIView"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdMediumTemplateView","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdSmallTemplateView"],"title":"Inherited By","kind":"relationships","type":"inheritedBy"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"POBNativeTemplateView","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"POBNativeAdMediumTemplateView","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdMediumTemplateView\/title"},{"value":[{"text":"POBNativeAdMediumTemplateView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdMediumTemplateView\/fragments","op":"replace"},{"value":"dsaIconImgView","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1dsaIconImgView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1dsaIconImgView\/fragments","value":[{"kind":"identifier","text":"dsaIconImgView"}]},{"op":"replace","value":"iconImgView","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1iconImgView\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1iconImgView\/fragments","op":"replace","value":[{"text":"iconImgView","kind":"identifier"}]},{"value":"privacyIconImgView","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1privacyIconImgView\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1privacyIconImgView\/fragments","value":[{"text":"privacyIconImgView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1adIconImgView\/title","value":"adIconImgView"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1adIconImgView\/fragments","value":[{"kind":"identifier","text":"adIconImgView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1descriptionLabel\/title","value":"descriptionLabel"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1descriptionLabel\/fragments","value":[{"text":"descriptionLabel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView\/title","value":"POBNativeTemplateView"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView\/fragments","value":[{"kind":"identifier","text":"POBNativeTemplateView"}],"op":"replace"},{"value":"POBNativeAdSmallTemplateView","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdSmallTemplateView\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdSmallTemplateView\/fragments","value":[{"kind":"identifier","text":"POBNativeAdSmallTemplateView"}],"op":"replace"},{"value":"ctaButton","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1ctaButton\/title"},{"op":"replace","value":[{"text":"ctaButton","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1ctaButton\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1titleLabel\/title","value":"titleLabel","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}],"op":"replace"}]}]}