{"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"metadata":{"symbolKind":"enum","role":"symbol","title":"POBNativeEventTrackingMethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeEventTrackingMethod"}],"navigatorTitle":[{"text":"POBNativeEventTrackingMethod","kind":"identifier"}],"roleHeading":"Enumeration","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:@E@POBNativeEventTrackingMethod"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/JS","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/image"]},{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/RawRepresentable-Implementations"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeEventTrackingMethod"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod"]},{"paths":["\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Native Event Tracking Methods","type":"text"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventTrackingMethod":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTrackingMethod"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeEventTrackingMethod"}],"title":"POBNativeEventTrackingMethod","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Native Event Tracking Methods"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod","url":"\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod"},"doc://com.pubmatic.openwrapsdk/SQ":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventTrackingMethod/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/Equatable-Implementations","url":"\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod\/equatable-implementations"},"doc://com.pubmatic.openwrapsdk/SY":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventTrackingMethod/image":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTrackingMethodImage"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"}],"title":"POBNativeEventTrackingMethod.image","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Image-pixel tracking - URL provided will be inserted as a 1x1 pixel at the time of the event."}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/image","url":"\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod\/image"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventTrackingMethod/JS":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTrackingMethodJS"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"JS"}],"title":"POBNativeEventTrackingMethod.JS","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Javascript-based tracking - URL provided will be inserted as a js tag at the time of the event."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/JS","type":"topic","url":"\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod\/js"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventTrackingMethod/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"title":"init(rawValue:)","role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/init(rawValue:)","url":"\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod\/init(rawvalue:)"},"doc://com.pubmatic.openwrapsdk/SH":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventTrackingMethod/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod\/rawrepresentable-implementations"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"POBNativeEventTrackingMethod","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBNativeEventTrackingMethod","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"POBNativeEventTrackingMethod","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/JS","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/image"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeEventTrackingMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"POBNativeEventTrackingMethod","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod\/fragments","value":[{"text":"POBNativeEventTrackingMethod","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod~1image\/title","op":"replace","value":"POBNativeEventTrackingMethodImage"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod~1image\/fragments","op":"replace","value":[{"text":"POBNativeEventTrackingMethodImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod~1JS\/title","op":"replace","value":"POBNativeEventTrackingMethodJS"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod~1JS\/fragments","value":[{"text":"POBNativeEventTrackingMethodJS","kind":"identifier"}]}]}]}