{"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"],"kind":"relationships"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/init(id:required:type:minimumWidth:minimumHeight:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/hmin","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/mimes","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/type","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/wmin"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativerequestimageasset"]},{"paths":["\/documentation\/openwrapsdk\/pobnativerequestimageasset"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBNativeRequestImageAsset","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"POBNativeRequestImageAsset","kind":"identifier"}],"role":"symbol","title":"POBNativeRequestImageAsset","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativeRequestImageAsset","kind":"identifier"}],"externalID":"c:objc(cs)POBNativeRequestImageAsset","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestImageAsset/hmin":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hmin"}],"url":"\/documentation\/openwrapsdk\/pobnativerequestimageasset\/hmin","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/hmin","type":"topic","title":"hmin","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hmin"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestAsset":{"abstract":[],"title":"POBNativeRequestAsset","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBNativeRequestAsset","kind":"identifier"}],"navigatorTitle":[{"text":"POBNativeRequestAsset","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativerequestasset","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset","kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestImageAsset":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset","kind":"symbol","title":"POBNativeRequestImageAsset","type":"topic","navigatorTitle":[{"text":"POBNativeRequestImageAsset","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"POBNativeRequestImageAsset","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativerequestimageasset"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestImageAsset/type":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/type","kind":"symbol","type":"topic","title":"type","navigatorTitle":[{"kind":"identifier","text":"type"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"text":"POBNativeImageAssetType","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBNativeImageAssetType"}],"abstract":[],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativerequestimageasset\/type"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestImageAsset/init(id:required:type:minimumWidth:minimumHeight:)":{"abstract":[],"navigatorTitle":[{"text":"initWithId:required:type:minimumWidth:minimumHeight:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativerequestimageasset\/init(id:required:type:minimumwidth:minimumheight:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/init(id:required:type:minimumWidth:minimumHeight:)","title":"init(id:required:type:minimumWidth:minimumHeight:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"required"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"POBNativeImageAssetType","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBNativeImageAssetType"},{"kind":"text","text":", "},{"text":"minimumWidth","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minimumHeight"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestImageAsset/mimes":{"url":"\/documentation\/openwrapsdk\/pobnativerequestimageasset\/mimes","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mimes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"title":"mimes","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/mimes","navigatorTitle":[{"text":"mimes","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestImageAsset/wmin":{"title":"wmin","url":"\/documentation\/openwrapsdk\/pobnativerequestimageasset\/wmin","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/wmin","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wmin","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"wmin"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeRequestImageAsset"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"POBNativeRequestImageAsset"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"POBNativeRequestImageAsset"}]},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/hmin","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/mimes","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/type","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/wmin"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestImageAsset\/init(id:required:type:minimumWidth:minimumHeight:)"]}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestAsset"],"title":"Conforms To","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeRequestImageAsset","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace"},{"value":"hmin","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset~1hmin\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset~1hmin\/fragments","op":"replace","value":[{"kind":"identifier","text":"hmin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestAsset\/title","value":"POBNativeRequestAsset"},{"op":"replace","value":[{"kind":"identifier","text":"POBNativeRequestAsset"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestAsset\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset\/title","value":"POBNativeRequestImageAsset","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset\/fragments","value":[{"text":"POBNativeRequestImageAsset","kind":"identifier"}],"op":"replace"},{"value":"type","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset~1type\/title"},{"value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset~1type\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset~1init(id:required:type:minimumWidth:minimumHeight:)\/title","op":"replace","value":"initWithId:required:type:minimumWidth:minimumHeight:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset~1init(id:required:type:minimumWidth:minimumHeight:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithId:required:type:minimumWidth:minimumHeight:","kind":"identifier"}]},{"value":"mimes","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset~1mimes\/title"},{"op":"replace","value":[{"text":"mimes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset~1mimes\/fragments"},{"op":"replace","value":"wmin","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset~1wmin\/title"},{"value":[{"kind":"identifier","text":"wmin"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestImageAsset~1wmin\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}