{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdRenderingCompletionBlock","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadrenderingcompletionblock"]},{"paths":["\/documentation\/openwrapsdk\/pobnativeadrenderingcompletionblock"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:POBNativeAd.h@T@POBNativeAdRenderingCompletionBlock","roleHeading":"Type Alias","modules":[{"name":"OpenWrapSDK"}],"title":"POBNativeAdRenderingCompletionBlock","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"POBNativeAdRenderingCompletionBlock","kind":"identifier"}],"symbolKind":"typealias","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdRenderingCompletionBlock"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAdRenderingCompletionBlock","kind":"identifier"},{"text":" = (any ","kind":"text"},{"text":"POBNativeAd","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","preciseIdentifier":"c:objc(pl)POBNativeAd"},{"kind":"text","text":", (any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd":{"navigatorTitle":[{"text":"POBNativeAd","kind":"identifier"}],"title":"POBNativeAd","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","url":"\/documentation\/openwrapsdk\/pobnativead","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAd"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdRenderingCompletionBlock":{"navigatorTitle":[{"text":"POBNativeAdRenderingCompletionBlock","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdRenderingCompletionBlock"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativeadrenderingcompletionblock","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdRenderingCompletionBlock","title":"POBNativeAdRenderingCompletionBlock","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeAdRenderingCompletionBlock"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"value":[{"text":"POBNativeAdRenderingCompletionBlock","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"POBNativeAdRenderingCompletionBlock","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:BFv(#*Qoobjc(pl)POBNativeAd#*$objc(cs)NSError)","text":"void (^)(id<POBNativeAd>, NSError *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"POBNativeAdRenderingCompletionBlock","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/title","value":"POBNativeAd","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/fragments","value":[{"kind":"identifier","text":"POBNativeAd"}]},{"op":"replace","value":"POBNativeAdRenderingCompletionBlock","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdRenderingCompletionBlock\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdRenderingCompletionBlock\/fragments","value":[{"text":"POBNativeAdRenderingCompletionBlock","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}