{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/address","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/ctaText","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/description","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/description2","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/displayURL","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/downloads","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/likes","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/phone","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/price","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/rating","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/salePrice","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/sponsored"]},{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"POBNativeDataAssetType","roleHeading":"Enumeration","externalID":"c:@E@POBNativeDataAssetType","navigatorTitle":[{"text":"POBNativeDataAssetType","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeDataAssetType","kind":"identifier"}],"symbolKind":"enum"},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"]}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativedataassettype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativedataassettype"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativeDataAssetType","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Native Data asset types"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/ctaText":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/ctaText","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/ctatext","title":"POBNativeDataAssetType.ctaText","abstract":[{"type":"text","text":"CTA description - descriptive text describing a ‘call to action’ button for the destination URL.    Value will be Text"}],"navigatorTitle":[{"text":"POBNativeDataAssetTypeCTAText","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ctaText","kind":"identifier"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/description2":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/description2","kind":"symbol","role":"symbol","title":"POBNativeDataAssetType.description2","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/description2","abstract":[{"text":"Additional descriptive text associated with the product or service being advertised. Value will be Text","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeDataAssetTypeDescription2"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"description2","kind":"identifier"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/description":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/description","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/description","title":"POBNativeDataAssetType.description","abstract":[{"text":"Descriptive text associated with the product or text service being advertised. Value is of type Text","type":"text"}],"navigatorTitle":[{"text":"POBNativeDataAssetTypeDescription","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/sponsored":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/sponsored","kind":"symbol","role":"symbol","title":"POBNativeDataAssetType.sponsored","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/sponsored","abstract":[{"type":"text","text":"Sponsored By message where response should contain the brand name of the sponsor. Value is of type Text"}],"navigatorTitle":[{"text":"POBNativeDataAssetTypeSponsored","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"sponsored","kind":"identifier"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/SH":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/salePrice":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/salePrice","kind":"symbol","role":"symbol","title":"POBNativeDataAssetType.salePrice","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/saleprice","abstract":[{"text":"Sale price that can be used together with price to indicate a discounted price compared to a regular price. Value should include currency symbol in localized format.     Value will be number formatted as string","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeDataAssetTypeSalePrice"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"salePrice","kind":"identifier"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/likes":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/likes","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/likes","title":"POBNativeDataAssetType.likes","abstract":[{"text":"Number of social ratings or “likes” of the product being offered to the user. Value will be number formatted as string","type":"text"}],"navigatorTitle":[{"text":"POBNativeDataAssetTypeLikes","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"likes"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeDataAssetType","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Native Data asset types"}],"navigatorTitle":[{"text":"POBNativeDataAssetType","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativedataassettype","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType","title":"POBNativeDataAssetType"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/rating":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/rating","kind":"symbol","role":"symbol","title":"POBNativeDataAssetType.rating","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/rating","abstract":[{"type":"text","text":"\/ Rating of the product being offered to the user. For example an app’s rating in an app store from 0-5.Value will be    number formatted as string"}],"navigatorTitle":[{"text":"POBNativeDataAssetTypeRating","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"rating","kind":"identifier"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/displayURL":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/displayURL","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/displayurl","title":"POBNativeDataAssetType.displayURL","abstract":[{"text":"Display URL for the text ad. Value will be Text","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeDataAssetTypeDisplayURL"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"displayURL","kind":"identifier"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/downloads":{"url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/downloads","type":"topic","kind":"symbol","navigatorTitle":[{"text":"POBNativeDataAssetTypeDownloads","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/downloads","title":"POBNativeDataAssetType.downloads","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloads","kind":"identifier"}],"abstract":[{"text":"Number downloads\/installs of this product.  Value will be number formatted as string","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/Equatable-Implementations":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/Equatable-Implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/equatable-implementations","abstract":[],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","abstract":[],"type":"topic"},"doc://com.pubmatic.openwrapsdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/price":{"role":"symbol","navigatorTitle":[{"text":"POBNativeDataAssetTypePrice","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"price","kind":"identifier"}],"title":"POBNativeDataAssetType.price","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/price","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/price","type":"topic","abstract":[{"text":"Price for product \/ app \/ in-app purchase. Value should include currency symbol in localized format. Value will be number formatted as string","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/init(rawValue:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/init(rawValue:)","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/address":{"title":"POBNativeDataAssetType.address","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/address","navigatorTitle":[{"kind":"identifier","text":"POBNativeDataAssetTypeAddress"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"address"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/address","abstract":[{"type":"text","text":"Represents Address of user. Value will be Text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType/phone":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/phone","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativedataassettype\/phone","title":"POBNativeDataAssetType.phone","abstract":[{"type":"text","text":"Represents Phone number of user. Value will be string"}],"navigatorTitle":[{"text":"POBNativeDataAssetTypePhone","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"POBNativeDataAssetType","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","value":[{"text":"POBNativeDataAssetType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"POBNativeDataAssetType"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/address","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/ctaText","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/description","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/description2","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/displayURL","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/downloads","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/likes","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/phone","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/price","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/rating","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/salePrice","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType\/sponsored"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeDataAssetType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1ctaText\/title","value":"POBNativeDataAssetTypeCTAText"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1ctaText\/fragments","value":[{"kind":"identifier","text":"POBNativeDataAssetTypeCTAText"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1description2\/title","value":"POBNativeDataAssetTypeDescription2"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1description2\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBNativeDataAssetTypeDescription2"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1description\/title","value":"POBNativeDataAssetTypeDescription"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1description\/fragments","value":[{"text":"POBNativeDataAssetTypeDescription","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1sponsored\/title","value":"POBNativeDataAssetTypeSponsored","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1sponsored\/fragments","value":[{"kind":"identifier","text":"POBNativeDataAssetTypeSponsored"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1salePrice\/title","value":"POBNativeDataAssetTypeSalePrice"},{"value":[{"kind":"identifier","text":"POBNativeDataAssetTypeSalePrice"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1salePrice\/fragments"},{"value":"POBNativeDataAssetTypeLikes","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1likes\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1likes\/fragments","value":[{"text":"POBNativeDataAssetTypeLikes","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"POBNativeDataAssetType","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/fragments","op":"replace","value":[{"text":"POBNativeDataAssetType","kind":"identifier"}]},{"value":"POBNativeDataAssetTypeRating","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1rating\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1rating\/fragments","value":[{"text":"POBNativeDataAssetTypeRating","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1displayURL\/title","value":"POBNativeDataAssetTypeDisplayURL"},{"op":"replace","value":[{"kind":"identifier","text":"POBNativeDataAssetTypeDisplayURL"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1displayURL\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1downloads\/title","value":"POBNativeDataAssetTypeDownloads","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1downloads\/fragments","value":[{"kind":"identifier","text":"POBNativeDataAssetTypeDownloads"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1price\/title","value":"POBNativeDataAssetTypePrice"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1price\/fragments","value":[{"text":"POBNativeDataAssetTypePrice","kind":"identifier"}]},{"op":"replace","value":"POBNativeDataAssetTypeAddress","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1address\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1address\/fragments","value":[{"kind":"identifier","text":"POBNativeDataAssetTypeAddress"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1phone\/title","value":"POBNativeDataAssetTypePhone","op":"replace"},{"value":[{"kind":"identifier","text":"POBNativeDataAssetTypePhone"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType~1phone\/fragments","op":"replace"}]}]}