{"sections":[],"metadata":{"externalID":"c:@E@POBNativeContextSubType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeContextSubType","kind":"identifier"}],"symbolKind":"enum","role":"symbol","modules":[{"name":"OpenWrapSDK"}],"title":"POBNativeContextSubType","navigatorTitle":[{"text":"POBNativeContextSubType","kind":"identifier"}],"roleHeading":"Enumeration"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/artical","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/audio","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/chatIM","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/email","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/general","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/image","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/marketplace","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/productReviewSite","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/sellingProducts","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/social","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/userGenerated","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/video"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeContextSubType","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativecontextsubtype"]},{"paths":["\/documentation\/openwrapsdk\/pobnativecontextsubtype"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Next-level context in which the ad appears. Again this reflects the primary context, and does not imply no presence of other elements."}],"references":{"doc://com.pubmatic.openwrapsdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","title":"Swift.RawRepresentable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/userGenerated":{"title":"POBNativeContextSubType.userGenerated","abstract":[{"type":"text","text":"User-generated content - forums, comments, etc."}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/userGenerated","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/usergenerated","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userGenerated"}],"navigatorTitle":[{"text":"POBNativeContextSubTypeUserGenerated","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/marketplace":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/marketplace","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/marketplace","title":"POBNativeContextSubType.marketplace","abstract":[{"type":"text","text":"Application store\/marketplace"}],"navigatorTitle":[{"text":"POBNativeContextSubTypeMarketplace","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"marketplace","kind":"identifier"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/social":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeContextSubTypeSocial"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/social","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/social","role":"symbol","title":"POBNativeContextSubType.social","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"social","kind":"identifier"}],"abstract":[{"type":"text","text":"General social content such as a general social network"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/email":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeContextSubTypeEmail"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/email","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/email","role":"symbol","title":"POBNativeContextSubType.email","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"email"}],"abstract":[{"type":"text","text":"Primarily email content"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/sellingProducts":{"type":"topic","title":"POBNativeContextSubType.sellingProducts","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/sellingProducts","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"sellingProducts","kind":"identifier"}],"navigatorTitle":[{"text":"POBNativeContextSubTypeSellingProducts","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Content focused on selling products, whether digital or physical","type":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/sellingproducts"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/RawRepresentable-Implementations":{"type":"topic","abstract":[],"kind":"article","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType":{"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeContextSubType"}],"title":"POBNativeContextSubType","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType","type":"topic","abstract":[{"type":"text","text":"Next-level context in which the ad appears. Again this reflects the primary context, and does not imply no presence of other elements."}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeContextSubType"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/audio":{"type":"topic","abstract":[{"type":"text","text":"Primarily audio content"}],"navigatorTitle":[{"text":"POBNativeContextSubTypeAudio","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/audio","title":"POBNativeContextSubType.audio","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audio","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/audio"},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","title":"Swift.Sendable"},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/Equatable-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/equatable-implementations","kind":"article","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/artical":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/artical","role":"symbol","title":"POBNativeContextSubType.artical","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/artical","abstract":[{"text":"Primarily article content (which of course could include images, etc as part of the article)","type":"text"}],"navigatorTitle":[{"text":"POBNativeContextSubTypeArtical","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"artical","kind":"identifier"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/video":{"type":"topic","abstract":[{"text":"Primarily video content","type":"text"}],"navigatorTitle":[{"text":"POBNativeContextSubTypeVideo","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/video","title":"POBNativeContextSubType.video","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"video"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/video"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/image":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"}],"type":"topic","role":"symbol","abstract":[{"text":"Primarily image content","type":"text"}],"navigatorTitle":[{"text":"POBNativeContextSubTypeImage","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/image","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/image","title":"POBNativeContextSubType.image"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/chatIM":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeContextSubTypeChatIM"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/chatIM","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/chatim","role":"symbol","title":"POBNativeContextSubType.chatIM","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"chatIM","kind":"identifier"}],"abstract":[{"type":"text","text":"Primarily chat\/IM content"}]},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/general":{"abstract":[{"text":"General or mixed content.","type":"text"}],"navigatorTitle":[{"text":"POBNativeContextSubTypeGeneral","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/general","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/general","type":"topic","title":"POBNativeContextSubType.general","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"general"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/productReviewSite":{"kind":"symbol","type":"topic","title":"POBNativeContextSubType.productReviewSite","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"productReviewSite","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/productReviewSite","abstract":[{"type":"text","text":"Product reviews site primarily (which may sell product secondarily)"}],"url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/productreviewsite","navigatorTitle":[{"text":"POBNativeContextSubTypeProductReviewSite","kind":"identifier"}],"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/init(rawValue:)":{"kind":"symbol","type":"topic","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/init(rawvalue:)","role":"symbol","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/init(rawValue:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"POBNativeContextSubType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"text":"POBNativeContextSubType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"POBNativeContextSubType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/artical","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/audio","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/chatIM","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/email","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/general","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/image","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/marketplace","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/productReviewSite","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/sellingProducts","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/social","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/userGenerated","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/video"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeContextSubType","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}]}},{"value":"POBNativeContextSubTypeUserGenerated","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1userGenerated\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1userGenerated\/fragments","value":[{"text":"POBNativeContextSubTypeUserGenerated","kind":"identifier"}],"op":"replace"},{"value":"POBNativeContextSubTypeMarketplace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1marketplace\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1marketplace\/fragments","value":[{"kind":"identifier","text":"POBNativeContextSubTypeMarketplace"}],"op":"replace"},{"value":"POBNativeContextSubTypeSocial","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1social\/title"},{"value":[{"kind":"identifier","text":"POBNativeContextSubTypeSocial"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1social\/fragments"},{"op":"replace","value":"POBNativeContextSubTypeEmail","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1email\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1email\/fragments","value":[{"text":"POBNativeContextSubTypeEmail","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1sellingProducts\/title","value":"POBNativeContextSubTypeSellingProducts","op":"replace"},{"value":[{"text":"POBNativeContextSubTypeSellingProducts","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1sellingProducts\/fragments","op":"replace"},{"value":"POBNativeContextSubType","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType\/fragments","value":[{"text":"POBNativeContextSubType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1audio\/title","value":"POBNativeContextSubTypeAudio"},{"value":[{"text":"POBNativeContextSubTypeAudio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1audio\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1artical\/title","value":"POBNativeContextSubTypeArtical","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1artical\/fragments","value":[{"kind":"identifier","text":"POBNativeContextSubTypeArtical"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1video\/title","value":"POBNativeContextSubTypeVideo","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1video\/fragments","value":[{"kind":"identifier","text":"POBNativeContextSubTypeVideo"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1image\/title","value":"POBNativeContextSubTypeImage","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1image\/fragments","op":"replace","value":[{"text":"POBNativeContextSubTypeImage","kind":"identifier"}]},{"value":"POBNativeContextSubTypeChatIM","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1chatIM\/title"},{"op":"replace","value":[{"kind":"identifier","text":"POBNativeContextSubTypeChatIM"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1chatIM\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1general\/title","value":"POBNativeContextSubTypeGeneral"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1general\/fragments","value":[{"kind":"identifier","text":"POBNativeContextSubTypeGeneral"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1productReviewSite\/title","value":"POBNativeContextSubTypeProductReviewSite","op":"replace"},{"value":[{"text":"POBNativeContextSubTypeProductReviewSite","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1productReviewSite\/fragments","op":"replace"}]}]}