{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/contentCentric","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/productSpcific","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/socialCentric"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType"},"metadata":{"externalID":"c:@E@POBNativeContextType","modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Enumeration","role":"symbol","navigatorTitle":[{"text":"POBNativeContextType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeContextType"}],"title":"POBNativeContextType","symbolKind":"enum"},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativecontexttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativecontexttype"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeContextType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The context in which the ad appears - what type of content is surrounding the ad on the  page at a high level."}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextType/contentCentric":{"title":"POBNativeContextType.contentCentric","url":"\/documentation\/openwrapsdk\/pobnativecontexttype\/contentcentric","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/contentCentric","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentCentric"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"POBNativeContextTypeContentCentric","kind":"identifier"}],"abstract":[{"type":"text","text":"Content-centric context such as newsfeed, article, image gallery, video gallery, or similar."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextType/socialCentric":{"url":"\/documentation\/openwrapsdk\/pobnativecontexttype\/socialcentric","title":"POBNativeContextType.socialCentric","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/socialCentric","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"socialCentric"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBNativeContextTypeSocialCentric"}],"abstract":[{"type":"text","text":"Social-centric context such as social network feed, email, chat, or similar."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextType/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/openwrapsdk\/pobnativecontexttype\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextType":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBNativeContextType"}],"url":"\/documentation\/openwrapsdk\/pobnativecontexttype","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeContextType","kind":"identifier"}],"title":"POBNativeContextType","abstract":[{"type":"text","text":"The context in which the ad appears - what type of content is surrounding the ad on the  page at a high level."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextType/productSpcific":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/productSpcific","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"productSpcific"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontexttype\/productspcific","abstract":[{"type":"text","text":"Product context such as product listings, details, recommendations, reviews, or similar."}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeContextTypeProductSpcific"}],"title":"POBNativeContextType.productSpcific","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextType/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/openwrapsdk\/pobnativecontexttype\/init(rawvalue:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/init(rawValue:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[]},"doc://com.pubmatic.openwrapsdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","title":"Swift.RawRepresentable"},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","title":"Swift.Sendable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextType/Equatable-Implementations":{"kind":"article","role":"collectionGroup","url":"\/documentation\/openwrapsdk\/pobnativecontexttype\/equatable-implementations","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/Equatable-Implementations","title":"Equatable Implementations","abstract":[]},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","value":"POBNativeContextType","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBNativeContextType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"POBNativeContextType"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/contentCentric","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/productSpcific","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextType\/socialCentric"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeContextType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType~1contentCentric\/title","value":"POBNativeContextTypeContentCentric","op":"replace"},{"value":[{"text":"POBNativeContextTypeContentCentric","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType~1contentCentric\/fragments"},{"op":"replace","value":"POBNativeContextTypeSocialCentric","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType~1socialCentric\/title"},{"op":"replace","value":[{"text":"POBNativeContextTypeSocialCentric","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType~1socialCentric\/fragments"},{"op":"replace","value":"POBNativeContextType","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType\/fragments","value":[{"text":"POBNativeContextType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType~1productSpcific\/title","value":"POBNativeContextTypeProductSpcific","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextType~1productSpcific\/fragments","value":[{"kind":"identifier","text":"POBNativeContextTypeProductSpcific"}],"op":"replace"}]}]}