{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdResponseAsset"],"kind":"relationships"},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/height","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/imageURL","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/type","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/width"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadimageresponseasset"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadimageresponseasset"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativeAdImageResponseAsset","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"POBNativeAdImageResponseAsset","kind":"identifier"}],"role":"symbol","title":"POBNativeAdImageResponseAsset","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativeAdImageResponseAsset","kind":"identifier"}],"externalID":"c:objc(cs)POBNativeAdImageResponseAsset","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdImageResponseAsset":{"url":"\/documentation\/openwrapsdk\/pobnativeadimageresponseasset","title":"POBNativeAdImageResponseAsset","navigatorTitle":[{"text":"POBNativeAdImageResponseAsset","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAdImageResponseAsset","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset","kind":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdImageResponseAsset/width":{"abstract":[],"navigatorTitle":[{"text":"width","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadimageresponseasset\/width","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/width","title":"width","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pubmatic.openwrapsdk/SQ":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdImageResponseAsset/imageURL":{"abstract":[],"navigatorTitle":[{"text":"imageURL","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativeadimageresponseasset\/imageurl","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/imageURL","type":"topic","title":"imageURL","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURL","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdResponseAsset":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdResponseAsset","role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadresponseasset","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"POBNativeAdResponseAsset","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdResponseAsset"}],"type":"topic","abstract":[],"title":"POBNativeAdResponseAsset"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdImageResponseAsset/initWithType:width:height:url:builder:":{"url":"\/documentation\/openwrapsdk\/pobnativeadimageresponseasset\/initwithtype:width:height:url:builder:","title":"initWithType:width:height:url:builder:","navigatorTitle":[{"text":"initWithType:width:height:url:builder:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithType:width:height:url:builder:","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/initWithType:width:height:url:builder:","kind":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdImageResponseAsset/type":{"title":"type","url":"\/documentation\/openwrapsdk\/pobnativeadimageresponseasset\/type","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/type","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@POBNativeImageAssetType","text":"POBNativeImageAssetType","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"type","kind":"identifier"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdImageResponseAsset/height":{"navigatorTitle":[{"kind":"identifier","text":"height"}],"url":"\/documentation\/openwrapsdk\/pobnativeadimageresponseasset\/height","abstract":[],"kind":"symbol","title":"height","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/height","role":"symbol"},"doc://com.pubmatic.openwrapsdk/SH":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"POBNativeAdImageResponseAsset"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"POBNativeAdImageResponseAsset","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"POBNativeAdImageResponseAsset"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/height","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/imageURL","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/type","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/width"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdImageResponseAsset\/initWithType:width:height:url:builder:"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdResponseAsset"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativeAdImageResponseAsset","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"POBNativeAdResponseAsset","preciseIdentifier":"c:objc(cs)POBNativeAdResponseAsset","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdResponseAsset","kind":"typeIdentifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdImageResponseAsset\/title","value":"POBNativeAdImageResponseAsset","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdImageResponseAsset\/fragments","op":"replace","value":[{"text":"POBNativeAdImageResponseAsset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdImageResponseAsset~1width\/title","op":"replace","value":"width"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdImageResponseAsset~1width\/fragments","value":[{"kind":"identifier","text":"width"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdImageResponseAsset~1imageURL\/title","value":"imageURL"},{"value":[{"text":"imageURL","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdImageResponseAsset~1imageURL\/fragments"},{"op":"replace","value":"POBNativeAdResponseAsset","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdResponseAsset\/title"},{"op":"replace","value":[{"text":"POBNativeAdResponseAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdResponseAsset\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdImageResponseAsset~1type\/title","value":"type","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdImageResponseAsset~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdImageResponseAsset~1height\/title","value":"height","op":"replace"},{"value":[{"kind":"identifier","text":"height"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdImageResponseAsset~1height\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}