{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBNativeAdMediumTemplateView","kind":"identifier"}]}]},{"content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"inlineContent":[{"text":"All these assets are required, and will be rendered by OpenWrap SDK.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdMediumTemplateView\/mainImgView"]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView"],"kind":"relationships","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSCoding","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)CALayerDelegate","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearance","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearanceContainer","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UICoordinateSpace","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIDynamicItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusEnvironment","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItemContainer","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UILargeContentViewerItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pubmatic.openwrapsdk\/5UIKit23UITraitChangeObservableP","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UITraitEnvironment","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIUserActivityRestoring"]}],"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdMediumTemplateView","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadmediumtemplateview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativeadmediumtemplateview"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:objc(cs)POBNativeAdMediumTemplateView","role":"symbol","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdMediumTemplateView"}],"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdMediumTemplateView"}],"title":"POBNativeAdMediumTemplateView"},"references":{"doc://com.pubmatic.openwrapsdk/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIDynamicItem"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIResponderStandardEditActions"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItemContainer"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearanceContainer"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateView":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"POBNativeTemplateView","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativetemplateview","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeTemplateView","kind":"identifier"}],"title":"POBNativeTemplateView","abstract":[]},"doc://com.pubmatic.openwrapsdk/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UITraitEnvironment"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdMediumTemplateView/mainImgView":{"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"mainImgView","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativeadmediumtemplateview\/mainimgview","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdMediumTemplateView\/mainImgView","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mainImgView","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"title":"mainImgView"},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH"},"doc://com.pubmatic.openwrapsdk/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)CALayerDelegate"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItem"},"doc://com.pubmatic.openwrapsdk/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UILargeContentViewerItem"},"doc://com.pubmatic.openwrapsdk/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearance","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdMediumTemplateView":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdMediumTemplateView","type":"topic","kind":"symbol","title":"POBNativeAdMediumTemplateView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdMediumTemplateView"}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeAdMediumTemplateView"}],"url":"\/documentation\/openwrapsdk\/pobnativeadmediumtemplateview"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"POBNativeAdMediumTemplateView","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBNativeAdMediumTemplateView","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"POBNativeAdMediumTemplateView"}]},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdMediumTemplateView\/mainImgView"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView"]}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativeAdMediumTemplateView","kind":"identifier"},{"kind":"text","text":" : "},{"text":"POBNativeTemplateView","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBNativeTemplateView"}]}]}},{"value":"POBNativeTemplateView","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView\/title","op":"replace"},{"value":[{"text":"POBNativeTemplateView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView\/fragments","op":"replace"},{"value":"mainImgView","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdMediumTemplateView~1mainImgView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdMediumTemplateView~1mainImgView\/fragments","value":[{"kind":"identifier","text":"mainImgView"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdMediumTemplateView\/title","op":"replace","value":"POBNativeAdMediumTemplateView"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdMediumTemplateView\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBNativeAdMediumTemplateView"}]}]}]}