{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAdView","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdView","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdView"}],"title":"POBNativeAdView","navigatorTitle":[{"text":"POBNativeAdView","kind":"identifier"}],"externalID":"c:objc(cs)POBNativeAdView","roleHeading":"Class","role":"symbol","modules":[{"name":"OpenWrapSDK"}],"symbolKind":"class"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)UIView"]},{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSCoding","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)CALayerDelegate","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearance","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearanceContainer","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UICoordinateSpace","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIDynamicItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusEnvironment","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItemContainer","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UILargeContentViewerItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pubmatic.openwrapsdk\/5UIKit23UITraitChangeObservableP","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UITraitEnvironment","doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadview"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"references":{"doc://com.pubmatic.openwrapsdk/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSCoding","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)CALayerDelegate","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIDynamicItem","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdView":{"abstract":[],"navigatorTitle":[{"text":"POBNativeAdView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadview","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdView","type":"topic","title":"POBNativeAdView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdView"}]},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(cs)UIView":{"title":"UIView","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)UIView","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)UIAppearance","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeAdView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"POBNativeAdView","kind":"identifier"}]},{"op":"replace","value":[{"text":"POBNativeAdView","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"add","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"POBNativeAdView","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdView\/title","value":"POBNativeAdView"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdView\/fragments","value":[{"text":"POBNativeAdView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}