{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAd","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/adView()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/dataAsset(withId:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/imageAsset(withId:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/registerView(forInteractions:clickableViews:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/renderAd(completion:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/renderAd(with:andCompletion:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/setAdDelegate(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/titleAsset(withId:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAd","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","externalID":"c:objc(pl)POBNativeAd","navigatorTitle":[{"kind":"identifier","text":"POBNativeAd"}],"title":"POBNativeAd","roleHeading":"Protocol","symbolKind":"protocol"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativead"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativead"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd/titleAsset(withId:)":{"navigatorTitle":[{"text":"titleAssetWithId:","kind":"identifier"}],"title":"titleAsset(withId:)","required":true,"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/titleAsset(withId:)","abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativead\/titleasset(withid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleAsset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"POBNativeAdTitleResponseAsset","preciseIdentifier":"c:objc(cs)POBNativeAdTitleResponseAsset","kind":"typeIdentifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd":{"navigatorTitle":[{"text":"POBNativeAd","kind":"identifier"}],"title":"POBNativeAd","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","url":"\/documentation\/openwrapsdk\/pobnativead","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAd"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd/imageAsset(withId:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"imageAsset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"POBNativeAdImageResponseAsset","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBNativeAdImageResponseAsset"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"imageAssetWithId:","kind":"identifier"}],"title":"imageAsset(withId:)","abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativead\/imageasset(withid:)","type":"topic","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/imageAsset(withId:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd/adView()":{"abstract":[],"required":true,"navigatorTitle":[{"text":"adView","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativead\/adview()","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/adView()","type":"topic","title":"adView()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adView"},{"kind":"text","text":"() -> "},{"text":"POBNativeAdView","preciseIdentifier":"c:objc(cs)POBNativeAdView","kind":"typeIdentifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd/setAdDelegate(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAdDelegate","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"POBNativeAdDelegate","preciseIdentifier":"c:objc(pl)POBNativeAdDelegate"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setAdDelegate:"}],"abstract":[],"title":"setAdDelegate(_:)","url":"\/documentation\/openwrapsdk\/pobnativead\/setaddelegate(_:)","type":"topic","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/setAdDelegate(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd/renderAd(with:andCompletion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBNativeTemplateView","text":"POBNativeTemplateView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"andCompletion"},{"text":": ","kind":"text"},{"text":"POBNativeAdRenderingCompletionBlock","preciseIdentifier":"c:POBNativeAd.h@T@POBNativeAdRenderingCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"renderAd(with:andCompletion:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/renderAd(with:andCompletion:)","required":true,"kind":"symbol","navigatorTitle":[{"text":"renderAdWithTemplateView:andCompletion:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativead\/renderad(with:andcompletion:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd/dataAsset(withId:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"dataAsset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"POBNativeAdDataResponseAsset","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBNativeAdDataResponseAsset"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dataAssetWithId:"}],"title":"dataAsset(withId:)","abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativead\/dataasset(withid:)","type":"topic","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/dataAsset(withId:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd/renderAd(completion:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"POBNativeAdRenderingCompletionBlock","preciseIdentifier":"c:POBNativeAd.h@T@POBNativeAdRenderingCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"renderAdWithCompletion:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativead\/renderad(completion:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/renderAd(completion:)","title":"renderAd(completion:)","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd/registerView(forInteractions:clickableViews:)":{"navigatorTitle":[{"kind":"identifier","text":"registerViewForInteractions:clickableViews:"}],"title":"registerView(forInteractions:clickableViews:)","type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativead\/registerview(forinteractions:clickableviews:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/registerView(forInteractions:clickableViews:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerView"},{"text":"(","kind":"text"},{"text":"forInteractions","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"clickableViews"},{"kind":"text","text":": ["},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"])","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"POBNativeAd"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"POBNativeAd","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"POBNativeAd","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/adView()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/dataAsset(withId:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/imageAsset(withId:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/registerView(forInteractions:clickableViews:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/renderAd(completion:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/renderAd(with:andCompletion:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/setAdDelegate(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd\/titleAsset(withId:)"],"title":"Instance Methods"}]},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAd"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1titleAsset(withId:)\/title","op":"replace","value":"titleAssetWithId:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1titleAsset(withId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"titleAssetWithId:"}],"op":"replace"},{"value":"POBNativeAd","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/fragments","value":[{"text":"POBNativeAd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1imageAsset(withId:)\/title","op":"replace","value":"imageAssetWithId:"},{"value":[{"kind":"text","text":"- "},{"text":"imageAssetWithId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1imageAsset(withId:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1adView()\/title","value":"adView"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adView"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1adView()\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1setAdDelegate(_:)\/title","op":"replace","value":"setAdDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1setAdDelegate(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setAdDelegate:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1renderAd(with:andCompletion:)\/title","op":"replace","value":"renderAdWithTemplateView:andCompletion:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1renderAd(with:andCompletion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"renderAdWithTemplateView:andCompletion:"}]},{"op":"replace","value":"dataAssetWithId:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1dataAsset(withId:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"dataAssetWithId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1dataAsset(withId:)\/fragments"},{"op":"replace","value":"renderAdWithCompletion:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1renderAd(completion:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1renderAd(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"renderAdWithCompletion:"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1registerView(forInteractions:clickableViews:)\/title","op":"replace","value":"registerViewForInteractions:clickableViews:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd~1registerView(forInteractions:clickableViews:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"registerViewForInteractions:clickableViews:","kind":"identifier"}]}]}]}