{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdResponseAsset"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdTitleResponseAsset\/length","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdTitleResponseAsset\/text"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdTitleResponseAsset"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadtitleresponseasset"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadtitleresponseasset"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBNativeAdTitleResponseAsset","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdTitleResponseAsset"}],"role":"symbol","title":"POBNativeAdTitleResponseAsset","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAdTitleResponseAsset","kind":"identifier"}],"externalID":"c:objc(cs)POBNativeAdTitleResponseAsset","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdTitleResponseAsset/text":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"text"}],"url":"\/documentation\/openwrapsdk\/pobnativeadtitleresponseasset\/text","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdTitleResponseAsset\/text","title":"text","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdResponseAsset":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdResponseAsset","role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadresponseasset","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"POBNativeAdResponseAsset","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdResponseAsset"}],"type":"topic","abstract":[],"title":"POBNativeAdResponseAsset"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdTitleResponseAsset/initWithText:length:builder:":{"title":"initWithText:length:builder:","url":"\/documentation\/openwrapsdk\/pobnativeadtitleresponseasset\/initwithtext:length:builder:","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdTitleResponseAsset\/initWithText:length:builder:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithText:length:builder:"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithText:length:builder:"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdTitleResponseAsset":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeAdTitleResponseAsset"}],"title":"POBNativeAdTitleResponseAsset","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdTitleResponseAsset","url":"\/documentation\/openwrapsdk\/pobnativeadtitleresponseasset","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBNativeAdTitleResponseAsset","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdTitleResponseAsset/length":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"length"}],"url":"\/documentation\/openwrapsdk\/pobnativeadtitleresponseasset\/length","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdTitleResponseAsset\/length","type":"topic","title":"length","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"length","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeAdTitleResponseAsset"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"POBNativeAdTitleResponseAsset"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"POBNativeAdTitleResponseAsset"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdTitleResponseAsset\/length","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdTitleResponseAsset\/text"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdTitleResponseAsset\/initWithText:length:builder:"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdResponseAsset"],"kind":"relationships"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativeAdTitleResponseAsset","kind":"identifier"},{"kind":"text","text":" : "},{"text":"POBNativeAdResponseAsset","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdResponseAsset","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBNativeAdResponseAsset"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdTitleResponseAsset~1text\/title","op":"replace","value":"text"},{"value":[{"kind":"identifier","text":"text"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdTitleResponseAsset~1text\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdResponseAsset\/title","value":"POBNativeAdResponseAsset"},{"value":[{"text":"POBNativeAdResponseAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdResponseAsset\/fragments","op":"replace"},{"value":"POBNativeAdTitleResponseAsset","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdTitleResponseAsset\/title"},{"op":"replace","value":[{"text":"POBNativeAdTitleResponseAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdTitleResponseAsset\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdTitleResponseAsset~1length\/title","value":"length"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdTitleResponseAsset~1length\/fragments","value":[{"kind":"identifier","text":"length"}]}]}]}