{"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderDelegate\/nativeAdLoader(_:didFailToReceiveAdWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderDelegate\/nativeAdLoader(_:didReceive:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderDelegate\/viewControllerForPresentingModal()"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderDelegate"},"metadata":{"roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdLoaderDelegate"}],"modules":[{"name":"OpenWrapSDK"}],"title":"POBNativeAdLoaderDelegate","navigatorTitle":[{"text":"POBNativeAdLoaderDelegate","kind":"identifier"}],"symbolKind":"protocol","externalID":"c:objc(pl)POBNativeAdLoaderDelegate","role":"symbol"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadloaderdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadloaderdelegate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdLoaderDelegate"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoaderDelegate/nativeAdLoader(_:didFailToReceiveAdWithError:)":{"required":true,"title":"nativeAdLoader(_:didFailToReceiveAdWithError:)","url":"\/documentation\/openwrapsdk\/pobnativeadloaderdelegate\/nativeadloader(_:didfailtoreceiveadwitherror:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderDelegate\/nativeAdLoader(_:didFailToReceiveAdWithError:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAdLoader"},{"text":"(","kind":"text"},{"text":"POBNativeAdLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBNativeAdLoader"},{"kind":"text","text":", "},{"text":"didFailToReceiveAdWithError","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"nativeAdLoader:didFailToReceiveAdWithError:","kind":"identifier"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoaderDelegate":{"url":"\/documentation\/openwrapsdk\/pobnativeadloaderdelegate","title":"POBNativeAdLoaderDelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAdLoaderDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdLoaderDelegate"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoaderDelegate/viewControllerForPresentingModal()":{"required":true,"url":"\/documentation\/openwrapsdk\/pobnativeadloaderdelegate\/viewcontrollerforpresentingmodal()","title":"viewControllerForPresentingModal()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderDelegate\/viewControllerForPresentingModal()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewControllerForPresentingModal","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewControllerForPresentingModal"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoaderDelegate/nativeAdLoader(_:didReceive:)":{"title":"nativeAdLoader(_:didReceive:)","url":"\/documentation\/openwrapsdk\/pobnativeadloaderdelegate\/nativeadloader(_:didreceive:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderDelegate\/nativeAdLoader(_:didReceive:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nativeAdLoader","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBNativeAdLoader","text":"POBNativeAdLoader","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didReceive","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)POBNativeAd","kind":"typeIdentifier","text":"POBNativeAd"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nativeAdLoader:didReceiveAd:"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"POBNativeAdLoaderDelegate","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"POBNativeAdLoaderDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"POBNativeAdLoaderDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderDelegate\/nativeAdLoader(_:didFailToReceiveAdWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderDelegate\/nativeAdLoader(_:didReceive:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderDelegate\/viewControllerForPresentingModal()"]}],"op":"replace"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"POBNativeAdLoaderDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"nativeAdLoader:didFailToReceiveAdWithError:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderDelegate~1nativeAdLoader(_:didFailToReceiveAdWithError:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderDelegate~1nativeAdLoader(_:didFailToReceiveAdWithError:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeAdLoader:didFailToReceiveAdWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderDelegate\/title","value":"POBNativeAdLoaderDelegate"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderDelegate\/fragments","value":[{"kind":"identifier","text":"POBNativeAdLoaderDelegate"}],"op":"replace"},{"value":"viewControllerForPresentingModal","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderDelegate~1viewControllerForPresentingModal()\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderDelegate~1viewControllerForPresentingModal()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewControllerForPresentingModal"}]},{"op":"replace","value":"nativeAdLoader:didReceiveAd:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderDelegate~1nativeAdLoader(_:didReceive:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"nativeAdLoader:didReceiveAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderDelegate~1nativeAdLoader(_:didReceive:)\/fragments"}]}]}