{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobplacement"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobplacement"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement"},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"]}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBPlacement","kind":"identifier"}],"role":"symbol","roleHeading":"Enumeration","symbolKind":"enum","title":"POBPlacement","externalID":"c:@E@POBPlacement","navigatorTitle":[{"text":"POBPlacement","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBPlacement"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"abstract":[{"text":"Video ad placement type with respect to main content","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inArticle","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inBanner","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inFeed","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inStream","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/interstitial"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement":{"role":"symbol","title":"POBPlacement","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBPlacement"}],"abstract":[{"type":"text","text":"Video ad placement type with respect to main content"}],"url":"\/documentation\/openwrapsdk\/pobplacement","navigatorTitle":[{"text":"POBPlacement","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement/interstitial":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitial"}],"url":"\/documentation\/openwrapsdk\/pobplacement\/interstitial","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/interstitial","role":"symbol","navigatorTitle":[{"text":"POBPlacementInterstitial","kind":"identifier"}],"abstract":[{"type":"text","text":"Video ad as an Interstitial"}],"type":"topic","kind":"symbol","title":"POBPlacement.interstitial"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement/RawRepresentable-Implementations":{"kind":"article","type":"topic","title":"RawRepresentable Implementations","url":"\/documentation\/openwrapsdk\/pobplacement\/rawrepresentable-implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/RawRepresentable-Implementations"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement/inFeed":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"inFeed","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Video ad in App feeds","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBPlacementInFeed"}],"url":"\/documentation\/openwrapsdk\/pobplacement\/infeed","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inFeed","title":"POBPlacement.inFeed"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement/init(rawValue:)":{"url":"\/documentation\/openwrapsdk\/pobplacement\/init(rawvalue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/init(rawValue:)","type":"topic","title":"init(rawValue:)","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","title":"Swift.RawRepresentable"},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement/inArticle":{"title":"POBPlacement.inArticle","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inArticle","url":"\/documentation\/openwrapsdk\/pobplacement\/inarticle","navigatorTitle":[{"kind":"identifier","text":"POBPlacementInArticle"}],"kind":"symbol","abstract":[{"text":"Video ad in Article","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inArticle"}]},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","title":"Swift.Sendable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement/inBanner":{"role":"symbol","kind":"symbol","title":"POBPlacement.inBanner","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inBanner"}],"abstract":[{"type":"text","text":"Video ad as a Banner"}],"url":"\/documentation\/openwrapsdk\/pobplacement\/inbanner","navigatorTitle":[{"kind":"identifier","text":"POBPlacementInBanner"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inBanner","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement/Equatable-Implementations":{"url":"\/documentation\/openwrapsdk\/pobplacement\/equatable-implementations","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/Equatable-Implementations","role":"collectionGroup","abstract":[],"type":"topic","kind":"article","title":"Equatable Implementations"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBPlacement/inStream":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inStream"}],"url":"\/documentation\/openwrapsdk\/pobplacement\/instream","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inStream","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBPlacementInStream"}],"abstract":[{"type":"text","text":"In-stream video ad"}],"type":"topic","kind":"symbol","title":"POBPlacement.inStream"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"POBPlacement"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBPlacement","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"POBPlacement"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inArticle","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inBanner","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inFeed","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/inStream","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBPlacement\/interstitial"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBPlacement"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"POBPlacement","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement\/title","op":"replace"},{"value":[{"kind":"identifier","text":"POBPlacement"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement\/fragments"},{"op":"replace","value":"POBPlacementInterstitial","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1interstitial\/title"},{"op":"replace","value":[{"kind":"identifier","text":"POBPlacementInterstitial"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1interstitial\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inFeed\/title","value":"POBPlacementInFeed","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inFeed\/fragments","value":[{"text":"POBPlacementInFeed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inArticle\/title","op":"replace","value":"POBPlacementInArticle"},{"value":[{"text":"POBPlacementInArticle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inArticle\/fragments"},{"op":"replace","value":"POBPlacementInBanner","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inBanner\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inBanner\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBPlacementInBanner"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inStream\/title","op":"replace","value":"POBPlacementInStream"},{"op":"replace","value":[{"kind":"identifier","text":"POBPlacementInStream"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBPlacement~1inStream\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}