{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBRewardedAdDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"All messages are guaranteed to occur on the main thread.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobrewardedaddelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedaddelegate"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"abstract":[{"type":"text","text":"Protocol for interaction with the POBRewardedAd instance."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAd(_:didFailToReceiveAdWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAd(_:didFailToShowAdWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAd(_:shouldReward:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidClick(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidDismiss(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidExpireAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidPresent(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidReceive(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidRecordImpression(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdWillLeaveApplication(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdWillPresent(_:)"]}],"kind":"symbol","metadata":{"symbolKind":"protocol","navigatorTitle":[{"text":"POBRewardedAdDelegate","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol","title":"POBRewardedAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBRewardedAdDelegate"}],"externalID":"c:objc(pl)POBRewardedAdDelegate","modules":[{"name":"OpenWrapSDK"}]},"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAdWillPresent(_:)":{"abstract":[],"required":true,"navigatorTitle":[{"text":"rewardedAdWillPresentAd:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedadwillpresent(_:)","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdWillPresent(_:)","type":"topic","title":"rewardedAdWillPresent(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rewardedAdWillPresent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"POBRewardedAd","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"text":")","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAd(_:didFailToReceiveAdWithError:)":{"title":"rewardedAd(_:didFailToReceiveAdWithError:)","url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedad(_:didfailtoreceiveadwitherror:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAd(_:didFailToReceiveAdWithError:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rewardedAd","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)POBRewardedAd","text":"POBRewardedAd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailToReceiveAdWithError"},{"text":": any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"rewardedAd:didFailToReceiveAdWithError:","kind":"identifier"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAd(_:shouldReward:)":{"navigatorTitle":[{"kind":"identifier","text":"rewardedAd:shouldReward:"}],"url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedad(_:shouldreward:)","abstract":[],"kind":"symbol","title":"rewardedAd(_:shouldReward:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"POBRewardedAd","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"text":", ","kind":"text"},{"text":"shouldReward","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"POBReward","preciseIdentifier":"c:objc(cs)POBReward"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAd(_:shouldReward:)","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAdDidPresent(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidPresent(_:)","role":"symbol","title":"rewardedAdDidPresent(_:)","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedaddidpresent(_:)","navigatorTitle":[{"text":"rewardedAdDidPresentAd:","kind":"identifier"}],"type":"topic","abstract":[],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAdDidPresent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"POBRewardedAd","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"kind":"text","text":")"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAdDidDismiss(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"rewardedAdDidDismissAd:"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidDismiss(_:)","title":"rewardedAdDidDismiss(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdDidDismiss","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBRewardedAd","preciseIdentifier":"c:objc(cs)POBRewardedAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedaddiddismiss(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAdDidReceive(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"rewardedAdDidReceiveAd:"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidReceive(_:)","title":"rewardedAdDidReceive(_:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rewardedAdDidReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedaddidreceive(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAdDidClick(_:)":{"url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedaddidclick(_:)","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidClick(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"rewardedAdDidClickAd:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdDidClick"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)POBRewardedAd","kind":"typeIdentifier","text":"POBRewardedAd"},{"kind":"text","text":")"}],"title":"rewardedAdDidClick(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate","navigatorTitle":[{"text":"POBRewardedAdDelegate","kind":"identifier"}],"title":"POBRewardedAdDelegate","type":"topic","abstract":[{"type":"text","text":"Protocol for interaction with the POBRewardedAd instance."}],"url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBRewardedAdDelegate"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAdDidRecordImpression(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"rewardedAdDidRecordImpression:"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidRecordImpression(_:)","title":"rewardedAdDidRecordImpression(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdDidRecordImpression","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBRewardedAd","preciseIdentifier":"c:objc(cs)POBRewardedAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedaddidrecordimpression(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAd(_:didFailToShowAdWithError:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAd"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBRewardedAd","text":"POBRewardedAd"},{"text":", ","kind":"text"},{"text":"didFailToShowAdWithError","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"rewardedAd:didFailToShowAdWithError:"}],"url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedad(_:didfailtoshowadwitherror:)","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAd(_:didFailToShowAdWithError:)","title":"rewardedAd(_:didFailToShowAdWithError:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAdDidExpireAd(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"rewardedAdDidExpireAd:"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidExpireAd(_:)","title":"rewardedAdDidExpireAd(_:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rewardedAdDidExpireAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedaddidexpiread(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAdWillLeaveApplication(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdWillLeaveApplication"},{"kind":"text","text":"("},{"text":"POBRewardedAd","preciseIdentifier":"c:objc(cs)POBRewardedAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"rewardedAdWillLeaveApplication:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedadwillleaveapplication(_:)","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdWillLeaveApplication(_:)","title":"rewardedAdWillLeaveApplication(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"POBRewardedAdDelegate","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBRewardedAdDelegate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"POBRewardedAdDelegate","kind":"identifier"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAd(_:didFailToReceiveAdWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAd(_:didFailToShowAdWithError:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAd(_:shouldReward:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidClick(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidDismiss(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidExpireAd(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidPresent(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidReceive(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidRecordImpression(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdWillLeaveApplication(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdWillPresent(_:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBRewardedAdDelegate"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"rewardedAdWillPresentAd:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdWillPresent(_:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdWillPresent(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rewardedAdWillPresentAd:"}]},{"value":"rewardedAd:didFailToReceiveAdWithError:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAd(_:didFailToReceiveAdWithError:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rewardedAd:didFailToReceiveAdWithError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAd(_:didFailToReceiveAdWithError:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAd(_:shouldReward:)\/title","value":"rewardedAd:shouldReward:","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAd(_:shouldReward:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rewardedAd:shouldReward:"}],"op":"replace"},{"value":"rewardedAdDidPresentAd:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidPresent(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"rewardedAdDidPresentAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidPresent(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidDismiss(_:)\/title","value":"rewardedAdDidDismissAd:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rewardedAdDidDismissAd:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidDismiss(_:)\/fragments"},{"value":"rewardedAdDidReceiveAd:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidReceive(_:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidReceive(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rewardedAdDidReceiveAd:","kind":"identifier"}]},{"value":"rewardedAdDidClickAd:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidClick(_:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidClick(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rewardedAdDidClickAd:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate\/title","value":"POBRewardedAdDelegate"},{"value":[{"text":"POBRewardedAdDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidRecordImpression(_:)\/title","value":"rewardedAdDidRecordImpression:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidRecordImpression(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rewardedAdDidRecordImpression:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAd(_:didFailToShowAdWithError:)\/title","value":"rewardedAd:didFailToShowAdWithError:","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAd(_:didFailToShowAdWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rewardedAd:didFailToShowAdWithError:"}],"op":"replace"},{"value":"rewardedAdDidExpireAd:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidExpireAd(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rewardedAdDidExpireAd:"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidExpireAd(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdWillLeaveApplication(_:)\/title","value":"rewardedAdWillLeaveApplication:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdWillLeaveApplication(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"rewardedAdWillLeaveApplication:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}