{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"metadata":{"symbolKind":"class","roleHeading":"Class","title":"POBRequest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBRequest"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"POBRequest","kind":"identifier"}],"externalID":"c:objc(cs)POBRequest"},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/init(publisherId:profileId:adFormat:impressions:)"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/adFormat","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/adServerURL","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/debug","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/impressions","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/networkTimeout","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/profileId","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/publisherId","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/returnAllBidStatus","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/testModeEnabled","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/versionId"],"title":"Instance Properties"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Represents an ad request for the given impression\/s & profile.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBRequest","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobrequest"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobrequest"]}],"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest/returnAllBidStatus":{"navigatorTitle":[{"kind":"identifier","text":"returnAllBidStatus"}],"url":"\/documentation\/openwrapsdk\/pobrequest\/returnallbidstatus","abstract":[],"kind":"symbol","title":"returnAllBidStatus","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"returnAllBidStatus"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/returnAllBidStatus","role":"symbol"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest/init(publisherId:profileId:adFormat:impressions:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"!(","kind":"text"},{"text":"publisherId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"profileId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"!, ","kind":"text"},{"text":"adFormat","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@POBAdFormat","kind":"typeIdentifier","text":"POBAdFormat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"impressions"},{"kind":"text","text":": ["},{"text":"POBImpression","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBImpression"},{"text":"]!)","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithPublisherId:profileId:adFormat:impressions:","kind":"identifier"}],"abstract":[],"title":"init(publisherId:profileId:adFormat:impressions:)","url":"\/documentation\/openwrapsdk\/pobrequest\/init(publisherid:profileid:adformat:impressions:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/init(publisherId:profileId:adFormat:impressions:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest/debug":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"debug","kind":"identifier"}],"title":"debug","abstract":[],"url":"\/documentation\/openwrapsdk\/pobrequest\/debug","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/debug"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest/profileId":{"abstract":[],"navigatorTitle":[{"text":"profileId","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrequest\/profileid","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/profileId","title":"profileId","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"profileId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"!","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest/networkTimeout":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkTimeout"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"networkTimeout","kind":"identifier"}],"abstract":[],"title":"networkTimeout","url":"\/documentation\/openwrapsdk\/pobrequest\/networktimeout","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/networkTimeout"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest/adServerURL":{"url":"\/documentation\/openwrapsdk\/pobrequest\/adserverurl","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/adServerURL","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"adServerURL","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adServerURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"adServerURL"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest/testModeEnabled":{"title":"testModeEnabled","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"testModeEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"testModeEnabled"}],"url":"\/documentation\/openwrapsdk\/pobrequest\/testmodeenabled","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/testModeEnabled"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest/versionId":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"versionId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"!","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"versionId"}],"abstract":[],"title":"versionId","url":"\/documentation\/openwrapsdk\/pobrequest\/versionid","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/versionId"},"doc://com.pubmatic.openwrapsdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest/impressions":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"impressions"},{"kind":"text","text":": ["},{"text":"POBImpression","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBImpression"},{"text":"]!","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"impressions","kind":"identifier"}],"abstract":[],"title":"impressions","url":"\/documentation\/openwrapsdk\/pobrequest\/impressions","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/impressions"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest/publisherId":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"publisherId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"publisherId"}],"abstract":[{"type":"text","text":"Identifier of the publisher."}],"title":"publisherId","url":"\/documentation\/openwrapsdk\/pobrequest\/publisherid","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/publisherId"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"POBRequest","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobrequest","abstract":[{"type":"text","text":"Represents an ad request for the given impression\/s & profile."}],"title":"POBRequest","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest","kind":"symbol","navigatorTitle":[{"text":"POBRequest","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest/adFormat":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/adFormat","kind":"symbol","role":"symbol","title":"adFormat","url":"\/documentation\/openwrapsdk\/pobrequest\/adformat","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"adFormat"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"POBAdFormat","preciseIdentifier":"c:@E@POBAdFormat"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"POBRequest","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBRequest"}],"op":"replace"},{"value":[{"text":"POBRequest","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/adFormat","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/adServerURL","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/debug","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/impressions","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/networkTimeout","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/profileId","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/publisherId","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/returnAllBidStatus","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/testModeEnabled","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/versionId"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/init(publisherId:profileId:adFormat:impressions:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"POBRequest","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"returnAllBidStatus","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1returnAllBidStatus\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1returnAllBidStatus\/fragments","value":[{"text":"returnAllBidStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1init(publisherId:profileId:adFormat:impressions:)\/title","value":"initWithPublisherId:profileId:adFormat:impressions:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1init(publisherId:profileId:adFormat:impressions:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPublisherId:profileId:adFormat:impressions:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1debug\/title","value":"debug","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1debug\/fragments","value":[{"kind":"identifier","text":"debug"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1profileId\/title","value":"profileId"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1profileId\/fragments","op":"replace","value":[{"text":"profileId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1networkTimeout\/title","value":"networkTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1networkTimeout\/fragments","value":[{"text":"networkTimeout","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1adServerURL\/title","value":"adServerURL"},{"value":[{"kind":"identifier","text":"adServerURL"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1adServerURL\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1testModeEnabled\/title","value":"testModeEnabled"},{"value":[{"text":"testModeEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1testModeEnabled\/fragments"},{"value":"versionId","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1versionId\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1versionId\/fragments","value":[{"kind":"identifier","text":"versionId"}]},{"value":"impressions","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1impressions\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1impressions\/fragments","value":[{"kind":"identifier","text":"impressions"}],"op":"replace"},{"op":"replace","value":"publisherId","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1publisherId\/title"},{"value":[{"kind":"identifier","text":"publisherId"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1publisherId\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest\/title","value":"POBRequest"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBRequest"}]},{"value":"adFormat","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1adFormat\/title","op":"replace"},{"value":[{"text":"adFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1adFormat\/fragments"}]}]}