{"kind":"symbol","metadata":{"role":"symbol","title":"POBRewardedAdEventDelegate","roleHeading":"Protocol","externalID":"c:objc(pl)POBRewardedAdEventDelegate","navigatorTitle":[{"text":"POBRewardedAdEventDelegate","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBRewardedAdEventDelegate"}],"symbolKind":"protocol"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/adServerAdDidRecordImpression()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/adServerDidWin()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/bidsProvider()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didClickAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didDismissAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didExpireAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didPresentAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/failedToLoadWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/failedToShowWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/openWrapPartnerDidWin(forBid:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/presentationController()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/shouldReward(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/willLeaveApp()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/willPresentAd()"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"The rewarded custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBRewardedAdEventDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedadeventdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedadeventdelegate"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/bidsProvider()":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/bidsProvider()","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bidsProvider"},{"text":"() -> (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)POBBidsProvider","text":"POBBidsProvider","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/bidsprovider()","navigatorTitle":[{"kind":"identifier","text":"bidsProvider"}],"required":true,"title":"bidsProvider()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate","role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate","title":"POBRewardedAdEventDelegate","navigatorTitle":[{"text":"POBRewardedAdEventDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The rewarded custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBRewardedAdEventDelegate","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/failedToShowWithError(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/failedToShowWithError(_:)","role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/failedtoshowwitherror(_:)","title":"failedToShowWithError(_:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"failedToShowWithError:"}],"kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToShowWithError"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/didExpireAd()":{"role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"didExpireAd"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didExpireAd","kind":"identifier"},{"text":"()","kind":"text"}],"title":"didExpireAd()","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/didexpiread()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didExpireAd()","type":"topic","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/didClickAd()":{"abstract":[],"required":true,"navigatorTitle":[{"text":"didClickAd","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/didclickad()","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didClickAd()","type":"topic","title":"didClickAd()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didClickAd","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/willPresentAd()":{"role":"symbol","required":true,"navigatorTitle":[{"text":"willPresentAd","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"willPresentAd","kind":"identifier"},{"text":"()","kind":"text"}],"title":"willPresentAd()","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/willpresentad()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/willPresentAd()","type":"topic","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/adServerDidWin()":{"type":"topic","title":"adServerDidWin()","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/adserverdidwin()","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adServerDidWin","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"adServerDidWin","kind":"identifier"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/adServerDidWin()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/shouldReward(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"shouldReward:"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/shouldReward(_:)","title":"shouldReward(_:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldReward","kind":"identifier"},{"kind":"text","text":"("},{"text":"POBReward","preciseIdentifier":"c:objc(cs)POBReward","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/shouldreward(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/didDismissAd()":{"title":"didDismissAd()","required":true,"navigatorTitle":[{"kind":"identifier","text":"didDismissAd"}],"abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didDismissAd()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didDismissAd","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/diddismissad()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/openWrapPartnerDidWin(forBid:)":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"openWrapPartnerDidWinForBid:"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/openWrapPartnerDidWin(forBid:)","title":"openWrapPartnerDidWin(forBid:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"openWrapPartnerDidWin","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forBid"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/openwrappartnerdidwin(forbid:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/didPresentAd()":{"navigatorTitle":[{"kind":"identifier","text":"didPresentAd"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didPresentAd()","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/didpresentad()","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didPresentAd","kind":"identifier"},{"text":"()","kind":"text"}],"title":"didPresentAd()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/willLeaveApp()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willLeaveApp","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"willLeaveApp","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/willLeaveApp()","kind":"symbol","required":true,"role":"symbol","abstract":[],"type":"topic","title":"willLeaveApp()","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/willleaveapp()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/failedToLoadWithError(_:)":{"abstract":[],"required":true,"navigatorTitle":[{"text":"failedToLoadWithError:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/failedtoloadwitherror(_:)","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/failedToLoadWithError(_:)","type":"topic","title":"failedToLoadWithError(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadWithError","kind":"identifier"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/presentationController()":{"abstract":[],"required":true,"navigatorTitle":[{"text":"presentationController","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/presentationcontroller()","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/presentationController()","type":"topic","title":"presentationController()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentationController","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/adServerAdDidRecordImpression()":{"navigatorTitle":[{"text":"adServerAdDidRecordImpression","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/adserveraddidrecordimpression()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/adServerAdDidRecordImpression()","required":true,"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adServerAdDidRecordImpression"},{"text":"()","kind":"text"}],"title":"adServerAdDidRecordImpression()","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"POBRewardedAdEventDelegate"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"text":"POBRewardedAdEventDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"POBRewardedAdEventDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/adServerAdDidRecordImpression()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/adServerDidWin()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/bidsProvider()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didClickAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didDismissAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didExpireAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didPresentAd()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/failedToLoadWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/failedToShowWithError(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/openWrapPartnerDidWin(forBid:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/presentationController()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/shouldReward(_:)","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/willLeaveApp()","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/willPresentAd()"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"POBRewardedAdEventDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1bidsProvider()\/title","value":"bidsProvider"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bidsProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1bidsProvider()\/fragments"},{"value":"POBRewardedAdEventDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate\/fragments","value":[{"text":"POBRewardedAdEventDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1failedToShowWithError(_:)\/title","value":"failedToShowWithError:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"failedToShowWithError:"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1failedToShowWithError(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1didExpireAd()\/title","op":"replace","value":"didExpireAd"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1didExpireAd()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didExpireAd"}],"op":"replace"},{"value":"didClickAd","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1didClickAd()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1didClickAd()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didClickAd"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1willPresentAd()\/title","value":"willPresentAd","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1willPresentAd()\/fragments","value":[{"kind":"text","text":"- "},{"text":"willPresentAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1adServerDidWin()\/title","value":"adServerDidWin","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1adServerDidWin()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adServerDidWin","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"shouldReward:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1shouldReward(_:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1shouldReward(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"shouldReward:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1didDismissAd()\/title","op":"replace","value":"didDismissAd"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1didDismissAd()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didDismissAd"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1openWrapPartnerDidWin(forBid:)\/title","value":"openWrapPartnerDidWinForBid:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"openWrapPartnerDidWinForBid:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1openWrapPartnerDidWin(forBid:)\/fragments","op":"replace"},{"value":"didPresentAd","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1didPresentAd()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"didPresentAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1didPresentAd()\/fragments"},{"value":"willLeaveApp","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1willLeaveApp()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willLeaveApp"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1willLeaveApp()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1failedToLoadWithError(_:)\/title","value":"failedToLoadWithError:","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1failedToLoadWithError(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"failedToLoadWithError:","kind":"identifier"}]},{"value":"presentationController","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1presentationController()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1presentationController()\/fragments","value":[{"kind":"text","text":"- "},{"text":"presentationController","kind":"identifier"}]},{"op":"replace","value":"adServerAdDidRecordImpression","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1adServerAdDidRecordImpression()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adServerAdDidRecordImpression"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1adServerAdDidRecordImpression()\/fragments","op":"replace"}]}]}