{"kind":"symbol","metadata":{"role":"symbol","title":"POBSignalGenerator","roleHeading":"Class","externalID":"c:objc(cs)POBSignalGenerator","navigatorTitle":[{"kind":"identifier","text":"POBSignalGenerator"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBSignalGenerator"}],"symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalGenerator\/generateSignal(for:andConfig:)"],"title":"Type Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBSignalGenerator"}],"languages":["swift"]}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"]}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobsignalgenerator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobsignalgenerator"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalGenerator"},"references":{"doc://com.pubmatic.openwrapsdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSignalGenerator/generateSignal(for:andConfig:)":{"navigatorTitle":[{"text":"generateSignalForBiddingHost:andConfig:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobsignalgenerator\/generatesignal(for:andconfig:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generateSignal"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"POBSDKBiddingHost","preciseIdentifier":"c:@E@POBSDKBiddingHost","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"andConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBSignalConfig","text":"POBSignalConfig"},{"text":"!) -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalGenerator\/generateSignal(for:andConfig:)","type":"topic","kind":"symbol","title":"generateSignal(for:andConfig:)","role":"symbol"},"doc://com.pubmatic.openwrapsdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSignalGenerator":{"navigatorTitle":[{"text":"POBSignalGenerator","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobsignalgenerator","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"POBSignalGenerator","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalGenerator","type":"topic","title":"POBSignalGenerator","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"POBSignalGenerator"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBSignalGenerator"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"POBSignalGenerator"}]},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalGenerator\/generateSignal(for:andConfig:)"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"POBSignalGenerator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalGenerator~1generateSignal(for:andConfig:)\/title","value":"generateSignalForBiddingHost:andConfig:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalGenerator~1generateSignal(for:andConfig:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"generateSignalForBiddingHost:andConfig:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalGenerator\/title","value":"POBSignalGenerator"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalGenerator\/fragments","value":[{"text":"POBSignalGenerator","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}