{"sections":[],"abstract":[{"type":"text","text":"Indicates bidding host for S2S bidders"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/ALMAX","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/unknown"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBSDKBiddingHost","kind":"identifier"}],"externalID":"c:@E@POBSDKBiddingHost","navigatorTitle":[{"text":"POBSDKBiddingHost","kind":"identifier"}],"symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"OpenWrapSDK"}],"title":"POBSDKBiddingHost","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBSDKBiddingHost","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobsdkbiddinghost"]},{"paths":["\/documentation\/openwrapsdk\/pobsdkbiddinghost"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKBiddingHost/init(rawValue:)":{"title":"init(rawValue:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/init(rawValue:)","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobsdkbiddinghost\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]},"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","title":"Swift.RawRepresentable"},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","title":"Swift.Sendable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKBiddingHost/unknown":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"navigatorTitle":[{"kind":"identifier","text":"POBSDKBiddingHostUnknown"}],"url":"\/documentation\/openwrapsdk\/pobsdkbiddinghost\/unknown","title":"POBSDKBiddingHost.unknown","type":"topic","kind":"symbol","abstract":[{"text":"Bidding host unknown. Default value","type":"text"}],"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKBiddingHost/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobsdkbiddinghost\/rawrepresentable-implementations","role":"collectionGroup"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKBiddingHost/ALMAX":{"navigatorTitle":[{"text":"POBSDKBiddingHostALMAX","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobsdkbiddinghost\/almax","abstract":[{"text":"Bidding host AppLovin MAX","type":"text"}],"kind":"symbol","title":"POBSDKBiddingHost.ALMAX","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ALMAX","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/ALMAX","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKBiddingHost":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost","navigatorTitle":[{"text":"POBSDKBiddingHost","kind":"identifier"}],"title":"POBSDKBiddingHost","type":"topic","abstract":[{"text":"Indicates bidding host for S2S bidders","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobsdkbiddinghost","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBSDKBiddingHost","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKBiddingHost/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/openwrapsdk\/pobsdkbiddinghost\/equatable-implementations","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"POBSDKBiddingHost","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"text":"POBSDKBiddingHost","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"POBSDKBiddingHost","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/ALMAX","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/unknown"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBSDKBiddingHost","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost~1unknown\/title","op":"replace","value":"POBSDKBiddingHostUnknown"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost~1unknown\/fragments","op":"replace","value":[{"text":"POBSDKBiddingHostUnknown","kind":"identifier"}]},{"value":"POBSDKBiddingHostALMAX","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost~1ALMAX\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost~1ALMAX\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBSDKBiddingHostALMAX"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost\/title","value":"POBSDKBiddingHost"},{"value":[{"text":"POBSDKBiddingHost","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}