{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig\/init(adFormat:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig\/adFormat","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig\/extras"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH"],"type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBSignalConfig"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This configuration includes the ad format and optional extras encapsulated within a Bundle."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig"},"metadata":{"title":"POBSignalConfig","modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Class","navigatorTitle":[{"text":"POBSignalConfig","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBSignalConfig"}],"role":"symbol","externalID":"c:objc(cs)POBSignalConfig","symbolKind":"class"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobsignalconfig"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobsignalconfig"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pubmatic.openwrapsdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","title":"Swift.Hashable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSignalConfig/extras":{"type":"topic","abstract":[],"title":"extras","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig\/extras","navigatorTitle":[{"text":"extras","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extras","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"url":"\/documentation\/openwrapsdk\/pobsignalconfig\/extras","role":"symbol"},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSignalConfig/adFormat":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig\/adFormat","abstract":[],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobsignalconfig\/adformat","navigatorTitle":[{"text":"adFormat","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"adFormat","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"POBAdFormat","preciseIdentifier":"c:@E@POBAdFormat"}],"role":"symbol","title":"adFormat","type":"topic"},"doc://com.pubmatic.openwrapsdk/objc(cs)NSObject":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/s7CVarArgP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSignalConfig":{"navigatorTitle":[{"kind":"identifier","text":"POBSignalConfig"}],"url":"\/documentation\/openwrapsdk\/pobsignalconfig","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBSignalConfig","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig","type":"topic","title":"POBSignalConfig","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/SQ":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSignalConfig/init(adFormat:)":{"title":"init(adFormat:)","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig\/init(adFormat:)","navigatorTitle":[{"text":"initWithAdFormat:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"adFormat","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@POBAdFormat","kind":"typeIdentifier","text":"POBAdFormat"},{"text":")","kind":"text"}],"url":"\/documentation\/openwrapsdk\/pobsignalconfig\/init(adformat:)","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"POBSignalConfig","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"POBSignalConfig","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"POBSignalConfig"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig\/adFormat","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig\/extras"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig\/init(adFormat:)"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(cs)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBSignalConfig","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"extras","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig~1extras\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig~1extras\/fragments","value":[{"kind":"identifier","text":"extras"}],"op":"replace"},{"op":"replace","value":"adFormat","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig~1adFormat\/title"},{"op":"replace","value":[{"text":"adFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig~1adFormat\/fragments"},{"value":"POBSignalConfig","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig\/fragments","op":"replace","value":[{"text":"POBSignalConfig","kind":"identifier"}]},{"value":"initWithAdFormat:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig~1init(adFormat:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig~1init(adFormat:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAdFormat:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}