{"sections":[],"abstract":[{"type":"text","text":"Video rendering delegate, It is used to provide video events from video renderer"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRenderingDelegate\/videoRendererDidOccur(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRenderingDelegate"},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBVideoRenderingDelegate"}],"externalID":"c:objc(pl)POBVideoRenderingDelegate","navigatorTitle":[{"text":"POBVideoRenderingDelegate","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","title":"POBVideoRenderingDelegate","role":"symbol","modules":[{"name":"OpenWrapSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBVideoRenderingDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"]}]}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobvideorenderingdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobvideorenderingdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoRenderingDelegate/videoRendererDidOccur(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRenderingDelegate\/videoRendererDidOccur(_:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoRendererDidOccur"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@POBVideoAdEvent","kind":"typeIdentifier","text":"POBVideoAdEvent"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"videoRendererDidOccurAdEvent:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobvideorenderingdelegate\/videorendererdidoccur(_:)","type":"topic","title":"videoRendererDidOccur(_:)","abstract":[],"kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoRenderingDelegate":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBVideoRenderingDelegate"}],"url":"\/documentation\/openwrapsdk\/pobvideorenderingdelegate","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRenderingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBVideoRenderingDelegate","kind":"identifier"}],"title":"POBVideoRenderingDelegate","abstract":[{"text":"Video rendering delegate, It is used to provide video events from video renderer","type":"text"}]},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"op":"replace","value":"POBVideoRenderingDelegate","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"text":"POBVideoRenderingDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"POBVideoRenderingDelegate","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRenderingDelegate\/videoRendererDidOccur(_:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject"],"kind":"relationships"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBVideoRenderingDelegate"},{"kind":"text","text":" <"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRenderingDelegate~1videoRendererDidOccur(_:)\/title","value":"videoRendererDidOccurAdEvent:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoRendererDidOccurAdEvent:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRenderingDelegate~1videoRendererDidOccur(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRenderingDelegate\/title","value":"POBVideoRenderingDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRenderingDelegate\/fragments","value":[{"text":"POBVideoRenderingDelegate","kind":"identifier"}]}]}]}