{"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRendering\/setVideoDelegate(_:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobvideorendering"]},{"paths":["\/documentation\/openwrapsdk\/pobvideorendering"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerRendering"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBVideoRendering","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBannerRendering","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerRendering","text":"POBBannerRendering"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRendering","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBVideoRendering"}],"externalID":"c:objc(pl)POBVideoRendering","navigatorTitle":[{"kind":"identifier","text":"POBVideoRendering"}],"symbolKind":"protocol","roleHeading":"Protocol","title":"POBVideoRendering","role":"symbol","modules":[{"name":"OpenWrapSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Ad video rendering protocol, implement these methods to write custom ad renderer","type":"text"}],"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoRendering":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"POBVideoRendering","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobvideorendering","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRendering","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBVideoRendering"}],"title":"POBVideoRendering","abstract":[{"text":"Ad video rendering protocol, implement these methods to write custom ad renderer","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoRendering/setVideoDelegate(_:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setVideoDelegate:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobvideorendering\/setvideodelegate(_:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRendering\/setVideoDelegate(_:)","required":true,"title":"setVideoDelegate(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setVideoDelegate"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBVideoRenderingDelegate","text":"POBVideoRenderingDelegate"},{"kind":"text","text":")!)"}]},"doc://com.pubmatic.openwrapsdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/objc(pl)NSObject","type":"unresolvable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerRendering":{"abstract":[{"text":"Ad banner rendering protocol, implement these methods to write custom ad renderer","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBBannerRendering"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbannerrendering","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerRendering","type":"topic","title":"POBBannerRendering","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBBannerRendering"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","value":"POBVideoRendering","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBVideoRendering"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"POBVideoRendering","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRendering\/setVideoDelegate(_:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerRendering"],"title":"Inherits From","kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBVideoRendering"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerRendering","kind":"typeIdentifier","text":"POBBannerRendering","preciseIdentifier":"c:objc(pl)POBBannerRendering"},{"text":">","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRendering\/title","value":"POBVideoRendering"},{"op":"replace","value":[{"kind":"identifier","text":"POBVideoRendering"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRendering\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRendering~1setVideoDelegate(_:)\/title","value":"setVideoDelegate:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setVideoDelegate:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRendering~1setVideoDelegate(_:)\/fragments","op":"replace"},{"value":"POBBannerRendering","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerRendering\/title"},{"value":[{"text":"POBBannerRendering","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerRendering\/fragments","op":"replace"}]}]}