{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/interstitial","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/standalone"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/Equatable-Implementations","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobvideoplcmt"]},{"paths":["\/documentation\/openwrapsdk\/pobvideoplcmt"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Video ad plcmt type for placement with respect to main content. Refer ORTB 2.6-202303 spec.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBVideoPlcmt","kind":"identifier"}]}]}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBVideoPlcmt","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","externalID":"c:@E@POBVideoPlcmt","navigatorTitle":[{"kind":"identifier","text":"POBVideoPlcmt"}],"title":"POBVideoPlcmt","roleHeading":"Enumeration","symbolKind":"enum"},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/SQ","doc:\/\/com.pubmatic.openwrapsdk\/SH","doc:\/\/com.pubmatic.openwrapsdk\/SY","doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP"],"kind":"relationships"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoPlcmt/standalone":{"abstract":[{"text":"For In-Banner video ad placement","type":"text"}],"type":"topic","title":"POBVideoPlcmt.standalone","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/standalone","kind":"symbol","navigatorTitle":[{"text":"POBVideoPlcmtStandalone","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"standalone","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobvideoplcmt\/standalone","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoPlcmt/interstitial":{"type":"topic","abstract":[{"text":"For full screen video ad placement","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBVideoPlcmtInterstitial"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/interstitial","title":"POBVideoPlcmt.interstitial","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitial"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobvideoplcmt\/interstitial"},"doc://com.pubmatic.openwrapsdk/SY":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.pubmatic.openwrapsdk/s8SendableP":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoPlcmt":{"abstract":[{"type":"text","text":"Video ad plcmt type for placement with respect to main content. Refer ORTB 2.6-202303 spec."}],"navigatorTitle":[{"text":"POBVideoPlcmt","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobvideoplcmt","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt","type":"topic","title":"POBVideoPlcmt","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBVideoPlcmt","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoPlcmt/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","title":"init(rawValue:)","url":"\/documentation\/openwrapsdk\/pobvideoplcmt\/init(rawvalue:)","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoPlcmt/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/openwrapsdk\/pobvideoplcmt\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://com.pubmatic.openwrapsdk/SQ":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoPlcmt/Equatable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/openwrapsdk\/pobvideoplcmt\/equatable-implementations"},"doc://com.pubmatic.openwrapsdk/SH":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"POBVideoPlcmt"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"POBVideoPlcmt"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"POBVideoPlcmt"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/interstitial","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/standalone"],"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBVideoPlcmt","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt~1standalone\/title","value":"POBVideoPlcmtStandalone"},{"value":[{"text":"POBVideoPlcmtStandalone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt~1standalone\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt~1interstitial\/title","value":"POBVideoPlcmtInterstitial","op":"replace"},{"value":[{"text":"POBVideoPlcmtInterstitial","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt~1interstitial\/fragments"},{"value":"POBVideoPlcmt","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt\/fragments","op":"replace","value":[{"text":"POBVideoPlcmt","kind":"identifier"}]}]}]}