{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBUserInfo\/addDataProvider(_:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBUserInfo"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobuserinfo\/adddataprovider(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobuserinfo\/adddataprovider(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","modules":[{"name":"OpenWrapSDK"}],"navigatorTitle":[{"text":"addDataProvider:","kind":"identifier"}],"title":"addDataProvider(_:)","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addDataProvider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBDataProvider","text":"POBDataProvider"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)POBUserInfo(im)addDataProvider:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addDataProvider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dataProvider","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider","kind":"typeIdentifier","text":"POBDataProvider","preciseIdentifier":"c:objc(cs)POBDataProvider"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDataProvider":{"role":"symbol","title":"POBDataProvider","url":"\/documentation\/openwrapsdk\/pobdataprovider","navigatorTitle":[{"text":"POBDataProvider","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBDataProvider","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBUserInfo":{"title":"POBUserInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBUserInfo"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobuserinfo","navigatorTitle":[{"text":"POBUserInfo","kind":"identifier"}],"abstract":[{"text":"Provides setters to pass user information","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBUserInfo"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBUserInfo/addDataProvider(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBUserInfo\/addDataProvider(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/pobuserinfo\/adddataprovider(_:)","title":"addDataProvider(_:)","abstract":[],"navigatorTitle":[{"text":"addDataProvider:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDataProvider"},{"kind":"text","text":"("},{"text":"POBDataProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBDataProvider"},{"kind":"text","text":")"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"addDataProvider:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addDataProvider:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"addDataProvider:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider","kind":"typeIdentifier","text":"POBDataProvider","preciseIdentifier":"c:objc(cs)POBDataProvider"},{"text":" *) ","kind":"text"},{"text":"dataProvider","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDataProvider\/title","value":"POBDataProvider"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDataProvider\/fragments","op":"replace","value":[{"text":"POBDataProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBUserInfo\/title","value":"POBUserInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBUserInfo\/fragments","value":[{"kind":"identifier","text":"POBUserInfo"}]},{"value":"addDataProvider:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBUserInfo~1addDataProvider(_:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBUserInfo~1addDataProvider(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addDataProvider:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}