{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBUserInfo\/dataProvider(withName:)"},"metadata":{"symbolKind":"method","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(cs)POBUserInfo(im)dataProviderWithName:","role":"symbol","title":"dataProvider(withName:)","navigatorTitle":[{"kind":"identifier","text":"dataProviderWithName:"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataProvider","kind":"identifier"},{"kind":"text","text":"("},{"text":"withName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBDataProvider","text":"POBDataProvider"},{"kind":"text","text":"?"}]},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBUserInfo"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataProvider"},{"text":"(","kind":"text"},{"text":"withName","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"POBDataProvider","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider","preciseIdentifier":"c:objc(cs)POBDataProvider"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobuserinfo\/dataprovider(withname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobuserinfo\/dataprovider(withname:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDataProvider":{"role":"symbol","title":"POBDataProvider","url":"\/documentation\/openwrapsdk\/pobdataprovider","navigatorTitle":[{"text":"POBDataProvider","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBDataProvider","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBUserInfo/dataProvider(withName:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBUserInfo\/dataProvider(withName:)","title":"dataProvider(withName:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataProvider"},{"text":"(","kind":"text"},{"text":"withName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"POBDataProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBDataProvider"},{"kind":"text","text":"?"}],"url":"\/documentation\/openwrapsdk\/pobuserinfo\/dataprovider(withname:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"dataProviderWithName:"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBUserInfo":{"title":"POBUserInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBUserInfo"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobuserinfo","navigatorTitle":[{"text":"POBUserInfo","kind":"identifier"}],"abstract":[{"text":"Provides setters to pass user information","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBUserInfo"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"dataProviderWithName:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"dataProviderWithName:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDataProvider","kind":"typeIdentifier","text":"POBDataProvider","preciseIdentifier":"c:objc(cs)POBDataProvider"},{"kind":"text","text":" *) "},{"text":"dataProviderWithName:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"name"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","value":"POBDataProvider","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDataProvider\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDataProvider\/fragments","value":[{"kind":"identifier","text":"POBDataProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBUserInfo~1dataProvider(withName:)\/title","op":"replace","value":"dataProviderWithName:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBUserInfo~1dataProvider(withName:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataProviderWithName:"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBUserInfo\/title","op":"replace","value":"POBUserInfo"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBUserInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBUserInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}