{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate"]]},"metadata":{"role":"symbol","modules":[{"name":"OpenWrapSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bidsProvider"},{"kind":"text","text":"() -> (any "},{"text":"POBBidsProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBidsProvider"},{"kind":"text","text":")?"}],"externalID":"c:objc(pl)POBRewardedAdEventDelegate(im)bidsProvider","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"bidsProvider"}],"roleHeading":"Instance Method","required":true,"title":"bidsProvider()"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bidsProvider","kind":"identifier"},{"text":"() -> (any ","kind":"text"},{"text":"POBBidsProvider","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidsProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBidsProvider"},{"kind":"text","text":")?"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/bidsProvider()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/bidsprovider()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/bidsprovider()"]}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/bidsProvider()":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/bidsProvider()","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bidsProvider"},{"text":"() -> (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)POBBidsProvider","text":"POBBidsProvider","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/bidsprovider()","navigatorTitle":[{"kind":"identifier","text":"bidsProvider"}],"required":true,"title":"bidsProvider()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate","role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate","title":"POBRewardedAdEventDelegate","navigatorTitle":[{"text":"POBRewardedAdEventDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The rewarded custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBRewardedAdEventDelegate","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidsProvider":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidsProvider"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"POBBidsProvider","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbidsprovider","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidsProvider","title":"POBBidsProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"bidsProvider"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bidsProvider"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id<POBBidsProvider>","preciseIdentifier":"c:Qoobjc(pl)POBBidsProvider"},{"text":") ","kind":"text"},{"kind":"identifier","text":"bidsProvider"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"bidsProvider","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1bidsProvider()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bidsProvider"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1bidsProvider()\/fragments","op":"replace"},{"value":"POBRewardedAdEventDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate\/title"},{"op":"replace","value":[{"text":"POBRewardedAdEventDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidsProvider\/title","value":"POBBidsProvider","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidsProvider\/fragments","op":"replace","value":[{"text":"POBBidsProvider","kind":"identifier"}]}]}]}