{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didExpireAd","kind":"identifier"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didExpireAd()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/didexpiread()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/didexpiread()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"OpenWrapSDK"}],"title":"didExpireAd()","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didExpireAd"},{"kind":"text","text":"()"}],"required":true,"navigatorTitle":[{"text":"didExpireAd","kind":"identifier"}],"externalID":"c:objc(pl)POBRewardedAdEventDelegate(im)didExpireAd","roleHeading":"Instance Method","role":"symbol"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/didExpireAd()":{"role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"didExpireAd"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didExpireAd","kind":"identifier"},{"text":"()","kind":"text"}],"title":"didExpireAd()","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/didexpiread()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didExpireAd()","type":"topic","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate","role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate","title":"POBRewardedAdEventDelegate","navigatorTitle":[{"text":"POBRewardedAdEventDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The rewarded custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBRewardedAdEventDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didExpireAd"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didExpireAd"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"didExpireAd","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1didExpireAd()\/title","op":"replace","value":"didExpireAd"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1didExpireAd()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didExpireAd","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"POBRewardedAdEventDelegate","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBRewardedAdEventDelegate"}]}]}]}