{"variants":[{"paths":["\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/didpresentad()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/didpresentad()"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didPresentAd()"},"metadata":{"modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","externalID":"c:objc(pl)POBRewardedAdEventDelegate(im)didPresentAd","navigatorTitle":[{"text":"didPresentAd","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPresentAd"},{"kind":"text","text":"()"}],"title":"didPresentAd()"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didPresentAd","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate","role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate","title":"POBRewardedAdEventDelegate","navigatorTitle":[{"text":"POBRewardedAdEventDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The rewarded custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBRewardedAdEventDelegate","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate/didPresentAd()":{"navigatorTitle":[{"kind":"identifier","text":"didPresentAd"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate\/didPresentAd()","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate\/didpresentad()","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didPresentAd","kind":"identifier"},{"text":"()","kind":"text"}],"title":"didPresentAd()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"didPresentAd","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didPresentAd","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didPresentAd","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"POBRewardedAdEventDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate\/fragments","value":[{"text":"POBRewardedAdEventDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1didPresentAd()\/title","op":"replace","value":"didPresentAd"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didPresentAd"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate~1didPresentAd()\/fragments"}]}]}