{"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativetemplateview\/titlelabel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativetemplateview\/titlelabel"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","title":"titleLabel","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier","text":"UILabel"},{"kind":"text","text":"!"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"titleLabel","kind":"identifier"}],"externalID":"c:objc(cs)POBNativeTemplateView(py)titleLabel"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleLabel"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/titleLabel"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateView":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"POBNativeTemplateView","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativetemplateview","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeTemplateView","kind":"identifier"}],"title":"POBNativeTemplateView","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateView/titleLabel":{"kind":"symbol","type":"topic","title":"titleLabel","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"url":"\/documentation\/openwrapsdk\/pobnativetemplateview\/titlelabel","role":"symbol","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateView\/titleLabel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"titleLabel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"titleLabel","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"titleLabel","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView\/title","value":"POBNativeTemplateView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView\/fragments","value":[{"kind":"identifier","text":"POBNativeTemplateView"}]},{"value":"titleLabel","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1titleLabel\/title"},{"value":[{"text":"titleLabel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateView~1titleLabel\/fragments","op":"replace"}]}]}