{"sections":[],"abstract":[{"type":"text","text":"Image-pixel tracking - URL provided will be inserted as a 1x1 pixel at the time of the event."}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod\/image"]}],"kind":"symbol","metadata":{"modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTrackingMethodImage"}],"externalID":"c:@E@POBNativeEventTrackingMethod@POBNativeEventTrackingMethodImage","title":"POBNativeEventTrackingMethod.image"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/image"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventTrackingMethod":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTrackingMethod"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeEventTrackingMethod"}],"title":"POBNativeEventTrackingMethod","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Native Event Tracking Methods"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod","url":"\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventTrackingMethod/image":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTrackingMethodImage"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"}],"title":"POBNativeEventTrackingMethod.image","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Image-pixel tracking - URL provided will be inserted as a 1x1 pixel at the time of the event."}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/image","url":"\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod\/image"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"POBNativeEventTrackingMethodImage","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBNativeEventTrackingMethodImage"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"POBNativeEventTrackingMethodImage","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod\/title","value":"POBNativeEventTrackingMethod","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod\/fragments","value":[{"kind":"identifier","text":"POBNativeEventTrackingMethod"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod~1image\/title","value":"POBNativeEventTrackingMethodImage","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod~1image\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBNativeEventTrackingMethodImage"}]}]}]}