{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod\/js"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod\/js"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JS","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/JS","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"JS","kind":"identifier"}],"title":"POBNativeEventTrackingMethod.JS","symbolKind":"case","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:@E@POBNativeEventTrackingMethod@POBNativeEventTrackingMethodJS","role":"symbol","navigatorTitle":[{"text":"POBNativeEventTrackingMethodJS","kind":"identifier"}],"roleHeading":"Case"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod"]]},"abstract":[{"text":"Javascript-based tracking - URL provided will be inserted as a js tag at the time of the event.","type":"text"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventTrackingMethod/JS":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTrackingMethodJS"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"JS"}],"title":"POBNativeEventTrackingMethod.JS","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Javascript-based tracking - URL provided will be inserted as a js tag at the time of the event."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod\/JS","type":"topic","url":"\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod\/js"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeEventTrackingMethod":{"navigatorTitle":[{"kind":"identifier","text":"POBNativeEventTrackingMethod"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeEventTrackingMethod"}],"title":"POBNativeEventTrackingMethod","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Native Event Tracking Methods"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeEventTrackingMethod","url":"\/documentation\/openwrapsdk\/pobnativeeventtrackingmethod"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"POBNativeEventTrackingMethodJS"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"POBNativeEventTrackingMethodJS","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"POBNativeEventTrackingMethodJS","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"POBNativeEventTrackingMethodJS","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod~1JS\/title"},{"value":[{"kind":"identifier","text":"POBNativeEventTrackingMethodJS"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod~1JS\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod\/title","op":"replace","value":"POBNativeEventTrackingMethod"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeEventTrackingMethod\/fragments","op":"replace","value":[{"text":"POBNativeEventTrackingMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}