{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidRecordImpression()","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdidrecordimpression()"]},{"paths":["\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdidrecordimpression()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rendererDidRecordImpression","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rendererDidRecordImpression","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","externalID":"c:objc(pl)POBAdRendererDelegate(im)rendererDidRecordImpression","navigatorTitle":[{"kind":"identifier","text":"rendererDidRecordImpression"}],"title":"rendererDidRecordImpression()","roleHeading":"Instance Method","symbolKind":"method","required":true},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate":{"url":"\/documentation\/openwrapsdk\/pobadrendererdelegate","type":"topic","abstract":[{"text":"Ad banner rendering delegate, It is used to provide feedback events from custom renderer","type":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBAdRendererDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"POBAdRendererDelegate","kind":"identifier"}],"title":"POBAdRendererDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererDidRecordImpression()":{"abstract":[],"required":true,"navigatorTitle":[{"text":"rendererDidRecordImpression","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdidrecordimpression()","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidRecordImpression()","title":"rendererDidRecordImpression()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rendererDidRecordImpression"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"rendererDidRecordImpression","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rendererDidRecordImpression","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"rendererDidRecordImpression"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate\/title","value":"POBAdRendererDelegate"},{"value":[{"text":"POBAdRendererDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidRecordImpression()\/title","value":"rendererDidRecordImpression","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidRecordImpression()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"rendererDidRecordImpression","kind":"identifier"}]}]}]}