{"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rendererDidRenderAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"!, "},{"text":"for","kind":"externalParam"},{"kind":"text","text":": (any "},{"text":"POBAdDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBAdDescriptor"},{"text":")!)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rendererDidRenderAd:forDescriptor:"}],"required":true,"roleHeading":"Instance Method","title":"rendererDidRenderAd(_:for:)","role":"symbol","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(pl)POBAdRendererDelegate(im)rendererDidRenderAd:forDescriptor:"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidRenderAd(_:for:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rendererDidRenderAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"renderedAd"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":" ","kind":"text"},{"text":"ad","kind":"internalParam"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor","preciseIdentifier":"c:objc(pl)POBAdDescriptor","kind":"typeIdentifier","text":"POBAdDescriptor"},{"text":")!)","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdidrenderad(_:for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdidrenderad(_:for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate":{"url":"\/documentation\/openwrapsdk\/pobadrendererdelegate","type":"topic","abstract":[{"text":"Ad banner rendering delegate, It is used to provide feedback events from custom renderer","type":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBAdRendererDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"POBAdRendererDelegate","kind":"identifier"}],"title":"POBAdRendererDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/rendererDidRenderAd(_:for:)":{"navigatorTitle":[{"text":"rendererDidRenderAd:forDescriptor:","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/rendererdidrenderad(_:for:)","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/rendererDidRenderAd(_:for:)","type":"topic","title":"rendererDidRenderAd(_:for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rendererDidRenderAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"!, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"POBAdDescriptor","preciseIdentifier":"c:objc(pl)POBAdDescriptor","kind":"typeIdentifier"},{"kind":"text","text":")!)"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdDescriptor":{"url":"\/documentation\/openwrapsdk\/pobaddescriptor","type":"topic","title":"POBAdDescriptor","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBAdDescriptor"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor","role":"symbol","abstract":[{"type":"text","text":"Ad descriptor protocol, provided creative string through "},{"type":"codeVoice","code":"renderableContent"},{"text":". POBAdRendering protocol renders object which conforms to POBAdDescriptor protocol","type":"text"}],"navigatorTitle":[{"text":"POBAdDescriptor","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"rendererDidRenderAd:forDescriptor:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rendererDidRenderAd:forDescriptor:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"rendererDidRenderAd:"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"renderedAd","kind":"internalParam"},{"kind":"text","text":" "},{"text":"forDescriptor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<POBAdDescriptor>","preciseIdentifier":"c:Qoobjc(pl)POBAdDescriptor","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"ad"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate\/title","value":"POBAdRendererDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate\/fragments","value":[{"kind":"identifier","text":"POBAdRendererDelegate"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidRenderAd(_:for:)\/title","value":"rendererDidRenderAd:forDescriptor:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1rendererDidRenderAd(_:for:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rendererDidRenderAd:forDescriptor:","kind":"identifier"}]},{"value":"POBAdDescriptor","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor\/fragments","value":[{"text":"POBAdDescriptor","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}