{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/viewControllerForPresentingModal()"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewControllerForPresentingModal","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"!","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobadrendererdelegate\/viewcontrollerforpresentingmodal()"]},{"paths":["\/documentation\/openwrapsdk\/pobadrendererdelegate\/viewcontrollerforpresentingmodal()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewControllerForPresentingModal","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"!","kind":"text"}],"modules":[{"name":"OpenWrapSDK"}],"title":"viewControllerForPresentingModal()","navigatorTitle":[{"text":"viewControllerForPresentingModal","kind":"identifier"}],"symbolKind":"method","platforms":[{"beta":false,"deprecated":false,"name":"iOS","introducedAt":"2.0","unavailable":false}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(pl)POBAdRendererDelegate(im)viewControllerForPresentingModal","required":true},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate/viewControllerForPresentingModal()":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate\/viewControllerForPresentingModal()","abstract":[],"role":"symbol","navigatorTitle":[{"text":"viewControllerForPresentingModal","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobadrendererdelegate\/viewcontrollerforpresentingmodal()","title":"viewControllerForPresentingModal()","required":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewControllerForPresentingModal"},{"text":"() -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdRendererDelegate":{"url":"\/documentation\/openwrapsdk\/pobadrendererdelegate","type":"topic","abstract":[{"text":"Ad banner rendering delegate, It is used to provide feedback events from custom renderer","type":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdRendererDelegate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBAdRendererDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"POBAdRendererDelegate","kind":"identifier"}],"title":"POBAdRendererDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"viewControllerForPresentingModal","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewControllerForPresentingModal","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"viewControllerForPresentingModal"},{"text":";","kind":"text"}]}]}},{"value":"viewControllerForPresentingModal","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1viewControllerForPresentingModal()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewControllerForPresentingModal"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate~1viewControllerForPresentingModal()\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate\/title","value":"POBAdRendererDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdRendererDelegate\/fragments","value":[{"kind":"identifier","text":"POBAdRendererDelegate"}],"op":"replace"}]}]}