{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notRequired"}],"externalID":"c:@E@POBDSAComplianceStatus@POBDSAComplianceStatusNotRequired","modules":[{"name":"OpenWrapSDK"}],"symbolKind":"case","roleHeading":"Case","title":"POBDSAComplianceStatus.notRequired","role":"symbol","navigatorTitle":[{"text":"POBDSAComplianceStatusNotRequired","kind":"identifier"}]},"kind":"symbol","abstract":[{"type":"text","text":"Not required"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notRequired"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobdsacompliancestatus\/notrequired"]},{"paths":["\/documentation\/openwrapsdk\/pobdsacompliancestatus\/notrequired"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/notRequired","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus","url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBDSAComplianceStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBDSAComplianceStatus"}],"role":"symbol","title":"POBDSAComplianceStatus","abstract":[{"type":"text","text":"DSA (Digital Services Act) compliance requirement status."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus/notRequired":{"navigatorTitle":[{"kind":"identifier","text":"POBDSAComplianceStatusNotRequired"}],"url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus\/notrequired","abstract":[{"type":"text","text":"Not required"}],"kind":"symbol","title":"POBDSAComplianceStatus.notRequired","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notRequired","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/notRequired","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"POBDSAComplianceStatusNotRequired","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBDSAComplianceStatusNotRequired"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"POBDSAComplianceStatusNotRequired"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus\/title","op":"replace","value":"POBDSAComplianceStatus"},{"op":"replace","value":[{"text":"POBDSAComplianceStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus~1notRequired\/title","value":"POBDSAComplianceStatusNotRequired","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus~1notRequired\/fragments","op":"replace","value":[{"text":"POBDSAComplianceStatusNotRequired","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}