{"sections":[],"metadata":{"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"case","title":"POBDSAComplianceStatus.requiredPubOnlinePlatform","role":"symbol","navigatorTitle":[{"text":"POBDSAComplianceStatusRequiredPubOnlinePlatform","kind":"identifier"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"requiredPubOnlinePlatform","kind":"identifier"}],"externalID":"c:@E@POBDSAComplianceStatus@POBDSAComplianceStatusRequiredPubOnlinePlatform"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobdsacompliancestatus\/requiredpubonlineplatform"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobdsacompliancestatus\/requiredpubonlineplatform"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredPubOnlinePlatform","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/requiredPubOnlinePlatform","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Required, bid responses without DSA object will not be accepted, Publisher is an Online Platform"},{"text":" ","type":"text"},{"type":"text","text":"Only bid response with DSA info will be rendered."}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus","url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBDSAComplianceStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBDSAComplianceStatus"}],"role":"symbol","title":"POBDSAComplianceStatus","abstract":[{"type":"text","text":"DSA (Digital Services Act) compliance requirement status."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus/requiredPubOnlinePlatform":{"type":"topic","title":"POBDSAComplianceStatus.requiredPubOnlinePlatform","url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus\/requiredpubonlineplatform","role":"symbol","abstract":[{"text":"Required, bid responses without DSA object will not be accepted, Publisher is an Online Platform","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Only bid response with DSA info will be rendered."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"requiredPubOnlinePlatform","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBDSAComplianceStatusRequiredPubOnlinePlatform"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus\/requiredPubOnlinePlatform"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"POBDSAComplianceStatusRequiredPubOnlinePlatform"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"POBDSAComplianceStatusRequiredPubOnlinePlatform","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"POBDSAComplianceStatusRequiredPubOnlinePlatform"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus\/title","value":"POBDSAComplianceStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus\/fragments","value":[{"kind":"identifier","text":"POBDSAComplianceStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus~1requiredPubOnlinePlatform\/title","value":"POBDSAComplianceStatusRequiredPubOnlinePlatform"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus~1requiredPubOnlinePlatform\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBDSAComplianceStatusRequiredPubOnlinePlatform"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}