{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbannereventdelegate\/didclickad()"]},{"paths":["\/documentation\/openwrapsdk\/pobbannereventdelegate\/didclickad()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didClickAd","kind":"identifier"},{"kind":"text","text":"()"}],"required":true,"externalID":"c:objc(pl)POBBannerEventDelegate(im)didClickAd","navigatorTitle":[{"text":"didClickAd","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","title":"didClickAd()","role":"symbol","modules":[{"name":"OpenWrapSDK"}]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didClickAd"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate\/didClickAd()"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEventDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerEventDelegate"}],"type":"topic","role":"symbol","abstract":[{"text":"The banner custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK.","type":"text"}],"navigatorTitle":[{"text":"POBBannerEventDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannereventdelegate","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate","title":"POBBannerEventDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEventDelegate/didClickAd()":{"abstract":[],"required":true,"navigatorTitle":[{"text":"didClickAd","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannereventdelegate\/didclickad()","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate\/didClickAd()","title":"didClickAd()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didClickAd"},{"kind":"text","text":"()"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didClickAd"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didClickAd","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didClickAd"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate\/title","value":"POBBannerEventDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"POBBannerEventDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate\/fragments"},{"op":"replace","value":"didClickAd","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate~1didClickAd()\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate~1didClickAd()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didClickAd","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}