{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failedWithError"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbannereventdelegate\/failedwitherror(_:)"]},{"paths":["\/documentation\/openwrapsdk\/pobbannereventdelegate\/failedwitherror(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate\/failedWithError(_:)","interfaceLanguage":"swift"},"metadata":{"required":true,"roleHeading":"Instance Method","title":"failedWithError(_:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"failedWithError","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"failedWithError:","kind":"identifier"}],"externalID":"c:objc(pl)POBBannerEventDelegate(im)failedWithError:"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEventDelegate/failedWithError(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedWithError","kind":"identifier"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"failedWithError:"}],"url":"\/documentation\/openwrapsdk\/pobbannereventdelegate\/failedwitherror(_:)","kind":"symbol","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate\/failedWithError(_:)","title":"failedWithError(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEventDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerEventDelegate"}],"type":"topic","role":"symbol","abstract":[{"text":"The banner custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK.","type":"text"}],"navigatorTitle":[{"text":"POBBannerEventDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannereventdelegate","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate","title":"POBBannerEventDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"failedWithError:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"failedWithError:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"failedWithError:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate~1failedWithError(_:)\/title","value":"failedWithError:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"failedWithError:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate~1failedWithError(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate\/title","value":"POBBannerEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate\/fragments","value":[{"kind":"identifier","text":"POBBannerEventDelegate"}]}]}]}