{"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate\/openWrapPartnerDidWin(forBid:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"openWrapPartnerDidWinForBid:"}],"symbolKind":"method","modules":[{"name":"OpenWrapSDK"}],"title":"openWrapPartnerDidWin(forBid:)","roleHeading":"Instance Method","externalID":"c:objc(pl)POBBannerEventDelegate(im)openWrapPartnerDidWinForBid:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openWrapPartnerDidWin","kind":"identifier"},{"kind":"text","text":"("},{"text":"forBid","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openWrapPartnerDidWin","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forBid"},{"text":" ","kind":"text"},{"text":"bidId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobbannereventdelegate\/openwrappartnerdidwin(forbid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobbannereventdelegate\/openwrappartnerdidwin(forbid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEventDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerEventDelegate"}],"type":"topic","role":"symbol","abstract":[{"text":"The banner custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK.","type":"text"}],"navigatorTitle":[{"text":"POBBannerEventDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannereventdelegate","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate","title":"POBBannerEventDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEventDelegate/openWrapPartnerDidWin(forBid:)":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"openWrapPartnerDidWinForBid:","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate\/openWrapPartnerDidWin(forBid:)","title":"openWrapPartnerDidWin(forBid:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"openWrapPartnerDidWin","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forBid"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbannereventdelegate\/openwrappartnerdidwin(forbid:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"openWrapPartnerDidWinForBid:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"openWrapPartnerDidWinForBid:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"openWrapPartnerDidWinForBid:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"bidId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"POBBannerEventDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBBannerEventDelegate"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate~1openWrapPartnerDidWin(forBid:)\/title","op":"replace","value":"openWrapPartnerDidWinForBid:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate~1openWrapPartnerDidWin(forBid:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"openWrapPartnerDidWinForBid:","kind":"identifier"}]}]}]}