{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ipAddress","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"text":"Location is determined from IP address","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Case","title":"POBLocSource.ipAddress","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ipAddress"}],"modules":[{"name":"OpenWrapSDK"}],"navigatorTitle":[{"kind":"identifier","text":"POBLocSourceIPAddress"}],"externalID":"c:@E@POBLocSource@POBLocSourceIPAddress","symbolKind":"case","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/poblocsource\/ipaddress"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/poblocsource\/ipaddress"]}],"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/ipAddress","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLocSource":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBLocSource"}],"abstract":[{"type":"text","text":"Location source"}],"title":"POBLocSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBLocSource","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource","url":"\/documentation\/openwrapsdk\/poblocsource"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLocSource/ipAddress":{"title":"POBLocSource.ipAddress","abstract":[{"text":"Location is determined from IP address","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ipAddress"}],"navigatorTitle":[{"text":"POBLocSourceIPAddress","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/poblocsource\/ipaddress","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/ipAddress"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"POBLocSourceIPAddress"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"POBLocSourceIPAddress","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"POBLocSourceIPAddress","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"POBLocSource","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource\/title"},{"value":[{"kind":"identifier","text":"POBLocSource"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource~1ipAddress\/title","value":"POBLocSourceIPAddress","op":"replace"},{"value":[{"text":"POBLocSourceIPAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource~1ipAddress\/fragments","op":"replace"}]}]}