{"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/poblocsource\/userprovided"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/poblocsource\/userprovided"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userProvided"}]}]}],"abstract":[{"text":"Location is provided by user","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userProvided"}],"externalID":"c:@E@POBLocSource@POBLocSourceUserProvided","navigatorTitle":[{"text":"POBLocSourceUserProvided","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","title":"POBLocSource.userProvided","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/userProvided"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLocSource":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBLocSource"}],"abstract":[{"type":"text","text":"Location source"}],"title":"POBLocSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBLocSource","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource","url":"\/documentation\/openwrapsdk\/poblocsource"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBLocSource/userProvided":{"type":"topic","abstract":[{"type":"text","text":"Location is provided by user"}],"navigatorTitle":[{"text":"POBLocSourceUserProvided","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBLocSource\/userProvided","title":"POBLocSource.userProvided","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userProvided","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/poblocsource\/userprovided"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"POBLocSourceUserProvided","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"POBLocSourceUserProvided","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"POBLocSourceUserProvided","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource\/title","value":"POBLocSource"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource\/fragments","value":[{"text":"POBLocSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource~1userProvided\/title","value":"POBLocSourceUserProvided","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBLocSource~1userProvided\/fragments","value":[{"text":"POBLocSourceUserProvided","kind":"identifier"}]}]}]}