{"sections":[],"metadata":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"bidder:didFailToReceiveBidsWithError:"}],"symbolKind":"method","modules":[{"name":"OpenWrapSDK"}],"title":"bidder(_:didFailToReceiveBidsWithError:)","roleHeading":"Instance Method","externalID":"c:objc(pl)POBBidderDelegate(im)bidder:didFailToReceiveBidsWithError:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bidder"},{"text":"(any ","kind":"text"},{"text":"POBBidding","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBidding"},{"text":", ","kind":"text"},{"text":"didFailToReceiveBidsWithError","kind":"externalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?)"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbidderdelegate\/bidder(_:didfailtoreceivebidswitherror:)"]},{"paths":["\/documentation\/openwrapsdk\/pobbidderdelegate\/bidder(_:didfailtoreceivebidswitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidderDelegate"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bidder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"bidder"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"POBBidding","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding","preciseIdentifier":"c:objc(pl)POBBidding"},{"text":", ","kind":"text"},{"text":"didFailToReceiveBidsWithError","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?)","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidderDelegate\/bidder(_:didFailToReceiveBidsWithError:)"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidding":{"url":"\/documentation\/openwrapsdk\/pobbidding","role":"symbol","kind":"symbol","title":"POBBidding","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidding","navigatorTitle":[{"text":"POBBidding","kind":"identifier"}],"type":"topic","abstract":[{"text":"Ad bidding protocol, which lists methods to be implmented to add new bidder. which is responsible for getting bids from various bidders.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidding"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidderDelegate":{"navigatorTitle":[{"kind":"identifier","text":"POBBidderDelegate"}],"url":"\/documentation\/openwrapsdk\/pobbidderdelegate","abstract":[{"text":"Ad bidder delegate protocol, which lists methods to be implmented by bidder delegate receiver.","type":"text"}],"kind":"symbol","title":"POBBidderDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBBidderDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidderDelegate","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidderDelegate/bidder(_:didFailToReceiveBidsWithError:)":{"required":true,"url":"\/documentation\/openwrapsdk\/pobbidderdelegate\/bidder(_:didfailtoreceivebidswitherror:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"bidder:didFailToReceiveBidsWithError:"}],"kind":"symbol","title":"bidder(_:didFailToReceiveBidsWithError:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bidder"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"POBBidding","preciseIdentifier":"c:objc(pl)POBBidding"},{"kind":"text","text":", "},{"text":"didFailToReceiveBidsWithError","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidderDelegate\/bidder(_:didFailToReceiveBidsWithError:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"bidder:didFailToReceiveBidsWithError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bidder:didFailToReceiveBidsWithError:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"bidder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<POBBidding>","preciseIdentifier":"c:Qoobjc(pl)POBBidding","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"bidder"},{"kind":"text","text":" "},{"text":"didFailToReceiveBidsWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"POBBidding","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidding\/fragments","value":[{"text":"POBBidding","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidderDelegate\/title","value":"POBBidderDelegate"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidderDelegate\/fragments","op":"replace","value":[{"text":"POBBidderDelegate","kind":"identifier"}]},{"value":"bidder:didFailToReceiveBidsWithError:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidderDelegate~1bidder(_:didFailToReceiveBidsWithError:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidderDelegate~1bidder(_:didFailToReceiveBidsWithError:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bidder:didFailToReceiveBidsWithError:","kind":"identifier"}]}]}]}