{"abstract":[{"text":"Icon image to rendered in native Ad","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeImageAssetType"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeImageAssetType\/icon"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeimageassettype\/icon"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeimageassettype\/icon"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"icon"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"POBNativeImageAssetTypeIcon","kind":"identifier"}],"role":"symbol","title":"POBNativeImageAssetType.icon","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"icon","kind":"identifier"}],"externalID":"c:@E@POBNativeImageAssetType@POBNativeImageAssetTypeIcon","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeImageAssetType/icon":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBNativeImageAssetTypeIcon"}],"abstract":[{"type":"text","text":"Icon image to rendered in native Ad"}],"url":"\/documentation\/openwrapsdk\/pobnativeimageassettype\/icon","title":"POBNativeImageAssetType.icon","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"icon","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeImageAssetType\/icon"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeImageAssetType":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeImageAssetType","kind":"symbol","type":"topic","title":"POBNativeImageAssetType","navigatorTitle":[{"text":"POBNativeImageAssetType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeImageAssetType"}],"abstract":[{"type":"text","text":"Native Image Asset Type"}],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeimageassettype"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"POBNativeImageAssetTypeIcon"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBNativeImageAssetTypeIcon"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"POBNativeImageAssetTypeIcon"}]}]}},{"value":"POBNativeImageAssetTypeIcon","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeImageAssetType~1icon\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeImageAssetType~1icon\/fragments","op":"replace","value":[{"text":"POBNativeImageAssetTypeIcon","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeImageAssetType\/title","value":"POBNativeImageAssetType","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeImageAssetType\/fragments","value":[{"kind":"identifier","text":"POBNativeImageAssetType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}