{"metadata":{"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"case","navigatorTitle":[{"text":"POBNativeImageAssetTypeMain","kind":"identifier"}],"roleHeading":"Case","title":"POBNativeImageAssetType.main","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"main","kind":"identifier"}],"externalID":"c:@E@POBNativeImageAssetType@POBNativeImageAssetTypeMain"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"main","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeImageAssetType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeImageAssetType\/main"},"abstract":[{"type":"text","text":"Main image to rendered in native Ad"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeimageassettype\/main"]},{"paths":["\/documentation\/openwrapsdk\/pobnativeimageassettype\/main"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeImageAssetType":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeImageAssetType","kind":"symbol","type":"topic","title":"POBNativeImageAssetType","navigatorTitle":[{"text":"POBNativeImageAssetType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeImageAssetType"}],"abstract":[{"type":"text","text":"Native Image Asset Type"}],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeimageassettype"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeImageAssetType/main":{"url":"\/documentation\/openwrapsdk\/pobnativeimageassettype\/main","abstract":[{"text":"Main image to rendered in native Ad","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"POBNativeImageAssetTypeMain","kind":"identifier"}],"role":"symbol","title":"POBNativeImageAssetType.main","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeImageAssetType\/main","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"main","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"POBNativeImageAssetTypeMain","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"POBNativeImageAssetTypeMain","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"POBNativeImageAssetTypeMain"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"POBNativeImageAssetType","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeImageAssetType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"POBNativeImageAssetType"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeImageAssetType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeImageAssetType~1main\/title","value":"POBNativeImageAssetTypeMain","op":"replace"},{"value":[{"kind":"identifier","text":"POBNativeImageAssetTypeMain"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeImageAssetType~1main\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}