{"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidFailToRenderAdWithError(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialRendererDidFailToRenderAdWithError"},{"kind":"text","text":"((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")!)","kind":"text"}],"required":true,"externalID":"c:objc(pl)POBInterstitialRendererDelegate(im)interstitialRendererDidFailToRenderAdWithError:","navigatorTitle":[{"text":"interstitialRendererDidFailToRenderAdWithError:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"OpenWrapSDK"}],"title":"interstitialRendererDidFailToRenderAdWithError(_:)","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialRendererDidFailToRenderAdWithError"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": (any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidfailtorenderadwitherror(_:)"]},{"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidfailtorenderadwitherror(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBInterstitialRendererDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBInterstitialRendererDelegate"}],"type":"topic","abstract":[{"type":"text","text":"Ad interstitial rendering delegate, It is used to provide feedback events from custom renderer"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate","title":"POBInterstitialRendererDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/interstitialRendererDidFailToRenderAdWithError(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialRendererDidFailToRenderAdWithError"},{"text":"((any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")!)"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialRendererDidFailToRenderAdWithError:"}],"type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidfailtorenderadwitherror(_:)","required":true,"kind":"symbol","role":"symbol","title":"interstitialRendererDidFailToRenderAdWithError(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidFailToRenderAdWithError(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"interstitialRendererDidFailToRenderAdWithError:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"interstitialRendererDidFailToRenderAdWithError:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"interstitialRendererDidFailToRenderAdWithError:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"POBInterstitialRendererDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate\/fragments","op":"replace","value":[{"text":"POBInterstitialRendererDelegate","kind":"identifier"}]},{"value":"interstitialRendererDidFailToRenderAdWithError:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidFailToRenderAdWithError(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidFailToRenderAdWithError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"interstitialRendererDidFailToRenderAdWithError:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}