{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidUnloadMRAIDAd()"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidunloadmraidad()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidunloadmraidad()"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialRendererDidUnloadMRAIDAd"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"interstitialRendererDidUnloadMRAIDAd","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","externalID":"c:objc(pl)POBInterstitialRendererDelegate(im)interstitialRendererDidUnloadMRAIDAd","navigatorTitle":[{"text":"interstitialRendererDidUnloadMRAIDAd","kind":"identifier"}],"title":"interstitialRendererDidUnloadMRAIDAd()","roleHeading":"Instance Method","symbolKind":"method","required":true},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/interstitialRendererDidUnloadMRAIDAd()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialRendererDidUnloadMRAIDAd"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialRendererDidUnloadMRAIDAd"}],"type":"topic","url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidunloadmraidad()","abstract":[],"required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidUnloadMRAIDAd()","title":"interstitialRendererDidUnloadMRAIDAd()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBInterstitialRendererDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBInterstitialRendererDelegate"}],"type":"topic","abstract":[{"type":"text","text":"Ad interstitial rendering delegate, It is used to provide feedback events from custom renderer"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate","title":"POBInterstitialRendererDelegate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"interstitialRendererDidUnloadMRAIDAd","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"interstitialRendererDidUnloadMRAIDAd","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"interstitialRendererDidUnloadMRAIDAd"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidUnloadMRAIDAd()\/title","value":"interstitialRendererDidUnloadMRAIDAd"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidUnloadMRAIDAd()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interstitialRendererDidUnloadMRAIDAd"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate\/title","value":"POBInterstitialRendererDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate\/fragments","value":[{"text":"POBInterstitialRendererDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}