{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidRenderAd()"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidrenderad()"]},{"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidrenderad()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interstitialRendererDidRenderAd","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"interstitialRendererDidRenderAd","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"interstitialRendererDidRenderAd()","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialRendererDidRenderAd"},{"text":"()","kind":"text"}],"externalID":"c:objc(pl)POBInterstitialRendererDelegate(im)interstitialRendererDidRenderAd","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBInterstitialRendererDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBInterstitialRendererDelegate"}],"type":"topic","abstract":[{"type":"text","text":"Ad interstitial rendering delegate, It is used to provide feedback events from custom renderer"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate","title":"POBInterstitialRendererDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/interstitialRendererDidRenderAd()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialRendererDidRenderAd"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialRendererDidRenderAd"}],"type":"topic","url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/interstitialrendererdidrenderad()","abstract":[],"required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/interstitialRendererDidRenderAd()","title":"interstitialRendererDidRenderAd()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"interstitialRendererDidRenderAd"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"interstitialRendererDidRenderAd","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"interstitialRendererDidRenderAd"},{"text":";","kind":"text"}]}]}},{"value":"POBInterstitialRendererDelegate","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate\/fragments","value":[{"text":"POBInterstitialRendererDelegate","kind":"identifier"}]},{"op":"replace","value":"interstitialRendererDidRenderAd","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidRenderAd()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"interstitialRendererDidRenderAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1interstitialRendererDidRenderAd()\/fragments"}]}]}