{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewControllerForPresentingModal","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/viewcontrollerforpresentingmodal()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/viewcontrollerforpresentingmodal()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/viewControllerForPresentingModal()"},"metadata":{"required":true,"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewControllerForPresentingModal","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!"}],"modules":[{"name":"OpenWrapSDK"}],"platforms":[{"beta":false,"introducedAt":"2.0","deprecated":false,"name":"iOS","unavailable":false}],"title":"viewControllerForPresentingModal()","navigatorTitle":[{"text":"viewControllerForPresentingModal","kind":"identifier"}],"externalID":"c:objc(pl)POBInterstitialRendererDelegate(im)viewControllerForPresentingModal","symbolKind":"method","role":"symbol"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBInterstitialRendererDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBInterstitialRendererDelegate"}],"type":"topic","abstract":[{"type":"text","text":"Ad interstitial rendering delegate, It is used to provide feedback events from custom renderer"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate","title":"POBInterstitialRendererDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate/viewControllerForPresentingModal()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewControllerForPresentingModal"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"viewControllerForPresentingModal"}],"type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate\/viewcontrollerforpresentingmodal()","required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate\/viewControllerForPresentingModal()","title":"viewControllerForPresentingModal()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"viewControllerForPresentingModal","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewControllerForPresentingModal","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"viewControllerForPresentingModal"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"POBInterstitialRendererDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate\/title"},{"op":"replace","value":[{"text":"POBInterstitialRendererDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate\/fragments"},{"op":"replace","value":"viewControllerForPresentingModal","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1viewControllerForPresentingModal()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewControllerForPresentingModal","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate~1viewControllerForPresentingModal()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}