{"metadata":{"navigatorTitle":[{"text":"POBSDKBiddingHostALMAX","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"OpenWrapSDK"}],"title":"POBSDKBiddingHost.ALMAX","roleHeading":"Case","externalID":"c:@E@POBSDKBiddingHost@POBSDKBiddingHostALMAX","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ALMAX","kind":"identifier"}],"role":"symbol"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Bidding host AppLovin MAX"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/ALMAX"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ALMAX","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobsdkbiddinghost\/almax"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobsdkbiddinghost\/almax"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKBiddingHost/ALMAX":{"navigatorTitle":[{"text":"POBSDKBiddingHostALMAX","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobsdkbiddinghost\/almax","abstract":[{"text":"Bidding host AppLovin MAX","type":"text"}],"kind":"symbol","title":"POBSDKBiddingHost.ALMAX","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ALMAX","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/ALMAX","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKBiddingHost":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost","navigatorTitle":[{"text":"POBSDKBiddingHost","kind":"identifier"}],"title":"POBSDKBiddingHost","type":"topic","abstract":[{"text":"Indicates bidding host for S2S bidders","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobsdkbiddinghost","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBSDKBiddingHost","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"POBSDKBiddingHostALMAX"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBSDKBiddingHostALMAX"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"POBSDKBiddingHostALMAX"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost~1ALMAX\/title","value":"POBSDKBiddingHostALMAX","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost~1ALMAX\/fragments","value":[{"text":"POBSDKBiddingHostALMAX","kind":"identifier"}]},{"value":"POBSDKBiddingHost","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBSDKBiddingHost"}]}]}]}