{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/unknown","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"POBSDKBiddingHost.unknown","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:@E@POBSDKBiddingHost@POBSDKBiddingHostUnknown","navigatorTitle":[{"text":"POBSDKBiddingHostUnknown","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"symbolKind":"case","roleHeading":"Case","role":"symbol"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobsdkbiddinghost\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobsdkbiddinghost\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Bidding host unknown. Default value","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKBiddingHost":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost","navigatorTitle":[{"text":"POBSDKBiddingHost","kind":"identifier"}],"title":"POBSDKBiddingHost","type":"topic","abstract":[{"text":"Indicates bidding host for S2S bidders","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobsdkbiddinghost","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBSDKBiddingHost","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKBiddingHost/unknown":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost\/unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"navigatorTitle":[{"kind":"identifier","text":"POBSDKBiddingHostUnknown"}],"url":"\/documentation\/openwrapsdk\/pobsdkbiddinghost\/unknown","title":"POBSDKBiddingHost.unknown","type":"topic","kind":"symbol","abstract":[{"text":"Bidding host unknown. Default value","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"POBSDKBiddingHostUnknown"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBSDKBiddingHostUnknown"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"POBSDKBiddingHostUnknown"}]}],"kind":"declarations"}},{"op":"replace","value":"POBSDKBiddingHost","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost\/title"},{"value":[{"kind":"identifier","text":"POBSDKBiddingHost"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost\/fragments"},{"value":"POBSDKBiddingHostUnknown","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost~1unknown\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost~1unknown\/fragments","op":"replace","value":[{"text":"POBSDKBiddingHostUnknown","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}