{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adDidExpireAd","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/addidexpiread()"]},{"paths":["\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/addidexpiread()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/adDidExpireAd()"},"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"adDidExpireAd","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adDidExpireAd","kind":"identifier"},{"text":"()","kind":"text"}],"title":"adDidExpireAd()","required":true,"modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(pl)POBInterstitialEventDelegate(im)adDidExpireAd","roleHeading":"Instance Method"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate","title":"POBInterstitialEventDelegate","navigatorTitle":[{"kind":"identifier","text":"POBInterstitialEventDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBInterstitialEventDelegate"}],"role":"symbol","abstract":[{"type":"text","text":"The interstitial custom event delegate. It is used to inform ad server events back to the OpenWrap SDK"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate","kind":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/adDidExpireAd()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adDidExpireAd","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"adDidExpireAd","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/addidexpiread()","kind":"symbol","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/adDidExpireAd()","title":"adDidExpireAd()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"adDidExpireAd"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"adDidExpireAd","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"adDidExpireAd"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate\/title","op":"replace","value":"POBInterstitialEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate\/fragments","value":[{"text":"POBInterstitialEventDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1adDidExpireAd()\/title","op":"replace","value":"adDidExpireAd"},{"value":[{"kind":"text","text":"- "},{"text":"adDidExpireAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1adDidExpireAd()\/fragments","op":"replace"}]}]}