{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/adServerAdDidRecordImpression()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/adserveraddidrecordimpression()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/adserveraddidrecordimpression()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adServerAdDidRecordImpression","kind":"identifier"},{"kind":"text","text":"()"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adServerAdDidRecordImpression","kind":"identifier"},{"text":"()","kind":"text"}],"required":true,"externalID":"c:objc(pl)POBInterstitialEventDelegate(im)adServerAdDidRecordImpression","navigatorTitle":[{"kind":"identifier","text":"adServerAdDidRecordImpression"}],"symbolKind":"method","roleHeading":"Instance Method","title":"adServerAdDidRecordImpression()","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate","title":"POBInterstitialEventDelegate","navigatorTitle":[{"kind":"identifier","text":"POBInterstitialEventDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBInterstitialEventDelegate"}],"role":"symbol","abstract":[{"type":"text","text":"The interstitial custom event delegate. It is used to inform ad server events back to the OpenWrap SDK"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate","kind":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/adServerAdDidRecordImpression()":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/adserveraddidrecordimpression()","required":true,"kind":"symbol","title":"adServerAdDidRecordImpression()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/adServerAdDidRecordImpression()","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"adServerAdDidRecordImpression"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adServerAdDidRecordImpression"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"adServerAdDidRecordImpression"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adServerAdDidRecordImpression","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"adServerAdDidRecordImpression","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate\/title","value":"POBInterstitialEventDelegate"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate\/fragments","value":[{"text":"POBInterstitialEventDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1adServerAdDidRecordImpression()\/title","value":"adServerAdDidRecordImpression"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adServerAdDidRecordImpression"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1adServerAdDidRecordImpression()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}