{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/openWrapPartnerDidWin(forBid:)"},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openWrapPartnerDidWin"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forBid"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"title":"openWrapPartnerDidWin(forBid:)","roleHeading":"Instance Method","externalID":"c:objc(pl)POBInterstitialEventDelegate(im)openWrapPartnerDidWinForBid:","navigatorTitle":[{"text":"openWrapPartnerDidWinForBid:","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"required":true,"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/openwrappartnerdidwin(forbid:)"]},{"paths":["\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/openwrappartnerdidwin(forbid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openWrapPartnerDidWin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forBid"},{"text":" ","kind":"text"},{"text":"bidId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate","title":"POBInterstitialEventDelegate","navigatorTitle":[{"kind":"identifier","text":"POBInterstitialEventDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBInterstitialEventDelegate"}],"role":"symbol","abstract":[{"type":"text","text":"The interstitial custom event delegate. It is used to inform ad server events back to the OpenWrap SDK"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate","kind":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/openWrapPartnerDidWin(forBid:)":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/openwrappartnerdidwin(forbid:)","required":true,"kind":"symbol","title":"openWrapPartnerDidWin(forBid:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/openWrapPartnerDidWin(forBid:)","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"openWrapPartnerDidWinForBid:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"openWrapPartnerDidWin","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forBid"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"openWrapPartnerDidWinForBid:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"openWrapPartnerDidWinForBid:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"openWrapPartnerDidWinForBid:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"bidId","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate\/title","value":"POBInterstitialEventDelegate"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate\/fragments","op":"replace","value":[{"text":"POBInterstitialEventDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1openWrapPartnerDidWin(forBid:)\/title","op":"replace","value":"openWrapPartnerDidWinForBid:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openWrapPartnerDidWinForBid:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1openWrapPartnerDidWin(forBid:)\/fragments"}]}]}