{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"willPresentAd","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/willpresentad()"]},{"paths":["\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/willpresentad()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"willPresentAd","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"willPresentAd","kind":"identifier"},{"kind":"text","text":"()"}],"required":true,"modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(pl)POBInterstitialEventDelegate(im)willPresentAd","role":"symbol","title":"willPresentAd()"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/willPresentAd()"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate","title":"POBInterstitialEventDelegate","navigatorTitle":[{"kind":"identifier","text":"POBInterstitialEventDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBInterstitialEventDelegate"}],"role":"symbol","abstract":[{"type":"text","text":"The interstitial custom event delegate. It is used to inform ad server events back to the OpenWrap SDK"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate","kind":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEventDelegate/willPresentAd()":{"url":"\/documentation\/openwrapsdk\/pobinterstitialeventdelegate\/willpresentad()","required":true,"kind":"symbol","title":"willPresentAd()","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEventDelegate\/willPresentAd()","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"willPresentAd","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willPresentAd"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"willPresentAd","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willPresentAd"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"willPresentAd","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate\/title","value":"POBInterstitialEventDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate\/fragments","value":[{"kind":"identifier","text":"POBInterstitialEventDelegate"}],"op":"replace"},{"value":"willPresentAd","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1willPresentAd()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"willPresentAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEventDelegate~1willPresentAd()\/fragments"}]}]}