{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"productReviewSite","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Product reviews site primarily (which may sell product secondarily)"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/productReviewSite","interfaceLanguage":"swift"},"metadata":{"title":"POBNativeContextSubType.productReviewSite","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"productReviewSite"}],"modules":[{"name":"OpenWrapSDK"}],"externalID":"c:@E@POBNativeContextSubType@POBNativeContextSubTypeProductReviewSite","navigatorTitle":[{"kind":"identifier","text":"POBNativeContextSubTypeProductReviewSite"}],"roleHeading":"Case","role":"symbol"},"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativecontextsubtype\/productreviewsite"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativecontextsubtype\/productreviewsite"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/productReviewSite":{"kind":"symbol","type":"topic","title":"POBNativeContextSubType.productReviewSite","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"productReviewSite","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/productReviewSite","abstract":[{"type":"text","text":"Product reviews site primarily (which may sell product secondarily)"}],"url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/productreviewsite","navigatorTitle":[{"text":"POBNativeContextSubTypeProductReviewSite","kind":"identifier"}],"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType":{"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeContextSubType"}],"title":"POBNativeContextSubType","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType","type":"topic","abstract":[{"type":"text","text":"Next-level context in which the ad appears. Again this reflects the primary context, and does not imply no presence of other elements."}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeContextSubType"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"POBNativeContextSubTypeProductReviewSite","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"POBNativeContextSubTypeProductReviewSite","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"POBNativeContextSubTypeProductReviewSite","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1productReviewSite\/title","value":"POBNativeContextSubTypeProductReviewSite","op":"replace"},{"value":[{"text":"POBNativeContextSubTypeProductReviewSite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1productReviewSite\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType\/title","value":"POBNativeContextSubType"},{"value":[{"kind":"identifier","text":"POBNativeContextSubType"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}