{"sections":[],"abstract":[{"text":"Primarily video content","type":"text"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/video","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"}],"externalID":"c:@E@POBNativeContextSubType@POBNativeContextSubTypeVideo","navigatorTitle":[{"text":"POBNativeContextSubTypeVideo","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","title":"POBNativeContextSubType.video","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"video"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativecontextsubtype\/video"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativecontextsubtype\/video"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType/video":{"type":"topic","abstract":[{"text":"Primarily video content","type":"text"}],"navigatorTitle":[{"text":"POBNativeContextSubTypeVideo","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType\/video","title":"POBNativeContextSubType.video","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"video"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype\/video"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeContextSubType":{"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativecontextsubtype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeContextSubType"}],"title":"POBNativeContextSubType","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeContextSubType","type":"topic","abstract":[{"type":"text","text":"Next-level context in which the ad appears. Again this reflects the primary context, and does not imply no presence of other elements."}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeContextSubType"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"POBNativeContextSubTypeVideo","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBNativeContextSubTypeVideo","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"POBNativeContextSubTypeVideo","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1video\/title","value":"POBNativeContextSubTypeVideo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType~1video\/fragments","value":[{"text":"POBNativeContextSubTypeVideo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType\/title","op":"replace","value":"POBNativeContextSubType"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeContextSubType\/fragments","value":[{"text":"POBNativeContextSubType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}