{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobvideoplcmt\/interstitial"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobvideoplcmt\/interstitial"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/interstitial"},"kind":"symbol","metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"POBVideoPlcmtInterstitial"}],"role":"symbol","roleHeading":"Case","title":"POBVideoPlcmt.interstitial","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"interstitial","kind":"identifier"}],"externalID":"c:@E@POBVideoPlcmt@POBVideoPlcmtInterstitial","modules":[{"name":"OpenWrapSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt"]]},"abstract":[{"type":"text","text":"For full screen video ad placement"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitial"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoPlcmt":{"abstract":[{"type":"text","text":"Video ad plcmt type for placement with respect to main content. Refer ORTB 2.6-202303 spec."}],"navigatorTitle":[{"text":"POBVideoPlcmt","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobvideoplcmt","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt","type":"topic","title":"POBVideoPlcmt","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBVideoPlcmt","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoPlcmt/interstitial":{"type":"topic","abstract":[{"text":"For full screen video ad placement","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBVideoPlcmtInterstitial"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/interstitial","title":"POBVideoPlcmt.interstitial","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitial"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobvideoplcmt\/interstitial"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"POBVideoPlcmtInterstitial","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBVideoPlcmtInterstitial"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"POBVideoPlcmtInterstitial","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"POBVideoPlcmt","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt\/fragments","value":[{"kind":"identifier","text":"POBVideoPlcmt"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt~1interstitial\/title","value":"POBVideoPlcmtInterstitial"},{"value":[{"kind":"identifier","text":"POBVideoPlcmtInterstitial"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt~1interstitial\/fragments"}]}]}