{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt"]]},"abstract":[{"text":"For In-Banner video ad placement","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobvideoplcmt\/standalone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobvideoplcmt\/standalone"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"POBVideoPlcmt.standalone","modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"POBVideoPlcmtStandalone"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standalone","kind":"identifier"}],"role":"symbol","externalID":"c:@E@POBVideoPlcmt@POBVideoPlcmtStandalone","symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/standalone"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standalone","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoPlcmt/standalone":{"abstract":[{"text":"For In-Banner video ad placement","type":"text"}],"type":"topic","title":"POBVideoPlcmt.standalone","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt\/standalone","kind":"symbol","navigatorTitle":[{"text":"POBVideoPlcmtStandalone","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"standalone","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobvideoplcmt\/standalone","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoPlcmt":{"abstract":[{"type":"text","text":"Video ad plcmt type for placement with respect to main content. Refer ORTB 2.6-202303 spec."}],"navigatorTitle":[{"text":"POBVideoPlcmt","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobvideoplcmt","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoPlcmt","type":"topic","title":"POBVideoPlcmt","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBVideoPlcmt","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"POBVideoPlcmtStandalone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"POBVideoPlcmtStandalone"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"POBVideoPlcmtStandalone"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt~1standalone\/title","value":"POBVideoPlcmtStandalone"},{"op":"replace","value":[{"kind":"identifier","text":"POBVideoPlcmtStandalone"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt~1standalone\/fragments"},{"op":"replace","value":"POBVideoPlcmt","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoPlcmt\/fragments","value":[{"text":"POBVideoPlcmt","kind":"identifier"}]}]}]}