{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"MRAID_3","kind":"identifier"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"API MRAID-3"}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobapi\/mraid_3"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobapi\/mraid_3"]}],"sections":[],"metadata":{"title":"POBAPI.MRAID_3","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"MRAID_3","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"externalID":"c:@E@POBAPI@POBAPI_MRAID_3","navigatorTitle":[{"text":"POBAPI_MRAID_3","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/MRAID_3"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAPI/MRAID_3":{"title":"POBAPI.MRAID_3","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MRAID_3"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI\/MRAID_3","abstract":[{"type":"text","text":"API MRAID-3"}],"url":"\/documentation\/openwrapsdk\/pobapi\/mraid_3","navigatorTitle":[{"text":"POBAPI_MRAID_3","kind":"identifier"}],"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAPI":{"type":"topic","url":"\/documentation\/openwrapsdk\/pobapi","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBAPI"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBAPI"}],"title":"POBAPI","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAPI","abstract":[{"type":"text","text":"List of supported API frameworks for this impression. If an API is not"},{"text":" ","type":"text"},{"type":"text","text":"explicitly listed, it is assumed not to be supported."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"POBAPI_MRAID_3","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBAPI_MRAID_3"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"POBAPI_MRAID_3","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1MRAID_3\/title","value":"POBAPI_MRAID_3"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI~1MRAID_3\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBAPI_MRAID_3"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI\/title","op":"replace","value":"POBAPI"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAPI\/fragments","value":[{"kind":"identifier","text":"POBAPI"}],"op":"replace"}]}]}