{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitial(_:didFailToShowAdWithError:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"interstitial(_:didFailToShowAdWithError:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"interstitial:didFailToShowAdWithError:"}],"required":true,"roleHeading":"Instance Method","externalID":"c:objc(pl)POBInterstitialDelegate(im)interstitial:didFailToShowAdWithError:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitial","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailToShowAdWithError","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"modules":[{"name":"OpenWrapSDK"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitial(_:didfailtoshowadwitherror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitial(_:didfailtoshowadwitherror:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitial","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"interstitial","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailToShowAdWithError"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate":{"kind":"symbol","title":"POBInterstitialDelegate","role":"symbol","abstract":[{"type":"text","text":"Protocol for interaction with the POBInterstitial instance."},{"text":" ","type":"text"},{"type":"text","text":"All messages are guaranteed to occur on the main thread."}],"url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBInterstitialDelegate"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBInterstitial","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"POBInterstitial","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial","title":"POBInterstitial","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial","abstract":[{"text":"Displays Interstitial Ads.","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitial(_:didFailToShowAdWithError:)":{"role":"symbol","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitial","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailToShowAdWithError"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"interstitial(_:didFailToShowAdWithError:)","navigatorTitle":[{"kind":"identifier","text":"interstitial:didFailToShowAdWithError:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitial(_:didFailToShowAdWithError:)","url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitial(_:didfailtoshowadwitherror:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"interstitial:didFailToShowAdWithError:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"interstitial:didFailToShowAdWithError:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"interstitial:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"interstitial"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didFailToShowAdWithError:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"POBInterstitialDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate\/fragments","value":[{"text":"POBInterstitialDelegate","kind":"identifier"}]},{"op":"replace","value":"POBInterstitial","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/title"},{"value":[{"kind":"identifier","text":"POBInterstitial"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitial(_:didFailToShowAdWithError:)\/title","value":"interstitial:didFailToShowAdWithError:","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitial(_:didFailToShowAdWithError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"interstitial:didFailToShowAdWithError:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}