{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidRecordImpression(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialdidrecordimpression(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialdidrecordimpression(_:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialDidRecordImpression"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"interstitial","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"interstitial","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The POBInterstitial instance sending the message."}]}]}],"kind":"parameters"}],"metadata":{"required":true,"symbolKind":"method","title":"interstitialDidRecordImpression(_:)","modules":[{"name":"OpenWrapSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialDidRecordImpression"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"POBInterstitial","preciseIdentifier":"c:objc(cs)POBInterstitial"},{"kind":"text","text":")"}],"externalID":"c:objc(pl)POBInterstitialDelegate(im)interstitialDidRecordImpression:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"interstitialDidRecordImpression:"}],"roleHeading":"Instance Method"},"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate":{"kind":"symbol","title":"POBInterstitialDelegate","role":"symbol","abstract":[{"type":"text","text":"Protocol for interaction with the POBInterstitial instance."},{"text":" ","type":"text"},{"type":"text","text":"All messages are guaranteed to occur on the main thread."}],"url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBInterstitialDelegate"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitialDidRecordImpression(_:)":{"role":"symbol","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialDidRecordImpression","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"interstitialDidRecordImpression(_:)","navigatorTitle":[{"kind":"identifier","text":"interstitialDidRecordImpression:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidRecordImpression(_:)","url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialdidrecordimpression(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBInterstitial","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"POBInterstitial","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial","title":"POBInterstitial","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial","abstract":[{"text":"Displays Interstitial Ads.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"interstitialDidRecordImpression:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"interstitialDidRecordImpression:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"interstitialDidRecordImpression:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)POBInterstitial","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial","text":"POBInterstitial"},{"kind":"text","text":" *) "},{"text":"interstitial","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate\/title","value":"POBInterstitialDelegate"},{"value":[{"kind":"identifier","text":"POBInterstitialDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate\/fragments"},{"value":"interstitialDidRecordImpression:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidRecordImpression(_:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidRecordImpression(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"interstitialDidRecordImpression:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/title","value":"POBInterstitial","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/fragments","value":[{"kind":"identifier","text":"POBInterstitial"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}