{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"interstitialDidClickAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBInterstitial","preciseIdentifier":"c:objc(cs)POBInterstitial","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OpenWrapSDK"}],"navigatorTitle":[{"text":"interstitialDidClickAd:","kind":"identifier"}],"title":"interstitialDidClickAd(_:)","externalID":"c:objc(pl)POBInterstitialDelegate(im)interstitialDidClickAd:","symbolKind":"method","roleHeading":"Instance Method","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialdidclickad(_:)"]},{"paths":["\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialdidclickad(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialDidClickAd"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"interstitial","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidClickAd(_:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBInterstitial","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"POBInterstitial","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial","title":"POBInterstitial","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial","abstract":[{"text":"Displays Interstitial Ads.","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate":{"kind":"symbol","title":"POBInterstitialDelegate","role":"symbol","abstract":[{"type":"text","text":"Protocol for interaction with the POBInterstitial instance."},{"text":" ","type":"text"},{"type":"text","text":"All messages are guaranteed to occur on the main thread."}],"url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBInterstitialDelegate"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitialDidClickAd(_:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialDidClickAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBInterstitial","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBInterstitial"},{"text":")","kind":"text"}],"title":"interstitialDidClickAd(_:)","navigatorTitle":[{"kind":"identifier","text":"interstitialDidClickAd:"}],"abstract":[],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialdidclickad(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialDidClickAd(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"interstitialDidClickAd:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"interstitialDidClickAd:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"interstitialDidClickAd:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial"},{"kind":"text","text":" *) "},{"text":"interstitial","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/title","value":"POBInterstitial","op":"replace"},{"value":[{"kind":"identifier","text":"POBInterstitial"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate\/title","value":"POBInterstitialDelegate"},{"value":[{"text":"POBInterstitialDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidClickAd(_:)\/title","value":"interstitialDidClickAd:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialDidClickAd:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialDidClickAd(_:)\/fragments"}]}]}