{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialWillLeaveApplication(_:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"interstitialWillLeaveApplication(_:)","roleHeading":"Instance Method","externalID":"c:objc(pl)POBInterstitialDelegate(im)interstitialWillLeaveApplication:","navigatorTitle":[{"kind":"identifier","text":"interstitialWillLeaveApplication:"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialWillLeaveApplication"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interstitialWillLeaveApplication","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"interstitial","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"interstitial","content":[{"type":"paragraph","inlineContent":[{"text":"The POBInterstitial instance sending the message.","type":"text"}]}]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"landing page URL in the internal browser, use ‘interstitialDidClickAd:’","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"instead."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialwillleaveapplication(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialwillleaveapplication(_:)"]}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate":{"kind":"symbol","title":"POBInterstitialDelegate","role":"symbol","abstract":[{"type":"text","text":"Protocol for interaction with the POBInterstitial instance."},{"text":" ","type":"text"},{"type":"text","text":"All messages are guaranteed to occur on the main thread."}],"url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBInterstitialDelegate"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialDelegate/interstitialWillLeaveApplication(_:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialWillLeaveApplication","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"interstitialWillLeaveApplication(_:)","navigatorTitle":[{"kind":"identifier","text":"interstitialWillLeaveApplication:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialDelegate\/interstitialWillLeaveApplication(_:)","url":"\/documentation\/openwrapsdk\/pobinterstitialdelegate\/interstitialwillleaveapplication(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBInterstitial","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"POBInterstitial","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial","title":"POBInterstitial","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial","abstract":[{"text":"Displays Interstitial Ads.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"interstitialWillLeaveApplication:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interstitialWillLeaveApplication:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"interstitialWillLeaveApplication:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial","text":"POBInterstitial","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBInterstitial"},{"text":" *) ","kind":"text"},{"text":"interstitial","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate\/title","value":"POBInterstitialDelegate"},{"value":[{"text":"POBInterstitialDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialWillLeaveApplication(_:)\/title","op":"replace","value":"interstitialWillLeaveApplication:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialDelegate~1interstitialWillLeaveApplication(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialWillLeaveApplication:"}]},{"value":"POBInterstitial","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/title"},{"value":[{"kind":"identifier","text":"POBInterstitial"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}