{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"kind":"text","text":", "},{"text":"shouldReward","kind":"externalParam"},{"kind":"text","text":": "},{"text":"POBReward","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBReward"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)POBRewardedAdDelegate(im)rewardedAd:shouldReward:","navigatorTitle":[{"text":"rewardedAd:shouldReward:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","title":"rewardedAd(_:shouldReward:)","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAd"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rewardedAd"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"POBRewardedAd","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldReward"},{"kind":"text","text":" "},{"text":"reward","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward","preciseIdentifier":"c:objc(cs)POBReward","kind":"typeIdentifier","text":"POBReward"},{"text":")","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedad(_:shouldreward:)"]},{"paths":["\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedad(_:shouldreward:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAd(_:shouldReward:)"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate","navigatorTitle":[{"text":"POBRewardedAdDelegate","kind":"identifier"}],"title":"POBRewardedAdDelegate","type":"topic","abstract":[{"type":"text","text":"Protocol for interaction with the POBRewardedAd instance."}],"url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBRewardedAdDelegate"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAd":{"title":"POBRewardedAd","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","abstract":[{"type":"text","text":"Displays Rewarded Ads."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBRewardedAd"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedad","navigatorTitle":[{"text":"POBRewardedAd","kind":"identifier"}],"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBReward":{"title":"POBReward","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBReward","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobreward","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBReward"}],"abstract":[{"type":"text","text":"Holds the general information about Reward to be provided to user."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAd(_:shouldReward:)":{"navigatorTitle":[{"kind":"identifier","text":"rewardedAd:shouldReward:"}],"url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedad(_:shouldreward:)","abstract":[],"kind":"symbol","title":"rewardedAd(_:shouldReward:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"POBRewardedAd","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"text":", ","kind":"text"},{"text":"shouldReward","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"POBReward","preciseIdentifier":"c:objc(cs)POBReward"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAd(_:shouldReward:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"rewardedAd:shouldReward:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rewardedAd:shouldReward:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"rewardedAd:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","kind":"typeIdentifier","text":"POBRewardedAd","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rewardedAd"},{"text":" ","kind":"text"},{"text":"shouldReward:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"POBReward","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward","preciseIdentifier":"c:objc(cs)POBReward"},{"text":" *) ","kind":"text"},{"text":"reward","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"POBRewardedAdDelegate","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate\/fragments","value":[{"text":"POBRewardedAdDelegate","kind":"identifier"}]},{"value":"POBRewardedAd","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd\/title","op":"replace"},{"value":[{"text":"POBRewardedAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBReward\/title","value":"POBReward"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBReward\/fragments","value":[{"text":"POBReward","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAd(_:shouldReward:)\/title","op":"replace","value":"rewardedAd:shouldReward:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAd(_:shouldReward:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rewardedAd:shouldReward:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}