{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdWillLeaveApplication"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"rewardedAd","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","preciseIdentifier":"c:objc(cs)POBRewardedAd","text":"POBRewardedAd"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The POBRewardedAd instance sending the message.","type":"text"}],"type":"paragraph"}],"name":"rewardedAd"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"landing page URL in the internal browser, use ‘RewardedAdDidClickAd:’","type":"text"},{"text":" ","type":"text"},{"text":"instead.","type":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedadwillleaveapplication(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedadwillleaveapplication(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdWillLeaveApplication(_:)"},"metadata":{"symbolKind":"method","title":"rewardedAdWillLeaveApplication(_:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdWillLeaveApplication"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)POBRewardedAd","text":"POBRewardedAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"rewardedAdWillLeaveApplication:","kind":"identifier"}],"externalID":"c:objc(pl)POBRewardedAdDelegate(im)rewardedAdWillLeaveApplication:"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAdWillLeaveApplication(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdWillLeaveApplication"},{"kind":"text","text":"("},{"text":"POBRewardedAd","preciseIdentifier":"c:objc(cs)POBRewardedAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"rewardedAdWillLeaveApplication:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedadwillleaveapplication(_:)","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdWillLeaveApplication(_:)","title":"rewardedAdWillLeaveApplication(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate","navigatorTitle":[{"text":"POBRewardedAdDelegate","kind":"identifier"}],"title":"POBRewardedAdDelegate","type":"topic","abstract":[{"type":"text","text":"Protocol for interaction with the POBRewardedAd instance."}],"url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBRewardedAdDelegate"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAd":{"title":"POBRewardedAd","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","abstract":[{"type":"text","text":"Displays Rewarded Ads."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBRewardedAd"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedad","navigatorTitle":[{"text":"POBRewardedAd","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"rewardedAdWillLeaveApplication:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rewardedAdWillLeaveApplication:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"rewardedAdWillLeaveApplication:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"POBRewardedAd","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"kind":"text","text":" *) "},{"text":"rewardedAd","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdWillLeaveApplication(_:)\/title","op":"replace","value":"rewardedAdWillLeaveApplication:"},{"value":[{"text":"- ","kind":"text"},{"text":"rewardedAdWillLeaveApplication:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdWillLeaveApplication(_:)\/fragments","op":"replace"},{"value":"POBRewardedAdDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate\/fragments","value":[{"text":"POBRewardedAdDelegate","kind":"identifier"}]},{"value":"POBRewardedAd","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd\/fragments","value":[{"text":"POBRewardedAd","kind":"identifier"}],"op":"replace"}]}]}