{"kind":"symbol","metadata":{"role":"symbol","title":"rewardedAdDidDismiss(_:)","roleHeading":"Instance Method","externalID":"c:objc(pl)POBRewardedAdDelegate(im)rewardedAdDidDismissAd:","navigatorTitle":[{"text":"rewardedAdDidDismissAd:","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdDidDismiss"},{"text":"(","kind":"text"},{"text":"POBRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"text":")","kind":"text"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rewardedAdDidDismiss","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"rewardedAd","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"POBRewardedAd","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedaddiddismiss(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedaddiddismiss(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidDismiss(_:)","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate","navigatorTitle":[{"text":"POBRewardedAdDelegate","kind":"identifier"}],"title":"POBRewardedAdDelegate","type":"topic","abstract":[{"type":"text","text":"Protocol for interaction with the POBRewardedAd instance."}],"url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBRewardedAdDelegate"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAdDidDismiss(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"rewardedAdDidDismissAd:"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAdDidDismiss(_:)","title":"rewardedAdDidDismiss(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdDidDismiss","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBRewardedAd","preciseIdentifier":"c:objc(cs)POBRewardedAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedaddiddismiss(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAd":{"title":"POBRewardedAd","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","abstract":[{"type":"text","text":"Displays Rewarded Ads."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBRewardedAd"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedad","navigatorTitle":[{"text":"POBRewardedAd","kind":"identifier"}],"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"rewardedAdDidDismissAd:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rewardedAdDidDismissAd:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"rewardedAdDidDismissAd:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBRewardedAd","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"text":" *) ","kind":"text"},{"text":"rewardedAd","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"POBRewardedAdDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate\/fragments","value":[{"text":"POBRewardedAdDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidDismiss(_:)\/title","value":"rewardedAdDidDismissAd:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"rewardedAdDidDismissAd:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAdDidDismiss(_:)\/fragments"},{"value":"POBRewardedAd","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd\/fragments","value":[{"kind":"identifier","text":"POBRewardedAd"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}