{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAd(_:didFailToReceiveAdWithError:)"},"metadata":{"role":"symbol","title":"rewardedAd(_:didFailToReceiveAdWithError:)","roleHeading":"Instance Method","externalID":"c:objc(pl)POBRewardedAdDelegate(im)rewardedAd:didFailToReceiveAdWithError:","navigatorTitle":[{"text":"rewardedAd:didFailToReceiveAdWithError:","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rewardedAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"POBRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailToReceiveAdWithError"},{"text":": any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedad(_:didfailtoreceiveadwitherror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedad(_:didfailtoreceiveadwitherror:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAd"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rewardedAd","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBRewardedAd","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","text":"POBRewardedAd"},{"kind":"text","text":", "},{"text":"didFailToReceiveAdWithError","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAd":{"title":"POBRewardedAd","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","abstract":[{"type":"text","text":"Displays Rewarded Ads."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBRewardedAd"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedad","navigatorTitle":[{"text":"POBRewardedAd","kind":"identifier"}],"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate","navigatorTitle":[{"text":"POBRewardedAdDelegate","kind":"identifier"}],"title":"POBRewardedAdDelegate","type":"topic","abstract":[{"type":"text","text":"Protocol for interaction with the POBRewardedAd instance."}],"url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBRewardedAdDelegate"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdDelegate/rewardedAd(_:didFailToReceiveAdWithError:)":{"title":"rewardedAd(_:didFailToReceiveAdWithError:)","url":"\/documentation\/openwrapsdk\/pobrewardedaddelegate\/rewardedad(_:didfailtoreceiveadwitherror:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdDelegate\/rewardedAd(_:didFailToReceiveAdWithError:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rewardedAd","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)POBRewardedAd","text":"POBRewardedAd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailToReceiveAdWithError"},{"text":": any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"rewardedAd:didFailToReceiveAdWithError:","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"rewardedAd:didFailToReceiveAdWithError:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rewardedAd:didFailToReceiveAdWithError:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"rewardedAd:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBRewardedAd","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBRewardedAd"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rewardedAd"},{"text":" ","kind":"text"},{"text":"didFailToReceiveAdWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"POBRewardedAd","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd\/fragments","value":[{"text":"POBRewardedAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate\/title","value":"POBRewardedAdDelegate"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBRewardedAdDelegate"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAd(_:didFailToReceiveAdWithError:)\/title","op":"replace","value":"rewardedAd:didFailToReceiveAdWithError:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdDelegate~1rewardedAd(_:didFailToReceiveAdWithError:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rewardedAd:didFailToReceiveAdWithError:"}],"op":"replace"}]}]}