{"metadata":{"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rendererForPartner:"}],"title":"renderer(forPartner:)","modules":[{"name":"OpenWrapSDK"}],"required":true,"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderer"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPartner"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> (any ","kind":"text"},{"kind":"typeIdentifier","text":"POBBannerRendering","preciseIdentifier":"c:objc(pl)POBBannerRendering"},{"text":")?","kind":"text"}],"externalID":"c:objc(pl)POBBannerEvent(im)rendererForPartner:"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobbannerevent\/renderer(forpartner:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobbannerevent\/renderer(forpartner:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/renderer(forPartner:)"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderer","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPartner"},{"text":" ","kind":"text"},{"text":"partner","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBannerRendering","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerRendering","text":"POBBannerRendering"},{"text":")?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEvent/renderer(forPartner:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderer","kind":"identifier"},{"kind":"text","text":"("},{"text":"forPartner","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBannerRendering","text":"POBBannerRendering"},{"text":")?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rendererForPartner:"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbannerevent\/renderer(forpartner:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/renderer(forPartner:)","title":"renderer(forPartner:)","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEvent":{"navigatorTitle":[{"text":"POBBannerEvent","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerevent","abstract":[],"kind":"symbol","title":"POBBannerEvent","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBBannerEvent"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerRendering":{"abstract":[{"text":"Ad banner rendering protocol, implement these methods to write custom ad renderer","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBBannerRendering"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobbannerrendering","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerRendering","type":"topic","title":"POBBannerRendering","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBBannerRendering"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"rendererForPartner:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rendererForPartner:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id<POBBannerRendering>","preciseIdentifier":"c:Qoobjc(pl)POBBannerRendering"},{"text":") ","kind":"text"},{"kind":"identifier","text":"rendererForPartner:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"partner"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1renderer(forPartner:)\/title","value":"rendererForPartner:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rendererForPartner:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1renderer(forPartner:)\/fragments","op":"replace"},{"value":"POBBannerEvent","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent\/title"},{"value":[{"text":"POBBannerEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent\/fragments"},{"value":"POBBannerRendering","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerRendering\/title","op":"replace"},{"value":[{"kind":"identifier","text":"POBBannerRendering"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerRendering\/fragments"}]}]}