{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/setDelegate(_:)"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobbannerevent\/setdelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobbannerevent\/setdelegate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"delegate","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate","kind":"typeIdentifier","text":"POBBannerEventDelegate","preciseIdentifier":"c:objc(pl)POBBannerEventDelegate"},{"text":")","kind":"text"}]}]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setDelegate:"}],"role":"symbol","title":"setDelegate(_:)","roleHeading":"Instance Method","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"POBBannerEventDelegate","preciseIdentifier":"c:objc(pl)POBBannerEventDelegate"},{"kind":"text","text":")"}],"externalID":"c:objc(pl)POBBannerEvent(im)setDelegate:","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEvent":{"navigatorTitle":[{"text":"POBBannerEvent","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannerevent","abstract":[],"kind":"symbol","title":"POBBannerEvent","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBBannerEvent"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEventDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBannerEventDelegate"}],"type":"topic","role":"symbol","abstract":[{"text":"The banner custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK.","type":"text"}],"navigatorTitle":[{"text":"POBBannerEventDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbannereventdelegate","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEventDelegate","title":"POBBannerEventDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBannerEvent/setDelegate(_:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"(any "},{"text":"POBBannerEventDelegate","preciseIdentifier":"c:objc(pl)POBBannerEventDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setDelegate:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbannerevent\/setdelegate(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBannerEvent\/setDelegate(_:)","title":"setDelegate(_:)","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setDelegate:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setDelegate:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<POBBannerEventDelegate>","preciseIdentifier":"c:Qoobjc(pl)POBBannerEventDelegate","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"delegate","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"POBBannerEvent","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBBannerEvent"}]},{"value":"POBBannerEventDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"POBBannerEventDelegate"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEventDelegate\/fragments"},{"op":"replace","value":"setDelegate:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1setDelegate(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBannerEvent~1setDelegate(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setDelegate:"}]}]}]}