{"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadloader\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativeadloader\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoader"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)POBNativeAdLoaderDelegate","text":"POBNativeAdLoaderDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderDelegate"},{"kind":"text","text":")? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoader\/delegate"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"POBNativeAdLoaderDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAdLoaderDelegate"},{"kind":"text","text":")?"}],"externalID":"c:objc(cs)POBNativeAdLoader(py)delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","title":"delegate","role":"symbol","modules":[{"name":"OpenWrapSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoader/delegate":{"url":"\/documentation\/openwrapsdk\/pobnativeadloader\/delegate","title":"delegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoader\/delegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAdLoaderDelegate","text":"POBNativeAdLoaderDelegate"},{"text":")?","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoader":{"abstract":[],"type":"topic","title":"POBNativeAdLoader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdLoader"}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeAdLoader"}],"url":"\/documentation\/openwrapsdk\/pobnativeadloader","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoader","kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoaderDelegate":{"url":"\/documentation\/openwrapsdk\/pobnativeadloaderdelegate","title":"POBNativeAdLoaderDelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoaderDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAdLoaderDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdLoaderDelegate"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)POBNativeAdLoaderDelegate","text":"id<POBNativeAdLoaderDelegate>"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoader~1delegate\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoader~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"value":"POBNativeAdLoader","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoader\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoader\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBNativeAdLoader"}]},{"value":"POBNativeAdLoaderDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderDelegate\/title"},{"value":[{"text":"POBNativeAdLoaderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoaderDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}