{"sections":[],"metadata":{"symbolKind":"init","roleHeading":"Initializer","title":"init(publisherId:profileId:adUnitId:templateType:eventHandler:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"publisherId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"profileId"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"adUnitId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"templateType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@POBNativeTemplateType","text":"POBNativeTemplateType"},{"text":", ","kind":"text"},{"text":"eventHandler","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAdEvent","text":"POBNativeAdEvent"},{"text":")","kind":"text"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"initWithPublisherId:profileId:adUnitId:templateType:eventHandler:","kind":"identifier"}],"externalID":"c:objc(cs)POBNativeAdLoader(im)initWithPublisherId:profileId:adUnitId:templateType:eventHandler:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"publisherId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"profileId"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":", ","kind":"text"},{"text":"adUnitId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateType"},{"kind":"text","text":": "},{"text":"POBNativeTemplateType","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateType","preciseIdentifier":"c:@E@POBNativeTemplateType"},{"kind":"text","text":", "},{"text":"eventHandler","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)POBNativeAdEvent","text":"POBNativeAdEvent","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEvent"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoader\/init(publisherId:profileId:adUnitId:templateType:eventHandler:)"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadloader\/init(publisherid:profileid:adunitid:templatetype:eventhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativeadloader\/init(publisherid:profileid:adunitid:templatetype:eventhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoader"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoader/init(publisherId:profileId:adUnitId:templateType:eventHandler:)":{"role":"symbol","navigatorTitle":[{"text":"initWithPublisherId:profileId:adUnitId:templateType:eventHandler:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"publisherId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"profileId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adUnitId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"templateType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"POBNativeTemplateType","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBNativeTemplateType"},{"kind":"text","text":", "},{"text":"eventHandler","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"POBNativeAdEvent","preciseIdentifier":"c:objc(pl)POBNativeAdEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(publisherId:profileId:adUnitId:templateType:eventHandler:)","url":"\/documentation\/openwrapsdk\/pobnativeadloader\/init(publisherid:profileid:adunitid:templatetype:eventhandler:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoader\/init(publisherId:profileId:adUnitId:templateType:eventHandler:)","type":"topic","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoader":{"abstract":[],"type":"topic","title":"POBNativeAdLoader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdLoader"}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeAdLoader"}],"url":"\/documentation\/openwrapsdk\/pobnativeadloader","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoader","kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateType":{"navigatorTitle":[{"text":"POBNativeTemplateType","kind":"identifier"}],"abstract":[{"type":"text","text":"The Type of the native ad template"}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeTemplateType"}],"title":"POBNativeTemplateType","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateType","url":"\/documentation\/openwrapsdk\/pobnativetemplatetype"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEvent":{"role":"symbol","navigatorTitle":[{"text":"POBNativeAdEvent","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBNativeAdEvent","kind":"identifier"}],"title":"POBNativeAdEvent","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeadevent","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEvent","type":"topic","abstract":[{"text":"The native custom event protocol. Your native custom event handler must implement this protocol to communicate with the ad server SDK.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithPublisherId:profileId:adUnitId:templateType:eventHandler:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPublisherId:profileId:adUnitId:templateType:eventHandler:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithPublisherId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"publisherId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"profileId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"profileId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adUnitId:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"adUnitId"},{"kind":"text","text":" "},{"text":"templateType:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@POBNativeTemplateType","text":"POBNativeTemplateType","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"templateType"},{"kind":"text","text":" "},{"text":"eventHandler:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<POBNativeAdEvent>","preciseIdentifier":"c:Qoobjc(pl)POBNativeAdEvent"},{"text":") ","kind":"text"},{"text":"eventHandler","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoader~1init(publisherId:profileId:adUnitId:templateType:eventHandler:)\/title","value":"initWithPublisherId:profileId:adUnitId:templateType:eventHandler:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPublisherId:profileId:adUnitId:templateType:eventHandler:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoader~1init(publisherId:profileId:adUnitId:templateType:eventHandler:)\/fragments"},{"value":"POBNativeAdLoader","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoader\/title"},{"op":"replace","value":[{"text":"POBNativeAdLoader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoader\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateType\/title","op":"replace","value":"POBNativeTemplateType"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateType\/fragments","value":[{"text":"POBNativeTemplateType","kind":"identifier"}]},{"value":"POBNativeAdEvent","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEvent\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEvent\/fragments","value":[{"text":"POBNativeAdEvent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}