{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"publisherId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"profileId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adUnitId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateType"},{"text":": ","kind":"text"},{"text":"POBNativeTemplateType","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateType","preciseIdentifier":"c:@E@POBNativeTemplateType"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"symbolKind":"init","roleHeading":"Initializer","title":"init(publisherId:profileId:adUnitId:templateType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"publisherId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"profileId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adUnitId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@POBNativeTemplateType","text":"POBNativeTemplateType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPublisherId:profileId:adUnitId:templateType:"}],"externalID":"c:objc(cs)POBNativeAdLoader(im)initWithPublisherId:profileId:adUnitId:templateType:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoader"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoader\/init(publisherId:profileId:adUnitId:templateType:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadloader\/init(publisherid:profileid:adunitid:templatetype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadloader\/init(publisherid:profileid:adunitid:templatetype:)"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoader/init(publisherId:profileId:adUnitId:templateType:)":{"title":"init(publisherId:profileId:adUnitId:templateType:)","url":"\/documentation\/openwrapsdk\/pobnativeadloader\/init(publisherid:profileid:adunitid:templatetype:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoader\/init(publisherId:profileId:adUnitId:templateType:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"publisherId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"profileId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adUnitId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"templateType"},{"kind":"text","text":": "},{"text":"POBNativeTemplateType","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBNativeTemplateType"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithPublisherId:profileId:adUnitId:templateType:","kind":"identifier"}],"abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdLoader":{"abstract":[],"type":"topic","title":"POBNativeAdLoader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAdLoader"}],"navigatorTitle":[{"kind":"identifier","text":"POBNativeAdLoader"}],"url":"\/documentation\/openwrapsdk\/pobnativeadloader","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdLoader","kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeTemplateType":{"navigatorTitle":[{"text":"POBNativeTemplateType","kind":"identifier"}],"abstract":[{"type":"text","text":"The Type of the native ad template"}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeTemplateType"}],"title":"POBNativeTemplateType","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateType","url":"\/documentation\/openwrapsdk\/pobnativetemplatetype"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithPublisherId:profileId:adUnitId:templateType:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithPublisherId:profileId:adUnitId:templateType:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithPublisherId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"publisherId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"profileId:"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"profileId"},{"text":" ","kind":"text"},{"text":"adUnitId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"adUnitId"},{"kind":"text","text":" "},{"text":"templateType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBNativeTemplateType","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeTemplateType","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBNativeTemplateType"},{"kind":"text","text":") "},{"text":"templateType","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoader~1init(publisherId:profileId:adUnitId:templateType:)\/title","value":"initWithPublisherId:profileId:adUnitId:templateType:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithPublisherId:profileId:adUnitId:templateType:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoader~1init(publisherId:profileId:adUnitId:templateType:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoader\/title","op":"replace","value":"POBNativeAdLoader"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdLoader\/fragments","value":[{"kind":"identifier","text":"POBNativeAdLoader"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateType\/title","value":"POBNativeTemplateType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeTemplateType\/fragments","value":[{"text":"POBNativeTemplateType","kind":"identifier"}]}]}]}