{"sections":[],"abstract":[{"type":"text","text":"Banner and MREC ad format"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat\/bannerAndMREC"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerAndMREC","kind":"identifier"}],"externalID":"c:@E@POBAdFormat@POBAdFormatBannerAndMREC","navigatorTitle":[{"kind":"identifier","text":"POBAdFormatBannerAndMREC"}],"symbolKind":"case","roleHeading":"Case","title":"POBAdFormat.bannerAndMREC","role":"symbol","modules":[{"name":"OpenWrapSDK"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAndMREC"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobadformat\/bannerandmrec"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobadformat\/bannerandmrec"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdFormat":{"abstract":[{"text":"Indicates the ad format to request\/render","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadformat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBAdFormat","kind":"identifier"}],"title":"POBAdFormat","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat","navigatorTitle":[{"text":"POBAdFormat","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdFormat/bannerAndMREC":{"type":"topic","abstract":[{"text":"Banner and MREC ad format","type":"text"}],"navigatorTitle":[{"text":"POBAdFormatBannerAndMREC","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat\/bannerAndMREC","title":"POBAdFormat.bannerAndMREC","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAndMREC"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadformat\/bannerandmrec"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"POBAdFormatBannerAndMREC","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"POBAdFormatBannerAndMREC","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"POBAdFormatBannerAndMREC","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat\/title","value":"POBAdFormat"},{"op":"replace","value":[{"text":"POBAdFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat~1bannerAndMREC\/title","value":"POBAdFormatBannerAndMREC"},{"op":"replace","value":[{"kind":"identifier","text":"POBAdFormatBannerAndMREC"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat~1bannerAndMREC\/fragments"}]}]}