{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobadformat\/native"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobadformat\/native"]}],"sections":[],"metadata":{"role":"symbol","title":"POBAdFormat.native","roleHeading":"Case","externalID":"c:@E@POBAdFormat@POBAdFormatNative","navigatorTitle":[{"text":"POBAdFormatNative","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"native"}],"symbolKind":"case"},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat\/native","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Native"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"native"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdFormat":{"abstract":[{"text":"Indicates the ad format to request\/render","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadformat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBAdFormat","kind":"identifier"}],"title":"POBAdFormat","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat","navigatorTitle":[{"text":"POBAdFormat","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdFormat/native":{"type":"topic","abstract":[{"text":"Native","type":"text"}],"navigatorTitle":[{"text":"POBAdFormatNative","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat\/native","title":"POBAdFormat.native","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"native"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadformat\/native"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"POBAdFormatNative","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBAdFormatNative"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"POBAdFormatNative","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"POBAdFormat","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat\/fragments","value":[{"text":"POBAdFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat~1native\/title","value":"POBAdFormatNative","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat~1native\/fragments","value":[{"kind":"identifier","text":"POBAdFormatNative"}]}]}]}