{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate\/didDismissAd()"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadeventdelegate\/diddismissad()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadeventdelegate\/diddismissad()"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didDismissAd","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"metadata":{"title":"didDismissAd()","required":true,"modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(pl)POBNativeAdEventDelegate(im)didDismissAd","navigatorTitle":[{"kind":"identifier","text":"didDismissAd"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didDismissAd","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol"},"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventDelegate/didDismissAd()":{"type":"topic","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate\/didDismissAd()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didDismissAd","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","title":"didDismissAd()","navigatorTitle":[{"text":"didDismissAd","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativeadeventdelegate\/diddismissad()","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventDelegate":{"title":"POBNativeAdEventDelegate","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBNativeAdEventDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativeadeventdelegate","navigatorTitle":[{"text":"POBNativeAdEventDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The native custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"didDismissAd","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"didDismissAd","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didDismissAd"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate~1didDismissAd()\/title","value":"didDismissAd"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didDismissAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate~1didDismissAd()\/fragments"},{"value":"POBNativeAdEventDelegate","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate\/fragments","value":[{"text":"POBNativeAdEventDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}