{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didRecordImpression","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadeventdelegate\/didrecordimpression()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadeventdelegate\/didrecordimpression()"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate"]]},"metadata":{"roleHeading":"Instance Method","title":"didRecordImpression()","required":true,"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didRecordImpression","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"didRecordImpression","kind":"identifier"}],"externalID":"c:objc(pl)POBNativeAdEventDelegate(im)didRecordImpression","symbolKind":"method","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate\/didRecordImpression()"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventDelegate/didRecordImpression()":{"type":"topic","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate\/didRecordImpression()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didRecordImpression","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"didRecordImpression()","navigatorTitle":[{"kind":"identifier","text":"didRecordImpression"}],"url":"\/documentation\/openwrapsdk\/pobnativeadeventdelegate\/didrecordimpression()","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventDelegate":{"title":"POBNativeAdEventDelegate","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBNativeAdEventDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativeadeventdelegate","navigatorTitle":[{"text":"POBNativeAdEventDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The native custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"didRecordImpression","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didRecordImpression","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"didRecordImpression","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate~1didRecordImpression()\/title","value":"didRecordImpression"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didRecordImpression"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate~1didRecordImpression()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate\/title","value":"POBNativeAdEventDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"POBNativeAdEventDelegate"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}