{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate\/willPresentAd()"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willPresentAd"},{"text":"()","kind":"text"}],"required":true,"externalID":"c:objc(pl)POBNativeAdEventDelegate(im)willPresentAd","navigatorTitle":[{"kind":"identifier","text":"willPresentAd"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"willPresentAd()","modules":[{"name":"OpenWrapSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willPresentAd"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeadeventdelegate\/willpresentad()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadeventdelegate\/willpresentad()"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventDelegate/willPresentAd()":{"type":"topic","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate\/willPresentAd()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"willPresentAd","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"willPresentAd()","navigatorTitle":[{"kind":"identifier","text":"willPresentAd"}],"url":"\/documentation\/openwrapsdk\/pobnativeadeventdelegate\/willpresentad()","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventDelegate":{"title":"POBNativeAdEventDelegate","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBNativeAdEventDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativeadeventdelegate","navigatorTitle":[{"text":"POBNativeAdEventDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The native custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"willPresentAd","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"willPresentAd","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"willPresentAd"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"willPresentAd","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate~1willPresentAd()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate~1willPresentAd()\/fragments","value":[{"kind":"text","text":"- "},{"text":"willPresentAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate\/title","value":"POBNativeAdEventDelegate"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate\/fragments","value":[{"text":"POBNativeAdEventDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}