{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate"]]},"kind":"symbol","metadata":{"title":"willLeaveApp()","modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willLeaveApp"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"willLeaveApp","kind":"identifier"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(pl)POBNativeAdEventDelegate(im)willLeaveApp","required":true},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate\/willLeaveApp()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeadeventdelegate\/willleaveapp()"]},{"paths":["\/documentation\/openwrapsdk\/pobnativeadeventdelegate\/willleaveapp()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willLeaveApp"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventDelegate":{"title":"POBNativeAdEventDelegate","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBNativeAdEventDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativeadeventdelegate","navigatorTitle":[{"text":"POBNativeAdEventDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The native custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdEventDelegate/willLeaveApp()":{"type":"topic","required":true,"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdEventDelegate\/willLeaveApp()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"willLeaveApp","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","title":"willLeaveApp()","navigatorTitle":[{"text":"willLeaveApp","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativeadeventdelegate\/willleaveapp()","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"willLeaveApp","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willLeaveApp","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"willLeaveApp","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"POBNativeAdEventDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate\/fragments","value":[{"text":"POBNativeAdEventDelegate","kind":"identifier"}]},{"value":"willLeaveApp","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate~1willLeaveApp()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdEventDelegate~1willLeaveApp()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willLeaveApp","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}