{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/female","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobgender\/female"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobgender\/female"]}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"female","kind":"identifier"}],"navigatorTitle":[{"text":"POBGenderFemale","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"title":"POBGender.female","symbolKind":"case","role":"symbol","externalID":"c:@E@POBGender@POBGenderFemale"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Gender female","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"female"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBGender":{"url":"\/documentation\/openwrapsdk\/pobgender","role":"symbol","title":"POBGender","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBGender","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"POBGender","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Gender to help deliver more relevant ads."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBGender/female":{"type":"topic","navigatorTitle":[{"text":"POBGenderFemale","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/female","url":"\/documentation\/openwrapsdk\/pobgender\/female","kind":"symbol","abstract":[{"type":"text","text":"Gender female"}],"role":"symbol","title":"POBGender.female","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"female","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"POBGenderFemale"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBGenderFemale"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"POBGenderFemale"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender\/title","value":"POBGender","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender\/fragments","value":[{"text":"POBGender","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender~1female\/title","value":"POBGenderFemale","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender~1female\/fragments","value":[{"text":"POBGenderFemale","kind":"identifier"}]}]}]}