{"abstract":[{"text":"Gender male","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobgender\/male"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobgender\/male"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"male","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"POBGenderMale","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"POBGender.male","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"male","kind":"identifier"}],"externalID":"c:@E@POBGender@POBGenderMale","modules":[{"name":"OpenWrapSDK"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/male","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBGender":{"url":"\/documentation\/openwrapsdk\/pobgender","role":"symbol","title":"POBGender","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBGender","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"POBGender","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Gender to help deliver more relevant ads."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBGender/male":{"navigatorTitle":[{"text":"POBGenderMale","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobgender\/male","abstract":[{"text":"Gender male","type":"text"}],"kind":"symbol","title":"POBGender.male","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"male","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBGender\/male","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"POBGenderMale","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"POBGenderMale"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"POBGenderMale"}]}]},"op":"replace"},{"value":"POBGender","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender\/fragments","value":[{"kind":"identifier","text":"POBGender"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender~1male\/title","value":"POBGenderMale"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBGender~1male\/fragments","value":[{"text":"POBGenderMale","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}