{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"init(publisherId:profileId:adUnitId:eventHandler:)","navigatorTitle":[{"text":"initWithPublisherId:profileId:adUnitId:eventHandler:","kind":"identifier"}],"externalID":"c:objc(cs)POBInterstitial(im)initWithPublisherId:profileId:adUnitId:eventHandler:","symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"publisherId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"profileId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adUnitId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"eventHandler","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"POBInterstitialEvent","preciseIdentifier":"c:objc(pl)POBInterstitialEvent","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Initializer"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/init(publisherId:profileId:adUnitId:eventHandler:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"publisherId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"profileId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":", ","kind":"text"},{"text":"adUnitId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"eventHandler","kind":"externalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBInterstitialEvent","text":"POBInterstitialEvent"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitial\/init(publisherid:profileid:adunitid:eventhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitial\/init(publisherid:profileid:adunitid:eventhandler:)"]}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialEvent":{"type":"topic","title":"POBInterstitialEvent","abstract":[{"type":"text","text":"The interstitial custom event protocol. Your interstitial custom event handler must implement this protocol to communicate with ad server SDK."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBInterstitialEvent"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialEvent","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialevent","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBInterstitial","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"POBInterstitial","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial","title":"POBInterstitial","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial","abstract":[{"text":"Displays Interstitial Ads.","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial/init(publisherId:profileId:adUnitId:eventHandler:)":{"url":"\/documentation\/openwrapsdk\/pobinterstitial\/init(publisherid:profileid:adunitid:eventhandler:)","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/init(publisherId:profileId:adUnitId:eventHandler:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithPublisherId:profileId:adUnitId:eventHandler:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"publisherId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"profileId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":", "},{"text":"adUnitId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"eventHandler","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)POBInterstitialEvent","text":"POBInterstitialEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(publisherId:profileId:adUnitId:eventHandler:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"initWithPublisherId:profileId:adUnitId:eventHandler:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPublisherId:profileId:adUnitId:eventHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithPublisherId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"publisherId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"profileId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"text":"profileId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"adUnitId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"adUnitId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"eventHandler:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<POBInterstitialEvent>","preciseIdentifier":"c:Qoobjc(pl)POBInterstitialEvent"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"eventHandler"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"POBInterstitialEvent","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEvent\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialEvent\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBInterstitialEvent"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/title","op":"replace","value":"POBInterstitial"},{"value":[{"text":"POBInterstitial","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/fragments","op":"replace"},{"value":"initWithPublisherId:profileId:adUnitId:eventHandler:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1init(publisherId:profileId:adUnitId:eventHandler:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1init(publisherId:profileId:adUnitId:eventHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPublisherId:profileId:adUnitId:eventHandler:"}]}]}]}