{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitial\/show(from:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitial\/show(from:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"show","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)POBInterstitial(im)showFromViewController:","navigatorTitle":[{"kind":"identifier","text":"showFromViewController:"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"OpenWrapSDK"}],"title":"show(from:)","role":"symbol"},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/show(from:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBInterstitial","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"POBInterstitial","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial","title":"POBInterstitial","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial","abstract":[{"text":"Displays Interstitial Ads.","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitial/show(from:)":{"abstract":[],"navigatorTitle":[{"text":"showFromViewController:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobinterstitial\/show(from:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitial\/show(from:)","title":"show(from:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":")","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showFromViewController:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"showFromViewController:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"showFromViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"POBInterstitial","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/title"},{"op":"replace","value":[{"text":"POBInterstitial","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1show(from:)\/title","value":"showFromViewController:","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitial~1show(from:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"showFromViewController:","kind":"identifier"}]}]}]}