{"sections":[],"abstract":[{"text":"Event Type Video clicked","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent\/clicked"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"clicked","kind":"identifier"}],"externalID":"c:@E@POBVideoAdEvent@POBVideoAdEventClicked","navigatorTitle":[{"kind":"identifier","text":"POBVideoAdEventClicked"}],"symbolKind":"case","roleHeading":"Case","modules":[{"name":"OpenWrapSDK"}],"title":"POBVideoAdEvent.clicked","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clicked"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobvideoadevent\/clicked"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobvideoadevent\/clicked"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoAdEvent/clicked":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent\/clicked","kind":"symbol","role":"symbol","title":"POBVideoAdEvent.clicked","url":"\/documentation\/openwrapsdk\/pobvideoadevent\/clicked","abstract":[{"type":"text","text":"Event Type Video clicked"}],"navigatorTitle":[{"kind":"identifier","text":"POBVideoAdEventClicked"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clicked"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoAdEvent":{"url":"\/documentation\/openwrapsdk\/pobvideoadevent","title":"POBVideoAdEvent","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBVideoAdEvent"}],"abstract":[{"type":"text","text":"Various Ad Event Types"}],"navigatorTitle":[{"kind":"identifier","text":"POBVideoAdEvent"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"POBVideoAdEventClicked"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"POBVideoAdEventClicked","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"POBVideoAdEventClicked","kind":"identifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent~1clicked\/title","op":"replace","value":"POBVideoAdEventClicked"},{"value":[{"text":"POBVideoAdEventClicked","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent~1clicked\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent\/title","op":"replace","value":"POBVideoAdEvent"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBVideoAdEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}