{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"firstQuartile","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Event Type First Quartile occured","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent\/firstQuartile"},"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"POBVideoAdEventFirstQuartile","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"POBVideoAdEvent.firstQuartile","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"firstQuartile"}],"externalID":"c:@E@POBVideoAdEvent@POBVideoAdEventFirstQuartile","modules":[{"name":"OpenWrapSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobvideoadevent\/firstquartile"]},{"paths":["\/documentation\/openwrapsdk\/pobvideoadevent\/firstquartile"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoAdEvent/firstQuartile":{"type":"topic","abstract":[{"text":"Event Type First Quartile occured","type":"text"}],"navigatorTitle":[{"text":"POBVideoAdEventFirstQuartile","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent\/firstQuartile","title":"POBVideoAdEvent.firstQuartile","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"firstQuartile"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobvideoadevent\/firstquartile"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoAdEvent":{"url":"\/documentation\/openwrapsdk\/pobvideoadevent","title":"POBVideoAdEvent","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBVideoAdEvent"}],"abstract":[{"type":"text","text":"Various Ad Event Types"}],"navigatorTitle":[{"kind":"identifier","text":"POBVideoAdEvent"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"POBVideoAdEventFirstQuartile","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"POBVideoAdEventFirstQuartile","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"POBVideoAdEventFirstQuartile"}]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent~1firstQuartile\/title","value":"POBVideoAdEventFirstQuartile","op":"replace"},{"value":[{"text":"POBVideoAdEventFirstQuartile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent~1firstQuartile\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent\/title","value":"POBVideoAdEvent"},{"op":"replace","value":[{"kind":"identifier","text":"POBVideoAdEvent"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent\/fragments"}]}]}