{"kind":"symbol","abstract":[{"type":"text","text":"Event Type Industry icon clicked"}],"metadata":{"roleHeading":"Case","title":"POBVideoAdEvent.iconClicked","modules":[{"name":"OpenWrapSDK"}],"role":"symbol","externalID":"c:@E@POBVideoAdEvent@POBVideoAdEventIconClicked","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"iconClicked","kind":"identifier"}],"navigatorTitle":[{"text":"POBVideoAdEventIconClicked","kind":"identifier"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iconClicked"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobvideoadevent\/iconclicked"]},{"paths":["\/documentation\/openwrapsdk\/pobvideoadevent\/iconclicked"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent\/iconClicked","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoAdEvent":{"url":"\/documentation\/openwrapsdk\/pobvideoadevent","title":"POBVideoAdEvent","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBVideoAdEvent"}],"abstract":[{"type":"text","text":"Various Ad Event Types"}],"navigatorTitle":[{"kind":"identifier","text":"POBVideoAdEvent"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoAdEvent/iconClicked":{"url":"\/documentation\/openwrapsdk\/pobvideoadevent\/iconclicked","title":"POBVideoAdEvent.iconClicked","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"iconClicked","kind":"identifier"}],"abstract":[{"text":"Event Type Industry icon clicked","type":"text"}],"navigatorTitle":[{"text":"POBVideoAdEventIconClicked","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent\/iconClicked"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"POBVideoAdEventIconClicked","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBVideoAdEventIconClicked"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"POBVideoAdEventIconClicked","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent\/title","value":"POBVideoAdEvent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent\/fragments","value":[{"text":"POBVideoAdEvent","kind":"identifier"}]},{"value":"POBVideoAdEventIconClicked","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent~1iconClicked\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent~1iconClicked\/fragments","value":[{"text":"POBVideoAdEventIconClicked","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}