{"abstract":[{"type":"text","text":"Event Type video paused"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent\/pause","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobvideoadevent\/pause"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobvideoadevent\/pause"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"POBVideoAdEventPause"}],"role":"symbol","roleHeading":"Case","title":"POBVideoAdEvent.pause","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause"}],"externalID":"c:@E@POBVideoAdEvent@POBVideoAdEventPause","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoAdEvent":{"url":"\/documentation\/openwrapsdk\/pobvideoadevent","title":"POBVideoAdEvent","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBVideoAdEvent"}],"abstract":[{"type":"text","text":"Various Ad Event Types"}],"navigatorTitle":[{"kind":"identifier","text":"POBVideoAdEvent"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoAdEvent/pause":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent\/pause","kind":"symbol","role":"symbol","title":"POBVideoAdEvent.pause","url":"\/documentation\/openwrapsdk\/pobvideoadevent\/pause","abstract":[{"type":"text","text":"Event Type video paused"}],"navigatorTitle":[{"text":"POBVideoAdEventPause","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pause"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"POBVideoAdEventPause"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBVideoAdEventPause","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"POBVideoAdEventPause","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"POBVideoAdEvent","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"POBVideoAdEvent"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent~1pause\/title","value":"POBVideoAdEventPause","op":"replace"},{"value":[{"text":"POBVideoAdEventPause","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent~1pause\/fragments"}]}]}