{"abstract":[{"type":"text","text":"Event Type Video unmuted"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unmute","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent\/unmute","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobvideoadevent\/unmute"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobvideoadevent\/unmute"]}],"kind":"symbol","metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"POBVideoAdEventUnmute"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unmute","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@E@POBVideoAdEvent@POBVideoAdEventUnmute","title":"POBVideoAdEvent.unmute"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoAdEvent":{"url":"\/documentation\/openwrapsdk\/pobvideoadevent","title":"POBVideoAdEvent","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBVideoAdEvent"}],"abstract":[{"type":"text","text":"Various Ad Event Types"}],"navigatorTitle":[{"kind":"identifier","text":"POBVideoAdEvent"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoAdEvent/unmute":{"abstract":[{"text":"Event Type Video unmuted","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobvideoadevent\/unmute","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmute"}],"title":"POBVideoAdEvent.unmute","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent\/unmute","navigatorTitle":[{"text":"POBVideoAdEventUnmute","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"POBVideoAdEventUnmute"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"POBVideoAdEventUnmute","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"POBVideoAdEventUnmute","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent\/title","value":"POBVideoAdEvent"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent\/fragments","value":[{"kind":"identifier","text":"POBVideoAdEvent"}],"op":"replace"},{"op":"replace","value":"POBVideoAdEventUnmute","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent~1unmute\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent~1unmute\/fragments","value":[{"text":"POBVideoAdEventUnmute","kind":"identifier"}]}]}]}