{"metadata":{"roleHeading":"Type Method","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addExternalUserId","kind":"identifier"},{"kind":"text","text":"("},{"text":"POBExternalUserId","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBExternalUserId"},{"text":"!)","kind":"text"}],"externalID":"c:objc(cs)OpenWrapSDK(cm)addExternalUserId:","navigatorTitle":[{"kind":"identifier","text":"addExternalUserId:"}],"symbolKind":"method","modules":[{"name":"OpenWrapSDK"}],"title":"addExternalUserId(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addExternalUserId"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"externalUserId"},{"kind":"text","text":": "},{"text":"POBExternalUserId","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId","preciseIdentifier":"c:objc(cs)POBExternalUserId"},{"text":"!)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"externalUserId","content":[{"type":"paragraph","inlineContent":[{"text":"Instance of POBExternalUserId storing user’s data received from identity vendors.","type":"text"}]}]}]},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"passed to OpenWrap SDK using this API."}]},{"inlineContent":[{"text":"This external user id passed to OpenWrap SDK will persist for an app session only.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK"]]},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/openwrapsdk\/openwrapsdk\/addexternaluserid(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/openwrapsdk\/addexternaluserid(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/addExternalUserId(_:)"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/addExternalUserId(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/addExternalUserId(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/openwrapsdk\/addexternaluserid(_:)","title":"addExternalUserId(_:)","abstract":[],"navigatorTitle":[{"text":"addExternalUserId:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addExternalUserId"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBExternalUserId","text":"POBExternalUserId","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBExternalUserId":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBExternalUserId","kind":"identifier"}],"title":"POBExternalUserId","kind":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobexternaluserid","abstract":[{"text":"Class to hold the user’s identity data.","type":"text"},{"text":" ","type":"text"},{"text":"This data will be fetched by the application from identity vendors which is required by different identity partners.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Application should pass this data to OpenWrap SDK which will be sent in each ad request."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId","role":"symbol","navigatorTitle":[{"text":"POBExternalUserId","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK":{"abstract":[{"type":"text","text":"Provides global configurations for the OpenWrap SDK, e.g. enabling logging, location access, etc. These configurations are globally applicable for OpenWrap SDK; you don’t have to set these for every ad request."}],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK","kind":"symbol","title":"OpenWrapSDK","navigatorTitle":[{"text":"OpenWrapSDK","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/openwrapsdk","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenWrapSDK","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"addExternalUserId:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"addExternalUserId:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"addExternalUserId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBExternalUserId","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBExternalUserId","text":"POBExternalUserId"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"externalUserId"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1addExternalUserId(_:)\/title","value":"addExternalUserId:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addExternalUserId:"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1addExternalUserId(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId\/title","op":"replace","value":"POBExternalUserId"},{"value":[{"text":"POBExternalUserId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBExternalUserId\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK\/title","value":"OpenWrapSDK","op":"replace"},{"op":"replace","value":[{"text":"OpenWrapSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK\/fragments"}]}]}