{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/allowLocationAccess(_:)"},"kind":"symbol","metadata":{"role":"symbol","title":"allowLocationAccess(_:)","roleHeading":"Type Method","externalID":"c:objc(cs)OpenWrapSDK(cm)allowLocationAccess:","navigatorTitle":[{"kind":"identifier","text":"allowLocationAccess:"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowLocationAccess"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/openwrapsdk\/allowlocationaccess(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/openwrapsdk\/allowlocationaccess(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowLocationAccess","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"allow","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"allow","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"YES\/NO value"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"codeListing","syntax":null,"code":["         serve location-based ads. When set to NO, the SDK will not attempt to access device location.","         When set to YES, the SDK will periodically try to fetch location efficiently."]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that, this only occurs if location services are enabled and the user has already authorized the use of"},{"type":"text","text":" "},{"type":"text","text":"location services for the application. The OpenWrap SDK never asks permission to use location services by itself."}]},{"inlineContent":[{"type":"text","text":"The default value is YES."}],"type":"paragraph"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK":{"abstract":[{"type":"text","text":"Provides global configurations for the OpenWrap SDK, e.g. enabling logging, location access, etc. These configurations are globally applicable for OpenWrap SDK; you don’t have to set these for every ad request."}],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK","kind":"symbol","title":"OpenWrapSDK","navigatorTitle":[{"text":"OpenWrapSDK","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/openwrapsdk","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenWrapSDK","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/allowLocationAccess(_:)":{"navigatorTitle":[{"kind":"identifier","text":"allowLocationAccess:"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"allowLocationAccess","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"role":"symbol","title":"allowLocationAccess(_:)","url":"\/documentation\/openwrapsdk\/openwrapsdk\/allowlocationaccess(_:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/allowLocationAccess(_:)","abstract":[],"kind":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"allowLocationAccess:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"allowLocationAccess:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"allowLocationAccess:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"allow","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OpenWrapSDK","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK\/fragments","value":[{"text":"OpenWrapSDK","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"allowLocationAccess:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1allowLocationAccess(_:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"allowLocationAccess:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1allowLocationAccess(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}