{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK"]]},"kind":"symbol","abstract":[{"text":"A property to get the current DSA (Digital Services Act) compliance status.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default value is @c POBDSAComplianceStatusNotRequired."}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/dsaComplianceStatus","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dsaComplianceStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"POBDSAComplianceStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus","preciseIdentifier":"c:@E@POBDSAComplianceStatus"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/openwrapsdk\/dsacompliancestatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/openwrapsdk\/dsacompliancestatus"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:objc(cs)OpenWrapSDK(cpy)dsaComplianceStatus","navigatorTitle":[{"kind":"identifier","text":"dsaComplianceStatus"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dsaComplianceStatus"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@POBDSAComplianceStatus","text":"POBDSAComplianceStatus","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Type Property","symbolKind":"property","title":"dsaComplianceStatus"},"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/dsaComplianceStatus":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"dsaComplianceStatus"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/dsaComplianceStatus","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dsaComplianceStatus"},{"kind":"text","text":": "},{"text":"POBDSAComplianceStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBDSAComplianceStatus"}],"url":"\/documentation\/openwrapsdk\/openwrapsdk\/dsacompliancestatus","abstract":[{"type":"text","text":"A property to get the current DSA (Digital Services Act) compliance status."},{"type":"text","text":" "},{"type":"text","text":"Default value is @c POBDSAComplianceStatusNotRequired."}],"title":"dsaComplianceStatus"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus","url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBDSAComplianceStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBDSAComplianceStatus"}],"role":"symbol","title":"POBDSAComplianceStatus","abstract":[{"type":"text","text":"DSA (Digital Services Act) compliance requirement status."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK":{"abstract":[{"type":"text","text":"Provides global configurations for the OpenWrap SDK, e.g. enabling logging, location access, etc. These configurations are globally applicable for OpenWrap SDK; you don’t have to set these for every ad request."}],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK","kind":"symbol","title":"OpenWrapSDK","navigatorTitle":[{"text":"OpenWrapSDK","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/openwrapsdk","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenWrapSDK","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","value":"dsaComplianceStatus","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dsaComplianceStatus"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"POBDSAComplianceStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus","preciseIdentifier":"c:@E@POBDSAComplianceStatus"},{"text":" ","kind":"text"},{"text":"dsaComplianceStatus","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1dsaComplianceStatus\/title","value":"dsaComplianceStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1dsaComplianceStatus\/fragments","op":"replace","value":[{"text":"dsaComplianceStatus","kind":"identifier"}]},{"op":"replace","value":"POBDSAComplianceStatus","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus\/fragments","value":[{"text":"POBDSAComplianceStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK\/title","op":"replace","value":"OpenWrapSDK"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK\/fragments","op":"replace","value":[{"text":"OpenWrapSDK","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}