{"metadata":{"modules":[{"name":"OpenWrapSDK"}],"title":"initialize(with:andCompletionHandler:)","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)OpenWrapSDK(cm)initializeWithConfig:andCompletionHandler:","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"OpenWrapSDKConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OpenWrapSDKConfig"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"andCompletionHandler"},{"text":": ","kind":"text"},{"text":"OpenWrapSDKInitCompletionBlock","preciseIdentifier":"c:OpenWrapSDK.h@T@OpenWrapSDKInitCompletionBlock","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"initializeWithConfig:andCompletionHandler:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/initialize(with:andCompletionHandler:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"text":"OpenWrapSDKConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OpenWrapSDKConfig","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"andCompletionHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": "},{"text":"OpenWrapSDKInitCompletionBlock","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKInitCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:OpenWrapSDK.h@T@OpenWrapSDKInitCompletionBlock"},{"text":"!)","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/openwrapsdk\/initialize(with:andcompletionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/openwrapsdk\/initialize(with:andcompletionhandler:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDKInitCompletionBlock":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKInitCompletionBlock","type":"topic","kind":"symbol","title":"OpenWrapSDKInitCompletionBlock","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenWrapSDKInitCompletionBlock"}],"navigatorTitle":[{"text":"OpenWrapSDKInitCompletionBlock","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/openwrapsdkinitcompletionblock"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/initialize(with:andCompletionHandler:)":{"title":"initialize(with:andCompletionHandler:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/initialize(with:andCompletionHandler:)","kind":"symbol","role":"symbol","url":"\/documentation\/openwrapsdk\/openwrapsdk\/initialize(with:andcompletionhandler:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)OpenWrapSDKConfig","kind":"typeIdentifier","text":"OpenWrapSDKConfig"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"andCompletionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenWrapSDKInitCompletionBlock","preciseIdentifier":"c:OpenWrapSDK.h@T@OpenWrapSDKInitCompletionBlock"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initializeWithConfig:andCompletionHandler:"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK":{"abstract":[{"type":"text","text":"Provides global configurations for the OpenWrap SDK, e.g. enabling logging, location access, etc. These configurations are globally applicable for OpenWrap SDK; you don’t have to set these for every ad request."}],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK","kind":"symbol","title":"OpenWrapSDK","navigatorTitle":[{"text":"OpenWrapSDK","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/openwrapsdk","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenWrapSDK","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDKConfig":{"navigatorTitle":[{"kind":"identifier","text":"OpenWrapSDKConfig"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OpenWrapSDKConfig","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/openwrapsdkconfig","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig","title":"OpenWrapSDKConfig","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initializeWithConfig:andCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithConfig:andCompletionHandler:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"initializeWithConfig:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OpenWrapSDKConfig","text":"OpenWrapSDKConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"text":" ","kind":"text"},{"kind":"identifier","text":"andCompletionHandler:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"OpenWrapSDKInitCompletionBlock","preciseIdentifier":"c:OpenWrapSDK.h@T@OpenWrapSDKInitCompletionBlock","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDKInitCompletionBlock"},{"text":") ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"OpenWrapSDKInitCompletionBlock","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKInitCompletionBlock\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKInitCompletionBlock\/fragments","value":[{"text":"OpenWrapSDKInitCompletionBlock","kind":"identifier"}]},{"value":"initializeWithConfig:andCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1initialize(with:andCompletionHandler:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1initialize(with:andCompletionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"initializeWithConfig:andCompletionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK\/title","value":"OpenWrapSDK","op":"replace"},{"value":[{"kind":"identifier","text":"OpenWrapSDK"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK\/fragments","op":"replace"},{"value":"OpenWrapSDKConfig","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDKConfig\/fragments","value":[{"kind":"identifier","text":"OpenWrapSDKConfig"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}