{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDSAComplianceStatus"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus","preciseIdentifier":"c:@E@POBDSAComplianceStatus","text":"POBDSAComplianceStatus","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"status","content":[{"inlineContent":[{"type":"text","text":"The DSA compliance status to be set. See @c POBDSAComplianceStatus for supported values."}],"type":"paragraph"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/openwrapsdk\/setdsacompliancestatus(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/openwrapsdk\/setdsacompliancestatus(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setDSAComplianceStatus(_:)"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK"]]},"metadata":{"symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDSAComplianceStatus","kind":"identifier"},{"kind":"text","text":"("},{"text":"POBDSAComplianceStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBDSAComplianceStatus"},{"kind":"text","text":")"}],"title":"setDSAComplianceStatus(_:)","navigatorTitle":[{"text":"setDSAComplianceStatus:","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"roleHeading":"Type Method","externalID":"c:objc(cs)OpenWrapSDK(cm)setDSAComplianceStatus:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Sets the DSA (Digital Services Act) compliance status."}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSAComplianceStatus":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus","url":"\/documentation\/openwrapsdk\/pobdsacompliancestatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBDSAComplianceStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBDSAComplianceStatus"}],"role":"symbol","title":"POBDSAComplianceStatus","abstract":[{"type":"text","text":"DSA (Digital Services Act) compliance requirement status."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK":{"abstract":[{"type":"text","text":"Provides global configurations for the OpenWrap SDK, e.g. enabling logging, location access, etc. These configurations are globally applicable for OpenWrap SDK; you don’t have to set these for every ad request."}],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK","kind":"symbol","title":"OpenWrapSDK","navigatorTitle":[{"text":"OpenWrapSDK","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/openwrapsdk","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenWrapSDK","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/OpenWrapSDK/setDSAComplianceStatus(_:)":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/OpenWrapSDK\/setDSAComplianceStatus(_:)","url":"\/documentation\/openwrapsdk\/openwrapsdk\/setdsacompliancestatus(_:)","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setDSAComplianceStatus","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@POBDSAComplianceStatus","text":"POBDSAComplianceStatus"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setDSAComplianceStatus:","kind":"identifier"}],"role":"symbol","title":"setDSAComplianceStatus(_:)","abstract":[{"type":"text","text":"Sets the DSA (Digital Services Act) compliance status."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"setDSAComplianceStatus:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"setDSAComplianceStatus:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setDSAComplianceStatus:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSAComplianceStatus","preciseIdentifier":"c:@E@POBDSAComplianceStatus","text":"POBDSAComplianceStatus","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"status"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"POBDSAComplianceStatus","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus\/title"},{"value":[{"text":"POBDSAComplianceStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSAComplianceStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK\/title","value":"OpenWrapSDK"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK\/fragments","op":"replace","value":[{"text":"OpenWrapSDK","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setDSAComplianceStatus(_:)\/title","value":"setDSAComplianceStatus:","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1OpenWrapSDK~1setDSAComplianceStatus(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setDSAComplianceStatus:"}],"op":"replace"}]}]}