{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRenderingDelegate\/videoRendererDidOccur(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoRendererDidOccur","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@POBVideoAdEvent","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent","text":"POBVideoAdEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRenderingDelegate"]]},"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoRendererDidOccur","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"POBVideoAdEvent","preciseIdentifier":"c:@E@POBVideoAdEvent"},{"kind":"text","text":")"}],"required":true,"externalID":"c:objc(pl)POBVideoRenderingDelegate(im)videoRendererDidOccurAdEvent:","navigatorTitle":[{"text":"videoRendererDidOccurAdEvent:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"OpenWrapSDK"}],"role":"symbol","title":"videoRendererDidOccur(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobvideorenderingdelegate\/videorendererdidoccur(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobvideorenderingdelegate\/videorendererdidoccur(_:)"]}],"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoAdEvent":{"url":"\/documentation\/openwrapsdk\/pobvideoadevent","title":"POBVideoAdEvent","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBVideoAdEvent"}],"abstract":[{"type":"text","text":"Various Ad Event Types"}],"navigatorTitle":[{"kind":"identifier","text":"POBVideoAdEvent"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoRenderingDelegate":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBVideoRenderingDelegate"}],"url":"\/documentation\/openwrapsdk\/pobvideorenderingdelegate","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRenderingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBVideoRenderingDelegate","kind":"identifier"}],"title":"POBVideoRenderingDelegate","abstract":[{"text":"Video rendering delegate, It is used to provide video events from video renderer","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoRenderingDelegate/videoRendererDidOccur(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRenderingDelegate\/videoRendererDidOccur(_:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoRendererDidOccur"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@POBVideoAdEvent","kind":"typeIdentifier","text":"POBVideoAdEvent"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"videoRendererDidOccurAdEvent:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobvideorenderingdelegate\/videorendererdidoccur(_:)","type":"topic","title":"videoRendererDidOccur(_:)","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"videoRendererDidOccurAdEvent:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoRendererDidOccurAdEvent:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"videoRendererDidOccurAdEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBVideoAdEvent","preciseIdentifier":"c:@E@POBVideoAdEvent","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoAdEvent","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"event","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"POBVideoAdEvent","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoAdEvent\/fragments","value":[{"text":"POBVideoAdEvent","kind":"identifier"}],"op":"replace"},{"value":"POBVideoRenderingDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRenderingDelegate\/title"},{"value":[{"text":"POBVideoRenderingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRenderingDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRenderingDelegate~1videoRendererDidOccur(_:)\/title","value":"videoRendererDidOccurAdEvent:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoRendererDidOccurAdEvent:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRenderingDelegate~1videoRendererDidOccur(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}