{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid\/bid(with:expiresAfter:refreshInterval:customTargeting:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"bid(with:expiresAfter:refreshInterval:customTargeting:)","roleHeading":"Type Method","externalID":"c:objc(cs)POBBid(cm)bidWithBid:expiresAfter:refreshInterval:customTargeting:","navigatorTitle":[{"text":"bidWithBid:expiresAfter:refreshInterval:customTargeting:","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bid","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"POBBid","preciseIdentifier":"c:objc(cs)POBBid","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"expiresAfter"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"refreshInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"customTargeting","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> "},{"text":"Any","kind":"keyword"},{"text":"!","kind":"text"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbid\/bid(with:expiresafter:refreshinterval:customtargeting:)"]},{"paths":["\/documentation\/openwrapsdk\/pobbid\/bid(with:expiresafter:refreshinterval:customtargeting:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bid","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"bid","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBBid","text":"POBBid","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid"},{"text":"!, ","kind":"text"},{"text":"expiresAfter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"refreshInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"text":"customTargeting","kind":"externalParam"},{"kind":"text","text":" "},{"text":"targetingParams","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> "},{"kind":"keyword","text":"Any"},{"text":"!","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBid":{"navigatorTitle":[{"kind":"identifier","text":"POBBid"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBid","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbid","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid","kind":"symbol","abstract":[{"type":"text","text":"Holds information of winning bid along with all the bids that participated in the auction."}],"role":"symbol","title":"POBBid"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBid/bid(with:expiresAfter:refreshInterval:customTargeting:)":{"title":"bid(with:expiresAfter:refreshInterval:customTargeting:)","url":"\/documentation\/openwrapsdk\/pobbid\/bid(with:expiresafter:refreshinterval:customtargeting:)","navigatorTitle":[{"text":"bidWithBid:expiresAfter:refreshInterval:customTargeting:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bid"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)POBBid","kind":"typeIdentifier","text":"POBBid"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"expiresAfter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"text":"refreshInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"text":"customTargeting","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"!","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid\/bid(with:expiresAfter:refreshInterval:customTargeting:)","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"bidWithBid:expiresAfter:refreshInterval:customTargeting:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"bidWithBid:expiresAfter:refreshInterval:customTargeting:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"bidWithBid:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)POBBid","text":"POBBid","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bid"},{"text":" ","kind":"text"},{"text":"expiresAfter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"expiresAfter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"refreshInterval:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"refreshInterval"},{"kind":"text","text":" "},{"text":"customTargeting:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"targetingParams","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid\/title","op":"replace","value":"POBBid"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid\/fragments","value":[{"kind":"identifier","text":"POBBid"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid~1bid(with:expiresAfter:refreshInterval:customTargeting:)\/title","op":"replace","value":"bidWithBid:expiresAfter:refreshInterval:customTargeting:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid~1bid(with:expiresAfter:refreshInterval:customTargeting:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"bidWithBid:expiresAfter:refreshInterval:customTargeting:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}