{"metadata":{"navigatorTitle":[{"text":"initWithBidDetails:andRequestDetails:","kind":"identifier"}],"role":"symbol","roleHeading":"Initializer","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(cs)POBBid(im)initWithBidDetails:andRequestDetails:","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"!("},{"text":"bidDetails","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]!, ","kind":"text"},{"kind":"externalParam","text":"andRequestDetails"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"title":"init(bidDetails:andRequestDetails:)"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid"]]},"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid\/init(bidDetails:andRequestDetails:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"!(","kind":"text"},{"text":"bidDetails","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!, ","kind":"text"},{"text":"andRequestDetails","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"requestDetails"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbid\/init(biddetails:andrequestdetails:)"]},{"paths":["\/documentation\/openwrapsdk\/pobbid\/init(biddetails:andrequestdetails:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBid/init(bidDetails:andRequestDetails:)":{"title":"init(bidDetails:andRequestDetails:)","url":"\/documentation\/openwrapsdk\/pobbid\/init(biddetails:andrequestdetails:)","navigatorTitle":[{"text":"initWithBidDetails:andRequestDetails:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"bidDetails"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!, ","kind":"text"},{"text":"andRequestDetails","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid\/init(bidDetails:andRequestDetails:)","abstract":[],"kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBid":{"navigatorTitle":[{"kind":"identifier","text":"POBBid"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBid","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbid","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid","kind":"symbol","abstract":[{"type":"text","text":"Holds information of winning bid along with all the bids that participated in the auction."}],"role":"symbol","title":"POBBid"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithBidDetails:andRequestDetails:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBidDetails:andRequestDetails:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithBidDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bidDetails"},{"text":" ","kind":"text"},{"text":"andRequestDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"requestDetails","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"initWithBidDetails:andRequestDetails:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid~1init(bidDetails:andRequestDetails:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid~1init(bidDetails:andRequestDetails:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBidDetails:andRequestDetails:"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid\/title","op":"replace","value":"POBBid"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid\/fragments","value":[{"text":"POBBid","kind":"identifier"}]}]}]}