{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"reward","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBReward","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward","text":"POBReward"},{"kind":"text","text":"!"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For example: {"},{"text":" ","type":"text"},{"type":"text","text":"“seatbid.bid.ext.rewardInfo”: {"},{"text":" ","type":"text"},{"type":"text","text":"“rewards”:[{"},{"type":"text","text":" "},{"type":"text","text":"“rewardType”: “type”,"},{"text":" ","type":"text"},{"type":"text","text":"“rewardValue”: “value” }]"},{"text":" ","type":"text"},{"type":"text","text":"}"},{"type":"text","text":" "},{"type":"text","text":"}"}]}]}],"metadata":{"title":"reward()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reward"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBReward","text":"POBReward"},{"text":"!","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"OpenWrapSDK"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"reward","kind":"identifier"}],"externalID":"c:objc(cs)POBBid(im)reward"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid\/reward()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobbid\/reward()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobbid\/reward()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBid":{"navigatorTitle":[{"kind":"identifier","text":"POBBid"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBid","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbid","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid","kind":"symbol","abstract":[{"type":"text","text":"Holds information of winning bid along with all the bids that participated in the auction."}],"role":"symbol","title":"POBBid"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBid/reward()":{"title":"reward()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reward"},{"text":"() -> ","kind":"text"},{"text":"POBReward","preciseIdentifier":"c:objc(cs)POBReward","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"\/documentation\/openwrapsdk\/pobbid\/reward()","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"reward","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid\/reward()"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBReward":{"title":"POBReward","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBReward","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobreward","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBReward"}],"abstract":[{"type":"text","text":"Holds the general information about Reward to be provided to user."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"reward","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"reward","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward","text":"POBReward","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBReward"},{"kind":"text","text":" *) "},{"text":"reward","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"POBBid","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBBid"}]},{"op":"replace","value":"reward","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid~1reward()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reward"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid~1reward()\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBReward\/title","value":"POBReward","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBReward\/fragments","value":[{"text":"POBReward","kind":"identifier"}],"op":"replace"}]}]}