{"sections":[],"metadata":{"symbolKind":"init","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"text":"cgSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"OpenWrapSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCGSize:"}],"roleHeading":"Initializer","externalID":"c:objc(cs)POBAdSize(im)initWithCGSize:","title":"init(cgSize:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobadsize\/init(cgsize:)-5hrmg"]},{"paths":["\/documentation\/openwrapsdk\/pobadsize\/init(cgsize:)-5hrmg"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdSize"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"!("},{"text":"cgSize","kind":"externalParam"},{"kind":"text","text":" "},{"text":"size","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdSize\/init(cgSize:)-5hrmg","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdSize":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBAdSize","kind":"identifier"}],"navigatorTitle":[{"text":"POBAdSize","kind":"identifier"}],"title":"POBAdSize","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdSize","abstract":[{"type":"text","text":"Defines the size of a banner ad."}],"url":"\/documentation\/openwrapsdk\/pobadsize","kind":"symbol","type":"topic","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdSize/init(cgSize:)-5hrmg":{"url":"\/documentation\/openwrapsdk\/pobadsize\/init(cgsize:)-5hrmg","type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithCGSize:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdSize\/init(cgSize:)-5hrmg","title":"init(cgSize:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"!("},{"text":"cgSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithCGSize:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCGSize:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCGSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"size","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdSize\/title","value":"POBAdSize"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdSize\/fragments","value":[{"kind":"identifier","text":"POBAdSize"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdSize~1init(cgSize:)-5hrmg\/title","value":"initWithCGSize:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdSize~1init(cgSize:)-5hrmg\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCGSize:"}]}]}]}