{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdSize"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdSize\/isZero()"},"kind":"symbol","metadata":{"symbolKind":"method","title":"isZero()","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(cs)POBAdSize(im)isZero","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isZero"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isZero","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobadsize\/iszero()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobadsize\/iszero()"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isZero"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"syntax":null,"code":["      NO, if the size is not equal to CGSizeZero."],"type":"codeListing"}]}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdSize/isZero()":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdSize\/isZero()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isZero","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isZero","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobadsize\/iszero()","title":"isZero()","type":"topic","kind":"symbol","abstract":[],"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdSize":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBAdSize","kind":"identifier"}],"navigatorTitle":[{"text":"POBAdSize","kind":"identifier"}],"title":"POBAdSize","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdSize","abstract":[{"type":"text","text":"Defines the size of a banner ad."}],"url":"\/documentation\/openwrapsdk\/pobadsize","kind":"symbol","type":"topic","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"isZero","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isZero"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isZero","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdSize~1isZero()\/title","value":"isZero"},{"value":[{"text":"- ","kind":"text"},{"text":"isZero","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdSize~1isZero()\/fragments"},{"op":"replace","value":"POBAdSize","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdSize\/title"},{"value":[{"kind":"identifier","text":"POBAdSize"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdSize\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}