{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEvent"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedadevent\/interactiondelegate()"]},{"paths":["\/documentation\/openwrapsdk\/pobrewardedadevent\/interactiondelegate()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEvent\/interactionDelegate()"},"kind":"symbol","metadata":{"externalID":"c:objc(pl)POBRewardedAdEvent(im)interactionDelegate","title":"interactionDelegate()","modules":[{"name":"OpenWrapSDK"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"interactionDelegate","kind":"identifier"},{"kind":"text","text":"() -> any "},{"kind":"typeIdentifier","text":"POBFullscreenAdInteractionDelegate","preciseIdentifier":"c:objc(pl)POBFullscreenAdInteractionDelegate"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"interactionDelegate"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interactionDelegate","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate","text":"POBFullscreenAdInteractionDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBFullscreenAdInteractionDelegate"}]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate":{"role":"symbol","title":"POBFullscreenAdInteractionDelegate","navigatorTitle":[{"kind":"identifier","text":"POBFullscreenAdInteractionDelegate"}],"abstract":[{"type":"text","text":"This delegate is used to inform the fullscreen ad events from OpenWrap SDK ads. Implement this if your ad server implementation requires to be informed about these events."}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBFullscreenAdInteractionDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEvent/interactionDelegate()":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"interactionDelegate"}],"url":"\/documentation\/openwrapsdk\/pobrewardedadevent\/interactiondelegate()","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEvent\/interactionDelegate()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interactionDelegate"},{"text":"() -> any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBFullscreenAdInteractionDelegate","text":"POBFullscreenAdInteractionDelegate"}],"title":"interactionDelegate()","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEvent":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBRewardedAdEvent"}],"type":"topic","role":"symbol","abstract":[{"text":"The rewarded custom event protocol. Your rewarded custom event handler must implement this protocol to communicate with the ad server SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBRewardedAdEvent"}],"url":"\/documentation\/openwrapsdk\/pobrewardedadevent","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEvent","title":"POBRewardedAdEvent"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"interactionDelegate","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interactionDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Qoobjc(pl)POBFullscreenAdInteractionDelegate","kind":"typeIdentifier","text":"id<POBFullscreenAdInteractionDelegate>"},{"text":") ","kind":"text"},{"text":"interactionDelegate","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"POBFullscreenAdInteractionDelegate","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate\/fragments","value":[{"text":"POBFullscreenAdInteractionDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEvent~1interactionDelegate()\/title","value":"interactionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEvent~1interactionDelegate()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interactionDelegate"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEvent\/title","value":"POBRewardedAdEvent","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEvent\/fragments","op":"replace","value":[{"text":"POBRewardedAdEvent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}