{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"requestAdWithBid:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"requestAd(with:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestAd","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"POBBid","preciseIdentifier":"c:objc(cs)POBBid"},{"text":"?)","kind":"text"}],"externalID":"c:objc(pl)POBRewardedAdEvent(im)requestAdWithBid:","modules":[{"name":"OpenWrapSDK"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAd"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"text":"bid","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid","kind":"typeIdentifier","text":"POBBid","preciseIdentifier":"c:objc(cs)POBBid"},{"text":"?)","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedadevent\/requestad(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedadevent\/requestad(with:)"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEvent"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEvent\/requestAd(with:)","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEvent/requestAd(with:)":{"required":true,"url":"\/documentation\/openwrapsdk\/pobrewardedadevent\/requestad(with:)","abstract":[],"navigatorTitle":[{"text":"requestAdWithBid:","kind":"identifier"}],"kind":"symbol","title":"requestAd(with:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAd"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"POBBid","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBid"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEvent\/requestAd(with:)","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBid":{"navigatorTitle":[{"kind":"identifier","text":"POBBid"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBid","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbid","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid","kind":"symbol","abstract":[{"type":"text","text":"Holds information of winning bid along with all the bids that participated in the auction."}],"role":"symbol","title":"POBBid"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEvent":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBRewardedAdEvent"}],"type":"topic","role":"symbol","abstract":[{"text":"The rewarded custom event protocol. Your rewarded custom event handler must implement this protocol to communicate with the ad server SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBRewardedAdEvent"}],"url":"\/documentation\/openwrapsdk\/pobrewardedadevent","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEvent","title":"POBRewardedAdEvent"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"requestAdWithBid:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestAdWithBid:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"requestAdWithBid:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBBid","preciseIdentifier":"c:objc(cs)POBBid","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bid"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"requestAdWithBid:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEvent~1requestAd(with:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"requestAdWithBid:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEvent~1requestAd(with:)\/fragments"},{"value":"POBBid","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid\/fragments","op":"replace","value":[{"text":"POBBid","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEvent\/title","op":"replace","value":"POBRewardedAdEvent"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEvent\/fragments","value":[{"kind":"identifier","text":"POBRewardedAdEvent"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}