{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEvent\/setDelegate(_:)"},"metadata":{"modules":[{"name":"OpenWrapSDK"}],"title":"setDelegate(_:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","text":"POBRewardedAdEventDelegate","preciseIdentifier":"c:objc(pl)POBRewardedAdEventDelegate"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"setDelegate:"}],"externalID":"c:objc(pl)POBRewardedAdEvent(im)setDelegate:","roleHeading":"Instance Method","role":"symbol"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobrewardedadevent\/setdelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobrewardedadevent\/setdelegate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEvent"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDelegate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)POBRewardedAdEventDelegate","text":"POBRewardedAdEventDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEvent/setDelegate(_:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setDelegate:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobrewardedadevent\/setdelegate(_:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEvent\/setDelegate(_:)","required":true,"title":"setDelegate(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)POBRewardedAdEventDelegate","text":"POBRewardedAdEventDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEvent":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBRewardedAdEvent"}],"type":"topic","role":"symbol","abstract":[{"text":"The rewarded custom event protocol. Your rewarded custom event handler must implement this protocol to communicate with the ad server SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBRewardedAdEvent"}],"url":"\/documentation\/openwrapsdk\/pobrewardedadevent","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEvent","title":"POBRewardedAdEvent"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAdEventDelegate":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAdEventDelegate","role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobrewardedadeventdelegate","title":"POBRewardedAdEventDelegate","navigatorTitle":[{"text":"POBRewardedAdEventDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The rewarded custom event delegate. It is used to inform the ad server SDK events back to the OpenWrap SDK."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBRewardedAdEventDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"setDelegate:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setDelegate:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)POBRewardedAdEventDelegate","text":"id<POBRewardedAdEventDelegate>"},{"kind":"text","text":") "},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"setDelegate:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEvent~1setDelegate(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"setDelegate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEvent~1setDelegate(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEvent\/title","value":"POBRewardedAdEvent","op":"replace"},{"value":[{"text":"POBRewardedAdEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEvent\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate\/title","value":"POBRewardedAdEventDelegate"},{"value":[{"text":"POBRewardedAdEventDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAdEventDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}