{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidsProvider\/bid(withId:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bid"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!) -> (any ","kind":"text"},{"text":"POBAdDescriptor","preciseIdentifier":"c:objc(pl)POBAdDescriptor","kind":"typeIdentifier"},{"text":")!","kind":"text"}],"required":true,"externalID":"c:objc(pl)POBBidsProvider(im)bidWithId:","navigatorTitle":[{"kind":"identifier","text":"bidWithId:"}],"symbolKind":"method","roleHeading":"Instance Method","title":"bid(withId:)","role":"symbol","modules":[{"name":"OpenWrapSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bid"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withId"},{"text":" ","kind":"text"},{"text":"bidId","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!) -> (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBAdDescriptor","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor","text":"POBAdDescriptor"},{"text":")!","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidsProvider"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbidsprovider\/bid(withid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobbidsprovider\/bid(withid:)"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdDescriptor":{"url":"\/documentation\/openwrapsdk\/pobaddescriptor","type":"topic","title":"POBAdDescriptor","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBAdDescriptor"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdDescriptor","role":"symbol","abstract":[{"type":"text","text":"Ad descriptor protocol, provided creative string through "},{"type":"codeVoice","code":"renderableContent"},{"text":". POBAdRendering protocol renders object which conforms to POBAdDescriptor protocol","type":"text"}],"navigatorTitle":[{"text":"POBAdDescriptor","kind":"identifier"}],"kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidsProvider/bid(withId:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"bidWithId:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbidsprovider\/bid(withid:)","required":true,"title":"bid(withId:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bid","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> (any "},{"kind":"typeIdentifier","text":"POBAdDescriptor","preciseIdentifier":"c:objc(pl)POBAdDescriptor"},{"kind":"text","text":")!"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidsProvider\/bid(withId:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidsProvider":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidsProvider"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"POBBidsProvider","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbidsprovider","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidsProvider","title":"POBBidsProvider"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"bidWithId:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bidWithId:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id<POBAdDescriptor>","preciseIdentifier":"c:Qoobjc(pl)POBAdDescriptor"},{"text":") ","kind":"text"},{"text":"bidWithId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"bidId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"POBAdDescriptor","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdDescriptor\/fragments","value":[{"kind":"identifier","text":"POBAdDescriptor"}]},{"value":"bidWithId:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidsProvider~1bid(withId:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidsProvider~1bid(withId:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"bidWithId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidsProvider\/title","value":"POBBidsProvider"},{"op":"replace","value":[{"text":"POBBidsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidsProvider\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}