{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventdidexpire()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventdidexpire()"]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullscreenAdEventDidExpire","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"OpenWrapSDK"}],"title":"fullscreenAdEventDidExpire()","navigatorTitle":[{"text":"fullscreenAdEventDidExpire","kind":"identifier"}],"symbolKind":"method","externalID":"c:objc(pl)POBFullscreenAdInteractionDelegate(im)fullscreenAdEventDidExpire","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreenAdEventDidExpire"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidExpire()","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate":{"role":"symbol","title":"POBFullscreenAdInteractionDelegate","navigatorTitle":[{"kind":"identifier","text":"POBFullscreenAdInteractionDelegate"}],"abstract":[{"type":"text","text":"This delegate is used to inform the fullscreen ad events from OpenWrap SDK ads. Implement this if your ad server implementation requires to be informed about these events."}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBFullscreenAdInteractionDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventDidExpire()":{"kind":"symbol","type":"topic","title":"fullscreenAdEventDidExpire()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreenAdEventDidExpire"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"fullscreenAdEventDidExpire","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventdidexpire()","role":"symbol","abstract":[],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventDidExpire()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"fullscreenAdEventDidExpire","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"fullscreenAdEventDidExpire","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"fullscreenAdEventDidExpire"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate\/title","op":"replace","value":"POBFullscreenAdInteractionDelegate"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate\/fragments","value":[{"kind":"identifier","text":"POBFullscreenAdInteractionDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventDidExpire()\/title","value":"fullscreenAdEventDidExpire","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventDidExpire()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fullscreenAdEventDidExpire"}]}]}]}