{"variants":[{"paths":["\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventwillleaveapplication()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventwillleaveapplication()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillLeaveApplication()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullscreenAdEventWillLeaveApplication","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"metadata":{"title":"fullscreenAdEventWillLeaveApplication()","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreenAdEventWillLeaveApplication","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"OpenWrapSDK"}],"externalID":"c:objc(pl)POBFullscreenAdInteractionDelegate(im)fullscreenAdEventWillLeaveApplication","navigatorTitle":[{"kind":"identifier","text":"fullscreenAdEventWillLeaveApplication"}],"required":true,"roleHeading":"Instance Method","role":"symbol"},"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventWillLeaveApplication()":{"title":"fullscreenAdEventWillLeaveApplication()","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreenAdEventWillLeaveApplication","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventWillLeaveApplication()","abstract":[],"url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventwillleaveapplication()","navigatorTitle":[{"kind":"identifier","text":"fullscreenAdEventWillLeaveApplication"}],"required":true,"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate":{"role":"symbol","title":"POBFullscreenAdInteractionDelegate","navigatorTitle":[{"kind":"identifier","text":"POBFullscreenAdInteractionDelegate"}],"abstract":[{"type":"text","text":"This delegate is used to inform the fullscreen ad events from OpenWrap SDK ads. Implement this if your ad server implementation requires to be informed about these events."}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBFullscreenAdInteractionDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"fullscreenAdEventWillLeaveApplication","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"fullscreenAdEventWillLeaveApplication","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"fullscreenAdEventWillLeaveApplication","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventWillLeaveApplication()\/title","value":"fullscreenAdEventWillLeaveApplication","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventWillLeaveApplication()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"fullscreenAdEventWillLeaveApplication","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate\/title","value":"POBFullscreenAdInteractionDelegate"},{"value":[{"text":"POBFullscreenAdInteractionDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}