{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullscreenAdEventImpression","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventImpression()"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventimpression()"]},{"paths":["\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventimpression()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"fullscreenAdEventImpression()","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"fullscreenAdEventImpression"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fullscreenAdEventImpression","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:objc(pl)POBFullscreenAdInteractionDelegate(im)fullscreenAdEventImpression","required":true,"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"method"},"kind":"symbol","references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate/fullscreenAdEventImpression()":{"title":"fullscreenAdEventImpression()","url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate\/fullscreenadeventimpression()","navigatorTitle":[{"kind":"identifier","text":"fullscreenAdEventImpression"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullscreenAdEventImpression"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate\/fullscreenAdEventImpression()","abstract":[],"required":true},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBFullscreenAdInteractionDelegate":{"role":"symbol","title":"POBFullscreenAdInteractionDelegate","navigatorTitle":[{"kind":"identifier","text":"POBFullscreenAdInteractionDelegate"}],"abstract":[{"type":"text","text":"This delegate is used to inform the fullscreen ad events from OpenWrap SDK ads. Implement this if your ad server implementation requires to be informed about these events."}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBFullscreenAdInteractionDelegate","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobfullscreenadinteractiondelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBFullscreenAdInteractionDelegate"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"fullscreenAdEventImpression","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"fullscreenAdEventImpression","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"fullscreenAdEventImpression","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventImpression()\/title","value":"fullscreenAdEventImpression"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate~1fullscreenAdEventImpression()\/fragments","value":[{"kind":"text","text":"- "},{"text":"fullscreenAdEventImpression","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate\/title","value":"POBFullscreenAdInteractionDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBFullscreenAdInteractionDelegate\/fragments","value":[{"text":"POBFullscreenAdInteractionDelegate","kind":"identifier"}]}]}]}