{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent\/proceed(onError:andDescription:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent"]]},"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobbidevent\/proceed(onerror:anddescription:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobbidevent\/proceed(onerror:anddescription:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proceed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"onError","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"code"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@POBBidEventErrorCode","text":"POBBidEventErrorCode","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"andDescription"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"If integration type is of primary ad server case like DFP and MoPub, the execution is continued by invoking ad server call ignoring OpenWrap’s bid.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"In case of No ad server integration, flow is completed by setting its state to default considering error at client side."}],"type":"paragraph"}]}],"metadata":{"required":true,"title":"proceed(onError:andDescription:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"proceed"},{"text":"(","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@POBBidEventErrorCode","text":"POBBidEventErrorCode","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"andDescription","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!)","kind":"text"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"proceedOnError:andDescription:","kind":"identifier"}],"externalID":"c:objc(pl)POBBidEvent(im)proceedOnError:andDescription:"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventErrorCode":{"navigatorTitle":[{"text":"POBBidEventErrorCode","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbideventerrorcode","abstract":[{"type":"text","text":"Specify the bid event error"}],"kind":"symbol","title":"POBBidEventErrorCode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidEventErrorCode"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEvent":{"navigatorTitle":[{"text":"POBBidEvent","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidEvent"}],"abstract":[{"type":"text","text":"This prototol is responsinble for interacting with SDK’s banner & interstitial objects to get bid details, continue the bid execution flow."},{"type":"text","text":" "},{"text":"All methods of this protocol are expected to be called from Main thread.","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobbidevent","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent","title":"POBBidEvent","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEvent/proceed(onError:andDescription:)":{"type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent\/proceed(onError:andDescription:)","abstract":[],"navigatorTitle":[{"text":"proceedOnError:andDescription:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbidevent\/proceed(onerror:anddescription:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"proceed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onError"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@POBBidEventErrorCode","text":"POBBidEventErrorCode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!)"}],"title":"proceed(onError:andDescription:)","kind":"symbol","role":"symbol","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"proceedOnError:andDescription:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"proceedOnError:andDescription:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"proceedOnError:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@POBBidEventErrorCode","text":"POBBidEventErrorCode","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode"},{"text":") ","kind":"text"},{"text":"code","kind":"internalParam"},{"kind":"text","text":" "},{"text":"andDescription:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"description"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"POBBidEventErrorCode","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode\/fragments","value":[{"text":"POBBidEventErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent\/title","op":"replace","value":"POBBidEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent\/fragments","value":[{"text":"POBBidEvent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent~1proceed(onError:andDescription:)\/title","value":"proceedOnError:andDescription:","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent~1proceed(onError:andDescription:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"proceedOnError:andDescription:","kind":"identifier"}]}]}]}