{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalGenerator"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generateSignal","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"biddingHost","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost","preciseIdentifier":"c:@E@POBSDKBiddingHost","kind":"typeIdentifier","text":"POBSDKBiddingHost"},{"kind":"text","text":", "},{"text":"andConfig","kind":"externalParam"},{"kind":"text","text":" "},{"text":"config","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)POBSignalConfig","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig","text":"POBSignalConfig","kind":"typeIdentifier"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK bidding host, requesting for signal"}]}],"name":"biddingHost"}],"kind":"parameters"},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"This should be used only in case of SDK bidding type of integration."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"generateSignal","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@POBSDKBiddingHost","kind":"typeIdentifier","text":"POBSDKBiddingHost"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andConfig"},{"text":": ","kind":"text"},{"text":"POBSignalConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBSignalConfig"},{"kind":"text","text":"!) -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"externalID":"c:objc(cs)POBSignalGenerator(cm)generateSignalForBiddingHost:andConfig:","role":"symbol","modules":[{"name":"OpenWrapSDK"}],"symbolKind":"method","title":"generateSignal(for:andConfig:)","navigatorTitle":[{"text":"generateSignalForBiddingHost:andConfig:","kind":"identifier"}],"roleHeading":"Type Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobsignalgenerator\/generatesignal(for:andconfig:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobsignalgenerator\/generatesignal(for:andconfig:)"]}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalGenerator\/generateSignal(for:andConfig:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSignalGenerator":{"navigatorTitle":[{"text":"POBSignalGenerator","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobsignalgenerator","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"POBSignalGenerator","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalGenerator","type":"topic","title":"POBSignalGenerator","kind":"symbol","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSDKBiddingHost":{"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost","navigatorTitle":[{"text":"POBSDKBiddingHost","kind":"identifier"}],"title":"POBSDKBiddingHost","type":"topic","abstract":[{"text":"Indicates bidding host for S2S bidders","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobsdkbiddinghost","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBSDKBiddingHost","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSignalGenerator/generateSignal(for:andConfig:)":{"navigatorTitle":[{"text":"generateSignalForBiddingHost:andConfig:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobsignalgenerator\/generatesignal(for:andconfig:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generateSignal"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"POBSDKBiddingHost","preciseIdentifier":"c:@E@POBSDKBiddingHost","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"andConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBSignalConfig","text":"POBSignalConfig"},{"text":"!) -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalGenerator\/generateSignal(for:andConfig:)","type":"topic","kind":"symbol","title":"generateSignal(for:andConfig:)","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBSignalConfig":{"navigatorTitle":[{"kind":"identifier","text":"POBSignalConfig"}],"url":"\/documentation\/openwrapsdk\/pobsignalconfig","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBSignalConfig","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig","type":"topic","title":"POBSignalConfig","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"generateSignalForBiddingHost:andConfig:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"generateSignalForBiddingHost:andConfig:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"generateSignalForBiddingHost:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSDKBiddingHost","kind":"typeIdentifier","text":"POBSDKBiddingHost","preciseIdentifier":"c:@E@POBSDKBiddingHost"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"biddingHost"},{"kind":"text","text":" "},{"text":"andConfig:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)POBSignalConfig","text":"POBSignalConfig","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBSignalConfig","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"config","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"POBSignalGenerator","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalGenerator\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalGenerator\/fragments","value":[{"text":"POBSignalGenerator","kind":"identifier"}]},{"op":"replace","value":"POBSDKBiddingHost","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost\/title"},{"value":[{"text":"POBSDKBiddingHost","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSDKBiddingHost\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalGenerator~1generateSignal(for:andConfig:)\/title","op":"replace","value":"generateSignalForBiddingHost:andConfig:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalGenerator~1generateSignal(for:andConfig:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"generateSignalForBiddingHost:andConfig:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig\/title","op":"replace","value":"POBSignalConfig"},{"op":"replace","value":[{"kind":"identifier","text":"POBSignalConfig"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBSignalConfig\/fragments"}]}]}