{"abstract":[{"type":"text","text":"Record impression when at least 1 pixel of the ad is visible."}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/method1pxViewable","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobimpressioncountingmethod\/method1pxviewable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobimpressioncountingmethod\/method1pxviewable"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"method1pxViewable"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"POBImpressionCountingMethod1pxViewable","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"POBImpressionCountingMethod.method1pxViewable","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"method1pxViewable"}],"externalID":"c:@E@POBImpressionCountingMethod@POBImpressionCountingMethod1pxViewable","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBImpressionCountingMethod":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBImpressionCountingMethod"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBImpressionCountingMethod","kind":"identifier"}],"kind":"symbol","title":"POBImpressionCountingMethod","url":"\/documentation\/openwrapsdk\/pobimpressioncountingmethod","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod","type":"topic","abstract":[{"type":"text","text":"Enum represents different criteria of ad impression record."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBImpressionCountingMethod/method1pxViewable":{"url":"\/documentation\/openwrapsdk\/pobimpressioncountingmethod\/method1pxviewable","title":"POBImpressionCountingMethod.method1pxViewable","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBImpressionCountingMethod1pxViewable"}],"type":"topic","abstract":[{"text":"Record impression when at least 1 pixel of the ad is visible.","type":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/method1pxViewable","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"method1pxViewable"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"POBImpressionCountingMethod1pxViewable"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"POBImpressionCountingMethod1pxViewable","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"POBImpressionCountingMethod1pxViewable"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod\/title","op":"replace","value":"POBImpressionCountingMethod"},{"value":[{"text":"POBImpressionCountingMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod~1method1pxViewable\/title","value":"POBImpressionCountingMethod1pxViewable"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod~1method1pxViewable\/fragments","op":"replace","value":[{"text":"POBImpressionCountingMethod1pxViewable","kind":"identifier"}]}]}]}