{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/methodOnLoad"},"sections":[],"abstract":[{"type":"text","text":"Record impression when ad is loaded in the web view."}],"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"methodOnLoad"}],"modules":[{"name":"OpenWrapSDK"}],"title":"POBImpressionCountingMethod.methodOnLoad","navigatorTitle":[{"kind":"identifier","text":"POBImpressionCountingMethodOnLoad"}],"symbolKind":"case","externalID":"c:@E@POBImpressionCountingMethod@POBImpressionCountingMethodOnLoad","role":"symbol"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"methodOnLoad"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobimpressioncountingmethod\/methodonload"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobimpressioncountingmethod\/methodonload"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBImpressionCountingMethod/methodOnLoad":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBImpressionCountingMethodOnLoad"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"methodOnLoad","kind":"identifier"}],"title":"POBImpressionCountingMethod.methodOnLoad","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobimpressioncountingmethod\/methodonload","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod\/methodOnLoad","type":"topic","abstract":[{"type":"text","text":"Record impression when ad is loaded in the web view."}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBImpressionCountingMethod":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBImpressionCountingMethod"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBImpressionCountingMethod","kind":"identifier"}],"kind":"symbol","title":"POBImpressionCountingMethod","url":"\/documentation\/openwrapsdk\/pobimpressioncountingmethod","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpressionCountingMethod","type":"topic","abstract":[{"type":"text","text":"Enum represents different criteria of ad impression record."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"POBImpressionCountingMethodOnLoad"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"POBImpressionCountingMethodOnLoad","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"POBImpressionCountingMethodOnLoad"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod~1methodOnLoad\/title","op":"replace","value":"POBImpressionCountingMethodOnLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod~1methodOnLoad\/fragments","value":[{"text":"POBImpressionCountingMethodOnLoad","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod\/title","value":"POBImpressionCountingMethod","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpressionCountingMethod\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBImpressionCountingMethod"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}