{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset\/init(id:required:type:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"kind":"text","text":" "},{"text":"assetId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"required","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"POBNativeDataAssetType","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType","preciseIdentifier":"c:@E@POBNativeDataAssetType"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Initializer","symbolKind":"init","navigatorTitle":[{"text":"initWithId:required:type:","kind":"identifier"}],"role":"symbol","modules":[{"name":"OpenWrapSDK"}],"title":"init(id:required:type:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"required"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@POBNativeDataAssetType","text":"POBNativeDataAssetType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)POBNativeRequestDataAsset(im)initWithId:required:type:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativerequestdataasset\/init(id:required:type:)"]},{"paths":["\/documentation\/openwrapsdk\/pobnativerequestdataasset\/init(id:required:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestDataAsset":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset","kind":"symbol","type":"topic","title":"POBNativeRequestDataAsset","navigatorTitle":[{"text":"POBNativeRequestDataAsset","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBNativeRequestDataAsset","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/openwrapsdk\/pobnativerequestdataasset"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeRequestDataAsset/init(id:required:type:)":{"type":"topic","title":"init(id:required:type:)","url":"\/documentation\/openwrapsdk\/pobnativerequestdataasset\/init(id:required:type:)","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"required","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"POBNativeDataAssetType","preciseIdentifier":"c:@E@POBNativeDataAssetType"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithId:required:type:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeRequestDataAsset\/init(id:required:type:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeDataAssetType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"POBNativeDataAssetType","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Native Data asset types"}],"navigatorTitle":[{"text":"POBNativeDataAssetType","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobnativedataassettype","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType","title":"POBNativeDataAssetType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithId:required:type:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithId:required:type:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"assetId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"required:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"required","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type:"},{"kind":"text","text":"("},{"text":"POBNativeDataAssetType","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeDataAssetType","preciseIdentifier":"c:@E@POBNativeDataAssetType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset\/title","op":"replace","value":"POBNativeRequestDataAsset"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset\/fragments","value":[{"kind":"identifier","text":"POBNativeRequestDataAsset"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset~1init(id:required:type:)\/title","op":"replace","value":"initWithId:required:type:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithId:required:type:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeRequestDataAsset~1init(id:required:type:)\/fragments"},{"value":"POBNativeDataAssetType","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/title"},{"value":[{"kind":"identifier","text":"POBNativeDataAssetType"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeDataAssetType\/fragments"}]}]}