{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/adExpiry","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adExpiry"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","externalID":"c:@E@POBBidEventErrorCode@POBBidEventErrorAdExpiry","navigatorTitle":[{"kind":"identifier","text":"POBBidEventErrorAdExpiry"}],"title":"POBBidEventErrorCode.adExpiry","roleHeading":"Case","symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbideventerrorcode\/adexpiry"]},{"paths":["\/documentation\/openwrapsdk\/pobbideventerrorcode\/adexpiry"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"adExpiry","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Indicates bid expiry","type":"text"}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventErrorCode/adExpiry":{"url":"\/documentation\/openwrapsdk\/pobbideventerrorcode\/adexpiry","title":"POBBidEventErrorCode.adExpiry","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/adExpiry","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adExpiry"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"POBBidEventErrorAdExpiry","kind":"identifier"}],"abstract":[{"text":"Indicates bid expiry","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventErrorCode":{"navigatorTitle":[{"text":"POBBidEventErrorCode","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbideventerrorcode","abstract":[{"type":"text","text":"Specify the bid event error"}],"kind":"symbol","title":"POBBidEventErrorCode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidEventErrorCode"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"POBBidEventErrorAdExpiry","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"POBBidEventErrorAdExpiry"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"POBBidEventErrorAdExpiry"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode~1adExpiry\/title","value":"POBBidEventErrorAdExpiry","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode~1adExpiry\/fragments","value":[{"text":"POBBidEventErrorAdExpiry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode\/title","op":"replace","value":"POBBidEventErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode\/fragments","value":[{"kind":"identifier","text":"POBBidEventErrorCode"}]}]}]}