{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"POBBidEventErrorClientSideAuctionLoss"}],"symbolKind":"case","modules":[{"name":"OpenWrapSDK"}],"title":"POBBidEventErrorCode.clientSideAuctionLoss","roleHeading":"Case","externalID":"c:@E@POBBidEventErrorCode@POBBidEventErrorClientSideAuctionLoss","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientSideAuctionLoss"}],"role":"symbol"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Indicates client-side auction loss"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/clientSideAuctionLoss","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientSideAuctionLoss","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobbideventerrorcode\/clientsideauctionloss"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobbideventerrorcode\/clientsideauctionloss"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventErrorCode":{"navigatorTitle":[{"text":"POBBidEventErrorCode","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbideventerrorcode","abstract":[{"type":"text","text":"Specify the bid event error"}],"kind":"symbol","title":"POBBidEventErrorCode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidEventErrorCode"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventErrorCode/clientSideAuctionLoss":{"navigatorTitle":[{"text":"POBBidEventErrorClientSideAuctionLoss","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbideventerrorcode\/clientsideauctionloss","abstract":[{"text":"Indicates client-side auction loss","type":"text"}],"kind":"symbol","title":"POBBidEventErrorCode.clientSideAuctionLoss","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientSideAuctionLoss"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventErrorCode\/clientSideAuctionLoss","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"POBBidEventErrorClientSideAuctionLoss","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"POBBidEventErrorClientSideAuctionLoss"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"POBBidEventErrorClientSideAuctionLoss"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"POBBidEventErrorCode","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode\/fragments","op":"replace","value":[{"text":"POBBidEventErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode~1clientSideAuctionLoss\/title","op":"replace","value":"POBBidEventErrorClientSideAuctionLoss"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventErrorCode~1clientSideAuctionLoss\/fragments","value":[{"kind":"identifier","text":"POBBidEventErrorClientSideAuctionLoss"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}