{"abstract":[{"text":"Ad position is visible","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdPosition"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdPosition\/aboveFold","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobadposition\/abovefold"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobadposition\/abovefold"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aboveFold"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aboveFold"}],"externalID":"c:@E@POBAdPosition@POBAdPositionAboveFold","modules":[{"name":"OpenWrapSDK"}],"symbolKind":"case","roleHeading":"Case","title":"POBAdPosition.aboveFold","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBAdPositionAboveFold"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdPosition":{"abstract":[{"type":"text","text":"Fold placement of the ad to be served."}],"navigatorTitle":[{"text":"POBAdPosition","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadposition","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdPosition","title":"POBAdPosition","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBAdPosition","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdPosition/aboveFold":{"abstract":[{"type":"text","text":"Ad position is visible"}],"navigatorTitle":[{"text":"POBAdPositionAboveFold","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadposition\/abovefold","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdPosition\/aboveFold","title":"POBAdPosition.aboveFold","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aboveFold"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"POBAdPositionAboveFold"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"POBAdPositionAboveFold","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"POBAdPositionAboveFold","kind":"identifier"}]}],"kind":"declarations"}},{"value":"POBAdPosition","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdPosition\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdPosition\/fragments","value":[{"kind":"identifier","text":"POBAdPosition"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdPosition~1aboveFold\/title","op":"replace","value":"POBAdPositionAboveFold"},{"value":[{"kind":"identifier","text":"POBAdPositionAboveFold"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdPosition~1aboveFold\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}