{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdPosition\/belowFold","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdPosition"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"belowFold","kind":"identifier"}],"externalID":"c:@E@POBAdPosition@POBAdPositionBelowFold","navigatorTitle":[{"kind":"identifier","text":"POBAdPositionBelowFold"}],"symbolKind":"case","roleHeading":"Case","title":"POBAdPosition.belowFold","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"belowFold"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Ad position is not visible & it needs user to scroll the page to make it visible","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobadposition\/belowfold"]},{"paths":["\/documentation\/openwrapsdk\/pobadposition\/belowfold"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdPosition":{"abstract":[{"type":"text","text":"Fold placement of the ad to be served."}],"navigatorTitle":[{"text":"POBAdPosition","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadposition","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdPosition","title":"POBAdPosition","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBAdPosition","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdPosition/belowFold":{"abstract":[{"text":"Ad position is not visible & it needs user to scroll the page to make it visible","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"POBAdPositionBelowFold"}],"url":"\/documentation\/openwrapsdk\/pobadposition\/belowfold","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdPosition\/belowFold","type":"topic","title":"POBAdPosition.belowFold","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"belowFold","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"POBAdPositionBelowFold","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"POBAdPositionBelowFold"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"POBAdPositionBelowFold"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"POBAdPosition","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdPosition\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdPosition\/fragments","op":"replace","value":[{"text":"POBAdPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdPosition~1belowFold\/title","value":"POBAdPositionBelowFold"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdPosition~1belowFold\/fragments","value":[{"text":"POBAdPositionBelowFold","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}