{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/openwrapsdk\/pobadposition\/fullscreen"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobadposition\/fullscreen"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdPosition"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreen"}]}]}],"abstract":[{"text":"Ad is in full screen","type":"text"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreen","kind":"identifier"}],"externalID":"c:@E@POBAdPosition@POBAdPositionFullscreen","navigatorTitle":[{"text":"POBAdPositionFullscreen","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","title":"POBAdPosition.fullscreen","role":"symbol","modules":[{"name":"OpenWrapSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdPosition\/fullscreen"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdPosition":{"abstract":[{"type":"text","text":"Fold placement of the ad to be served."}],"navigatorTitle":[{"text":"POBAdPosition","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadposition","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdPosition","title":"POBAdPosition","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBAdPosition","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdPosition/fullscreen":{"abstract":[{"text":"Ad is in full screen","type":"text"}],"navigatorTitle":[{"text":"POBAdPositionFullscreen","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobadposition\/fullscreen","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdPosition\/fullscreen","type":"topic","title":"POBAdPosition.fullscreen","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreen","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"POBAdPositionFullscreen"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBAdPositionFullscreen"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"POBAdPositionFullscreen","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdPosition\/title","value":"POBAdPosition","op":"replace"},{"value":[{"kind":"identifier","text":"POBAdPosition"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdPosition\/fragments"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdPosition~1fullscreen\/title","op":"replace","value":"POBAdPositionFullscreen"},{"value":[{"text":"POBAdPositionFullscreen","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdPosition~1fullscreen\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}