{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/adFormat"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adFormat"},{"kind":"text","text":": "},{"text":"POBAdFormat","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBAdFormat"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest"]]},"metadata":{"role":"symbol","title":"adFormat","roleHeading":"Instance Property","externalID":"c:objc(cs)POBRequest(py)adFormat","navigatorTitle":[{"kind":"identifier","text":"adFormat"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adFormat"},{"text":": ","kind":"text"},{"text":"POBAdFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBAdFormat"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobrequest\/adformat"]},{"paths":["\/documentation\/openwrapsdk\/pobrequest\/adformat"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"POBRequest","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobrequest","abstract":[{"type":"text","text":"Represents an ad request for the given impression\/s & profile."}],"title":"POBRequest","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest","kind":"symbol","navigatorTitle":[{"text":"POBRequest","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest/adFormat":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/adFormat","kind":"symbol","role":"symbol","title":"adFormat","url":"\/documentation\/openwrapsdk\/pobrequest\/adformat","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"adFormat"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"POBAdFormat","preciseIdentifier":"c:@E@POBAdFormat"}],"type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdFormat":{"abstract":[{"text":"Indicates the ad format to request\/render","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadformat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBAdFormat","kind":"identifier"}],"title":"POBAdFormat","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat","navigatorTitle":[{"text":"POBAdFormat","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"adFormat"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"adFormat"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"POBAdFormat","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBAdFormat"},{"text":" ","kind":"text"},{"text":"adFormat","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest\/title","value":"POBRequest","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest\/fragments","value":[{"kind":"identifier","text":"POBRequest"}]},{"op":"replace","value":"adFormat","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1adFormat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1adFormat\/fragments","value":[{"text":"adFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat\/title","op":"replace","value":"POBAdFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat\/fragments","value":[{"kind":"identifier","text":"POBAdFormat"}]}]}]}