{"sections":[],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"!("},{"text":"publisherId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"profileId"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"adFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"POBAdFormat","preciseIdentifier":"c:@E@POBAdFormat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"impressions"},{"text":": [","kind":"text"},{"text":"POBImpression","preciseIdentifier":"c:objc(cs)POBImpression","kind":"typeIdentifier"},{"kind":"text","text":"]!)"}],"externalID":"c:objc(cs)POBRequest(im)initWithPublisherId:profileId:adFormat:impressions:","navigatorTitle":[{"kind":"identifier","text":"initWithPublisherId:profileId:adFormat:impressions:"}],"symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"OpenWrapSDK"}],"title":"init(publisherId:profileId:adFormat:impressions:)","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/init(publisherId:profileId:adFormat:impressions:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"!(","kind":"text"},{"kind":"externalParam","text":"publisherId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pubId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"profileId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"!, ","kind":"text"},{"text":"adFormat","kind":"externalParam"},{"kind":"text","text":": "},{"text":"POBAdFormat","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@POBAdFormat"},{"kind":"text","text":", "},{"text":"impressions","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBImpression","text":"POBImpression","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpression"},{"text":"]!)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobrequest\/init(publisherid:profileid:adformat:impressions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobrequest\/init(publisherid:profileid:adformat:impressions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest/init(publisherId:profileId:adFormat:impressions:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"!(","kind":"text"},{"text":"publisherId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"profileId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"!, ","kind":"text"},{"text":"adFormat","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@POBAdFormat","kind":"typeIdentifier","text":"POBAdFormat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"impressions"},{"kind":"text","text":": ["},{"text":"POBImpression","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBImpression"},{"text":"]!)","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithPublisherId:profileId:adFormat:impressions:","kind":"identifier"}],"abstract":[],"title":"init(publisherId:profileId:adFormat:impressions:)","url":"\/documentation\/openwrapsdk\/pobrequest\/init(publisherid:profileid:adformat:impressions:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest\/init(publisherId:profileId:adFormat:impressions:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBAdFormat":{"abstract":[{"text":"Indicates the ad format to request\/render","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobadformat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"POBAdFormat","kind":"identifier"}],"title":"POBAdFormat","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat","navigatorTitle":[{"text":"POBAdFormat","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBImpression":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBImpression","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBImpression"}],"kind":"symbol","abstract":[{"text":"Holds the general information about an ad impression. Use this class setters to pass impression level information in bid request.","type":"text"}],"title":"POBImpression","url":"\/documentation\/openwrapsdk\/pobimpression","navigatorTitle":[{"kind":"identifier","text":"POBImpression"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRequest":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"POBRequest","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/openwrapsdk\/pobrequest","abstract":[{"type":"text","text":"Represents an ad request for the given impression\/s & profile."}],"title":"POBRequest","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRequest","kind":"symbol","navigatorTitle":[{"text":"POBRequest","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPublisherId:profileId:adFormat:impressions:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPublisherId:profileId:adFormat:impressions:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithPublisherId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pubId"},{"kind":"text","text":" "},{"text":"profileId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"profileId"},{"kind":"text","text":" "},{"text":"adFormat:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@POBAdFormat","text":"POBAdFormat","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBAdFormat"},{"kind":"text","text":") "},{"text":"adFormat","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"impressions:"},{"kind":"text","text":"("},{"text":"NSArray<POBImpression *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"impressions","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"initWithPublisherId:profileId:adFormat:impressions:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1init(publisherId:profileId:adFormat:impressions:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest~1init(publisherId:profileId:adFormat:impressions:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithPublisherId:profileId:adFormat:impressions:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"POBAdFormat","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBAdFormat\/fragments","op":"replace","value":[{"text":"POBAdFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpression\/title","value":"POBImpression"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBImpression\/fragments","value":[{"kind":"identifier","text":"POBImpression"}],"op":"replace"},{"value":"POBRequest","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRequest\/fragments","op":"replace","value":[{"text":"POBRequest","kind":"identifier"}]}]}]}