{"kind":"symbol","identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate\/bidEvent(_:didFailToReceiveBidWithError:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbideventdelegate\/bidevent(_:didfailtoreceivebidwitherror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobbideventdelegate\/bidevent(_:didfailtoreceivebidwitherror:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bidEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"bidEventObject","kind":"internalParam"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)POBBidEvent","text":"POBBidEvent","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent","kind":"typeIdentifier"},{"text":")!, ","kind":"text"},{"text":"didFailToReceiveBidWithError","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")!)"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:objc(pl)POBBidEventDelegate(im)bidEvent:didFailToReceiveBidWithError:","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"bidEvent:didFailToReceiveBidWithError:","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"symbolKind":"method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bidEvent"},{"text":"((any ","kind":"text"},{"text":"POBBidEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBidEvent"},{"kind":"text","text":")!, "},{"text":"didFailToReceiveBidWithError","kind":"externalParam"},{"kind":"text","text":": (any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"title":"bidEvent(_:didFailToReceiveBidWithError:)"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEvent":{"navigatorTitle":[{"text":"POBBidEvent","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidEvent"}],"abstract":[{"type":"text","text":"This prototol is responsinble for interacting with SDK’s banner & interstitial objects to get bid details, continue the bid execution flow."},{"type":"text","text":" "},{"text":"All methods of this protocol are expected to be called from Main thread.","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobbidevent","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent","title":"POBBidEvent","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventDelegate/bidEvent(_:didFailToReceiveBidWithError:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bidEvent"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBBidEvent","text":"POBBidEvent"},{"kind":"text","text":")!, "},{"kind":"externalParam","text":"didFailToReceiveBidWithError"},{"text":": (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")!)","kind":"text"}],"navigatorTitle":[{"text":"bidEvent:didFailToReceiveBidWithError:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbideventdelegate\/bidevent(_:didfailtoreceivebidwitherror:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate\/bidEvent(_:didFailToReceiveBidWithError:)","title":"bidEvent(_:didFailToReceiveBidWithError:)","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventDelegate":{"navigatorTitle":[{"kind":"identifier","text":"POBBidEventDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBidEventDelegate","kind":"identifier"}],"abstract":[{"text":"Protocol for bid event notifications","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobbideventdelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate","title":"POBBidEventDelegate","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"bidEvent:didFailToReceiveBidWithError:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bidEvent:didFailToReceiveBidWithError:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"bidEvent:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)POBBidEvent","kind":"typeIdentifier","text":"id<POBBidEvent>"},{"text":") ","kind":"text"},{"text":"bidEventObject","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didFailToReceiveBidWithError:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent\/title","value":"POBBidEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent\/fragments","value":[{"kind":"identifier","text":"POBBidEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate~1bidEvent(_:didFailToReceiveBidWithError:)\/title","value":"bidEvent:didFailToReceiveBidWithError:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate~1bidEvent(_:didFailToReceiveBidWithError:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bidEvent:didFailToReceiveBidWithError:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate\/title","value":"POBBidEventDelegate"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate\/fragments","op":"replace","value":[{"text":"POBBidEventDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}