{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bidEvent"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"bidEventObject","kind":"internalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)POBBidEvent","text":"POBBidEvent","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent"},{"text":")!, ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":" "},{"text":"bid","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"POBBid","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBid"},{"text":"!)","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bidEvent"},{"kind":"text","text":"((any "},{"text":"POBBidEvent","preciseIdentifier":"c:objc(pl)POBBidEvent","kind":"typeIdentifier"},{"text":")!, ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)POBBid","text":"POBBid","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"required":true,"externalID":"c:objc(pl)POBBidEventDelegate(im)bidEvent:didReceiveBid:","navigatorTitle":[{"text":"bidEvent:didReceiveBid:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","title":"bidEvent(_:didReceive:)","role":"symbol","modules":[{"name":"OpenWrapSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate\/bidEvent(_:didReceive:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobbideventdelegate\/bidevent(_:didreceive:)"]},{"paths":["\/documentation\/openwrapsdk\/pobbideventdelegate\/bidevent(_:didreceive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventDelegate/bidEvent(_:didReceive:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bidEvent","kind":"identifier"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)POBBidEvent","text":"POBBidEvent","kind":"typeIdentifier"},{"text":")!, ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBBid","kind":"typeIdentifier","text":"POBBid"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"bidEvent:didReceiveBid:"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobbideventdelegate\/bidevent(_:didreceive:)","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate\/bidEvent(_:didReceive:)","title":"bidEvent(_:didReceive:)","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEvent":{"navigatorTitle":[{"text":"POBBidEvent","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBBidEvent"}],"abstract":[{"type":"text","text":"This prototol is responsinble for interacting with SDK’s banner & interstitial objects to get bid details, continue the bid execution flow."},{"type":"text","text":" "},{"text":"All methods of this protocol are expected to be called from Main thread.","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobbidevent","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEvent","title":"POBBidEvent","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBid":{"navigatorTitle":[{"kind":"identifier","text":"POBBid"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBid","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobbid","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid","kind":"symbol","abstract":[{"type":"text","text":"Holds information of winning bid along with all the bids that participated in the auction."}],"role":"symbol","title":"POBBid"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBBidEventDelegate":{"navigatorTitle":[{"kind":"identifier","text":"POBBidEventDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBBidEventDelegate","kind":"identifier"}],"abstract":[{"text":"Protocol for bid event notifications","type":"text"}],"url":"\/documentation\/openwrapsdk\/pobbideventdelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBidEventDelegate","title":"POBBidEventDelegate","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"bidEvent:didReceiveBid:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"bidEvent:didReceiveBid:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"bidEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<POBBidEvent>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)POBBidEvent"},{"kind":"text","text":") "},{"kind":"internalParam","text":"bidEventObject"},{"kind":"text","text":" "},{"text":"didReceiveBid:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"POBBid","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBBid","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBBid"},{"text":" *) ","kind":"text"},{"text":"bid","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate~1bidEvent(_:didReceive:)\/title","op":"replace","value":"bidEvent:didReceiveBid:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bidEvent:didReceiveBid:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate~1bidEvent(_:didReceive:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent\/title","value":"POBBidEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEvent\/fragments","value":[{"kind":"identifier","text":"POBBidEvent"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid\/title","op":"replace","value":"POBBid"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBid\/fragments","op":"replace","value":[{"text":"POBBid","kind":"identifier"}]},{"value":"POBBidEventDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBBidEventDelegate\/fragments","op":"replace","value":[{"text":"POBBidEventDelegate","kind":"identifier"}]}]}]}