{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/belowArticle","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"symbolKind":"case","role":"symbol","title":"POBNativePlacementType.belowArticle","modules":[{"name":"OpenWrapSDK"}],"externalID":"c:@E@POBNativePlacementType@POBNativePlacementTypeBelowArticle","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"belowArticle"}],"navigatorTitle":[{"text":"POBNativePlacementTypeBelowArticle","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Recommendation widget, most commonly presented below the article content.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"belowArticle","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeplacementtype\/belowarticle"]},{"paths":["\/documentation\/openwrapsdk\/pobnativeplacementtype\/belowarticle"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType","title":"POBNativePlacementType","url":"\/documentation\/openwrapsdk\/pobnativeplacementtype","type":"topic","abstract":[{"text":"The FORMAT of the ad you are purchasing, separate from the surrounding context","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativePlacementType","kind":"identifier"}],"navigatorTitle":[{"text":"POBNativePlacementType","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType/belowArticle":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/belowArticle","title":"POBNativePlacementType.belowArticle","url":"\/documentation\/openwrapsdk\/pobnativeplacementtype\/belowarticle","type":"topic","abstract":[{"text":"Recommendation widget, most commonly presented below the article content.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"belowArticle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBNativePlacementTypeBelowArticle"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"POBNativePlacementTypeBelowArticle","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POBNativePlacementTypeBelowArticle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"POBNativePlacementTypeBelowArticle"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType\/title","value":"POBNativePlacementType","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType\/fragments","value":[{"kind":"identifier","text":"POBNativePlacementType"}],"op":"replace"},{"value":"POBNativePlacementTypeBelowArticle","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1belowArticle\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1belowArticle\/fragments","op":"replace","value":[{"text":"POBNativePlacementTypeBelowArticle","kind":"identifier"}]}]}]}