{"abstract":[{"text":"In the feed of content - for example as an item inside the organic feed\/grid\/listing\/carousel.","type":"text"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/feed","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeplacementtype\/feed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobnativeplacementtype\/feed"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"feed"}],"title":"POBNativePlacementType.feed","externalID":"c:@E@POBNativePlacementType@POBNativePlacementTypeFeed","roleHeading":"Case","modules":[{"name":"OpenWrapSDK"}],"navigatorTitle":[{"kind":"identifier","text":"POBNativePlacementTypeFeed"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"feed","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType"]]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType","title":"POBNativePlacementType","url":"\/documentation\/openwrapsdk\/pobnativeplacementtype","type":"topic","abstract":[{"text":"The FORMAT of the ad you are purchasing, separate from the surrounding context","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativePlacementType","kind":"identifier"}],"navigatorTitle":[{"text":"POBNativePlacementType","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType/feed":{"abstract":[{"type":"text","text":"In the feed of content - for example as an item inside the organic feed\/grid\/listing\/carousel."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/openwrapsdk\/pobnativeplacementtype\/feed","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"feed","kind":"identifier"}],"title":"POBNativePlacementType.feed","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/feed","navigatorTitle":[{"kind":"identifier","text":"POBNativePlacementTypeFeed"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"POBNativePlacementTypeFeed","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"POBNativePlacementTypeFeed","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"POBNativePlacementTypeFeed","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType\/title","value":"POBNativePlacementType"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType\/fragments","op":"replace","value":[{"text":"POBNativePlacementType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1feed\/title","value":"POBNativePlacementTypeFeed"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1feed\/fragments","value":[{"kind":"identifier","text":"POBNativePlacementTypeFeed"}],"op":"replace"}]}]}