{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/outsideCoreContent","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType"]]},"sections":[],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeplacementtype\/outsidecorecontent"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeplacementtype\/outsidecorecontent"]}],"abstract":[{"type":"text","text":"Outside the core content - for example in the ads section on the right rail, as a banner-style placement near the content, etc."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"outsideCoreContent"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outsideCoreContent","kind":"identifier"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","externalID":"c:@E@POBNativePlacementType@POBNativePlacementTypeOutsideCoreContent","navigatorTitle":[{"text":"POBNativePlacementTypeOutsideCoreContent","kind":"identifier"}],"title":"POBNativePlacementType.outsideCoreContent","roleHeading":"Case","symbolKind":"case"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType","title":"POBNativePlacementType","url":"\/documentation\/openwrapsdk\/pobnativeplacementtype","type":"topic","abstract":[{"text":"The FORMAT of the ad you are purchasing, separate from the surrounding context","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"POBNativePlacementType","kind":"identifier"}],"navigatorTitle":[{"text":"POBNativePlacementType","kind":"identifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativePlacementType/outsideCoreContent":{"url":"\/documentation\/openwrapsdk\/pobnativeplacementtype\/outsidecorecontent","type":"topic","kind":"symbol","navigatorTitle":[{"text":"POBNativePlacementTypeOutsideCoreContent","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativePlacementType\/outsideCoreContent","title":"POBNativePlacementType.outsideCoreContent","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"outsideCoreContent","kind":"identifier"}],"abstract":[{"type":"text","text":"Outside the core content - for example in the ads section on the right rail, as a banner-style placement near the content, etc."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"POBNativePlacementTypeOutsideCoreContent"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"POBNativePlacementTypeOutsideCoreContent","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"POBNativePlacementTypeOutsideCoreContent","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"POBNativePlacementType","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType\/title"},{"op":"replace","value":[{"text":"POBNativePlacementType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType\/fragments"},{"value":"POBNativePlacementTypeOutsideCoreContent","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1outsideCoreContent\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativePlacementType~1outsideCoreContent\/fragments","value":[{"text":"POBNativePlacementTypeOutsideCoreContent","kind":"identifier"}]}]}]}