{"abstract":[{"text":"Creates and returns a POBDSATransparencyInfo instance based on the provided dictionary.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/build(with:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/build(with:)"]},{"paths":["\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/build(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"build"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"dsaInfo","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo","kind":"typeIdentifier","text":"POBDSATransparencyInfo","preciseIdentifier":"c:objc(cs)POBDSATransparencyInfo"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"A dictionary containing the data needed to build a POBDSATransparencyInfo object.","type":"text"}],"type":"paragraph"}],"name":"dsaInfo"}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A newly created POBDSATransparencyInfo instance populated with the data from the passed dictionary."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"buildWithDictionary:"}],"role":"symbol","roleHeading":"Type Method","title":"build(with:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"build"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBDSATransparencyInfo","text":"POBDSATransparencyInfo","kind":"typeIdentifier"}],"externalID":"c:objc(cs)POBDSATransparencyInfo(cm)buildWithDictionary:","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSATransparencyInfo":{"url":"\/documentation\/openwrapsdk\/pobdsatransparencyinfo","type":"topic","title":"POBDSATransparencyInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBDSATransparencyInfo","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo","role":"symbol","abstract":[{"type":"text","text":"The POBDSATransparencyInfo class represents the transparency information for DSA (Digital Services Act) compliance."},{"text":" ","type":"text"},{"type":"text","text":"It provides the domain name and user parameters for platform or sell-side use."}],"navigatorTitle":[{"kind":"identifier","text":"POBDSATransparencyInfo"}],"kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSATransparencyInfo/build(with:)":{"title":"build(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]) -> ","kind":"text"},{"text":"POBDSATransparencyInfo","preciseIdentifier":"c:objc(cs)POBDSATransparencyInfo","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/build(with:)","navigatorTitle":[{"text":"buildWithDictionary:","kind":"identifier"}],"abstract":[{"text":"Creates and returns a POBDSATransparencyInfo instance based on the provided dictionary.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/build(with:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"buildWithDictionary:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildWithDictionary:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)POBDSATransparencyInfo","text":"POBDSATransparencyInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo"},{"kind":"text","text":" *) "},{"text":"buildWithDictionary:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dsaInfo"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo\/title","op":"replace","value":"POBDSATransparencyInfo"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo\/fragments","op":"replace","value":[{"text":"POBDSATransparencyInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1build(with:)\/title","op":"replace","value":"buildWithDictionary:"},{"value":[{"text":"+ ","kind":"text"},{"text":"buildWithDictionary:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1build(with:)\/fragments"}]}]}