{"abstract":[{"type":"text","text":"Domain of the entity that applied user parameters for DSA."}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/domainName"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/domainname"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/domainname"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"domainName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"domainName"}],"role":"symbol","title":"domainName","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"domainName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:objc(cs)POBDSATransparencyInfo(py)domainName","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSATransparencyInfo/domainName":{"title":"domainName","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"domainName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/domainname","navigatorTitle":[{"kind":"identifier","text":"domainName"}],"abstract":[{"type":"text","text":"Domain of the entity that applied user parameters for DSA."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/domainName"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSATransparencyInfo":{"url":"\/documentation\/openwrapsdk\/pobdsatransparencyinfo","type":"topic","title":"POBDSATransparencyInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBDSATransparencyInfo","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo","role":"symbol","abstract":[{"type":"text","text":"The POBDSATransparencyInfo class represents the transparency information for DSA (Digital Services Act) compliance."},{"text":" ","type":"text"},{"type":"text","text":"It provides the domain name and user parameters for platform or sell-side use."}],"navigatorTitle":[{"kind":"identifier","text":"POBDSATransparencyInfo"}],"kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"domainName","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"domainName","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"domainName"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1domainName\/title","op":"replace","value":"domainName"},{"value":[{"text":"domainName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1domainName\/fragments"},{"value":"POBDSATransparencyInfo","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo\/title"},{"value":[{"text":"POBDSATransparencyInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}