{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/uniqueuserparamsstring(from:)"]},{"paths":["\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/uniqueuserparamsstring(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)POBDSATransparencyInfo(cm)uniqueUserParamsStringFromArray:","modules":[{"name":"OpenWrapSDK"}],"role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"text":"uniqueUserParamsStringFromArray:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uniqueUserParamsString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)POBDSATransparencyInfo","kind":"typeIdentifier","text":"POBDSATransparencyInfo"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"uniqueUserParamsString(from:)","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"uniqueUserParamsString"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"transparencyInfoArray","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBDSATransparencyInfo","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo","text":"POBDSATransparencyInfo"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"An array of POBDSATransparencyInfo objects containing user parameters.","type":"text"}],"type":"paragraph"}],"name":"transparencyInfoArray"}]},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"A string containing unique user parameters sorted in ascending order and joined by commas.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Returns an empty string if the input array is empty or contains no user parameters."}],"type":"paragraph"}]}],"abstract":[{"text":"Creates a unique, comma-separated string of user parameters from an array of transparency info objects.","type":"text"}],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/uniqueUserParamsString(from:)","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSATransparencyInfo":{"url":"\/documentation\/openwrapsdk\/pobdsatransparencyinfo","type":"topic","title":"POBDSATransparencyInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBDSATransparencyInfo","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo","role":"symbol","abstract":[{"type":"text","text":"The POBDSATransparencyInfo class represents the transparency information for DSA (Digital Services Act) compliance."},{"text":" ","type":"text"},{"type":"text","text":"It provides the domain name and user parameters for platform or sell-side use."}],"navigatorTitle":[{"kind":"identifier","text":"POBDSATransparencyInfo"}],"kind":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSATransparencyInfo/uniqueUserParamsString(from:)":{"title":"uniqueUserParamsString(from:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uniqueUserParamsString"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"POBDSATransparencyInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBDSATransparencyInfo"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/uniqueuserparamsstring(from:)","navigatorTitle":[{"text":"uniqueUserParamsStringFromArray:","kind":"identifier"}],"abstract":[{"text":"Creates a unique, comma-separated string of user parameters from an array of transparency info objects.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/uniqueUserParamsString(from:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"uniqueUserParamsStringFromArray:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"uniqueUserParamsStringFromArray:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"uniqueUserParamsStringFromArray:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<POBDSATransparencyInfo *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"transparencyInfoArray"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"POBDSATransparencyInfo","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo\/fragments","op":"replace","value":[{"text":"POBDSATransparencyInfo","kind":"identifier"}]},{"op":"replace","value":"uniqueUserParamsStringFromArray:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1uniqueUserParamsString(from:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"uniqueUserParamsStringFromArray:"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1uniqueUserParamsString(from:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}