{"sections":[],"abstract":[{"text":"An array of NSNumber objects representing user parameters for platform or sell-side use.","type":"text"},{"text":" ","type":"text"},{"text":"This property stores an array of integers, encapsulated as NSNumber objects,","type":"text"},{"text":" ","type":"text"},{"text":"that can be used by the platform or sell-side for DSA compliance.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/userParams","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userParams"},{"text":": [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]","kind":"text"}],"externalID":"c:objc(cs)POBDSATransparencyInfo(py)userParams","navigatorTitle":[{"text":"userParams","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","title":"userParams","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"userParams","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo"]]},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/userparams"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/userparams"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSATransparencyInfo/userParams":{"title":"userParams","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"userParams","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"]","kind":"text"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobdsatransparencyinfo\/userparams","navigatorTitle":[{"text":"userParams","kind":"identifier"}],"abstract":[{"text":"An array of NSNumber objects representing user parameters for platform or sell-side use.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This property stores an array of integers, encapsulated as NSNumber objects,"},{"type":"text","text":" "},{"type":"text","text":"that can be used by the platform or sell-side for DSA compliance."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo\/userParams"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBDSATransparencyInfo":{"url":"\/documentation\/openwrapsdk\/pobdsatransparencyinfo","type":"topic","title":"POBDSATransparencyInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"POBDSATransparencyInfo","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBDSATransparencyInfo","role":"symbol","abstract":[{"type":"text","text":"The POBDSATransparencyInfo class represents the transparency information for DSA (Digital Services Act) compliance."},{"text":" ","type":"text"},{"type":"text","text":"It provides the domain name and user parameters for platform or sell-side use."}],"navigatorTitle":[{"kind":"identifier","text":"POBDSATransparencyInfo"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"userParams"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"userParams"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"text":" * ","kind":"text"},{"text":"userParams","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1userParams\/title","value":"userParams"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo~1userParams\/fragments","value":[{"kind":"identifier","text":"userParams"}]},{"value":"POBDSATransparencyInfo","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo\/title"},{"op":"replace","value":[{"kind":"identifier","text":"POBDSATransparencyInfo"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBDSATransparencyInfo\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}