{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward\/unspecified()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","title":"unspecified()","roleHeading":"Type Method","externalID":"c:objc(cs)POBReward(cm)unspecifiedReward","navigatorTitle":[{"kind":"identifier","text":"unspecifiedReward"}],"modules":[{"name":"OpenWrapSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unspecified"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBReward","text":"POBReward"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unspecified","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)POBReward","text":"POBReward","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobreward\/unspecified()"]},{"paths":["\/documentation\/openwrapsdk\/pobreward\/unspecified()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBReward":{"title":"POBReward","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBReward","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobreward","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBReward"}],"abstract":[{"type":"text","text":"Holds the general information about Reward to be provided to user."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBReward/unspecified()":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"unspecifiedReward"}],"url":"\/documentation\/openwrapsdk\/pobreward\/unspecified()","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward\/unspecified()","title":"unspecified()","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unspecified"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)POBReward","text":"POBReward","kind":"typeIdentifier"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"unspecifiedReward"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"unspecifiedReward","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)POBReward","text":"POBReward","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"unspecifiedReward","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"POBReward","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBReward\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBReward\/fragments","op":"replace","value":[{"text":"POBReward","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBReward~1unspecified()\/title","op":"replace","value":"unspecifiedReward"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBReward~1unspecified()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unspecifiedReward"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}