{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"nativeAdDidDismissModal:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"nativeAdDidDismissModal(_:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdDidDismissModal"},{"text":"(any ","kind":"text"},{"text":"POBNativeAd","preciseIdentifier":"c:objc(pl)POBNativeAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)POBNativeAdDelegate(im)nativeAdDidDismissModal:","modules":[{"name":"OpenWrapSDK"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdDidDismissModal"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"POBNativeAd","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAd"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeaddiddismissmodal(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeaddiddismissmodal(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidDismissModal(_:)","interfaceLanguage":"swift"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate":{"title":"POBNativeAdDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdDelegate"}],"type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativeaddelegate","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdDelegate"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd":{"navigatorTitle":[{"text":"POBNativeAd","kind":"identifier"}],"title":"POBNativeAd","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","url":"\/documentation\/openwrapsdk\/pobnativead","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAd"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate/nativeAdDidDismissModal(_:)":{"required":true,"url":"\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeaddiddismissmodal(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"nativeAdDidDismissModal:"}],"kind":"symbol","title":"nativeAdDidDismissModal(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdDidDismissModal"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)POBNativeAd","kind":"typeIdentifier","text":"POBNativeAd"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidDismissModal(_:)","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"nativeAdDidDismissModal:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeAdDidDismissModal:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"nativeAdDidDismissModal:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<POBNativeAd>","preciseIdentifier":"c:Qoobjc(pl)POBNativeAd"},{"kind":"text","text":") "},{"text":"nativeAd","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate\/title","value":"POBNativeAdDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate\/fragments","value":[{"text":"POBNativeAdDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/title","op":"replace","value":"POBNativeAd"},{"op":"replace","value":[{"kind":"identifier","text":"POBNativeAd"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/fragments"},{"value":"nativeAdDidDismissModal:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdDidDismissModal(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdDidDismissModal(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeAdDidDismissModal:","kind":"identifier"}]}]}]}