{"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAd(_:didRecordClickForAsset:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativead(_:didrecordclickforasset:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativead(_:didrecordclickforasset:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeAd","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"internalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAd","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","text":"POBNativeAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRecordClickForAsset"},{"text":" ","kind":"text"},{"text":"assetId","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"nativeAd:didRecordClickForAsset:","kind":"identifier"}],"role":"symbol","title":"nativeAd(_:didRecordClickForAsset:)","roleHeading":"Instance Method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAd"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)POBNativeAd","kind":"typeIdentifier","text":"POBNativeAd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didRecordClickForAsset"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:objc(pl)POBNativeAdDelegate(im)nativeAd:didRecordClickForAsset:","modules":[{"name":"OpenWrapSDK"}]},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate/nativeAd(_:didRecordClickForAsset:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAd"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","text":"POBNativeAd","preciseIdentifier":"c:objc(pl)POBNativeAd"},{"text":", ","kind":"text"},{"text":"didRecordClickForAsset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"nativeAd:didRecordClickForAsset:"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAd(_:didRecordClickForAsset:)","title":"nativeAd(_:didRecordClickForAsset:)","required":true,"type":"topic","url":"\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativead(_:didrecordclickforasset:)","role":"symbol","kind":"symbol","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd":{"navigatorTitle":[{"text":"POBNativeAd","kind":"identifier"}],"title":"POBNativeAd","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","url":"\/documentation\/openwrapsdk\/pobnativead","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAd"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate":{"title":"POBNativeAdDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdDelegate"}],"type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativeaddelegate","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdDelegate"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"nativeAd:didRecordClickForAsset:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeAd:didRecordClickForAsset:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"nativeAd:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)POBNativeAd","text":"id<POBNativeAd>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"nativeAd","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didRecordClickForAsset:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"assetId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"nativeAd:didRecordClickForAsset:","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAd(_:didRecordClickForAsset:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAd:didRecordClickForAsset:"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAd(_:didRecordClickForAsset:)\/fragments","op":"replace"},{"op":"replace","value":"POBNativeAd","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/fragments","value":[{"kind":"identifier","text":"POBNativeAd"}]},{"value":"POBNativeAdDelegate","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate\/fragments","op":"replace","value":[{"text":"POBNativeAdDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}