{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate"]]},"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdWillPresentModal(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeadwillpresentmodal(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeadwillpresentmodal(_:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAdWillPresentModal"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"internalParam"},{"kind":"text","text":": any "},{"text":"POBNativeAd","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAd"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"method","title":"nativeAdWillPresentModal(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeAdWillPresentModal","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"POBNativeAd","preciseIdentifier":"c:objc(pl)POBNativeAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OpenWrapSDK"}],"role":"symbol","navigatorTitle":[{"text":"nativeAdWillPresentModal:","kind":"identifier"}],"externalID":"c:objc(pl)POBNativeAdDelegate(im)nativeAdWillPresentModal:"},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate/nativeAdWillPresentModal(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeAdWillPresentModal","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"POBNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAd"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeAdWillPresentModal:","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdWillPresentModal(_:)","title":"nativeAdWillPresentModal(_:)","type":"topic","url":"\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeadwillpresentmodal(_:)","role":"symbol","kind":"symbol","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate":{"title":"POBNativeAdDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdDelegate"}],"type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativeaddelegate","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdDelegate"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate","role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd":{"navigatorTitle":[{"text":"POBNativeAd","kind":"identifier"}],"title":"POBNativeAd","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","url":"\/documentation\/openwrapsdk\/pobnativead","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAd"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"nativeAdWillPresentModal:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeAdWillPresentModal:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"nativeAdWillPresentModal:"},{"kind":"text","text":"("},{"text":"id<POBNativeAd>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)POBNativeAd"},{"kind":"text","text":") "},{"kind":"internalParam","text":"nativeAd"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdWillPresentModal(_:)\/title","value":"nativeAdWillPresentModal:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdWillPresentModal(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeAdWillPresentModal:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate\/title","value":"POBNativeAdDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate\/fragments","value":[{"kind":"identifier","text":"POBNativeAdDelegate"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/title","op":"replace","value":"POBNativeAd"},{"op":"replace","value":[{"kind":"identifier","text":"POBNativeAd"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/fragments"}]}]}