{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdDidRecordImpression"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nativeAd"},{"text":": any ","kind":"text"},{"text":"POBNativeAd","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBNativeAd"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate"]]},"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdDidRecordImpression"},{"text":"(any ","kind":"text"},{"text":"POBNativeAd","preciseIdentifier":"c:objc(pl)POBNativeAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)POBNativeAdDelegate(im)nativeAdDidRecordImpression:","navigatorTitle":[{"kind":"identifier","text":"nativeAdDidRecordImpression:"}],"symbolKind":"method","roleHeading":"Instance Method","title":"nativeAdDidRecordImpression(_:)","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeaddidrecordimpression(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeaddidrecordimpression(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidRecordImpression(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAd":{"navigatorTitle":[{"text":"POBNativeAd","kind":"identifier"}],"title":"POBNativeAd","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAd","url":"\/documentation\/openwrapsdk\/pobnativead","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POBNativeAd"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate/nativeAdDidRecordImpression(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeAdDidRecordImpression","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"POBNativeAd","preciseIdentifier":"c:objc(pl)POBNativeAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"nativeAdDidRecordImpression:","kind":"identifier"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate\/nativeAdDidRecordImpression(_:)","title":"nativeAdDidRecordImpression(_:)","type":"topic","url":"\/documentation\/openwrapsdk\/pobnativeaddelegate\/nativeaddidrecordimpression(_:)","role":"symbol","kind":"symbol","abstract":[]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBNativeAdDelegate":{"title":"POBNativeAdDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBNativeAdDelegate"}],"type":"topic","abstract":[],"url":"\/documentation\/openwrapsdk\/pobnativeaddelegate","navigatorTitle":[{"kind":"identifier","text":"POBNativeAdDelegate"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBNativeAdDelegate","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"nativeAdDidRecordImpression:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeAdDidRecordImpression:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"nativeAdDidRecordImpression:"},{"text":"(","kind":"text"},{"text":"id<POBNativeAd>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)POBNativeAd"},{"text":") ","kind":"text"},{"text":"nativeAd","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/title","op":"replace","value":"POBNativeAd"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAd\/fragments","value":[{"text":"POBNativeAd","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdDidRecordImpression(_:)\/title","value":"nativeAdDidRecordImpression:"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate~1nativeAdDidRecordImpression(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeAdDidRecordImpression:"}],"op":"replace"},{"value":"POBNativeAdDelegate","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBNativeAdDelegate\/fragments","value":[{"kind":"identifier","text":"POBNativeAdDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}