{"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/setDelegate(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering"]]},"metadata":{"symbolKind":"method","externalID":"c:objc(pl)POBInterstitialRendering(im)setDelegate:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDelegate","kind":"identifier"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)POBInterstitialRendererDelegate","text":"POBInterstitialRendererDelegate","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"setDelegate:","kind":"identifier"}],"required":true,"role":"symbol","title":"setDelegate(_:)","modules":[{"name":"OpenWrapSDK"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"delegate","kind":"internalParam"},{"text":": (any ","kind":"text"},{"text":"POBInterstitialRendererDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBInterstitialRendererDelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate"},{"text":")!)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendering\/setdelegate(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendering\/setdelegate(_:)"]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendering/setDelegate(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/setDelegate(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"text":"((any ","kind":"text"},{"kind":"typeIdentifier","text":"POBInterstitialRendererDelegate","preciseIdentifier":"c:objc(pl)POBInterstitialRendererDelegate"},{"text":")!)","kind":"text"}],"abstract":[],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendering\/setdelegate(_:)","navigatorTitle":[{"kind":"identifier","text":"setDelegate:"}],"type":"topic","kind":"symbol","required":true,"role":"symbol","title":"setDelegate(_:)"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendering":{"navigatorTitle":[{"text":"POBInterstitialRendering","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialRendering","kind":"identifier"}],"abstract":[{"type":"text","text":"Ad interstitial rendering protocol, implement these methods to write custom ad renderer"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendering","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering","title":"POBInterstitialRendering","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendererDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBInterstitialRendererDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"POBInterstitialRendererDelegate"}],"type":"topic","abstract":[{"type":"text","text":"Ad interstitial rendering delegate, It is used to provide feedback events from custom renderer"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendererdelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendererDelegate","title":"POBInterstitialRendererDelegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"setDelegate:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setDelegate:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"setDelegate:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<POBInterstitialRendererDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)POBInterstitialRendererDelegate"},{"kind":"text","text":") "},{"kind":"internalParam","text":"delegate"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1setDelegate(_:)\/title","value":"setDelegate:"},{"value":[{"kind":"text","text":"- "},{"text":"setDelegate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1setDelegate(_:)\/fragments"},{"op":"replace","value":"POBInterstitialRendering","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering\/fragments","value":[{"text":"POBInterstitialRendering","kind":"identifier"}]},{"value":"POBInterstitialRendererDelegate","op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendererDelegate\/fragments","value":[{"kind":"identifier","text":"POBInterstitialRendererDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}