{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/setVideoDelegate(_:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering"]]},"metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setVideoDelegate"},{"text":"((any ","kind":"text"},{"text":"POBVideoRenderingDelegate","preciseIdentifier":"c:objc(pl)POBVideoRenderingDelegate","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"title":"setVideoDelegate(_:)","symbolKind":"method","externalID":"c:objc(pl)POBInterstitialRendering(im)setVideoDelegate:","modules":[{"name":"OpenWrapSDK"}],"navigatorTitle":[{"kind":"identifier","text":"setVideoDelegate:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setVideoDelegate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"POBVideoRenderingDelegate","preciseIdentifier":"c:objc(pl)POBVideoRenderingDelegate","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRenderingDelegate"},{"kind":"text","text":")!)"}]}]}],"variants":[{"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendering\/setvideodelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendering\/setvideodelegate(_:)"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendering/setVideoDelegate(_:)":{"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/setVideoDelegate(_:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setVideoDelegate","kind":"identifier"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)POBVideoRenderingDelegate","kind":"typeIdentifier","text":"POBVideoRenderingDelegate"},{"text":")!)","kind":"text"}],"abstract":[],"title":"setVideoDelegate(_:)","url":"\/documentation\/openwrapsdk\/pobinterstitialrendering\/setvideodelegate(_:)","navigatorTitle":[{"kind":"identifier","text":"setVideoDelegate:"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendering":{"navigatorTitle":[{"text":"POBInterstitialRendering","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialRendering","kind":"identifier"}],"abstract":[{"type":"text","text":"Ad interstitial rendering protocol, implement these methods to write custom ad renderer"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendering","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering","title":"POBInterstitialRendering","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoRenderingDelegate":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBVideoRenderingDelegate"}],"url":"\/documentation\/openwrapsdk\/pobvideorenderingdelegate","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRenderingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBVideoRenderingDelegate","kind":"identifier"}],"title":"POBVideoRenderingDelegate","abstract":[{"text":"Video rendering delegate, It is used to provide video events from video renderer","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"setVideoDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setVideoDelegate:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setVideoDelegate:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)POBVideoRenderingDelegate","text":"id<POBVideoRenderingDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"setVideoDelegate:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1setVideoDelegate(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"setVideoDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1setVideoDelegate(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering\/title","value":"POBInterstitialRendering"},{"value":[{"text":"POBInterstitialRendering","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering\/fragments"},{"op":"replace","value":"POBVideoRenderingDelegate","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRenderingDelegate\/title"},{"value":[{"text":"POBVideoRenderingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRenderingDelegate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}