{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":" "},{"text":"loadTimeOrientation","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIInterfaceOrientation","kind":"typeIdentifier","text":"UIInterfaceOrientation"},{"kind":"text","text":")"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/show(from:in:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering"]]},"kind":"symbol","metadata":{"title":"show(from:in:)","role":"symbol","externalID":"c:objc(pl)POBInterstitialRendering(im)showFromViewController:inOrientation:","navigatorTitle":[{"kind":"identifier","text":"showFromViewController:inOrientation:"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"OpenWrapSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"text":"UIInterfaceOrientation","preciseIdentifier":"c:@E@UIInterfaceOrientation","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"2.0","deprecated":false}],"required":true},"variants":[{"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendering\/show(from:in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openwrapsdk\/pobinterstitialrendering\/show(from:in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendering":{"navigatorTitle":[{"text":"POBInterstitialRendering","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"POBInterstitialRendering","kind":"identifier"}],"abstract":[{"type":"text","text":"Ad interstitial rendering protocol, implement these methods to write custom ad renderer"}],"url":"\/documentation\/openwrapsdk\/pobinterstitialrendering","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering","title":"POBInterstitialRendering","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBInterstitialRendering/show(from:in:)":{"title":"show(from:in:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"!, ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIInterfaceOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientation"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"showFromViewController:inOrientation:"}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBInterstitialRendering\/show(from:in:)","type":"topic","url":"\/documentation\/openwrapsdk\/pobinterstitialrendering\/show(from:in:)","kind":"symbol","abstract":[],"required":true},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"showFromViewController:inOrientation:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showFromViewController:inOrientation:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"showFromViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inOrientation:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@UIInterfaceOrientation","text":"UIInterfaceOrientation","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"loadTimeOrientation","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering\/title","value":"POBInterstitialRendering","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering\/fragments","op":"replace","value":[{"text":"POBInterstitialRendering","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1show(from:in:)\/title","value":"showFromViewController:inOrientation:"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBInterstitialRendering~1show(from:in:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"showFromViewController:inOrientation:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}