{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"availableRewards","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)POBReward","text":"POBReward","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"externalID":"c:objc(cs)POBRewardedAd(py)availableRewards","navigatorTitle":[{"text":"availableRewards","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","title":"availableRewards","modules":[{"name":"OpenWrapSDK"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd\/availableRewards"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"availableRewards"},{"text":": [","kind":"text"},{"text":"POBReward","preciseIdentifier":"c:objc(cs)POBReward","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward","kind":"typeIdentifier"},{"kind":"text","text":"]? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Calling this method has no effect until the ad is received(rewardedAdDidReceiveAd:) and is ready to show, i.e. ‘isReady’ flag is true."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobrewardedad\/availablerewards"]},{"paths":["\/documentation\/openwrapsdk\/pobrewardedad\/availablerewards"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAd/availableRewards":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"availableRewards"}],"url":"\/documentation\/openwrapsdk\/pobrewardedad\/availablerewards","kind":"symbol","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd\/availableRewards","type":"topic","title":"availableRewards","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"availableRewards","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)POBReward","text":"POBReward"},{"text":"]?","kind":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBRewardedAd":{"title":"POBRewardedAd","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBRewardedAd","abstract":[{"type":"text","text":"Displays Rewarded Ads."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBRewardedAd"}],"kind":"symbol","url":"\/documentation\/openwrapsdk\/pobrewardedad","navigatorTitle":[{"text":"POBRewardedAd","kind":"identifier"}],"role":"symbol"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBReward":{"title":"POBReward","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POBReward","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobreward","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBReward"}],"abstract":[{"type":"text","text":"Holds the general information about Reward to be provided to user."}],"identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBReward"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"availableRewards","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"availableRewards","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<POBReward *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"availableRewards","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd~1availableRewards\/title","op":"replace","value":"availableRewards"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd~1availableRewards\/fragments","value":[{"kind":"identifier","text":"availableRewards"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd\/title","value":"POBRewardedAd","op":"replace"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBRewardedAd\/fragments","op":"replace","value":[{"kind":"identifier","text":"POBRewardedAd"}]},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBReward\/title","op":"replace","value":"POBReward"},{"op":"replace","value":[{"kind":"identifier","text":"POBReward"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBReward\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}