{"metadata":{"externalID":"c:objc(pl)POBVideoRendering(im)setVideoDelegate:","modules":[{"name":"OpenWrapSDK"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"setVideoDelegate:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setVideoDelegate"},{"text":"((any ","kind":"text"},{"text":"POBVideoRenderingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBVideoRenderingDelegate"},{"text":")!)","kind":"text"}],"required":true,"title":"setVideoDelegate(_:)","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRendering\/setVideoDelegate(_:)"},"hierarchy":{"paths":[["doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRendering"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setVideoDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"delegate","kind":"internalParam"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)POBVideoRenderingDelegate","text":"POBVideoRenderingDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRenderingDelegate"},{"kind":"text","text":")!)"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openwrapsdk\/pobvideorendering\/setvideodelegate(_:)"]},{"paths":["\/documentation\/openwrapsdk\/pobvideorendering\/setvideodelegate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"references":{"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoRenderingDelegate":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POBVideoRenderingDelegate"}],"url":"\/documentation\/openwrapsdk\/pobvideorenderingdelegate","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRenderingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"POBVideoRenderingDelegate","kind":"identifier"}],"title":"POBVideoRenderingDelegate","abstract":[{"text":"Video rendering delegate, It is used to provide video events from video renderer","type":"text"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoRendering/setVideoDelegate(_:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setVideoDelegate:","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobvideorendering\/setvideodelegate(_:)","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRendering\/setVideoDelegate(_:)","required":true,"title":"setVideoDelegate(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setVideoDelegate"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)POBVideoRenderingDelegate","text":"POBVideoRenderingDelegate"},{"kind":"text","text":")!)"}]},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK":{"role":"collection","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK","abstract":[{"type":"text","text":"[Test] OpenWrapSDK is a Swift Package that brings the robust PubMatic platform to iOS devices everywhere. Integrate the OpenWrap SDK into your iOS app so you can use the PubMatic platform to control, monitor, and optimize your inventory’s financial performance. The OpenWrap SDK lets you leverage PubMatic’s robust platform of OpenWrap capabilities within your mobile app."}],"kind":"symbol","url":"\/documentation\/openwrapsdk","title":"OpenWrapSDK","type":"topic"},"doc://com.pubmatic.openwrapsdk/documentation/OpenWrapSDK/POBVideoRendering":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"POBVideoRendering","kind":"identifier"}],"url":"\/documentation\/openwrapsdk\/pobvideorendering","type":"topic","identifier":"doc:\/\/com.pubmatic.openwrapsdk\/documentation\/OpenWrapSDK\/POBVideoRendering","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"POBVideoRendering"}],"title":"POBVideoRendering","abstract":[{"text":"Ad video rendering protocol, implement these methods to write custom ad renderer","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"setVideoDelegate:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setVideoDelegate:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"setVideoDelegate:"},{"text":"(","kind":"text"},{"text":"id<POBVideoRenderingDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)POBVideoRenderingDelegate"},{"kind":"text","text":") "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"POBVideoRenderingDelegate","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRenderingDelegate\/title"},{"value":[{"text":"POBVideoRenderingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRenderingDelegate\/fragments"},{"op":"replace","value":"setVideoDelegate:","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRendering~1setVideoDelegate(_:)\/title"},{"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRendering~1setVideoDelegate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setVideoDelegate:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRendering\/title","value":"POBVideoRendering"},{"value":[{"text":"POBVideoRendering","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pubmatic.openwrapsdk~1documentation~1OpenWrapSDK~1POBVideoRendering\/fragments","op":"replace"}]}]}